### ISSUE TITLE
Latest commits (Jan 17) broke mmseqs cluster

### ISSUE THREAD

**Issue by alquraishi** [soedinglab/mmseqs2#10]
I just tried building the latest version and using mmseqs cluster, but it fails with this error:

```
Could not open data file tmp/clu_step0!
mv: cannot stat `tmp/clu': No such file or directory
mv: cannot stat `tmp/clu.index': No such file or directory
Could not move result to clu

```

Reverting to an older copy (latest before Jan 17) solves the problem.

**Comment by martin-steinegger** [comment]
Thank you for reporting. I fixed the issue. 
Could you rerun the clustering again?

**Comment by fxsuper** [comment]
Thanks for the quick fix. Yes it appears to be working fine now.

**Comment by alquraishi** [comment]
Thanks for the quick fix. Yes it appears to be working fine now.

**Comment by mooreryan** [comment]
Just a heads up, I downloaded the precompiled linux binary today and I think I got the same problem. 

```
Clustering step 1...
Could not open data file p.aa_orfs/tmp/clu_step0!
mv: cannot stat ‘p.aa_orfs/tmp/clu’: No such file or directory
mv: cannot stat ‘p.aa_orfs/tmp/clu.index’: No such file or directory
Could not move result to p.aa_orfs/p.aa_orfs.DB.mmseqs_linclust
```

The version is d879ce2fa8d1ef3b0aa89d23e8988dad729cc5a6.

**Comment by martin-steinegger** [comment]
@mooreryan could you please add the log?

**Comment by mooreryan** [comment]
Sure, here are the log and err files from linclust. The same problem also occurs when using cluster as well.

[linclust.err.txt](https://github.com/soedinglab/mmseqs2/files/800241/linclust.err.txt)
[linclust.out.txt](https://github.com/soedinglab/mmseqs2/files/800242/linclust.out.txt)

**Comment by milot-mirdita** [comment]
Hi Ryan, 

Could you please delete and recreate the tmp folder for linclust, run it again and post the log?
It seems like there was already some broken output from a run before there and that is now masking the issue.

We will try to improve the tmp folder handling in the future, sorry about that.

Best regards,
Milot

**Comment by mooreryan** [comment]
Thanks! Starting with a clean tmp folder seems to have solved the problem for both linclust and the regular cluster program as well.
