### ISSUE TITLE
Minimum possible min-seq-id for clustering

### ISSUE THREAD

**Issue by altaetran** [soedinglab/MMseqs2#100]
Hi,

I'm wondering what the minimum sequence id we can use for clustering is, and if there are other parameters we can set to achieve an accurate clustering at low min-seq-id. I am interested in clustering at 25%-40% identity if possible. Thank you!

Best,
Han

**Comment by martin-steinegger** [comment]
@altaetran 
I think 40%-25% is still doable with sequence/sequence clustering but if you want some more sensitivity than you could try a "profile-profile" clustering. See https://github.com/soedinglab/MMseqs2/issues/66

**Comment by martin-steinegger** [comment]
Can I close this issue?
