### ISSUE TITLE
[Potential Bug] Some libs crash with database in diff path

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#102]
Hi,

I'm using the mmseqs hosted in linuxbrew version 3-be8f6.

I'm using a routine to hierarchical cluster which I remove gradually the redundancy.  
I've got some errors when I try to execute this routine in different directory compared with
when execute all clusters in same directory.  

The routine consists in:
1- create the first DB (/home/base/first.db)
2- create directory ( e.g. /home/base/90id )
3- execute the higher level of cluster and create tsv (e.g. 90% id) in this directory with /home/base/first.db
4- createsubdb in this directory (/home/base/90id/subset90.db)
5- back to previous dir (/home/base/) and create the next one (/home/base/80id)
6- execute the higher level of cluster and create tsv (e.g. 80% id) in this directory with /home/base/90id/subset90.db

Since all steps (prefilter, align, clust, createtsv) require the same db the bug identified was related to createtsv module.

> acpguedes@haldane:~/test/any/id_0.8cov_0.3evalue_0.001$ mmseqs createtsv /home/acpguedes/test/any/id_0.9cov_0.3evalue_0.001/subset.db /home/acpguedes/test/any/id_0.9cov_0.3evalue_0.001/subset.db MMseqsClust MMseqsClust.tsv
> Program call:
> /home/acpguedes/test/any/id_0.9cov_0.3evalue_0.001/subset.db /home/acpguedes/test/any/id_0.9cov_0.3evalue_0.001/subset.db MMseqsClust MMseqsClust.tsv 
> 
> MMseqs Version:                  	3-be8f6
> first sequence as respresentative	false
> 
> Query file is /home/acpguedes/test/any/id_0.9cov_0.3evalue_0.001/subset.db
> Could not open data file /home/acpguedes/test/any/id_0.9cov_0.3evalue_0.001/subset.db_h!
> 

I also get the same bug with result2flat:
```
mmseqs createdb tcdb_found.fa tcdb_found.db -v 0  
mkdir linclust_tmp  
mmseqs linclust tcdb_found.db tcdb_found.clu90 linclust_tmp -a -c 0.9 --min-seq-id 0.9 -v 0 --threads 15  
mmseqs result2repseq tcdb_found.db tcdb_found.clu90 tcdb_found.clu90rep  
mmseqs result2flat tcdb_found.db tcdb_found.db tcdb_found.clu90rep tcdb_found90.fa  --use-fasta-header  
mmseqs createsubdb tcdb_found.clu90 tcdb_found.db tcdb_found90.db  
mmseqs linclust tcdb_found90.db tcdb_found.clu70 linclust_tmp -a -c 0.9 --min-seq-id 0.7 -v 0 --threads 15  
mmseqs result2repseq tcdb_found90.db tcdb_found.clu70 tcdb_found.clu70rep  
mmseqs result2flat tcdb_found90.db tcdb_found90.db tcdb_found.clu70rep tcdb_found70.fa  --use-fasta-header 
```
Witch return me this in the last command

> $ mmseqs result2flat tcdb_found90.db tcdb_found90.db tcdb_found.clu70rep tcdb_found70.fa  --use-fasta-header
> Program call:
> tcdb_found90.db tcdb_found90.db tcdb_found.clu70rep tcdb_found70.fa --use-fasta-header 
> 
> MMseqs Version: 	3-be8f6
> Use fasta header	true
> Verbosity       	3
> 
> Query file is tcdb_found90.db
> Could not open data file tcdb_found90.db_h!
> 

It's seams that some bug related with

**Comment by milot-mirdita** [comment]
Thats a bit of a usability trap on our side.

`createsubdb` will only create a new subset database for the sequence db, but not for the header db (`_h` suffix). 

You can either also create that:
```
mmseqs createsubdb tcdb_found.clu90 tcdb_found.db_h tcdb_found90.db_h
```

Or save some space by creating symlinks:
```
ln -s tcdb_found.db_h tcdb_found90.db_h
ln -s tcdb_found.db_h.index tcdb_found90.db_h.index
```

Or pass the database with all entries to `result2flat`:
```
mmseqs result2flat tcdb_found.db tcdb_found.db tcdb_found.clu70rep tcdb_found70.fa  --use-fasta-header
```

Either of these will work. We'll think of something to avoid this trap.

**Comment by acpguedes** [comment]
Thank you for fast response. 
I tried the way you wrote and it's work fine. 
So, I'll close this thread.
Regards,
