### ISSUE TITLE
NEWMAPDB variable missing in updatecluster 

### ISSUE THREAD

**Issue by i-lanc** [soedinglab/MMseqs2#103]
## Context
It appears that the documentation gives only 5 parameters for clusterupdate:
mmseqs clusterupdate oldDB newDB oldDB_clustering outDB tmp

However, from the code, it seems that mmseq2 actually requires 6 input parameters:
mmseqs clusterupdate OLDB NEWDB OLDCLUST NEWMAPDB NEWCLUST TMP_PATH

I am not sure what NEWMAPDB is vs NEWDB, and so I've tried running the code giving a unique name to each. The clustering appears to run, but the tools for generating fasta and tsv results fail (see detail below) 

## Expected Behavior
Looking to generate fasta and tsv results from updated clusters with a new database that contains both the old database and a set of new sequences. 

## Current Behavior
While clustering appears to run, I am not able to successfully generate fasta and tsv files. 
For the fasta, I get output that looks like the following: 
Entry  does not contain a header!2509593Entry 4480592Entry 
Entry 1542108 does not contain a header! does not contain a header!4479347 does not contain a header!Entry 
4477267
Entry 
Entry 
5003334

For tsv, the tool fails with:
MMseqs Version:                  	f3b88f27def72ac5392131b98e079930f3b087c7
first sequence as respresentative	false
Target column                    	0
Add Full Header                  	false

Query file is x
Data file is x_clu 
Start writing file to x.tsv
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string::_S_construct null not valid
Aborted

This issue was also brought to the attention of Dr. Söding in a recent email 

Thank you, 

Irena

**Comment by milot-mirdita** [comment]
The clustering workflow creates a new sequence database (NEWMAPDB) that has consistent identifiers with already existing sequences in OLDDB.

All tools further down the pipeline expect NEWMAPDB as input and NEWDB can usually be deleted.

I'll update the documentation. Sorry for the confusion. Please let me know if you still have issues.

**Comment by i-lanc** [comment]
Thanks for the quick response!

I'm still a bit unclear on what is meant when you say a new sequence database (NEWMAPDB) is created. When I run updateclusters, it looks like the NEWMAPDB is now a soft link that links back to the NEWDB database file, rather than a new updated cluster database being created.

**Comment by milot-mirdita** [comment]
Yes, you are right. 
It only updates the `.index` files. The data files remain the same, so no deleting of the old files.

**Comment by i-lanc** [comment]
Ok, thank you. Unfortunately I am still not sure why my initial run failed. It had the following input, with a new unique name given for both the updated index files as well as the newly generated cluster. 

mmseq2 updatecluster Old_db New_db_with_updated_seq Old_cluster New_unique_name New_unique_cluster tmp_folder 

If necessary, I can provide the input files as they are a subset of public protein databases. 

Thanks, 

Irena

**Comment by milot-mirdita** [comment]
Your initial run did not work, because it was the wrong sequence database passed to `createtsv`.

We should probably give a better error message though.

**Comment by i-lanc** [comment]
Should NEWDB or NEWMAPDB be passed to createtsv?

**Comment by milot-mirdita** [comment]
NEWMAPDB

**Comment by i-lanc** [comment]
Trying out NEWMAPDB (soft link) in the following format
`mmseqs createtsv NEWMAPDB NEWMAPDB NEWCLUST NEWCLUST.tsv`

I receive the following error:
Start writing file to NEWCLUST_clu.tsv
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted

**Comment by milot-mirdita** [comment]
Could you please paste the whole command line invocation and output for both commands?
That might be a different issue after all.

**Comment by i-lanc** [comment]
Here is my initial clustering update:
`mmseqs clusterupdate Uniprot_Unreviewed_Zmays /home/ec2-user/MMSeqs2/Uniprot_Unreviewed_Zmays_Tomato_Dmagna_kmer20_results/Uniprot_Unreviewed_Zmays_Tomato_Dmagna Uniprot_Unreviewed_Zmays_clu Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWMAPDB Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWCLUST_clu ./tmp`

And the tsv generation:
`mmseqs createtsv ./Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWMAPDB Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWMAPDB Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWCLUST_clu Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWCLUST_clu.tsv`

tsv error message:
```
MMseqs Version:                         f3b88f27def72ac5392131b98e079930f3b087c7
first sequence as respresentative       false
Target column                           0
Add Full Header                         false

Query file is ./Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWMAPDB
Target file is Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWMAPDB
Data file is Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWCLUST_clu
Start writing file to Uniprot_Unreviewed_Zmays_updated_Tomato_Daphnia_NEWCLUST_clu.tsv
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted
```

**Comment by milot-mirdita** [comment]
Could you also post the output of `ls -la .` and `ls -la tmp`

I think I need the input sequences after all though.

**Comment by i-lanc** [comment]
After looking through the input results, I think I have an idea of what the issue might be. The new database consisted of the original database + a completely separate out-group, with no sequences that grouped at all with the original. Once I added in some new sequences that joined existing clusters, the code appeared to run without issue. 

Is it problematic to add a new database where the new sequences do not overlap at all with the original, otherwise it will lead to an error?

**Comment by milot-mirdita** [comment]
`clusterupdate` should give you an error and stop executing completely in that case. I am not sure why its not doing that.

**Comment by i-lanc** [comment]
I'm not able to recreate this error with other data sets with the same configuration (i.e. adding the same data set + a completely separate outgroup). I was able to get concatdbs to run properly, so other runs have worked without issue.
