### ISSUE TITLE
mmseqs2 cannot remove identical sequences in cluster or linclust

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#104]
## Expected Behavior
mmseqs2 should remove exactly identical sequences if I run linclust or cluster on the attached file.
[pdb_seqres.protein.fasta.gz](https://github.com/soedinglab/MMseqs2/files/2195016/pdb_seqres.protein.fasta.gz)

## Current Behavior
In both cluster and linclust, the result contains multiple entries with identical sequence "MGIFNGIIEFLSNINFEVIAQLTMIAMIGIAGPMIIFLLAVRRGNL" or "EVIAQLTMIAMIGIAGPMIIFLLAVRRGNL"

## Steps to Reproduce (for bugs)
```bash
mkdir -p mmseqs2_cluster
./mmseqs2/bin/mmseqs createdb pdb_seqres.protein.fasta mmseqs2_cluster/pdb_seqres.protein.DB
./mmseqs2/bin/mmseqs cluster mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.cluster /tmp/zcx/mmseqs2  --min-seq-id 0.9 --cov-mode 1 -c 0.9
./mmseqs2/bin/mmseqs createseqfiledb mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.cluster mmseqs2_cluster/pdb_seqres.protein.cluster.DB
./mmseqs2/bin/mmseqs result2flat mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.cluster.DB mmseqs2_cluster/pdb_seqres.protein.cluster.fasta
./mmseqs2/bin/mmseqs linclust mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.linclust /tmp/zcx/mmseqs2  --min-seq-id 0.9 --cov-mode 1 -c 0.9
./mmseqs2/bin/mmseqs createseqfiledb mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.linclust mmseqs2_cluster/pdb_seqres.protein.linclust.DB
./mmseqs2/bin/mmseqs result2flat mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.DB mmseqs2_cluster/pdb_seqres.protein.linclust.DB mmseqs2_cluster/pdb_seqres.protein.linclust.fasta
```

## MMseqs Output (for bugs)
[pdb_seqres.protein.cluster.fasta.gz](https://github.com/soedinglab/MMseqs2/files/2195015/pdb_seqres.protein.cluster.fasta.gz)
[pdb_seqres.protein.linclust.fasta.gz](https://github.com/soedinglab/MMseqs2/files/2195014/pdb_seqres.protein.linclust.fasta.gz)
The output is compressed by gzip as github does not support .fasta file.

## Context
I suspect this is because short sequence has a low alignment score. When you are estimating sequence identity according to alignment score, you will get false negative for short sequence.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): e3f80a7b0a32b1bc4122b73c045a9dd2f7da42e3
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): statically-compiled SSE4.1
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
Support SSE but not AVX2. 125G.
* Operating system and version:
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago

**Comment by kad-ecoli** [comment]
Here is the full output
[mmseqs_cluster.txt](https://github.com/soedinglab/MMseqs2/files/2195026/mmseqs_cluster.txt)

**Comment by kad-ecoli** [comment]
I think this is related to https://github.com/soedinglab/MMseqs2/issues/88
However, I do not think it is inconvenient to demand users to be aware of so many small tweaks. Also, I did not find the '-s' option in linclust. Cleaner solutions include:
1. mmseqs2 cluster and linclust include subroutine to merge identical sequences before the actual clustering
2. adjust alignment score - sequence identity calibration for short sequence.
I guess solution 1 is not that hard to implement.

**Comment by martin-steinegger** [comment]
@kad-ecoli thank you for reporting this issues. 

Yes, the issues is related to https://github.com/soedinglab/MMseqs2/issues/88. I do not find solution 1. very elegant since we do need more CPU time, IO and hard disk space.
If you do not mind this slight overhead than you could just run clusthash (see https://github.com/soedinglab/MMseqs2/wiki#how-to-redundancy-filter-sequences-with-identical-length-and-100-length-overlap). 

I will think about a more elegant solution for this problem.

**Comment by kad-ecoli** [comment]
Thanks for pointing to the clusthash stuff. Of course there is no free lunch in any additional feature. Since clusthash seems to be much faster than even linclust, maybe we can have it as an optional preprocessing step in cluster/linclust workflow.

**Comment by martin-steinegger** [comment]
@kad-ecoli I implemented a solution into linclust, which should not miss same sequences again for nearly zero costs. Could you please try the newest version and see if you still encounter this problem?

**Comment by kad-ecoli** [comment]
The problem seems to still occur if I use the static linux version (AVS). If you just update the github code but not the static linux version, could you rebuild the binaries?

**Comment by martin-steinegger** [comment]
@kad-ecoli Thank you for testing it. The static build should be always up to date. MMseqs2 always reports the commit id. Could you check if its the most recent commit. If yes than could you please provide an example so that I can reproduce your issuse?

**Comment by kad-ecoli** [comment]
MMseqs2 Version: 4eb5e14267f64f2fb337995bd824ef279e04f266

Input file:
[pdb_seqres.protein.fasta.gz](https://github.com/soedinglab/MMseqs2/files/2195016/pdb_seqres.protein.fasta.gz)

**Comment by martin-steinegger** [comment]
Thank you for uploading the example. I have tried your example and it results in two clusters and one clusters.

This call produces two clusters:

     mmseqs createdb pdb_seqres.protein.fasta pdb_seqres.protein
     mmseqs cluster pdb_seqres.protein pdb_seqres.protein_clu tmp --min-seq-id 0.9

This call produces just one cluster:

     mmseqs cluster pdb_seqres.protein pdb_seqres.protein_clu_1.0_v2 tmp --min-seq-id 1.0 --cov-mode 1 -c 0.9

**Comment by kad-ecoli** [comment]
I still have the same issue. The script to reproduce the issue is attached. Is this related to my incorrect invoke of createseqfiledb and/or result2flat?

[test_mmseqs2.sh.zip](https://github.com/soedinglab/MMseqs2/files/2326332/test_mmseqs2.sh.zip)

**Comment by martin-steinegger** [comment]
@kad-ecoli thank you for the script. If I run your script I end up with two clusters, which is expected because of the coverage mode. In default Linclust just clusters sequences with at least 80% bidirectional coverage. The maximum overlap in your example is 65%.

 If you want fragments to be clustered you need to add  `--cov-mode 1`. This turns on the unidirectional coverage. So the short sequence should be 80% covered. 

See also https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster

**Comment by kad-ecoli** [comment]
How do you check there are two clusters? There are far more entries in the resulting fasta file.

**Comment by martin-steinegger** [comment]
The `createseqfiledb` format contains all sequences. Each cluster starts with an entry that has two fasta headers. The structure of the format is described here https://github.com/soedinglab/MMseqs2/wiki#cluster-fasta-like-format.
Maybe you just want to have the representative sequences? 
You can extract the rep sequences with the following commands.
```
mmseqs result2repseq DB clu clu_rep
mmseqs result2flat DB DB clu_rep clu_rep.fasta --use-fasta-header
```
