### ISSUE TITLE
mmseq2 vs. blastp

### ISSUE THREAD

**Issue by yiming-gcm** [soedinglab/MMseqs2#107]
Recently I came across the tool you have developed: MMseqs2 and I have tested for the protein search. It is very fast comparing to blastp. However, I noticed the number of hit is about 1/3 of the blastp hit if I use the most sensitive parameter -s 7.5 and the same evalue cutoff 0.01. The target database is about 2M sequence and the query is 10K sequence. I noticed a lot of warning message was printed "Sequence 131 produces too many hits. Results might be truncated”. I have tried to change other parameters, such as —max-accept, but the situation does not change. It would be great if you could provide some information about how to produce all the hits as close as possible to blastp (with the same evalue cutoff), but much faster. Thanks.

**Comment by martin-steinegger** [comment]
Could you please explain how you compare blastp and MMseqs2? Could you please provide the hits that you can not find? 

We do not produce exactly the same hits than blast since we do use a different compositional bias correction. 

The warning "Sequence XXX produces too many hits. Results might be truncated" indicates that their are too many high scoring diagonal (> target database size / 2). So we can not order them perfectly. How often does this message occur?

**Comment by yiming-gcm** [comment]
My taget database contains about 2M sequence (from ~120 species) and my query database contains about 10K sequence (one species)

For blastp, I use blastp command with evalue cutoff 0.01 as following:
> blastp -db $db_blastp/AllDB -query $spe_fasta -out $spe_id.blastp.txt -evalue 0.01 -outfmt 6 -num_threads $num_cores
 
For mmseq2, I use 
> mmseqs search $mmseq_db_dir/$spe_id $mmseq_db_dir/AllDB $search_dir/$spe_id $tmp_dir --threads $num_cores -s 7.5 -e 0.01
Then I convert them to outfmt6, 
> mmseqs convertalis $mmseq_db_dir/$spe_id $mmseq_db_dir/AllDB $search_dir/$spe_id $outfmt6/$spe_id.mmseq.txt

Then I count the number of lines of the two output files. I noticed that blastp has about 3 times hits than mmseqs. 

The message “…too many hits” occurs very frequently and therefore I wondered mmseqs could identify the hits, but the results may be truncated.

**Comment by martin-steinegger** [comment]
We only report the top 300 hits as default. You need to increase `--max-seqs`. Also the e-value of `0.01` corresponds to an e-value of '0.1' in MMseqs2.

**Comment by yiming-gcm** [comment]
In total I have 2.2M sequences in the target DB and I set --max-seqs=3000000. It still prints the message "...too many hits". What else am I missing?

**Comment by milot-mirdita** [comment]
`--max-seqs=` should not work and give an error. You have to leave out the equal sign.

**Comment by yiming-gcm** [comment]
Yes, I mean --max-seqs 3000000

**Comment by martin-steinegger** [comment]
Did the --max-seqs reduce the difference between blastp and MMseqs2 a lot? 
Did you also use the '-e 0.1'? 

Could you give us some examples of sequences that can not be found please?

**Comment by yiming-gcm** [comment]
MMseqs (max-seqs=target DB size, evalue=0.1) produce more hits than blastp (max_target_seqs=target DB size, evalue=0.01). blastp has about 1% not found by MMseqs and MMseqs has about 5% not found by blastp. I think the difference was due to the cutoff sensitivity as most of hits not found by each other has the bitscore is around 50.  For my case, it takes about 5hours using 64 cores for MMseqs and 8 hours for blastp. The speed is not much faster than blastp. 

However, about 5% of the sequences still prints a lot of warning "sequence ... too many hits" even if I set max-seqs to the size of target DB for MMseqs. Do you know why? I think if all the hits are printed out, then it would find more hits. 

I noticed that MMseqs also produced more than HSPs. How could I limit to the best HSP? is this parameter --alt-ali for number of output HSP? 

One example, the pair was identified by blastp (evalue 0.01), not by MMSeqs (evalue 0.1): https://www.ebi.ac.uk/Tools/services/web/toolresult.ebi?jobId=emboss_needle-I20180724-094628-0802-32011448-p2m&context=protein&analysis=alignment

**Comment by acpguedes** [comment]
In my experience, MMseqs could be more faster if you index (mmseqs createindex) the database before the searches, like more than 10 times faster.

**Comment by martin-steinegger** [comment]
@acpguedes I do not think the indexing should take too much time in the case of @yiming-gcm. Because he uses sequence/sequence searches. 

@acpguedes Since you perform iterative search the index has to be  rebuild every iteration. Building the index several times and searching a small query sets leads to a high overhead.

**Comment by yiming-gcm** [comment]
@martin-steinegger Thanks for providing the help.
What I am looking for is: I have 2M sequences containing from ~100 species. For each of 2M sequence, I want to find out ALL the hits/similar sequences within the given threshold, such as evalue 0.01, NOT the best hit. 
I tested the following approach: 
First I build the targetDB using 2M sequence. Then I created the index. Then for each query species (~20K sequence), I created the queryDB, then I use MMseqs search with the parameters --max-seqs num_DB_Seq, -s 7.5 -e 0.01

The program call is:
~/db_mmseqs/10141 ~/db_mmseqs/AllDB ~/db_mmseqs/tmp/8799019798690856849/pref_7.5 --sub-mat blosum62.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 2264996 --offset-result 0 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 
--min-ungapped-score 15 --spaced-kmer-mode 1 --pca 1 --pcb 1.5 --threads 64 -v 3 -s 7.5 

How long do you think it takes for 64 cores to get the results for 2M vs. 2M sequences with all the possible hits?

**Comment by martin-steinegger** [comment]
Could you also provide the log please?  The `--max-seqs num_DB_Seq` slows down the search.

**Comment by yiming-gcm** [comment]
Is the following what you need?

Program call:
~/seq_data/fasta/10141.fasta ~/seq_data/db_mmseqs/10141 

MMseqs Version:      	a6fadb4b083af4575e9117d4b405128051468c1e
Max. sequence length 	65535
Split Seq. by len    	true
Offset of numeric ids	0
Verbosity            	3

.Time for merging files: 0h 0m 0s 4ms
Time for merging files: 0h 0m 0s 5ms
Time for merging files: 0h 0m 0s 6ms
Time for merging files: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 225ms
Program call:
~/seq_data/db_mmseqs/10141 ~/seq_data/db_mmseqs/AllDB ~/seq_data/search/10141 ~/seq_da
ta/db_mmseqs/tmp --threads 64 --max-seqs 2264996 -s 7.5 -e 0.1 

MMseqs Version:                    	a6fadb4b083af4575e9117d4b405128051468c1e
Sub Matrix                         	blosum62.out
Add backtrace                      	false
Alignment mode                     	2
E-value threshold                  	0.1
Seq. Id Threshold                  	0
Seq. Id. Mode                      	0
Alternative alignments             	0
Coverage threshold                 	0
Coverage Mode                      	0
Max. sequence length               	65535
Max. results per query             	2264996
Compositional bias                 	1
Realign hit                        	false
Max Reject                         	2147483647
Max Accept                         	2147483647
Include identical Seq. Id.         	false
No preload                         	false
Early exit                         	false
Pseudo count a                     	1
Pseudo count b                     	1.5
Score bias                         	0
Threads                            	64
Verbosity                          	3
Sensitivity                        	7.5
K-mer size                         	0
K-score                            	2147483647
Alphabet size                      	21
Offset result                      	0
Split DB                           	0
Split mode                         	2
Split Memory Limit                 	0
Diagonal Scoring                   	1
Exact k-mer matching               	0
Mask Residues                      	1
Minimum Diagonal score             	15
Spaced Kmer                        	1
Mask profile                       	1
Profile e-value threshold          	0.001
Use global sequence weighting      	false
Filter MSA                         	1
Maximum sequence identity threshold	0.9
Minimum seq. id.                   	0
Minimum score per column           	-20
Minimum coverage                   	0
Select n most diverse seqs         	1000
Omit Consensus                     	false
Min codons in orf                  	30
Max codons in length               	32734
Max orf gaps                       	2147483647
Contig start mode                  	2
Contig end mode                    	2
Orf start mode                     	0
Forward Frames                     	1,2,3
Reverse Frames                     	1,2,3
Translation Table                  	1
Use all table starts               	false
Offset of numeric ids              	0
Add Orf Stop                       	false
Number search iterations           	1
Start sensitivity                  	4
Search steps                       	1
Sets the MPI runner                	
Remove Temporary Files             	false

Program call:
~/seq_data/db_mmseqs/10141 ~/seq_data/db_mmseqs/AllDB ~/seq_data/db_mmseqs/tmp/8799019798690856849/pref_7.5 --sub-mat blosum
62.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 2264996 --offset-result 0 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 
--min-ungapped-score 15 --spaced-kmer-mode 1 --pca 1 --pcb 1.5 --threads 64 -v 3 -s 7.5 

MMseqs Version:           	a6fadb4b083af4575e9117d4b405128051468c1e
Sub Matrix                	blosum62.out
Sensitivity               	7.5
K-mer size                	0
K-score                   	2147483647
Alphabet size             	21
Max. sequence length      	65535
Max. results per query    	2264996
Offset result             	0
Split DB                  	0
Split mode                	2
Split Memory Limit        	0
Coverage threshold        	0
Coverage Mode             	0
Compositional bias        	1
Diagonal Scoring          	1
Exact k-mer matching      	0
Mask Residues             	1
Minimum Diagonal score    	15
Include identical Seq. Id.	false
Spaced Kmer               	1
No preload                	false
Early exit                	false
Pseudo count a            	1
Pseudo count b            	1.5
Threads                   	64
Verbosity                 	3

Initialising data structures...
Using 64 threads.
Use index  ~/seq_data/db_mmseqs/AllDB.sk6
Index version: 7
Generated by:  a6fadb4b083af4575e9117d4b405128051468c1e
KmerSize:     6
AlphabetSize: 21
Type:         1
Spaced:       1
KmerScore:    0
SequenceType: 0
Headers:      0
ScoreMatrix:  blosum62.out
Substitution matrices...
Use kmer size 6 and split 1 using Target split mode.
Needed memory (16780554175 byte) of total memory (304045634764 byte)
Target database: ~/seq_data/db_mmseqs/AllDB(Size: 2264995)
Query database type: Aminoacid
Target database type: Aminoacid
Time for init: 0h 0m 3s 994ms
Query database: ~/seq_data/db_mmseqs/10141(size=18106)
Process prefiltering step 1 of 1

k-mer similarity threshold: 73
k-mer match probability: 0

Starting prefiltering scores calculation (step 1 of 1)
Query db start  1 to 18106
Target db start  1 to 2264995

**Comment by martin-steinegger** [comment]
Yes, could you please upload the whole log as file. I need to see the exact runtimes of the prefilter and alignment in order to reason about it.

**Comment by yiming-gcm** [comment]
[mmseqs.log](https://github.com/soedinglab/MMseqs2/files/2240955/mmseqs.log)

**Comment by martin-steinegger** [comment]
Thanks a lot for the log!

The prefilter takes 15 minutes, while the alignment runs for 4.5 hours. I think your `--max-seqs` is way to high since in average only 4000 hits are accepted by the alignment. You could reduce `--max-seqs` to 100.000 without losing many, if any at all, hits. 

Another tweak is using the property of the prefilter results, that they are already well sorted and distinguish well between homologs and non-homologs. It is possible to reduce the run time without losing many, if any, hits of the alignment by using the `--max-rejected` parameter. It stops aligning after `N` consecutive rejected alignments (alignments that do not fulfill the alignment criteria). You could try `--max-rejected 10.`  

Another tweak would be to increase the `--min-ungapped-score`. I have never really optimized this parameter. It could lead to a huge gains in speed for the alignment by rejecting prefilter hits more strictly. Try `--min-ungapped-score 30`.

You mentioned in an email that you also tested DIAMOND and it was less sensitive. Could you please give us your comparison results?

**Comment by yiming-gcm** [comment]
DIAMOND missed about 1/3 of blastp hits, but it takes about 10 mins, while for blastp, it takes 8 hours to generate the blastp hits. For MMseqs with -s 5.7, it takes about 1 hours to generate the results and it missed about 15% of blastp and gain 5% more hits than blastp. For MMseq with -s 7.5, it takes about 5 hours, it missed about 3% of blastp hits and gain 10% more hits than blastp.

**Comment by acpguedes** [comment]
For iterative searches, 3 iterations at least, it's seems that mmseqs retrieve more sequences than psi-blast. Anyway you can see some differences that could be explained by bias composition, that's why I include Jackhmmer in comparision, since Jackhmmer use HMM instead PSSM and have diferent bias composition.

> mmseqs search example.db /databases/mmseqs/all.mmseqs example_found.db tmp/ --e-profile 0.001 -k 7 -s 7 -a -e 10 --threads  --max-seqs 17702628 --alignment-mode 3 --num-iterations 3    
>  
> time psiblast -query  -db /databases/fadb/freeze/all.fa -evalue 10  -num_iterations 3 -num_alignments 17702628 -num_descriptions 17702628 -inclusion_ethresh 0.001  -num_threads    
>  
> time jackhmmer --cpu  -N 3 -E 10 --incE   /databases/fadb/freeze/all.fa    

The number of alignments was:  
- mmseqs = 155565  
- psi-blast = 162250  
- jackhmmer = 965722  
but the number of sequences was:  
- mmseqs = 155565  
- psi-blast = 147355  
- jackhmmer = 231779  
  
The query was a multi domain proteins that could lead to higher number of hits.  

[Sample_size_1_Report_size_17702628_e-value_10.pdf](https://github.com/soedinglab/MMseqs2/files/2245886/Sample_size_1_Report_size_17702628_e-value_10.pdf)

**Comment by martin-steinegger** [comment]
@yiming-gcm were you able to test any of my recommendations to improve the speed of mmseqs?

**Comment by yiming-gcm** [comment]
sorry to the late response. it did improve the speed. Thanks.

**Comment by zhaoxvwahaha** [comment]
> We only report the top 300 hits as default. You need to increase `--max-seqs`. Also the e-value of `0.01` corresponds to an e-value of '0.1' in MMseqs2.

@martin-steinegger 
Hi, could you give me some advice for the following questions? 
I used the  MMseqs2 Version: 24f6b52a38cd8cf66d10ce00bf37dc815fef986e-MPI
I would like to get the same or more sensitive result than PSI-blast, the commond I used for PSI-blast is :
psiblast -query query.faa -db database -evalue 0.001 -outfmt 6 -out psiblast.out
So how could I set the parameter of MMseqs2:
(1) evalue 0.001 of PSI-blast corresponds to evalue 0.01 of MMseqs2, right?
(2) the default -num_iterations of PSI-blast is 1, that corrsponds to 2 in MMseqs2? more this parameter, more sensititive ?
(3) default -max_target_seqs is 500 for PSI-blast, the --max-seqs of MMseqs2 is [0.000], that means output all hits? the --max-seqs is the number of different subjects or just the HSP for each query?

Thanks in advance.
