### ISSUE TITLE
using many profiles

### ISSUE THREAD

**Issue by SilasK** [soedinglab/MMseqs2#108]
Hello, I have a question: is there a way to map a set of proteins to a *set of profiles*? Doing this using one by one and converting the output to m8- files adds a lot of overhead. 

As I understand you do this during the cluster algorithm. I would have pre-clustered proteins, and I want to map proteins to the cluster, which is the closest.

**Comment by martin-steinegger** [comment]
Are your profiles in the MMseqs2 clusters format? If yes than you can update the cluster database by following the next steps.

(0) search the profiles against the set of new proteins.
(1) use `swapresults` to get mapping of protein to profile.
(2) use `filterdb ... --extract-lines 1` to extract the top hit for each protein. 
(3) trim only the first column since the cluster format just has only the sequence identifier. This can be done with `fliterdb ... --trim-to-one-column`.
(4) swap again to get a profile (cluster) to  protein mapping `swapresults`.
(5) use `mergedbs` to combine your old database with your new database.

This is really hardcore mmseqs internal knowledge. We will offer a MMseqs2 tutorial at the ECCB18 if you want to learn more about its internals.

**Comment by milot-mirdita** [comment]
We talked about your problem, this solution won't quite work yet (at least the last step). We will think about something on Monday and update you.

**Comment by milot-mirdita** [comment]
Hi @SilasK, sorry again for the delay.
Could you expand a bit on what you want to achieve?
(1) Do you want to "update" your profiles, by adding new sequences to that profile?
This is a bit tricky, we would need to provide something similar to the cluster updating, but for a search  instead. The tricky part is, that the sequence databases of the profiles and the new sequences have to be merged first, while retaining the profile identifiers.

(2) Do you just want to know what profile this protein should belong to? Step (0) to (2) is already enough for that.

I can look into (1), if this is what you need. I am a bit busy with another paper submission currently, so I might need some time.

**Comment by SilasK** [comment]
Thank you for your response
I’m interested in (2) knowing to which profile each protein belongs. 

So I will try steps (0)-(2). Do I still have to put the profiles in a specific format?

**Comment by milot-mirdita** [comment]
What format are they currently in?

**Comment by milot-mirdita** [comment]
I misunderstood your initial post. So the full workflow, would be something like this:

For this small set of profiles you also don't need the swap. You can search directly against the profiles.
Query-side profiles becomes useful for millions of them. The target-side profile search can still handle a few 100k profiles without exploding in memory.

```
mmseqs createdb queries.fasta queries
mmseqs msa2profile stockholm profiles
mmseqs search queries profiles result tmpDir -k 5
mmseqs filterdb result best --extract-lines 1
mmseqs convertalis queries profiles best best.tsv
```

See [this](https://github.com/soedinglab/MMseqs2/wiki#how-to-create-a-target-profile-database-from-pfam) section in the wiki for more details.

**Comment by SilasK** [comment]
I red trough the section in the doc, but I don’t know how I should use my my targets  (target_1.fasta … target_10000.fasta).

**Comment by martin-steinegger** [comment]
@SilasK could you solve the problem?

**Comment by SilasK** [comment]
Hello @martin-steinegger, not completely. 
I would like to find a way to merge different profiles/msa in one database. I realized that one can put multiple msa in one Stockholm formatted file, but I didn't manage to made it work. mmseqs took only the first msa from my Stockholm formatted file. Maybe I have some formatting issues. 

- Is this the way to go?
- Where does mmseqs take the name from, which metadata line?  For now, it names the profile according to the first seq which is not that useful. 

For me it

**Comment by SilasK** [comment]
I think I got it working.

I used the GF AC metadata for the name of the profile.

**Comment by martin-steinegger** [comment]
Thanks for letting us know. 
@milot-mirdita is this something we should add to the documentation?

**Comment by martin-steinegger** [comment]
It depends on your use case. If your profiles are query centric than you can use mmseqs to create the profiles. Mmseqs alignment is a center star alignment which does not allow gaps in the query sequence. 

     mmseqs search query target aln tmp -a
     mmseqs result2profile query target aln prof 

If you need a protein family representation than creating profiles from MSAs makes more sense. 

      mmseqs search query target aln tmp
      mmseqs createseqfiledb target aln alnseq
      mmseqs apply alnseq alnseqmsa — msaaligner
