### ISSUE TITLE
MMseqs2 different number of clusters for each run with same parameter

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [soedinglab/MMseqs2#110]
## Expected Behavior
Same number of clusters and singletons for multiple number of runs with same parameters

## Current Behavior
I had run MMseqs2 clustering multiple time with same default parameters on same data set and staring with empty directory every time, I end up with different no of multi member clusters(>2) and singletons every time I run MMseqs2 clustering with default parameters.

**Point to be noted**: 
I have added --cascaded term to the default command-line, will that effect my results for each run.

mmseqs createdb dataset.fa DB
mkdir tmp
mmseqs cluster DB clu tmp/ --cascaded
mmseqs createtsv DB DB clu clu.tsv

Let me know, if you need any additional information.

Regards,
Vijay N

**Comment by martin-steinegger** [comment]
Thank you for reporting this issues. Could please update your MMseqs2 version, the --cascaded flag does not exists anymore in the current version of mmseqs. We already fixed the stability issues of the clustering.

**Comment by narsapuramvijaykumar** [comment]
Thank you martin, I will update my copy of MMseqs.
If  I was using the old version of MMseqs, how bad do you think the clusters can be..?

**Comment by martin-steinegger** [comment]
The cluster should be good as well but the clustering was not stable. Meaning it might not be exactly reproducible.
