### ISSUE TITLE
Sensitivity stepping in search 

### ISSUE THREAD

**Issue by mooreryan** [soedinglab/MMseqs2#112]
Quick question regarding https://github.com/soedinglab/MMseqs2/issues/107#issuecomment-407433121 and https://github.com/soedinglab/mmseqs2/wiki#how-to-find-the-best-hit-the-fastest-way.

The wiki says

> Queries are only used again in the next iteration, if no match could be found that fulfilled the acceptance criteria in the previous iteration.

So let's say I run this command....

```
$ mmseqs search queries subjects out tmp -e 0.001 -c 0.8 --cov-mode 0 --min-seq-id 0.3 --start-sens 1 --sens-steps 7 -s 7
```

Then would my acceptance criteria for each step be 30% sequence identity over 80% of aligned residues (of query and target) with evalue of < 0.001?  I.e., if there was a hit with evalue 0.000001 but only 25% identity then that query would be passed on to the next round, but a query with a hit of 50% identity over 85% of length and evalue 0.00001 would NOT get pushed through to the next round.  Is that right?

Also, then would my final output file only have "hits" that are at least 30 % identity over 80% of the alignment and under 0.001 for evalue?

**Comment by martin-steinegger** [comment]
Thanks for the question! 
Yes this is right your final output should only contain hits with 30% identity, over 80% bidirectional coverage and an e-value of < 0.0001
