### ISSUE TITLE
impact of the sequence order in input file

### ISSUE THREAD

**Issue by matgachet** [soedinglab/MMseqs2#115]
﻿Hello,

I am working with mmseqs2, I was asking myself about the order of fasta files when I use the command mmseqs _createdb / cluster_.

I observed some little differences if I change the order of fasta sequences on the command _createdb_.

Command line :

I used these commands :
 
   - _mmseqs createdb --dont-shuffle (true/false) file.faa panproteome.db_

   - _export TMP_DIR=$(mktemp -d ) && mmseqs cluster panproteome.db families.db ${TMP_DIR} --min-seq-id 0.8 -c 0.8 --threads 2 --kmer-per-seq 80 --max-seqs 300 && rm -rf ${TMP_DIR}_

  - _mmseqs createtsv panproteome.db panproteome.db families.db families.tsv --first-seq-as-repr true_

I use : _MMseqs2 Version: 5.9375b_

I took a dataset (available in the attachment) for an example and I have this result :

results :
		
	order 1 :
		dont-shuffle : false  -> cluster numbers :4296
		dont-shuffle : true  -> cluster numbers :  4290

	order 2 :
		dont-shuffle : false -> cluster numbers : 4297
		dont-shuffle : true -> cluster numbers :  4298

Is it an expected result to obtain different number of cluster depending on fasta sequence order ?

Attachment : fasta sequences ( 2 different order) and clustering files (families.tsv) for each condition.
[results.tar.gz](https://github.com/soedinglab/MMseqs2/files/2379387/results.tar.gz)

**Comment by martin-steinegger** [comment]
@matgachet Clustering algorithms have an exponential number of possibilities to cluster the connectivity graph. Therefore a change of variables (i.e. input order) affects the outcome of the clustering.

We can only guarantee that the clustering is consistent between multiple runs of MMseqs2 with the same parameters (including input).
