### ISSUE TITLE
Filterdb command in wiki for getting best result when mapping

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#122]
In the [wiki](https://github.com/soedinglab/MMseqs2/wiki#mapping-very-similar-sequences-using-mmseqs-map) when using `filterdb` should be 2 DBs instead of 4. With this command targetDB gets overwritten:

`mmseqs filterdb queryDB targetDB resultDB bestResultDB --extract-lines 1`

and `filterdb` help:

`Usage: <i:resultDB> <o:resultDB> [options]`

**Comment by milot-mirdita** [comment]
Fixed, thanks a lot!
