### ISSUE TITLE
Could not open profile_seq_h.index.126 for writing!

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [soedinglab/MMseqs2#128]
Hello 

I am having an issue while trying to create profiles from alignments. I am using NOG trimmed alignments, only a few of them. 
I convert them to stockholm first with esl-reformat from HMMER 
esl-reformat stockholm NOG.COG0016.clustalo_trimmed.fa > COG0016.sto
Then :
mmseqs convertmsa COG0016.sto COG0016_db
mmseqs msa2profile COG0016_db COG0016_profile

At the last step, for the profile creation I get an error message : 
Could not open COG0016_profile_seq_h.index.126 for writing!

Here are the logs : [COG0016.log](https://github.com/soedinglab/MMseqs2/files/2465789/COG0016.log)

Whichever file I am using I always get this particular index 126. Also I used sudo for permission it does not change anything. Well, there is also a full collections of empty files appearing... just around 1021

## Steps to Reproduce (for bugs)
I am adding all intermediary files, though github doesn't let me upload things with exotic extensions, so I had to rename all of them by appending .txt at the end.

wget http://eggnogdb.embl.de/download/eggnog_4.5/data/NOG/NOG.trimmed_algs.tar.gz
tar -xzf  NOG.trimmed_algs.tar.gz
mv NOG_trimmed_algs/NOG.COG0016.clustalo_trimmed.fa ../
[NOG.COG0016.clustalo_trimmed.fa.txt](https://github.com/soedinglab/MMseqs2/files/2465875/NOG.COG0016.clustalo_trimmed.fa.txt)
esl-reformat stockholm NOG.COG0016.clustalo_trimmed.fa > COG0016.sto
[COG0016.sto.txt](https://github.com/soedinglab/MMseqs2/files/2465876/COG0016.sto.txt)
mmseqs convertmsa COG0016.sto COG0016_db
[COG0016_db.txt](https://github.com/soedinglab/MMseqs2/files/2465877/COG0016_db.txt)
[COG0016_db.index.txt](https://github.com/soedinglab/MMseqs2/files/2465879/COG0016_db.index.txt)
mmseqs msa2profile COG0016_db COG0016_profile

It would be cool if you could help me with that.

Best,

Seb

**Comment by milot-mirdita** [comment]
The `msa2profile` module creates 8 files per thread and since your machine seems to be using `192` threads, its easily hitting the default maximum open files per process limit on your system.

Check your current softlimit (`ulimit -Sn`) and hardlimit (`ulimit -Hn`) of open files and then increase the soft limit to about 2048 (`ulimit -Sn 2048`). That should allow msa2profile to complete successfully.

I will add something to handle this issue more gracefully in the future.

**Comment by Sebastien-Raguideau** [comment]
Hi,

Thanks. Though finally I did something slightly different. Maybe you can advise me on it. 

Do you reckon importing exterior alignment is equivalent to running mmseq on the COG sequences against themselves and then creating a profile out of it? 

Here an example : 
mmseqs createdb COG0016.faa COG0016_db > log_COG0016 2>&1 
mmseqs search  COG0016_db COG0016_db COG0016_AL /mnt/ramdisk/seb_temp --num-iterations 2 > log_COG0016 2>&1
mmseqs result2profile COG0016_db COG0016_db COG0016_AL COG0016_profile	> log_COG0016 2>&1

Best,
Seb

**Comment by milot-mirdita** [comment]
Hi Seb,
That would create a search database of about 2500 times the same profile.

Don't you want to have each eggNOG group as a separate profile?
Something like the following command would create one concatenated STOCKHOLM file of all MSAs in the eggNOG, which then can be passed to `convertmsa` and `msa2profile` (together with the increased ulimit):

```
find NOG_trimmed_algs -type f -name "*.fa" -exec sh -c "printf '# STOCKHOLM 1.0\n#=GF AC   %s\n' \"\$(basename \"{}\" .fa)\" >> NOG_trimmed_algs.sto;  esl-reformat pfam {} | tail -n +3 >> NOG_trimmed_algs.sto" \;
```

Does this help?

Best regards,
Milot
