### ISSUE TITLE
Profile fails when trying to cluster using profiles 

### ISSUE THREAD

**Issue by ctSkennerton** [soedinglab/MMseqs2#131]
## Expected Behavior
I'm trying to follow the workflow in the readme for [clustering using profiles](https://github.com/soedinglab/MMseqs2/wiki#how-to-cluster-using-profiles) but I keep getting the following error during the `search` step.
## Current Behavior
```
Could not get realpath of cog0303.fa_DB_CLU_0.7_0.5_repseq_h!
Error: Create profile died
```

## Steps to Reproduce (for bugs)

```
wget ftp://ftp.ncbi.nih.gov/pub/wolf/COGs/COG0303/cog0303.fa
touch cog0303.fa
mmseqs2/bin/mmseqs createdb cog0303.fa cog0303.fa_DB
mmseqs2/bin/mmseqs cluster cog0303.fa_DB cog0303.fa_DB_CLU_0.7_0.5 /tmp -s 6 --min-seq-id 0.7 -c 0.5 --cluster-mode 1
mmseqs2/bin/mmseqs createsubdb cog0303.fa_DB_CLU_0.7_0.5 cog0303.fa_DB cog0303.fa_DB_CLU_0.7_0.5_repseq
mmseqs2/bin/mmseqs search cog0303.fa_DB_CLU_0.7_0.5_repseq cog0303.fa_DB_CLU_0.7_0.5_repseq cog0303.fa_DB_CLU_0.7_0.5_repseq_search /tmp --num-iterations 3 --add-self-matches
mmseqs2/bin/mmseqs clust cog0303.fa_DB_CLU_0.7_0.5_repseq cog0303.fa_DB_CLU_0.7_0.5_repseq_search cog0303.fa_DB_CLU_0.7_0.5_repseq_search_clust --cluster-mode 1 -s 6
```

## Your Environment
I'm running this in an EC2 c5.4xlarge instance with the following OS information
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
MemTotal=31897300 kB
```
I downloaded MMseqs2 Release 6-f5a1c from github with the SSE4.1 version of the binary.

Any idea what I'm doing wrong?

**Comment by altaetran** [comment]
I had this issue too!

**Comment by martin-steinegger** [comment]
You also need to create a header database. 

mmseqs2/bin/mmseqs createsubdb cog0303.fa_DB_CLU_0.7_0.5 cog0303.fa_DB_h cog0303.fa_DB_CLU_0.7_0.5_repseq_h

We should change the default behavior for createsubdb.

**Comment by ctSkennerton** [comment]
thanks, it worked
