### ISSUE TITLE
taxonomy convertkb not mapping

### ISSUE THREAD

**Issue by shandley** [soedinglab/MMseqs2#132]
## Expected Behavior
Attempting to run to convert annotation mapping file
mmseqs convertkb uniprot_sprot_trembl.dat.gz targetDB.mapping --kb-columns OX --mapping-file targetDB.lookup

## Current Behavior
Can not find accession in mapping:

Could not find accession Q6P378 in mapping!
Could not find accession P34974 in mapping!
Could not find accession Q9Z1S9 in mapping!

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

1) Downloaded all viral proteins from UniProtKB
2) Created target DB with UniProtKB entries

mmseqs createdb target.fasta targetDB

3) Confirmed targetBD.lookup format
0	H8YHR3
1	A0A0E3HJU1
2	A0A0M3M679
3	A0A142IHD3
4	A0A1D8Q0G9
5	I3XPF8
6	Q66N09
7	D5XLT2
8	D9IRE9
9	Q50BU6

4) Downloaded and concatenated uniprot_sprot_trembl.dat.gz

5) Ran:
mmseqs convertkb uniprot_sprot_trembl.dat.gz targetDB.mapping --kb-columns OX --mapping-file targetDB.lookup

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by martin-steinegger** [comment]
Thanks for reporting this issue. I have reworked the taxonomy. I will adjust the documentation tomorrow.

**Comment by martin-steinegger** [comment]
I have updated the wiki. Sorry for the delay. I will build a more convenient way to create taxonomical databases soon.

**Comment by martin-steinegger** [comment]
I have added a createtaxdb tool which should help to add taxonomical information to a sequence database. I have also added it the documentation. Please let me know if you encounter any problems. https://github.com/soedinglab/MMseqs2/wiki#taxonomy-assignment-using-mmseqs-taxonomy
