### ISSUE TITLE
Crash on easy-cluster with files with >50,000 sequences

### ISSUE THREAD

**Issue by josemduarte** [soedinglab/MMseqs2#136]
I've got a file with about 200,000 sequences. When running mmseqs2 `easy-cluster` like this:
```
mmseqs easy-cluster test.fasta out.db tmp --min-seq-id 1.00 -c 0.90 -s 8 --max-seqs 1000 --cluster-mode 1 --threads 6
```
the program crashes with:
```
*** Error in `/opt/mmseqs2/bin/mmseqs': munmap_chunk(): invalid pointer: 0x00007f4554305010 ***
```
If I subselect some sequences from the file into another file, everything works fine up to about 50,000-60,000 sequences. With any number of sequences above that, the crash happens consistently. The crash does not seem to depend on a certain input but only on the size of the input.

The crash __does not__ happen with version 3-be8f6, but it does happen with any version after that.

## MMseqs Output (for bugs)
This is the part of the output where the crash happens:
```
Program call:
kmermatcher tmp/16988974474605539078/input tmp/16988974474605539078/clu_tmp/2433631712707271207/linclust/8168197228582123863/pref --sub-mat blosum62.out --alph-size 13 --min-seq-id 1 --kmer-per-seq 21 --mask 0 --cov-mode 0 -k 0 -c 0.9 --max-seq-len 65535 --hash-shift 5 --split-memory-limit 0 --include-only-extendable 0 --skip-n-repeat-kmer 0 --threads 6 -v 3

MMseqs Version:                      	1c7ad90e2a9a249cbe4858b5002dc052b3333475
Sub Matrix                           	blosum62.out
Alphabet size                        	13
Seq. Id Threshold                    	1
Kmer per sequence                    	21
Mask Residues                        	0
Coverage Mode                        	0
K-mer size                           	14
Coverage threshold                   	0.9
Max. sequence length                 	65535
Shift hash                           	5
Split Memory Limit                   	0
Include only extendable              	false
Skip sequence with n repeating k-mers	0
Threads                              	6
Verbosity                            	3

Database type: Aminoacid
V -> I
M -> L
Q -> E
T -> S
R -> K
Y -> F
S -> A
N -> D
Reduced amino acid alphabet:
A C D E F G H I K L P W X

Needed memory (24649184 byte) of total memory (30364135833 byte)
Process file into 1 parts
Generate k-mers list 0
.......
Time for fill: 0h 0m 0s 364ms
Done.
Sort kmer ... Done.
Time for sort: 0h 0m 0s 202ms
Sort by rep. sequence ... Done
Time for sort: 0h 0m 0s 150ms
Time for fill: 0h 0m 0s 8ms
Time for merging files: 0h 0m 0s 38ms
*** Error in `/opt/mmseqs2/bin/mmseqs': munmap_chunk(): invalid pointer: 0x00007fa2ba2b7010 ***
Aborted
Error: kmermatcher died
Error: linclust died
Error: Search died
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used: 1c7ad90e2a9a249cbe4858b5002dc052b3333475
* Which MMseqs version was used: AVX2 static
* Server specifications: 32GB RAM
* Operating system and version: Ubuntu Linux 16.04.3

**Comment by martin-steinegger** [comment]
Thank you for the report. Could you please provide the file?

**Comment by josemduarte** [comment]
Here is the [full file](https://drive.google.com/file/d/1SI5ODslZeELYWcRsuL58XT5v_UOArwdr/view?usp=sharing). 

I tested by subselecting sequences out of that file. 

For instance the crash happens with this file:
```
head -90000 test.fasta > test-90000.fasta
```
whilst it doesn't happen with this other file:
```
head -89000 test.fasta > test-89000.fasta
```

**Comment by martin-steinegger** [comment]
Thank you for the file. I can not reproduce the bug. 
Could you compile mmseqs2 with debug flags and send me the back trace? 

      cmake -DCMAKE_BUILD_TYPE=Debug ..
      make -j 6
      gdb --args kmermatcher tmp/16988974474605539078/input tmp/16988974474605539078/clu_tmp/2433631712707271207/linclust/8168197228582123863/pref --sub-mat blosum62.out --alph-size 13 --min-seq-id 1 --kmer-per-seq 21 --mask 0 --cov-mode 0 -k 0 -c 0.9 --max-seq-len 65535 --hash-shift 5 --split-memory-limit 0 --include-only-extendable 0 --skip-n-repeat-kmer 0 --threads 6 -v 3

After GDB started type `r` an after it crashed `bt`.

**Comment by josemduarte** [comment]
I've tried this:
```
gdb --args ~/git/MMseqs2/build/bin/mmseqs kmermatcher tmp/14020823439690622662/input tmp/14020823439690622662/clu_tmp/13817195423418140833/linclust/5869534598694216613/pref --sub-mat blosum62.out --alph-size 13 --min-seq-id 1 --kmer-per-seq 21 --mask 0 --cov-mode 0 -k 0 -c 0.9 --max-seq-len 65535 --hash-shift 5 --split-memory-limit 0 --include-only-extendable 0 --skip-n-repeat-kmer 0 --threads 6 -v 3
```
and this is what I'm getting:
```
Thread 1 "mmseqs" received signal SIGSEGV, Segmentation fault.
0x00007ffff68c1c01 in __GI___libc_free (mem=0x7ffff3152010) at malloc.c:3123
3123	malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff68c1c01 in __GI___libc_free (mem=0x7ffff3152010) at malloc.c:3123
#1  0x000055555569ea2c in DBReader<unsigned int>::close (this=0x7fffffffdd90) at /home/jose/git/MMseqs2/src/commons/DBReader.cpp:353
#2  0x000055555572f571 in kmermatcher (argc=32, argv=0x7fffffffe1b8, command=...) at /home/jose/git/MMseqs2/src/linclust/kmermatcher.cpp:479
#3  0x0000555555692a63 in runCommand (p=..., argc=32, argv=0x7fffffffe1b8) at /home/jose/git/MMseqs2/src/commons/Application.cpp:62
#4  0x000055555569328d in main (argc=34, argv=0x7fffffffe1a8) at /home/jose/git/MMseqs2/src/commons/Application.cpp:135
```

**Comment by martin-steinegger** [comment]
Thank you for the backtrace. I have added a fix for a memory issue. Could you please try the newest version?

**Comment by josemduarte** [comment]
I've tried the full easy-cluster run again and it works great, thanks for the quick fix!
