### ISSUE TITLE
E-value maximum threshold not applied properly during iterative searches

### ISSUE THREAD

**Issue by ChiaraVanni** [soedinglab/MMseqs2#137]
### Expected Behaviour
MMSEQS2 should return only hits with an e-value lower or equal to the maximum threshold set using the -e option in iterative searches.

### Current Behaviour
MMSEQS2 returns also hits with higher e-values.

This behaviour is not observed during a non-iterative search, where the e-value maximum threshold is properly applied.

### Steps to Reproduce (for bugs)
mmseqs createdb QUERY.fasta queryDB
mmseqs createdb DB.fasta targetDB
mmseqs search queryDB targetDB resultDB tmp  --num-iterations 2 --threads 8 -e 1e-20 

### MMseqs Output (for bugs)
LOG file: mmseqs_261118.log
here https://gist.github.com/ChiaraVanni/53a4477436c8c05aa708c2eda90ef6cc

### Your Environment
Include as many relevant details about the environment you experienced the bug in.

Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): **7427bfa0d8b7d2b7540cb8b86f37a763be998709**
Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): self-compiled
For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: cmake version 3.10.12 and gcc version 5.4.0
Server specifications (especially CPU support for AVX2/SSE and amount of system memory): Running in a machine with 80 cores and 2Tb
Operating system and version: Linux 4.9.0-8-amd64 x86_64, Debian GNU/Linux 9

**Comment by martin-steinegger** [comment]
Thanks for reporting this! 
It should be fixed now
