### ISSUE TITLE
Large integer values in aln_length and mismatch output columns

### ISSUE THREAD

**Issue by hoelzer** [soedinglab/MMseqs2#138]
Hi, 

we just run an easy-search of a lncRNA database (FASTA) against a large indexed genome (FASTA) with default parameters and got the following output:

`└─> head mlu.aln 
lnc-SEMA6A-5:1	MLU_1_162	0.679	575	176	0	197	746	49406	49980	3.015E-45	189

lnc-TPCN2-6:1	MLU_8_38	0.780	99	21	0	44	142	32699	32796	1.421E-10	71

lnc-TPCN2-6:1	MLU_29_27	0.776	76	17	0	45	120	43884	43959	1.365E-07	62

lnc-TPCN2-6:1	MLU_336_6	0.791	67	14	0	35	101	56475	56541	8.884E-07	59

lnc-TPCN2-6:1	MLU_1044_0	0.783	4294967215	4294967279	0	144	62	48340	48415	1.658E-06	58

lnc-TPCN2-6:1	MLU_185_31	0.760	4294967203	4294967274	0	144	50	16903	16995	5.779E-06	56

lnc-TPCN2-6:1	MLU_36_80	0.840	50	8	0	44	93	21998	22047	1.079E-05	55

lnc-PLCD3-1:14	MLU_593_1	0.776	4294966671	4294967157	0	627	1	30011	30633	2.583E-130	472

lnc-PLCD3-1:14	MLU_593_1	0.823	4294967107	4294967263	0	826	636	29811	30000	1.599E-41	177

LINC00658:1	MLU_54_59	0.764	4294967162	4294967265	0	767	632	26985	27124	2.375E-18	99`

What are the large numbers in the aln_length and mismatch columns? 

Thx!

EDIT: Maybe this occurs because we tried to search nucleotide queries against a nucleotide database, what the tool is maybe not intended for?

**Comment by martin-steinegger** [comment]
Yes, the nucl/nucl search is still experimental. We do not support indexed nucleotide sequences yet. Do you want to align nucleotide/nucleotide or six-frame/six-frame?

**Comment by hoelzer** [comment]
ok, we wanted to align a multi-fasta nucleotide file against another multi-fasta nucleotide file. Therefore, we indexed nucleotide sequences and maybe due to this we got this strange high integer values in the output columns

**Comment by martin-steinegger** [comment]
you can just try to run it without the index.

**Comment by hoelzer** [comment]
will give it a try, thanks!

**Comment by martin-steinegger** [comment]
We do have indexed nucleotide searches now

**Comment by hoelzer** [comment]
Great, thanks for the Info!

Martin Steinegger <notifications@github.com> schrieb am Sa., 20. Apr. 2019,
00:57:
