### ISSUE TITLE
non standard fasta file created by "mmseqs result2flat"

### ISSUE THREAD

**Issue by jhcepas** [soedinglab/mmseqs2#14]
## Expected Behavior
a fasta file with all the singleton sequences produced by a clustering analysis

## Current Behavior
a non-standard fasta file where header lines are duplicated 

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.
```
$mmseqs cluster all_proteomes.db cluster.db tmp
$ mmseqs createseqfiledb all_proteomes.db cluster.db cluster.seq --max-sequences 1
$ mmseqs result2flat all_proteomes.db all_proteomes.db cluster.seq cluster.fasta
$ head cluster.fasta
>10090.00080
>10090.00080
MKSFLLFLTIILLVVIQIQTGSLGQATTAASGTNKNSTSTKKTPLKSGASSIIDAGACSFLFFANTLMCLFYLS
>10090.00273
>10090.00273
MARARQEGSSPEPVEGLARDSPRPFPLGRLMPSAVSCSLCEPGLPAAPAAPALLPAAYLCAPTAPPAVTAALGGPRWPGGHRSRPRGPRPDGPQPSLSPAQQHLESPVPSAPEALAGGPTQAAPGVRVEEEEWAREIGAQLRRMADDLNAQYERRRQEEQHRHRPSPWRVMYNLFMGLLPLPRDPGAPEMEPN
```
## Your Environment
Using latest github version of mmseqs compiled on a AVX system
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 88d72a91b63690f4001a2da0528a02781fd8e8c1
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): self-compiled
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): AVX
* Operating system and version: Linux

**Comment by elsherbini** [comment]
I believe the flat-file is not a fasta file per se. It is a file with the following format:

>cluster_1_id
>cluster_1_member_1_id
cluster_1_member_1_sequence
>cluster_1_member_2_id
cluster_1_member_2_sequence
>cluster_2_id
>cluster_2_member_1_id
...

So everytime you see two lines starting with a >, that is the start of a new cluster. In the two that you show, it looks like both those clusters only had one sequence in them.

**Comment by jhcepas** [comment]
I see, thanks!
It would be useful to have a FASTA-export feature.

**Comment by ksteczk** [comment]
For those still interested: I found that
`cat that_strange_output.fa |grep --no-group-separator -B 1 '^[^>]'`
produces regular fasta file.

**Comment by ksteczk** [comment]
I briefly wrote a short perl command to translate mmseqs' "strange fasta" into regular fasta with one representative per cluster:
`perl -nlE 'if(/^>/){if(! $c){$c=0;}if($c==1){print $_;$p=1;}$c++;}else{$c=0;if($p){print $_;}undef $p}' <INPUT_FILE> > <OUTPUT_FASTA>`
and it seems to be working for now.
