### ISSUE TITLE
Unable to generate TSV

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#140]
## Expected Behavior
Get a customised TSV with results from search 

## Current Behavior
Don't generate output, instead generate a large amount of empty files with this name:
pbps_pdb_found.tsv.1
pbps_pdb_found.tsv.2
...
pbps_pdb_found.tsv.35
AND
pbps_pdb_found.tsv.index.1
....
pbps_pdb_found.tsv.index.35

## Steps to Reproduce (for bugs)
mmseqs createdb pbps_pdb.fa pbps_pdb.DB  
mmseqs createdb /databases/fadb/pdbaa.fa pdbaa.DB  
mmseqs search pbps_pdb.DB pdbaa.DB pbps_pdb_found.out tmp --num-iterations 3 --start-sens 5.5 --sens-steps 1 -s 7.5 --threads 15 --max-seqs $(grep -c "^>" /databases/fadb/pdbaa.fa )  
mmseqs convertalis pdbaa.DB pbps_pdb.DB pbps_pdb_found.out pbps_pdb_found.tsv --format-output "query,target,evalue,nident,bits,qstart,qend,qcov,tstart,tend,tcov"

## MMseqs Output (for bugs)
Program call:
convertalis pdbaa.DB pbps_pdb.DB pbps_pdb_found.out pbps_pdb_found.tsv --format-output query,target,evalue,nident,bits,qstart,qend,qcov,tstart,tend,tcov 

MMseqs Version:        	3265a001da7fc13c09daef39c58128d31c6086a7
Sub Matrix             	blosum62.out
Alignment Format       	0
Format alignment output	query,target,evalue,nident,bits,qstart,qend,qcov,tstart,tend,tcov
Translation Table      	1
Gap open cost          	11
Gap extension cost     	1
Database Output        	false
Preload mode           	0
Threads                	36
Verbosity              	3

Query Header database: pdbaa.DB_h
Touch data file pdbaa.DB_h ... Done.
Target database: pbps_pdb.DB
Touch data file pbps_pdb.DB_h ... Done.
Alignment database: pbps_pdb_found.out
Start writing to pbps_pdb_found.tsv
Invalid database read for database data file=Invalid database read for database data file=Invalid database read for database data file=Invalid database read for database data file=Invalid database read for database data file=Invalid database read for database data file=Invalid database read for database data file=Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.index
getData: local id (4294967295) >= db size (501)
pbps_pdb.DB_h, database index=Invalid database read for database data file=pbps_pdb.DB_h, database index=Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexInvalid database read for database data file=pbps_pdb.DB_h, database index=Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexInvalid database read for database data file=pbps_pdb.DB_h, database index=Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexInvalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexInvalid database read for database data file=pbps_pdb.DB_h, database index=Invalid database read for database data file=Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexInvalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexInvalid database read for database data file=Invalid database read for database data file=pbps_pdb.DB_h, database index=Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.indexpbps_pdb.DB_h, database index=Invalid database read for database data file=pbps_pdb.DB_h.index
getData: local id (Invalid database read for database data file=pbps_pdb.DB_h, database index=pbps_pdb.DB_h.index
getData: local id (4294967295) >= db size (501)

getData: local id (4294967295) >= db size (501)

## Your Environment

MMseqs2 Version: 3265a001da7fc13c09daef39c58128d31c6086a7ls

**Comment by milot-mirdita** [comment]
Can you try swapping the order of the sequence databases in convertalis:
convertalis pbps_pdb.DB pdbaa.DB

Generally, they should be passed in the same order as in search.

**Comment by acpguedes** [comment]
Ho, sorry.
Thanks
