### ISSUE TITLE
BLAST output problem with version 5877873cbcd50a6d954607fc2df1210f8c2c3a4b

### ISSUE THREAD

**Issue by tberner** [soedinglab/MMseqs2#142]
## Expected Behavior
Identical results except the column “tend”.
Correct BLAST output format.

## Current Behavior
Problems:
A)	The number of hits differs for both version 
B)	In the output of the new version "." appears in the blast format output file (taln column) and  additional line breaks for some hits (see attached output files)
The old version produced the correct BLAST output form except a bug in “tend”. 
The new version fixed the bug, but does not produce correct BLAST output (format).

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

parameter setting for both runs:
-e 100.0 --threads 1 -s 8.5 -a --comp-bias-corr 0 --max-seqs 500 --mask 0 --orf-start-mode 1

input query file:
[input_sequence.txt](https://github.com/soedinglab/MMseqs2/files/2657225/input_sequence.txt)

input target file:
https://www.arabidopsis.org/download_files/Genes/TAIR10_genome_release/TAIR10_chromosome_files/TAIR10_chr_all.fas

## MMseqs Output (for bugs)
[old_version.txt](https://github.com/soedinglab/MMseqs2/files/2657223/old_version.txt)
[new_version.txt](https://github.com/soedinglab/MMseqs2/files/2657224/new_version.txt)

## Your Environment
Ubuntu 14.10 (GNU/Linux 3.16.0-43-generic x86_64)

MMseqs:
Old version: 4e23d5f1d13a435c7b6c9406137ed68ce297e0fc
New version: 5877873cbcd50a6d954607fc2df1210f8c2c3a4b:

**Comment by martin-steinegger** [comment]
I tried to reproduce the issue. The `converalis` step for tblastn searches using an indexed is broken. 

```
mmseqs createdb input_sequence.txt query
mmseqs createdb TAIR10_chr_all.fas target
mmseqs createindex target tmp  --comp-bias-corr 0 --mask 0
mmseqs search query target aln_index tmp  -e 100.0 --threads 24 -s 8.5 -a --comp-bias-corr 0 --max-seqs 500 --mask 0 --orf-start-mode 1
mmseqs convertalis query target aln_index aln.m8 --format-output query,target,qstart,qend,tstart,tend,qaln,taln
```

Searching without an index returns the correct results 

[result.txt](https://github.com/soedinglab/MMseqs2/files/2659435/result.txt)

```
mmseqs createdb input_sequence.txt query
mmseqs createdb TAIR10_chr_all.fas target
mmseqs search query target aln_index tmp  -e 100.0 --threads 24 -s 8.5 -a --comp-bias-corr 0 --max-seqs 500 --mask 0 --orf-start-mode 1
mmseqs convertalis query target aln_index aln.m8 --format-output query,target,qstart,qend,tstart,tend,qaln,taln
```

I would recommend to search without a index for tblastn searches until this issues is resolved.

**Comment by JensKeilwagen** [comment]
Thanks a lot for that hint. We have used this now for a while and it works.
Do you plan to fix the problem with indexed db?

**Comment by martin-steinegger** [comment]
Yes, we will fix it with the next versions. We will release it this month.

**Comment by martin-steinegger** [comment]
This should be fixed by now.
