### ISSUE TITLE
no DB to sam file conversion?

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#143]
According the main `mmseqs` help doc (mmseqs2   v7.4e23d):

```
convertalis       	Convert alignment DB to BLAST-tab format, SAM flat file, or to raw pairwise alignments
```

However, `mmseqs convertalis` doesn't actually seem to have any option for generating a SAM file. Am I just missing this feature in the `mmseqs convertalis` docs or maybe the help docs need to be updated?

**Comment by milot-mirdita** [comment]
We were meaning to implement that format, though that never happened. We will update the description text.

**Comment by martin-steinegger** [comment]
@nick-youngblut I haved added beta support for SAM. "samtools view" seems to be able to verify the format. I have not yet figured out how to best compute a mapq value.

**Comment by nick-youngblut** [comment]
Awesome! Thanks for adding SAM support! I'll give it a try ASAP. The mapq question is a good one. Sorry that I can't be of help with that.

**Comment by nick-youngblut** [comment]
I'm getting the following error when creating the sam file and then converting to a bam via 
`samtools view -b -h {input.sam} > {output.bam}`: 

```
[E::sam_parse1] CIGAR and query sequence are of different length
[W::sam_read1] Parse error at line 740584
[main_samview] truncated file.
```

mmseqs version: 8.fac81

For the alignment, I'm using:

```
mmseqs search -a --alignment-mode 4 
  --threads {threads} -s 2 -c 0.9 --cov-mode 2 \
  {input.reads_db} {input.genes_db} \
  {output.db} {output.tmp_dir}
```

For conversion of the alignment db to sam, I'm using:
```
mmseqs convertalis \
  --threads {threads} \
  --format-mode 1 \
  {input.query_db} {input.target_db} {input.aln_db} \
  {output.sam}
```

**Comment by martin-steinegger** [comment]
@nick-youngblut interesting. I never tested --alignment-mode 4 with sam. Thank you for pointing it out!

**Comment by martin-steinegger** [comment]
--alignment-mode 4 should work with sam
