### ISSUE TITLE
old wiki docs?: mmseqs createfasta

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#145]
The mmseqs2 wiki mentions `mmseqs createfasta`, but for `MMseqs2 Version: 7.4e23d`, I don't see any `createfasta` subcommand. Is the documentation out of date or is `createfasta` accessed via some other method besides an mmseqs subcommand?

**Comment by martin-steinegger** [comment]
Thank you for pointing this out. We removed `createfasta` and replaced it with `createtsv`. 
 I have rewritten part of the documentation, explaining the database formats and how to convert them more in detail.
