### ISSUE TITLE
"there must be an error" messages while clustering

### ISSUE THREAD

**Issue by rattei** [soedinglab/mmseqs2#15]
While clustering a database of about 10 million proteins, we receive lots of "there must be an error" messages, e.g.:

there must be an error: 1835775 deleted from 4496505 that now is empty, but not assigned to a cluster
there must be an error: 6964402 deleted from 7957737 that now is empty, but not assigned to a cluster
there must be an error: 2422408 deleted from 2413081 that now is empty, but not assigned to a cluster
...

This is the script running the clustering:
```
MMSEQS=mmseqs-static_avx2
SEQFILE=eggnog4.proteins.core_periphery.fa.gz
pigz -dc $SEQFILE >$TMPDIR/db.fasta
$MMSEQS createdb $TMPDIR/db.fasta $TMPDIR/db
mkdir $TMPDIR/clutmp
$MMSEQS cluster $TMPDIR/db $TMPDIR/db_clu $TMPDIR/clutmp --cascaded -e 1 --threads 16
```

The effect is independent from the mmseqs2 binary (your static avx2 binary, self-compiled sse4.1 binary). We run Fedora 25 with 4.9.5 kernel. The machine has 40 cores and 1 TB RAM.

Thanks for your help,
Thomas Rattei

**Comment by martin-steinegger** [comment]
Hi Thomas, 

thank you for reporting this bug. There is indeed an issues with using '--diag-mode 0', which is used automatically at the first cascaded clustering step. I temporarily switched it to '--diag-mode 1'. Diagonal mode 0 is turning off the ungapped alignment stage and changes the score to a probability over the sum of all double diagonal kmer matches. The change to  '--diag-mode 1' will not affect the quality of the clustering.

I will fix the '--diag-mode 0' in the next days. 

Best regrads,
Martin

**Comment by rattei** [comment]
Hi Martin,

thanks for the quick advice. Will now use --diag-mode 1 and will inform you if there are further issues.

Best,
Thomas

**Comment by rattei** [comment]
Hi Martin,

I just recognized that mmseqs cluster only has a diag-score option, which already defaults to 1. No diag-mode option there. Should I change the diag-score option or is diag-mode a compile option that I should modify?

Best,
Thomas

**Comment by milot-mirdita** [comment]
Hi Thomas,

Martin pushed an update earlier. Just pull the latest version and try again. You don't have to change anything else.

Best,
Milot

**Comment by rattei** [comment]
Hi Milot,

thanks for the super-quick fix. Have tried it with the new version and we don't get any error messages anymore :)

Best,
Thomas

**Comment by rattei** [comment]
Hi Martin, hi Milot,

I am currently playing around with the cascaded clustering of the SIMAP sequences. So far I failed in really modifying the sensitivity of the clustering. I could not use the --alph-size and --sub-mat parameters, get always errors like "Could not find statistics for  gapopen 11 and gapextend 1".

Is it impossible to combine --alph-size and --sub-mat with --cascaded, as in the example below?
... --cascaded -s 7.5 --alph-size 11 --sub-mat blosum45.out -k 7 ...
(the matrix file blosum45.out was downloaded from the mmseqs2 repo)

I've tried to figure this out with the manual, but could not find out what I did wrong.

Thanks for your help,
best wishes
Thomas

**Comment by milot-mirdita** [comment]
Hi Thomas,

Just a heads-up: Martin, who should be able to help you, is on vacation until next week.

About the sub-mat parameter: Everything except blosum62 is pretty untested. Also supplying a custom score matrix won't work yet, since we rely on some pretrained hard-coded values (BlastScoreUtils.cpp).

You should probably only tweak the -s, -c and --min-seq-id (and maybe --min-ungapped-score) parameters.

Best regards,
Milot

**Comment by rattei** [comment]
Dear Milot,

thanks for the quick reply. It helps me a lot, and I will for the moment prevent the less tested options. Will stick to BL62 for the moment, and will play with the options you've mentioned.

Best wishes,
Thomas

**Comment by martin-steinegger** [comment]
Dear Thomas, 

I fixed the issues with diag-score 0 and rolled back to the original clustering workflow. Could you please test if the issues is solved? Thanks a lot.

Best regards,
Martin

**Comment by rattei** [comment]
Dear Martin,

thanks! Have checked out the latest code and it works fine :)

Best,
Thomas

**Comment by martin-steinegger** [comment]
I have included the feature to change the substition matrix (see https://github.com/soedinglab/MMseqs2/issues/20).

**Comment by rattei** [comment]
Hi Martin,

great, thanks for the notice. We'll definitely explore this option.

Best,
Thomas
