### ISSUE TITLE
Understanding cluster using profiles

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#151]
I tried  [cluster using profiles](https://github.com/soedinglab/MMseqs2/wiki#how-to-cluster-using-profiles) using this [test dataset](https://github.com/soedinglab/MMseqs2/files/2765258/subset.txt).

I performed this procedure:

> mmseqs createdb subset.fa subset.db
> mmseqs prefilter subset.db subset.db subset.prefilter.db -s 8.5
> mmseqs align subset.db subset.db subset.prefilter.db subset.align.db --min-seq-id 0.9
> mmseqs clust subset.db subset.align.db subset.clust.db
> 
> mmseqs createsubdb subset.clust.db subset.db subset.90.db
> mmseqs prefilter subset.90.db subset.90.db subset.90.prefilter.db -s 8.5
> mmseqs align subset.90.db subset.90.db subset.90.prefilter.db subset.20.aling.db --min-seq-id 0.2 
> mmseqs clust subset.90.db subset.20.aling.db subset.20.clust.db
> 
> mmseqs mergeclusters subset.db final_clu subset.clust.db subset.20.clust.db 
> mmseqs createtsv subset.db subset.db final_clu final_clu.tsv
> mmseqs result2profile subset.db subset.db final_clu final_clu.profile 
> mmseqs search final_clu.profile final_clu.profile_consensus final_clu.profile.DB2 tmp --add-self-matches 
> mmseqs clust final_clu.profile final_clu.profile.DB2 final_clu.profile.clu 
> mmseqs createtsv final_clu.profile final_clu.profile.clu final_clu.profile.clu.tsv

In the end I got this [meaningless tsv](https://github.com/soedinglab/MMseqs2/files/2765314/final_clu.profile.clu.txt).

I didn't understand this tsv which is different from those created with simple cluster of proteins.

I'd like to know if I did something wrong or how to understand this file.

Thanks in advance

**Comment by martin-steinegger** [comment]
You need to change the last line from
      
      mmseqs createtsv final_clu.profile final_clu.profile.clu final_clu.profile.clu.tsv

to
  
      mmseqs createtsv final_clu.profile final_clu.profile final_clu.profile.clu final_clu.profile.clu.tsv 

If you just use one sequence database than it only maps the first column to an identifier.

**Comment by acpguedes** [comment]
Thanks a lot.

Also, I'd like to know if profile generated from search output (simple search, seqs against seqs) can include HSP from some same sequence in different profiles.
I mean, if some protein has 2 domains and two different queries matches with each domain (query 1 -> domain 1; query 2 -> domain 2), the two profiles generated at the end will include the same protein?

**Comment by milot-mirdita** [comment]
Martin implemented the `--alt-ali` parameter a while ago, so that one query can find multiple domains on one target. However, I am not 100% sure if it also works with profiles.

For your question however: Different queries are always handled independently and will generate profiles independently from each other. The case you described will be handled automatically.

**Comment by acpguedes** [comment]
Thanks @martin-steinegger & @milot-mirdita
