### ISSUE TITLE
Question : clustering several fastq

### ISSUE THREAD

**Issue by jupollet** [soedinglab/MMseqs2#154]
Hi,
in another tools ( https://github.com/ggautreau/PPanGGOLiN ) it refer to MMseqs2 and talk about clustering several genome as FASTA/FASTQ and output a TSV for use in their tools.
In your documentation I only see clustering for one FASTA/FASTQ at a time.
How can I cluster 8 fastq together with MMseqs2 ?

thanks

**Comment by martin-steinegger** [comment]
@jupollet it is possible to use more arguments for createdb 

    mmseqs createdb input1.fasta input2.fastq input3.fasta ... outputdb
    mmseqs cluster outputdb clu tmp 
    mmseqs createtsv  outputdb outputdb clu clu.tsv

**Comment by jupollet** [comment]
Thank you !
