### ISSUE TITLE
mmseqs tsv2db

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#155]
`mmseqs tsv2db` doesn't create a *.dbtype file. Is this intentional? How do I create a *.dbtype file, given that it appears to be a binary file?

In general, I find the "hidden" requirements of extra files such as the *.dbtype and *.index files to be very frustrating, because it can be hard to know which files are actually required for each `mmseq` command versus which files are stated as required inputs. This is especially challenging when using pipeline software such as `snakemake`.

```
$ conda list
# packages in environment at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/plass:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
curl                      7.63.0               h74213dd_0    conda-forge
gawk                      4.2.1                h470a237_0    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.63.0               hbdb9355_0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0                h5b517e9_3    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
mmseqs2                   7.4e23d              h21aa3a5_1    bioconda
ncurses                   6.1                  hfc679d8_2    conda-forge
openmp                    7.0.0                h2d50403_0    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pigz                      2.3.4                         0    conda-forge
plass                     2.c7e35              h21aa3a5_1    bioconda
samtools                  1.9                  h8ee4bcc_1    bioconda
tk                        8.6.9                ha92aebf_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by milot-mirdita** [comment]
`dbtype` is a recent development that is going to help a lot with usability with some planned enhancements, such as automatic validation of input database types (which is a huge usability pitfall currently). `tsv2db` needs a flag to specify what the output dbtype is supposed to be. I'll add that soon.

The requirement for the indexed database format (the file itself and the corresponding `.index` files) exist since the beginning of mmseqs' development. There is no other feasible solution to fast linear and random access in millions or billions of entries that we are currently handling. 

How can we improve the user experience with regards to workflow management systems in your view?

**Comment by alpapan** [comment]
I think the most helpful way is to use the basename of the relevant files and let mmseq find the associated files automatically (enforcing therefore naming using the conventions). 

For example, we don't need to specify mydb.ffdata and mydb.ffindex, just specify mydb

Would that help?

**Comment by milot-mirdita** [comment]
Pretty much every module does take the base names of the databases. One of the few modules where you CAN give it the .index is `createsubdb`, but it also takes the base name and resolves it to the file it actually needs. Did we miss anything?

**Comment by nick-youngblut** [comment]
Yeah, I think the base names helps. It would also be helpful if the help doc for each subcommand listed which files are needed for input (eg., *.index and *.dbtype) and which files will be written. 

At times, I found out the hard way that a certain subcommand doesn't create all files for the next step in the mmseqs workflow that I'm running, so I have to figure out how to create them after getting the error message stating that I need them (eg., Issue #146)

**Comment by martin-steinegger** [comment]
@nick-youngblut we check the compatibility of the input database in each module. I hope this reduces usability problems.

**Comment by nick-youngblut** [comment]
@martin-steinegger thanks for checking!
