### ISSUE TITLE
not sure if createdb finished correctly and cluster not found outputDB

### ISSUE THREAD

**Issue by jupollet** [soedinglab/MMseqs2#157]
Hi,

when I run this command to create my fastq database the processus stopped always when it reached 362 Mio sequences processed.
`mmseqs createdb $(find /media/sf_a8de220a-fde1-4b79-8b3f-c186f59a249a/NO
DAT/data/FASTQ/cas | grep '.fastq$')  /media/sf_a8de220a-fde1-4b79-8b3f-c186f59a249a/NODAT/result/MMSEQS2/casDB `

362 Mio. sequences processed
..........................................Processus arrêté

After, when I run clustering 

`mmseqs cluster /media/sf_a8de220a-fde1-4b79-8b3f-c186f59a249a/result/MMSEQS2/casDB clust_casDB tmp`

I get this error : 

`/media/sf_NODAT/result/MMSEQS2/casDB not found`

In my output folder I have several casDB.X casDB.index.X and casDB_h casDB_h.dbtype casDB_h.index.0 but no casDB .

**Comment by milot-mirdita** [comment]
Thats definitely wrong.

Is about 362 million the expected number of total FASTQ entries? Could you post the whole log? Was there anything written to stderr?

How much RAM does your machine have?

**Comment by jupollet** [comment]
No, I expected more than 566 million of total FASTQ entries. I just clear the log .. but anything else written to sterr just the number of sequences processed.
I am in VirtualBox Ubuntu 16.04 and have 10Go of RAM.

**Comment by milot-mirdita** [comment]
You definitely need more RAM. Half a billion sequences will require 24GB for reading in the database alone.

Linclust, the first clustering step, will not be a limiting factor, but the steps afterwards will be. Depending on how well linclust is able to reduce your dataset, the MMseqs2 prefilter will require up to 500GB RAM for optimal speed, though it will be able to run with much less at a slightly reduced speed.

If you only require linclust quality of clustering (down to 50% sequence identity), then 32GB RAM might be enough. For clustering such a large number of sequences with the full MMseqs2 clustering workflow (<50% sequence identity) we recommend at least 64GB to 128GB RAM compute nodes.

**Comment by acpguedes** [comment]
@milot-mirdita I had similar issue. Actually, prefilter step using all NCBI nr (~180M sequences) crash with me in a 180GB RAM server. Of course might be better reducing the database ~70% identity.

Anyway, I never tried but there are `--split-memory-limit` command. Does it work to control memory usage, or you recommend some other strategy to use large size DBs in environments with limited resources?

**Comment by martin-steinegger** [comment]
180 Million sequences should not crash on 180 GB. Could you open an issue for this? MMseqs2 uses the system memory as upper limit in default. The upper limit can be controlled with --split-memory-limit

**Comment by milot-mirdita** [comment]
createdb should need about 24 byte per sequence to track the creation of the index, which when explodes on the machine with 10GB ram apparently. 

@acpguedes We recently clusterd 2 billion sequences on 128GB nodes, however also with a bit of pain. `--split-memory-limit` will help. However the description message is wrong, the parameter expects kilobyte of memory not megabyte. Try running with about 70% of your RAM.

**Comment by jupollet** [comment]
I understand better , thank you for your explanations.

**Comment by acpguedes** [comment]
@martin-steinegger  and @milot-mirdita , thanks. I'll try carefully and if I had problem I'll open a issue reporting you.
