### ISSUE TITLE
Problems compiling MMseqs2

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#158]
Hi
I am trying to compile the MPI version of MMseqs2 and I am getting the following [error](https://gist.github.com/genomewalker/ff89e56ea3435429f9d76f43e1646ca8) 

## Expected Behavior
Should compile without errors
## Current Behavior
Fails with:
```
src/CMakeFiles/mmseqs-framework.dir/build.make:1598: recipe for target 'src/CMakeFiles/mmseqs-framework.dir/linclust/kmerindexdb.cpp.o' failed
make[2]: *** [src/CMakeFiles/mmseqs-framework.dir/linclust/kmerindexdb.cpp.o] Error 1
CMakeFiles/Makefile2:459: recipe for target 'src/CMakeFiles/mmseqs-framework.dir/all' failed
make[1]: *** [src/CMakeFiles/mmseqs-framework.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
## Steps to Reproduce (for bugs)
```
cmake -DHAVE_MPI=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=. ..
make
```
## MMseqs Output (for bugs)
Full error log [here](https://gist.github.com/genomewalker/ff89e56ea3435429f9d76f43e1646ca8) 
## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): fe2b746e63519424f565b4fbeb4ca5dba905adc7
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): Self-compiled
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
GCC: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
OPENMPI: (OpenRTE) 1.10.2
CMAKE: 3.5.1
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): Intel Xeon Processor (Skylake, IBRS) with 256GB ()
* Operating system and version: Ubuntu 5.4.0-6ubuntu1~16.04.10

**Comment by milot-mirdita** [comment]
Thanks for the bug report. MMseqs2 MPI should compile again in git master.

@martin-steinegger please review 7835260463bf8e4fc2b08096b55668e40a906033

**Comment by genomewalker** [comment]
Hi Milot
Working perfectly now :-)
Thank you very much
Antonio

**Comment by martin-steinegger** [comment]
Looks good Milot. Thank you!
