### ISSUE TITLE
createsubdb creating database but not with entries from filter file

### ISSUE THREAD

**Issue by shafferm** [soedinglab/MMseqs2#162]
## Expected Behavior
A database will be created that is a filtered version of the master database.

## Current Behavior
The new database includes only copies of an entry in the original index which is not in the filter file and is repeated for number of ids present in filter file.

## Steps to Reproduce (for bugs)
I am able to reproduce with a small 8 sequence fasta file which is a subset of an old uniref90 download and a single entry filter file.
[uniref90_head.fasta.gz](https://github.com/soedinglab/MMseqs2/files/2847259/uniref90_head.fasta.gz)
[uniref90_head_subset.txt](https://github.com/soedinglab/MMseqs2/files/2847255/uniref90_head_subset.txt)
```
mmseqs createdb uniref90_head.fasta uniref90_head.mmsdb
mmseqs createsubdb uniref90_head_subset.txt uniref90_head.mmsdb uniref90_head.subset.mmsdb
mmseqs createsubdb uniref90_head_subset.txt uniref90_head.mmsdb_h uniref90_head.filt.mmsdb_h
```
Then the resulting uniref90_head.filt.mmsdb_h only has a single entry (UniRef90_Q197F8 Uncharacterized protein 002R n=1 Tax=Invertebrate iridescent virus 3 TaxID=345201 RepID=002R_IIV3 
) which is from the fasta but not the id from the filter file (UniRef90_Q6GZX2).

## MMseqs Output (for bugs)
No errors given. Only run times.

## Context
I am trying to implement a reciprocal best hits approach. I am searching a fasta file of genes against a uniref90 fasta file. Both are fasta's of amino acids. The forward search (query=genes, target=uniref) goes fine and the reverse search (query=uniref, target=genes) works fine with the full database. Reciprocal best hits were found. To speed up the reverse search I wanted to filter uniref to only include the best hits from the forward search. To do this I used `createsubdb` with the top hits from the forward search as the filter file. The search (query=filtered uniref, target=genes) ran successfully but no alignments were found. Based on this I investigated the _h file from the sub-database and saw the problem.

## Your Environment
Used on a CentOS 7 server and installed via conda. Version is 7.4e23d.

**Comment by martin-steinegger** [comment]
You can not use the fasta header identifier. The `createsubdb` uses the internal numeric identifer given by `createdb`. 
I think it would be a great if MMseqs2 could support reciprocal best hit searches. Would you be willing to share you script? Here is the way I would script it.

     mmseqs search seqDbA seqDbB alnRes tmp 
     # extract top hit
     mmseqs filterdb alnRes alnResFilter --extract-lines 1
     # transpose the result A->B changes to B->A
     mmseqs swapdb alnResFilter alnResFilterSwaped 
     # extract subset of detected sequences from seqDbB
     mmseqs createsubdb alnResFilterSwaped.index seqDbB seqDbBSubdb  
     mmseqs createsubdb alnResFilterSwaped.index seqDbB_h seqDbBSubdb_h
     # perform second search 
     mmseqs search seqDbBSubdb seqDbA alnRes tmp 
    ... TODO check if detected from search A -> B and B-> A are the same

**Comment by shafferm** [comment]
Okay. I didn't realize that. I assumed from the wiki page with `createsubdb` grabbing from the index could be equivalent to the fasta file headers.

Your way is about what I was doing but with some intermediate python code for extra filtering. First I filter out all hits in the forward search which didn't meet a set bitscore threshold. Could I do this easily with `filterdb`? Next if a query sequence had multiple best hits with the same bitscore in the forward search then I retained all those target sequences for the reverse search. It's an edge case but could be important with our annotation pipeline. On my tests on real data we do see query sequences with multiple best hits when bitscores are less than ~90. Your script is a great first try though. Really clears up how to use the `filterdb` and `createsubdb` commands for me.

**Comment by milot-mirdita** [comment]
To filter the alignment result taking only lines that have a  score (`filter-column 2`) greater equal  (`comparison-operator ge`) to score-threshold (`comparison-value`) you can use:
```
mmseqs filterdb --filter-column 2 --comparison-operator ge --comparison-value score-threshold
```

Filtering by a query specific threshold would also be possible in a somewhat roundabout way:
```
mmseqs apply alnRes1 alnResTargetValue -- awk '{ compute something on each line } END { print a fake alignment result that has the value you want to filter by the score column }'
mmseqs mergedbs alnRes1 alnResMerged alnResTargetValue alnRes1
mmseqs filterdb alnResMerged alnResOut --filter-column 2 --comparison-operator ge --beats-first
```
The `apply` step has some overhead since it starts a new process for each query, but its easier than writing a specialized MMseqs2 module.

**Comment by milot-mirdita** [comment]
We provide a reciprocal best hit workflow now with `mmseqs rbh`.
