### ISSUE TITLE
Avoid index after query seq name & Deal with MPI parameter. 

### ISSUE THREAD

**Issue by Grindell** [soedinglab/MMseqs2#163]
Hi, 

Here are the following settings I used in order to get a .m8 file. 

```
mmseqs2=/beegfs/home/TOOLS/mmseqs2/bin/mmseqs
$mmseqs2 createdb\
 /path/species.fa\
 /path/species_mmseqs2_db
$mmseqs2 search\
 /path/species_mmseqs2_db\
 /path1/path2/refseq/viral_queries_seq/mmseq_db\
 /path1/path2/species/result_mmseqs2\
 /path1/path2/species/tpm -a -s 7.5 -e 0.1
$mmseqs2 convertalis\
 /path/species_mmseqs2_db\
 /path1/path2/refseq/viral_queries_seq/mmseq_db\
 /path1/path2/species/result_mmseqs2\
 /path1/path2/species/result_mmseqs2_db.m8
```

and here is the head file.m8 I get: 

```
scaffold_2855_1	YP_009173613.1	0.742	377	96	1	55020	53895	70	446	1.803E-180	566
scaffold_2855_1	YP_004091438.1	0.729	377	101	1	55020	53895	66	442	2.282E-173	546
scaffold_2855_1	YP_007676312.1	0.721	377	104	1	55020	53895	65	441	4.321E-170	536
scaffold_2855_0	YP_093986897.1	0.683	376	119	0	55020	53895	67	442	3.184E-167	528
scaffold_2855_2	YP_009894551.1	0.672	376	123	0	55020	53895	67	442	3.210E-164	519
```

Here is my question.
**First**, do you know how could I avoid to add the `index _number` after the query's name? such as `scaffold_2855_1 or scaffold_2855_0 or scaffold_2855_2` etc.

**Second question:**
I did not really understand the MPI parameters in order to be faster. I have actually a SLURM server where I submit all my jobs (so actually it is one job with 20 threads per run), if I well understood I can run the program from different machines by using this parameter? How could I do with the settings I used above? 

Thank you for you help.

**Comment by milot-mirdita** [comment]
For MPI you have to compile MMseq2 yourself with MPI development headers/libraries installed and `cmake -DHAVE_MPI=1 ...`. The `-MPI` version suffix on any MMseqs2 module call will show up if you compiled it correctly. Then you have to define one environment variable `RUNNER` that contains your MPI runner call. E.g.:
```
export RUNNER="mpirun --pernode
```
Make sure to start only one MPI process per compute node (`--pernode` parameter in this case). The parallelization within a node still happens over OpenMP. 

MMseqs2 workflows (search, cluster, ...) will automatically use the `$RUNNER` environment variable to parallelize modules that support it (e.g. `prefilter`, `align`, ...). 

If you call MMseqs2 modules directly (e.g. again `prefilter`) you have to do a normal MPI call:
```
mpirun --pernode mmseqs prefilter ...
```

We don't really have a list of MPI enabled MMseqs2 modules, except for looking in the code for modules that call `MMseqsMPI::init`.

**Comment by Grindell** [comment]
Ok thank you for your time, I was really helpful.  

About the  index _number added at each queries' names, have you an idea to avoid a such adding? because I have to get the fasta sequences after this process and for that I need the exact scaffold's name, without an index added.

**Comment by milot-mirdita** [comment]
What exactly are you doing there? Is this a nucl-nucl or nucl-protein search? MMseqs2 will usually take characters until the first whitespace in the FASTA header as the identifier (if it does not recognize the format, it has a separate parsing logic for e.g. Uniprot format etc). I'd suggest you write a simple `awk` script that trims the suffix.

**Comment by Grindell** [comment]
It is a blastx like run so a genome nucl query and a protein database. Yes that is what I thought to do but maybe there where another way directly in the parameters.

**Comment by milot-mirdita** [comment]
So the `_N` suffix comes already form your FASTA files? 
If thats the case: We already have a feature request in #82 for being able to adapt the parsing logic for FASTA headers. However none had time to work on that yet. We will keep that in mind for the future.

**Comment by Grindell** [comment]
No, as you can see for instance I got a result such as: 

`scaffold_770_2	979	NP_068312.1	0.439	41	22	1	30349	30469	469	508	5.595E-04	38
`
and when I do a `grep 'scaffold_770_2' /beegfs/data/me/genome23.fa`
I get nothing but on the other hand, `scaffold_770 ` without the suffix does exist. It seems that it is during the mmseqs2 process that there was an addition of the `_N` suffix.

**Comment by martin-steinegger** [comment]
What version are you using? In the past we Splitted sequences but we stopped this in later versions.

**Comment by Grindell** [comment]
It is this one `MMseqs2 Version: 4e23d5f1d13a435c7b6c9406137ed68ce297e0fc`

**Comment by martin-steinegger** [comment]
I think the feature was introduced after this commit. Could you rerun your example with the newest version?

**Comment by Grindell** [comment]
It did work with the last version thanks a lot for your help.
