### ISSUE TITLE
performance fail on single query search

### ISSUE THREAD

**Issue by gabrielepozzati** [soedinglab/MMseqs2#165]
## Expected Behavior
MMseq2 expected to work faster than JackHMMer 3
## Current Behavior
MMseq2 works slower than JackHMMer 3
## Steps to Reproduce
-Download from Uniprot the Uniref90 database ( ~ 90 millions sequences) and A0A011 sequence in FASTA format
-Create a target database with: mmseqs2/bin/mmseqs createdb uniref90.fasta uniref90_db
-Create a target database index with: mmseqs2/bin/mmseqs createindex uniref90_db tmp -s 4
-Create a query database with: mmseqs2/bin/mmseqs createdb A0A011 A0A011_db
-Compare the execution time of the two following commands:
mmseqs2/bin/mmseqs search A0A011_db uniref90_db A0A011_align_db tmp -a -s 1 --num-iterations 3
jackhmmer --cpu 28 -E 1e-3 --incE 1e-3 --noali -N 3 -A stk_alignment output uniref90.fasta

## Context
I've run many times slight variations of the commands listed above, in order to check the differences between the two programs and MMseqs does not seem to be quicker than JackHMMer.
The best time I obtained for MMseq2 is around 16 min while JackHMMer only requires 14 min.
Maybe I'm doing something wrong ... the HMMer version is HMMER 3.1b2

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:")
dbeeb55b6cdf16118c221cf7943a70a1d2972daa
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
Statically-compiled AVX2
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
CPU: Intel Xeon E7-8860v4
$ cat /proc/cpuinfo | grep avx2 
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
Cores: 4x18 (of which 28 have been used for the job)
Memory: 3072 GB/node
* Operating system and version:
Ubuntu Xenial (16.04 LTS)

**Comment by milot-mirdita** [comment]
The sequence A0A011 is a single query right?
MMseqs2 does not parallelize over single queries, it only parallelizes over query sets. So what jackhmmer does in 14 minutes on 28 cores, MMseqs2 does on a single core. You can improve the speed by making sure the index is forced into the OS' page cache (e.g. using `mmseqs touch index_db` or using https://github.com/hoytech/vmtouch, the pages cached with `touch` can be evicted again, while `vmtouch` the index forced to remain in RAM).

**Comment by martin-steinegger** [comment]
@gabrielepozzati This is crucial for single queries that the database is already in memory. If the database is not in memory, MMseqs2 needs to fetch 100s of GBs each iterations. The tool `mmseqs touch` loads the database into memory.   
My recommended workflow for single queries would be 

     mmseqs createdb uniref90.fasta uniref90
     mmseqs createindex uniref90 tmp 
     mmseqs touch uniref90.idxdb
     mmseqs search A0A011_db uniref90.idxdb  -a -s 1 --num-iterations 3 --db-load-mode 2

The `--db-load-mode 2`  relies of the fact that the database was already fetched in to ram. It can speed up single queries substantially.

**Comment by gabrielepozzati** [comment]
@milot-mirdita @martin-steinegger I'll check it out, thank you very much for your replies!

**Comment by milot-mirdita** [comment]
We also added an explanation to the [wiki](https://github.com/soedinglab/MMseqs2/wiki#how-to-search-small-query-sets-fast) on how to solve this issue.

**Comment by gabrielepozzati** [comment]
The only similar command in mmseq is touchdb ... I guess its a typo!
Anyway I'm a bit confused, I have to provide as an input to touchdb formatted_database
or formatted_database.idx?

**Comment by milot-mirdita** [comment]
Sorry about the confusion. MMseqs2 will resolve the file endings automatically, you only have to provide it the base name of the database. I edited Martins answer. The wiki entry should be correct.

**Comment by gabrielepozzati** [comment]
ok, with the proper set-up it is considerably faster! Thanks!
