### ISSUE TITLE
result2msa --allow-deletion - Segmentation fault

### ISSUE THREAD

**Issue by gabrielepozzati** [soedinglab/MMseqs2#167]
## Expected Behavior
Computing MSA with deletions in query
## Current Behavior
Segmentation fault, empty files output
## Steps to Reproduce (for bugs)
$ mmseqs2/bin/mmseqs result2msa mmseq_form_db/A0A011_db mmseq_form_db/uniref90_db mmseq_form_db/A0A011_align_db mmseq_form_db/A0A011_msa --allow-deletion true

## MMseqs Output (for bugs)
Program call:
result2msa mmseq_form_db/A0A011_db mmseq_form_db/uniref90_db mmseq_form_db/A0A011_align_db mmseq_form_db/A0A011_msa --allow-deletion true 

MMseqs Version:                    	dbeeb55b6cdf16118c221cf7943a70a1d2972daa
Sub Matrix                         	blosum62.out
Profile e-value threshold          	0.001
Allow Deletion                     	true
Add internal id                    	false
Compositional bias                 	1
Filter MSA                         	0
Maximum sequence identity threshold	0.9
Minimum seq. id.                   	0
Minimum score per column           	-20
Minimum coverage                   	0
Select n most diverse seqs         	1000
Threads                            	28
Compress MSA                       	false
Summarize headers                  	false
Summary prefix                     	cl
Omit Consensus                     	false
Skip Query                         	false
Gap open cost                      	11
Gap extension cost                 	1
Compressed                         	0
Verbosity                          	3

Touch data file mmseq_form_db/A0A011_db ... Done.
Start computing  multiple sequence alignments.
Query database type: Aminoacid
Target database type: Aminoacid
Segmentation fault

## Context
After searching a single sequence (A0A011) over a db (uniref90) I wanted to obtain an MSA. I also want the gaps in the query so I added the --allow-deletion true flag. Over smaller alignments (for instance the one from A0A010) this works, but it does not for larger ones (30 vs 990 aligned seqs). Running the same command without the flag ends correctly over any sequence.

## Your Environment
* Git commit used (The string after "MMseqs Version:")
dbeeb55b6cdf16118c221cf7943a70a1d2972daa

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
Statically-compiled AVX2

* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
CPU: Intel Xeon E7-8860v4
$ cat /proc/cpuinfo | grep avx2
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
Cores: 4x18 (of which 28 have been used for the job)
Memory: 3072 GB/node

* Operating system and version:
Ubuntu Xenial (16.04 LTS)

**Comment by milot-mirdita** [comment]
`--allow-deletion` is still quite experimental and not well tested.

For this use case, I would recommend you to create unaligned FASTA clusters with `createseqfiledb` and then align those with an established MSA aligner (such as ClustalO). The `apply` module might help in calling the aligner on each cluster. This is basically the workflow for creating the Uniclust30 alignments that are then turned into HMM profiles for usage in HH-suite.

`result2msa` should be used for its center-star alignments based on a representative sequence.

**Comment by milot-mirdita** [comment]
Should not crash anymore, however it's still quite experimental.
Feel free to play around with the option though.

**Comment by gabrielepozzati** [comment]
Thanks, I'll check it out!
