### ISSUE TITLE
Bug when creating tsv file from taxonomy output?

### ISSUE THREAD

**Issue by NicolaasVanRenne** [soedinglab/MMseqs2#169]
Dear all, 

When I run the taxonomy with -s 1 everything runs smooth, but when I increase sensitivity to -s 2 or -s 3 it just gives a bug: 

Invalid database read for database data file=/home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h, database index=/home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h.index
getData: local id (4294967295) >= db size (333844)

So my database uniprot-bacteria_20190304 is 333844 'items' long: but apparently he tries mapping to 'item 4294967295'. I think. Which is strange because I dont find this particular number anywhere in the files I'm using. Is this a bug? 

What's also strange: I get the bug when I'm running it on protein strings of 30aa or 50aa long. But with 100aa it works perfectly fine in any sensitivity... 

I really don't get it...

THIS WORKS FINE:  (from an -s 1 output)
---------------------------------------------
mmseqs createtsv /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304 /home/nicolaas/mmseqs2/result/resultaat058 /home/nicolaas/mmseqs2/result/resultaat058.tsv
Program call:
createtsv /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304 /home/nicolaas/mmseqs2/result/resultaat058 /home/nicolaas/mmseqs2/result/resultaat058.tsv

MMseqs Version:                         7.4e23d
first sequence as respresentative       false
Target column                           1
Add Full Header                         false
Database Output                         false
Threads                                 4
Verbosity                               3

Query database: /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa
Touch data file /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa_h ... Done.
Target database: /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304
Touch data file /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h ... Done.
Result database: /home/nicolaas/mmseqs2/result/resultaat058
Start writing to /home/nicolaas/mmseqs2/result/resultaat058.tsv
Time for merging files: 0h 0m 0s 628ms
Done.
Time for processing: 0h 0m 3s 745ms

THIS ONE JAMS (from -s 2 output)
---------------------------------------
 mmseqs createtsv /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304 /home/nicolaas/mmseqs2/result/resultaat059 /home/nicolaas/mmseqs2/result/resultaat059.tsv
Program call:
createtsv /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304 /home/nicolaas/mmseqs2/result/resultaat059 /home/nicolaas/mmseqs2/result/resultaat059.tsv

MMseqs Version:                         7.4e23d
first sequence as respresentative       false
Target column                           1
Add Full Header                         false
Database Output                         false
Threads                                 4
Verbosity                               3

Query database: /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa
Touch data file /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa_h ... Done.
Target database: /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304
Touch data file /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h ... Done.
Result database: /home/nicolaas/mmseqs2/result/resultaat059
Start writing to /home/nicolaas/mmseqs2/result/resultaat059.tsv
Invalid database read for database data file=/home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h, database index=/home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h.index
getData: local id (4294967295) >= db size (333844)

HELP?

**Comment by NicolaasVanRenne** [comment]
It makes several tsv files:
resultaat059.tsv.0
resultaat059.tsv.1
resultaat059.tsv.2
resultaat059.tsv.3 

but all the lines combined are less than the original datafile ("resultaat059") from whence it came... That doesnt make sense. 

I dont find the code that makes these tsv.0 etc so I am unable to understand what it does wrong...

**Comment by martin-steinegger** [comment]
Sorry for the inconvenience. Could you please provide all mmseqs calls for the example? It is hard to see what goes wrong from this example. Thanks a lot!

**Comment by NicolaasVanRenne** [comment]
#step1: create database from fastq (long DNA reads)
mmseqs createdb /home/nicolaas/mmseqs2/data/basreads_full.fastq /home/nicolaas/mmseqs2/basreads/full/pipeline030/reads/reads

#step2: extract orfs with minimum 30 aa
mmseqs extractorfs /home/nicolaas/mmseqs2/basreads/full/pipeline030/reads/reads /home/nicolaas/mmseqs2/basreads/full/pipeline030/orfs/orfs --min-length 30 -v 3

#step3: translate codons into aa
 mmseqs translatenucs /home/nicolaas/mmseqs2/basreads/full/pipeline030/orfs/orfs /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa -v 3

#step4: run taxonomy which creates resultaat059 and resultaat059.index
mmseqs taxonomy /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304 /home/nicolaas/mmseqs2/result/resultaat059 tmpDir -s 2 

#step5: create tsv file 
 mmseqs createtsv /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304 /home/nicolaas/mmseqs2/result/resultaat059 /home/nicolaas/mmseqs2/result/resultaat059.tsv

Don't understand why it won't fly.

**Comment by NicolaasVanRenne** [comment]
tried deleting all the files created from these commands, and ran the thing again (you never know).

Bugs again at last createtsv step:
Invalid database read for database data file=/home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h, database index=/home/nicolaas/mmseqs2/databases/taxonomy/uniprot-bacteria/uniprot-bacteria_20190304_h.index
getData: local id (4294967295) >= db size (333844)

**Comment by NicolaasVanRenne** [comment]
Looks like either something is wrong with the tsv partitions, or with the mergers thereafter

**Comment by martin-steinegger** [comment]
The issues is that you call with the query and target database `createtsv`. You need just the query database. After the taxonomy workflow is completed there is a taxonomy identifier and not a sequence identifier in the result file. So if createtsv tries to look up the identifier it breaks. If you call `createtsv` with only the query database then it will only translate the query but not the target information.  

      mmseqs createtsv /home/nicolaas/mmseqs2/basreads/full/pipeline030/aa/aa /home/nicolaas/mmseqs2/result/resultaat059 /home/nicolaas/mmseqs2/result/resultaat059.tsv

**Comment by NicolaasVanRenne** [comment]
Thank you so much. That does work indeed. 

I just don't reall understand why. If I run `mmseqs createtsv -h` then he says;

Usage: <i:queryDB> [<i:targetDB>] <i:resultDB> <o:tsvFile> [options]

So then why is the targetDB indicated? What is the difference between <> brackets and [] brackets? 

Could you shed some light on this?

**Comment by martin-steinegger** [comment]
Great!
The <> indicates a path to a database file, i: input, o: output. The [] indicates if it is optional. 
The targetDB and the options are optional in `createtsv`.

**Comment by soeding** [comment]
I added a section to explain the general syntax of mmseqs commands and workflows and the Usage information in the section "Getting started".
Martin, please check! Thanks.

**Comment by NicolaasVanRenne** [comment]
Great. Now I actually understand what the difference is between i: and o: 
👍 

Just a quick question: I mostly use default settings like -k 0 which sets kmer to optimum (although I must admit I have no idea what the mathematical basis of this feature is). And it works fine, the algorithm seems to use kmer=6. Why does it use 6, and not 7? What would happen if I use 7? Would it be more sensitive and slower? I'm a veterinarian, the nature biotech paper is mostly elvish to me.

Will try to toy around and benchmark some more.

Thanks for the help.

Nicolaas

**Comment by NicolaasVanRenne** [comment]
never mind. 

> Can not fit databased into 7616935526 byte. Please use a computer with more main memory.
