### ISSUE TITLE
create DB from fasta results in Fasta entry: 0 is invalid

### ISSUE THREAD

**Issue by sbyma** [soedinglab/MMseqs2#170]
## Expected Behavior
DB should be formed. 
## Current Behavior
Fails to parse fasta file. 
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.
`mmseqs2/bin/mmseqs createdb test.fa DB`

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

MMseqs Version:                 84e4ba6e8ef49b5764e604b9f4d0d90e3d3c0721
Max. sequence length            65535
Split Seq. by len               true
Database type                   0
Do not shuffle input database   true
Offset of numeric ids           0
Compressed                      0
Verbosity                       3

Fasta entry: 0 is invalid.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

Test file in question:

```
> CHIPD00001 | ACU57510.1 | Cpin_0001 | C7P9R7_CHIPD | Chromosomal replication initiator protein dnaA
MNKTCEQVWERCLNIIRDIVEWQPFKTWFEPIKPIQLENNVLTIQVPSQFFYEYLEEHYVGLLGKTIKRELGKDARLEYR
IVVENGTPHQHPKTVNMPGQFTKSKKDSEVDFPLTIQNPVKNPFVIPGIKRVQIDSQLNPHYTFESYIEGDCNRVARRAG
KTVSEKPGGTSFNPLVIYGAVGLGKTHLAQAIGNEVKRIHPNKAVLYVSAEKFINQFIDHSKNSIINDFIHFYQLIDVLI
VDDIQFFARAEKTQDAFFAIFNHLHQSGKQLILTSDKPPKDLDGLQERLLSRFRWGLSADMQMPDFETRMEILEMKMRND
GLEMPKEVVKYVAYNIQSNVRELEGALISLLAQSSLNRKEIDLELAKRVLKSFVKTSSKEITIESIQKMVCEYFDVPYDK
LLQKTRKREIVQARQITMYLAKSFTKNSLKTIGEHFGGRDHTTVIHSCQTVKDLMDTDNAFRDNVIELQQKVQLAAM

> CHIPD00002 | ACU57511.1 | Cpin_0002 | C7P9R8_CHIPD | RNA polymerase, sigma-24 subunit, ECF subfamily
MPQEGQHTLWSAIRKGDETAFRQLFEECWEPLFTYASRITIDHSLAQDSVQSLFIHIWEKRDSLPDVTAILPYLRSALKN
RLLNALRDEHVYQKHVDLFTQVVDTNSPSSAEPLHLKETEQQLLQSINRLPGKMKDVFYLHRIEDLSVAEIACKLGTSPQ
TIRNQISTAIQRLKTTFV
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

statically compiled version
Ubuntu 18.04

**Comment by martin-steinegger** [comment]
Your fasta is malformed. Please remove the spaces between "> ID"

**Comment by sbyma** [comment]
Thanks, closing issue.
