### ISSUE TITLE
sequence identity same result clarification

### ISSUE THREAD

**Issue by ashishr123** [soedinglab/MMseqs2#173]
Hi,
I am new to MMSeqs2. It is really a good tool. However, I have 2 queries, may be basic too. But I want your opinions.
In an attempt to build a set of 30-90% sequence similarity, I removed the redundant hits myself firstly and then deployed a minimum sequence identity threshold of 30% and coverage 1 (All 92 input sequences are close homologues and so I want to avoid the partial match to build the good set), it resulted in 52 hits. So, now as you are guiding, the multiple resultant cluster sets have the sequence identity lesser than 30%, but the 52 hits share a sequence identity > 30%. Is this correct that this way my reduced set of 52 hits contains the sequences that are 30-90% identical?

Further, why is it that for another sequence-group, the resultant set spans the same 45 sequences for both 30% and 90% cutoffs. So, does it mean that the length of atleast 1 representative sequence is bigger and it spans multiple sequences in either of these ranges to result in the same set? How should this result be defined?
Thanks for your clarifications.

**Comment by martin-steinegger** [comment]
Sorry for the late answer. We had some deadlines coming up. Did you check on the coverage criteria. If you want to match partial hits you might want to use `--cov-mode 1`.  Maybe this documentation might help to set your parameters https://github.com/soedinglab/MMseqs2/wiki#clustering-criteria and https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster

**Comment by ashishr123** [comment]
Although I found these pages, thank you for the support and your links.

**Comment by martin-steinegger** [comment]
Did it resolve your issue?
