### ISSUE TITLE
Clustering method for nucleotide & protein sequences

### ISSUE THREAD

**Issue by Grindell** [soedinglab/MMseqs2#177]
Hello, I was wondering if it was possible to use the clustering method for a database composed of both nucleotides and protein sequences ? 

The idea behind my question is that  I would like to cluster these sequences together and then translate the nucleotides sequences in order to make an phylogenetic tree for all the sequences in the clusters in  amino acide level. I know that some clustering method take as input the tab format after a blastx research, and then creates cluster based on the identities, coverages and evalues. Does mmseqs2 can do a such a thing ? Furthermore I need a very sensitive method because I'm working on relatively fast evolutions organisms, so I'm expected to find only well supported homology on specific short locations in sequences (conserved domains). Thanks you for your time.

**Comment by martin-steinegger** [comment]
I am not sure if I understood the question correctly. What you want to achieve? Do you want to cluster a genome together with protein sequences on the amino acid level?

**Comment by Grindell** [comment]
Yes that's it. I want to cluster scaffolds with amino acids sequences.

**Comment by martin-steinegger** [comment]
So I still do not really understand exact use case. But it would be possible to extract all translated orfs from the genomes and merge them with the proteins before clustering. 

``` 
mmseqs createdb genomes.fas genome 
mmseqs extractorfs genome genome_orfs 
mmseqs translatenucs genome_orfs  genome_aa
mmseqs createdb proteins.fas proteins 
mmseqs concatdbs proteins genome_aa allproteins_h
mmseqs concatdbs proteins_h genome_aa_h allproteins_h
mmseqs cluster allproteins allproteins_clu tmp 
``` 
But I think it would be easier to just search with the proteins against the genomes 

``` 
mmseqs createdb proteins.fas proteins 
mmseqs createdb genomes.fas genome 
mmseqs search proteins genomes aln tmp -a 
```

**Comment by Grindell** [comment]
Maybe I can explain it better with a schema:

![Capture d’écran 2019-11-12 à 14 09 11](https://user-images.githubusercontent.com/39563212/68674382-0f492680-0556-11ea-8f25-2ca2d25fddd1.png)

Here In order to make a cluster I had two steps: 

The first one is a mmseqs2 (blastx) between a nucleotide query and a protein database.
This gives me a .m8 outfile. 

Then I used SiLix in order to read the .m8 file. This allows me to create cluster of sequence. 
Here for exemple `Sp1` and `Sp2` are together because they match with the same `Vseqs`. 

Do you see what I mean?

**Comment by martin-steinegger** [comment]
The figure and your explanation helped me to understand your workflow better. However, I do not understand where the neon green and black bars (super dark green?) originate from? Are these ORFs from the query set? 

Silix uses single linkage clustering. This can be done in MMseqs2 using `--cluster-mode 1` but we can not cluster non-symmetric sets (query/target) with MMseqs2. To overcome this limination I would recommend your to combine the ORFs of the query with the proteins from the target and cluster them together.

**Comment by Grindell** [comment]
`The figure and your explanation helped me to understand your workflow better. However, I do not understand where the neon green and black bars (super dark green?) originate from? Are these ORFs from the query set?`

The green bars are the query sequences and yes they correspond to ORFs from the query set. (To be more precise these are the portions of the hits found in the genomes by a previous mmseqs  search with a viral protein db against nucleotides genomes queries. 


`Silix uses single linkage clustering. This can be done in MMseqs2 using --cluster-mode 1 but we can not cluster non-symmetric sets (query/target) with MMseqs2. To overcome this limination I would recommend your to combine the ORFs of the query with the proteins from the target and cluster them together.
`
You mean combine nucleotide and protein sequence into the same file and then make a cluster analysis ? Or to translate the ORFs of the query and then make a cluster analysis?

**Comment by Grindell** [comment]
Ok I got the ORF sequences from the query and then translated them to protein. 
I then cat these sequence with the other protein sequences from the target and made a cluster analysis:

`mmseqs cluster Protein_virus_db DB_clu tmp --threads 10 -s 12 -c 0.8 --cov-mode 1 -e 0.1`

But in the process I get the following message: 

`Can not find any score per column for coverage 0.800000 and sequence identity 0.000000. No hit will be filtered.`
Do you know why? 
I also wondered since I am looking for partially conservated domains of target sequence into the queries, should I use more the --cov-mode1 or 2?
