### ISSUE TITLE
Again: Invalid database read for database data file (#64)

### ISSUE THREAD

**Issue by pmjklemm** [soedinglab/MMseqs2#178]
## Expected Behavior

no error and more coffee 

## Current Behavior

The mmseqs convertalis throws the following error:

**Invalid database read for database data file=test/E.faa.mmseqsp_h, database index=test/E.faa.mmseqsp_h.index
getData: local id (4294967295) >= db size (72)**

## Steps to Reproduce (for bugs)

1. build DB 

> mmseqs createdb --dbtype 1 C.faa C.faa.mmseqsp

and

> mmseqs createdb --dbtype 1 E.faa E.faa.mmseqsp

2. search

> mmseqs search C.faa.mmseqsp E.faa.mmseqsp E.faa.vs.C.faa.mmseqsp . --threads 1 -e 1e-05

3. do convertalis 

> mmseqs convertalis E.faa.mmseqsp C.faa.mmseqsp E.faa.vs.C.faa.mmseqsp E.faa.vs.C.faa.mmseqsp.bla

-> The error occures here

## MMseqs Output (for bugs)

here are all my files in the directory:

> 
> 14083925917902872037/  C.faa.mmseqsp_h.dbtype  E.faa.mmseqsp           E.faa.mmseqsp.index           E.faa.vs.C.faa.mmseqsp.bla.2  E.faa.vs.C.faa.mmseqsp.bla.7        E.faa.vs.C.faa.mmseqsp.bla.index.4  E.faa.vs.C.faa.mmseqsp.index
> C.faa                 C.faa.mmseqsp_h.index   E.faa.mmseqsp.dbtype    E.faa.mmseqsp.lookup          E.faa.vs.C.faa.mmseqsp.bla.3  E.faa.vs.C.faa.mmseqsp.bla.index.0  E.faa.vs.C.faa.mmseqsp.bla.index.5  latest
> C.faa.mmseqsp         C.faa.mmseqsp.index     E.faa.mmseqsp_h         E.faa.vs.C.faa.mmseqsp        E.faa.vs.C.faa.mmseqsp.bla.4  E.faa.vs.C.faa.mmseqsp.bla.index.1  E.faa.vs.C.faa.mmseqsp.bla.index.6
> C.faa.mmseqsp.dbtype  C.faa.mmseqsp.lookup    E.faa.mmseqsp_h.dbtype  E.faa.vs.C.faa.mmseqsp.bla.0  E.faa.vs.C.faa.mmseqsp.bla.5  E.faa.vs.C.faa.mmseqsp.bla.index.2  E.faa.vs.C.faa.mmseqsp.bla.index.7
> C.faa.mmseqsp_h       E.faa                   E.faa.mmseqsp_h.index   E.faa.vs.C.faa.mmseqsp.bla.1  E.faa.vs.C.faa.mmseqsp.bla.6  E.faa.vs.C.faa.mmseqsp.bla.index.3  E.faa.vs.C.faa.mmseqsp.dbtype

The precise output is : 

> `Program call:
> convertalis E.faa.mmseqsp C.faa.mmseqsp E.faa.vs.C.faa.mmseqsp E.faa.vs.C.faa.mmseqsp.bla
> 
> MMseqs Version:         5d7cecc696fa3dfc60dce1acbe7f30a513ec209f
> Substitution Matrix     blosum62.out
> Alignment Format        0
> Format alignment output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
> Translation Table       1
> Gap open cost           11
> Gap extension cost      1
> Database Output         false
> Preload mode            0
> Search type             0
> Threads                 8
> Compressed              0
> Verbosity               3
> 
> Query database: E.faa.mmseqsp
> Touch data file E.faa.mmseqsp_h ... Done.
> Target database: C.faa.mmseqsp
> Touch data file C.faa.mmseqsp_h ... Done.
> Alignment database: E.faa.vs.C.faa.mmseqsp
> Start writing to E.faa.vs.C.faa.mmseqsp.bla
> Invalid database read for database data file=E.faa.mmseqsp_h, database index=E.faa.mmseqsp_h.index
> getData: local id (4294967295) >= db size (72)
> Invalid database read for database data file=Invalid database read for database data file=E.faa.mmseqsp_h, database index=E.faa.mmseqsp_h, database index=Invalid database read for database data file=E.faa.mmseqsp_h, database index=E.faa.m
> mseqsp_h.indexE.faa.mmseqsp_h.index
> E.faa.mmseqsp_h.index
> getData: local id (getData: local id (
> getData: local id (4294967295) >= db size (4294967295) >= db size (724294967295) >= db size (72)
> )
> 72)

## Context

I use the newest version (cloned today and compiled with no errors) and some version 2-3 month old. 

## Your Environment

linux, 4 cores, plenty of RAM ...

## FILES

[inputfiles.zip](https://github.com/soedinglab/MMseqs2/files/2979000/inputfiles.zip)

**Comment by martin-steinegger** [comment]
Please flip the parameters in convertalis 

         mmseqs convertalis  C.faa.mmseqsp E.faa.mmseqsp E.faa.vs.C.faa.mmseqsp E.faa.vs.C.faa.mmseqsp.bla

**Comment by pmjklemm** [comment]
you are right, thank you.
