### ISSUE TITLE
mmseqs taxonomy: level separator also in classifications

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#179]
I believe that the separator for the taxonomy generated by `mmseqs taxonomy` is ":". However, some of the taxonomic classifications, at least at the species level, have ":" in the names (eg., `Blautia sp. CAG:37_48_57` or `Clostridium sp. CAG:7`). Using ":" instead of say ";" (as most taxonomy strings are set as) makes parsing the taxonomy string a pain.

**Comment by martin-steinegger** [comment]
@milot-mirdita do you have any solution for this?

**Comment by milot-mirdita** [comment]
There are two entries with `;` in their name:
```
447744	|	Salicornia aff. perennans Wucherer 3a;09	|		|	scientific name	|
980544	|	Cassava brown streak virus-[Malawi:Karonga 17;2009]	|		|	scientific name	|
```

I found these unique special characters in a `names.dmp` that I had lying around here:
```
`^<=>_-,;:!?/.'"()[]{}@*&#%+`
```

I guess we could use a pipe character `|`. The kraken style report Florian implemented is using `;`.
Or we could strip `;` off, while importing the names?

**Comment by milot-mirdita** [comment]
Thanks a lot for the bug report and also thanks to the NCBI for quickly answering my email.
