### ISSUE TITLE
Clustering error during processing of some fasta files

### ISSUE THREAD

**Issue by matveykolesnik** [soedinglab/MMseqs2#181]
For some reasons mmseqs cluster fails during clustering of the attached protein fasta.

Commands:
```
mmseqs createdb test2.faa test2.db
mmseqs cluster test2.db test2.clu tmp --min-seq-id 0.9
```
fasta file and log are attached in gist
https://gist.github.com/matveykolesnik/7b4376daba0a1f5846747a7b4bb33d81

**Comment by martin-steinegger** [comment]
Thanks a lot for reporting this bug. I have fixed the issue. We will make a new release of the software this week.
