### ISSUE TITLE
Entry ## is longer than max seq. len 65535

### ISSUE THREAD

**Issue by cmajones** [soedinglab/MMseqs2#183]
## Expected Behavior
Hi there! I am hoping to cluster a fasta file of contigs from an assembly of 134 samples. 

## Current Behavior
Getting error message that entries are longer than max sequence length of 65535 ([see error output](https://gist.github.com/cmajones/f8e3a9c3da8998672ef342788a2f050e)).

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

Command: `mmseqs easy-cluster scaffolds.fasta MRN_clustered tmp`

## MMseqs Output (for bugs)
[See output here](https://gist.github.com/cmajones/f8e3a9c3da8998672ef342788a2f050e)

## Context
Am I missing an option for controlling max sequence length in mmseqs? Allowing for large contigs would be helpful in this context of a cross-assembly from 134 samples, containing 422691 sequences ranging in length from 679 kbp to 127 bp. 

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used: MMseqs2 Version: 8.fac81
* Which MMseqs version was used: Installed via miniconda on ubuntu server. 
* Server specifications: 80 core server, 1.5 TB memory
* Operating system and version: ubuntu 16.04.5

Thanks for your help!

**Comment by martin-steinegger** [comment]
We do not support such long sequences yet. What is your use case? Do you want to assign shorter fragments to longer contigs?

**Comment by cmajones** [comment]
Didn't see that as an option, sorry! Running now. 

Our use case is human microbiome samples purified for viral content. I'm trying to group contigs together into families without worrying about deficient viral protein databases.

**Comment by martin-steinegger** [comment]
so the clustering mode you chose will try to align sequences together that have a similar length. You might want to use --cov-mode 1  (see https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster)

**Comment by martin-steinegger** [comment]
@cmajones did this solve your problem?

**Comment by cmajones** [comment]
It did! Thanks @martin-steinegger
