### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by chodarq** [soedinglab/MMseqs2#187]
Hi,

I'm running MMseq2s to clusterize a huge set of fasta sequences (near 640000). I run  the easy-cluster procedure (mmseqs easy-cluster scaffold.fa clustered tmp) but in some point the follow message appear:

Index table: Masked residues: 2748074
Index table: fill
Segmentation fault (core dumped)
Error: Prefilter step 0 died
Error: Search died

Any idea of what happend?
Thanks

**Comment by martin-steinegger** [comment]
Thank you for reporting this. Could you please provide more information like version of MMseqs2, output log, platform, computer specification?

**Comment by chodarq** [comment]
Sure, sorry.
MMseq2 is version '44bde75f0e9f4d0ffc60970bee13347fe89bcb96'. Is running on a Dell computer with 64 cores, in a 5TB partition of HDD and 1Tb of RAM, and with Ubuntu 18.04 LTS.
I don't find any log file so I attach you the log of the running prior to the fault ( 1>log.txt)
Hope that help, thanks!! 
[log.txt](https://github.com/soedinglab/MMseqs2/files/3076480/log.txt)

**Comment by martin-steinegger** [comment]
It seems that you try to cluster nucleotide sequences that are longer than 65536? You need to increase the sequence length using `--max-seq-len`.

**Comment by chodarq** [comment]
Oh..could be. File is an output for a metagenome assembly. There is a limitation in the --max-seq-len option?
Thanks!

**Comment by martin-steinegger** [comment]
The clustering might need slightly more memory with an increased `--max-seq-len`. But There should be no problem on your computer with the memory. Sequences longer than 2^16 are not yet well tested but clustering should work without any further issues .

**Comment by chodarq** [comment]
I will try and inform anything.
Thanks!

**Comment by chodarq** [comment]
Just for inform. Three days ago, I use the --max-seq-len parameter with the large of the longest scaffold as the limit. It works in terms of the segmentation fault don't appear, but, it's still running...so, I'm not sure whether I'm processing data or in an infinite loop. Processors are all (64) running at 100% and  8Gb of memory are used. 
Greetings,
Christian.

**Comment by martin-steinegger** [comment]
Ah good that there is no seg. fault anymore. Could you attach the log output?

**Comment by chodarq** [comment]
Once finish...sure. I forget to put the log out in 1> ...my mistake.

**Comment by martin-steinegger** [comment]
Did the run finished? If not, would it be possible to share the data with me?

**Comment by martin-steinegger** [comment]
I will close this issues for now. Please reopen it if you have an update.
