### ISSUE TITLE
mmseqs alignall + convertalis producing inconsistent, duplicate alignment results

### ISSUE THREAD

**Issue by geronimp** [soedinglab/MMseqs2#194]
## Expected Behavior
Related to the `alignall` function in https://github.com/soedinglab/MMseqs2/issues/60
I think what this function is supposed to produce is the all vs all alignments for all members of a cluster

## Current Behavior
Produces the alignment but the values are off, multiple alignments are produced for the same pairs of sequences, each with very different bit score and evalue etc. In some cases percent ids are >100% 
```
$ head alignDb.m8 
test_proteins~seq_444_18	test_proteins~seq_444_18	439.000	201	4294879057	0	2	0	202	0	1.000E+00	40
test_proteins~seq_444_18	test_proteins~seq_444_18	83.000	216	4294949368	0	3	0	202	0	2.820E-01	19
test_proteins~seq_444_18	test_proteins~seq_444_18	75.000	224	4294950496	0	2	0	202	0	2.550E-01	13
test_proteins~seq_444_18	test_proteins~seq_444_18	73.000	267	4294947805	0	8	0	202	0	2.280E-01	16
test_proteins~seq_444_18	test_proteins~seq_444_18	146.000	263	4294928898	0	7	0	202	0	3.840E-01	22
test_proteins~seq_444_18	test_proteins~seq_444_18	77.000	251	4294947969	0	4	0	202	0	2.500E-01	7
test_proteins~seq_444_18	test_proteins~seq_444_18	83.000	250	4294946546	0	4	0	202	0	2.630E-01	23
test_proteins~seq_444_18	test_proteins~seq_444_18	79.000	246	4294947862	0	7	0	202	0	2.540E-01	34
test_proteins~seq_444_18	test_proteins~seq_444_18	76.000	246	4294948600	0	2	0	202	0	2.480E-01	35
test_proteins~seq_444_18	test_proteins~seq_444_18	82.000	242	4294947452	0	9	0	202	0	2.630E-01	11
```
## Steps to Reproduce (for bugs)
Seqeunces in test_proteins.faa [found here](https://gist.github.com/geronimp/64e2dbf0c885f1771982ce381b773657)
```
mmseqs createdb test_proteins.faa db 
mmseqs cluster db clu /tmp/tmpd9nk3khu --max-seqs 1000 --threads 40 --min-seq-id 0.3 -e 0.000010 -c 0.7 
mmseqs alignall db clu alignDb -a 
mmseqs convertalis db db alignDb alignDb.m8 
```
## MMseqs Output (for bugs)
alignall output:
```
$ mmseqs alignall db clu alignDb -a 
alignall db clu alignDb -a 

MMseqs Version:           	a75cb1cd514aed10f13ef5717ddad064b7178ea3
Substitution matrix       	blosum62.out
Add backtrace             	true
Alignment mode            	0
E-value threshold         	0.001
Seq. id. threshold        	0
Min. alignment length     	0
Seq. id. mode             	0
Alternative alignments    	0
Coverage threshold        	0
Coverage mode             	0
Max sequence length       	65535
Compositional bias        	1
Realign hits              	false
Max reject                	2147483647
Max accept                	2147483647
Include identical seq. id.	false
Preload mode              	0
Pseudo count a            	1
Pseudo count b            	1.5
Score bias                	0
Gap open cost             	11
Gap extension cost        	1
Threads                   	4
Compressed                	0
Verbosity                 	3

[======================================================================] 100.00 % 0s 5ms
Time for merging files: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 194ms
```
convertalis output:
```
$ mmseqs convertalis db db alignDb alignDb.m8 
convertalis db db alignDb alignDb.m8 

MMseqs Version:        	a75cb1cd514aed10f13ef5717ddad064b7178ea3
Substitution matrix    	blosum62.out
Alignment format       	0
Format alignment output	query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
Translation table      	1
Gap open cost          	11
Gap extension cost     	1
Database output        	false
Preload mode           	0
Search type            	0
Threads                	4
Compressed             	0
Verbosity              	3

[======================================================================] 100.00 % 0s 1ms
Time for merging files: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 11ms
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
MMseqs version: 8.fac81 (conda) 
OS: Ubuntu 18.04.2 LTS

**Comment by martin-steinegger** [comment]
This modul still has some issues since it introduces an extra column. I have described how to convert the results here: https://github.com/soedinglab/MMseqs2/issues/60#issuecomment-382681873
I hope it helps

**Comment by geronimp** [comment]
Hi Martin,

Thanks for your comment, I appreciate you looking into this. What you describe in that comment refers to the formatting of file, but this bug report is related to the duplicate entries in the output file, for instance in the example I originally posted, the alignment between seq_336_11 and seq_129_9 is listed 60 times, each with different bit scores, evalues and in some cases with percent identified >100% which is impossible. Looking now, it appears each pair of sequences are reported 60 times, consistent with the number of input sequences. I'm not sure if thats related? 

Thanks again,
J

**Comment by martin-steinegger** [comment]
It is a format issue. The output of alignall technically is not a valid alignment database. Therefore it can not be converted by `convertalis`. The first two columns contain the identifier for the alignment of A against B. convertalis can just handle a single identifier. We will validate this in the near future. 

Here is a script how to generate the desired result:  

      mmseqs createdb test_proteins.faa db 
      mmseqs cluster db clu /tmp/tmpd9nk3khu --max-seqs 1000 --threads 40 --min-seq-id 0.3 -e   0.000010 -c 0.7 
      mmseqs alignall db clu alignDb --alignment-mode 3 
      mmseqs createtsv db db alignDb alignDb.tsv
      OFS="\t" awk 'FNR==NR{a[$1]=$2;next}{$3=a[$3]; $1=""; for(i=2;i<NF;i++){printf("%s\t",$i)} printf("\n")}' db.lookup  alignDb.tsv > alignDb_correct.tsv

**Comment by geronimp** [comment]
I see so the problem was I was using convertalis rather than createtsv. Sorry for the confusion! 
Thanks again for your time!

**Comment by martin-steinegger** [comment]
Yes! This module is quite special and therefore creates usability issues. Sorry for the inconvenience.
