### ISSUE TITLE
Problems with MPI version

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#198]
Hi
we are having some problems using the MPI version with commit 39ee37f97ab065a3763ee10b834b3e6e25aae491

Thank you
Antonio

## Expected Behavior
MPI version should use all threads in each of the nodes for prefilter

## Current Behavior
MPI only uses all threads in one node and one thread in the rest. It works as expected on release 7-4e23d and has the wrong behavior on 39ee37f97ab065a3763ee10b834b3e6e25aae491

## Steps to Reproduce (for bugs)
The command we use in both cases is:
```{bash}
export OMPI_MCA_btl=^openib
export OMP_NUM_THREADS=28

RUNNER="mpirun --mca btl_tcp_if_include ens3 -n 10 --map-by ppr:1:node --bind-to none " "${MMSEQS}" clusterupdate "${SDIR}"/marine_hmp_db_03112017 "${SDIR}"/mg_gtdb_orfs_db "${SDIR}"/marine_hmp_db_03112017_clu "${DIR}"/mg_gtdb_update/mg_gtdb_db_052019 "${DIR}"/mg_gtdb_update/mg_gtdb_db_052019_clu "${DIR}"/mg_gtdb_update/tmp --min-seq-id 0.3 -s 5 --cov-mode 0 -c 0.8
```

## MMseqs Output (for bugs)
release [7-4e23d](https://gist.github.com/genomewalker/96cfc0c4754cd4f2cd1ce6925576c876) log
commit [39ee37f](https://gist.github.com/genomewalker/8a83a8707dae2bc3179df730a5b695b7) log

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" 39ee37f97ab065a3763ee10b834b3e6e25aae491
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): Self-compiled
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: gcc 5.4 and open MPI 1.10.2
```
cmake -DHAVE_MPI=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/vol/attached/opt/MMseqs2-7-4e23d ..
```
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): cloud system (10 instances, BiBiGrid) with Intel Xeon Processor (Skylake, IBRS) with 28 vCPUs and 256G of memory
* Operating system and version: Ubuntu 16.04.5 LTS

**Comment by martin-steinegger** [comment]
@milot-mirdita @elileka any idea what could go wrong? do you have similar problems?

**Comment by elileka** [comment]
Yes, that's the issue I wrote you about with the automatic division into "splits". I tried to temporarily bypass it by setting --split manually to the number of nodes.

**Comment by genomewalker** [comment]
Hi @martin-steinegger; Hi @elileka 
splitting it manually works as expected. In our case, we also had to specify `--local-tmp` as it was giving the following error during the prefiltering: `Query sequence type not implemented!`

**Comment by martin-steinegger** [comment]
@genomewalker  Do you have a `.dbtype` for your query database? `--local-tmp` should not solve this issue.

**Comment by genomewalker** [comment]
Yes, we have. It failed when prefiltering the `NEWDB.newSeqs` against `OLDDB.repSeq` step. We didn't modify anything but `--local-tmp` and a fresh `tmp` folder. We are updating a clustering result.

**Comment by martin-steinegger** [comment]
This problem should be solved now right?

**Comment by elileka** [comment]
The split logic also got a face lift so splitting manually should not be required anymore.
Please do update if you encounter problems.
