### ISSUE TITLE
Clusterupdate workflow problems

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#199]
Hi
we are having several problems with the `clusterupdate` workflow on 39ee37f97ab065a3763ee10b834b3e6e25aae491-MPI.

## Expected Behavior
The `clusterupdate` workflow should update existing clusters and the number of sequences should match OLDDB+NEWDB
## Current Behavior
The workflow has problems in some of the steps:

1) Most probably related to the new behavior of not merging files, the logic [here](https://github.com/soedinglab/MMseqs2/blob/master/data/update_clustering.sh#L218) fails to create the `updatedClust` when concatenating the old cluster results with the new hits. When the workflow is on its [final step](https://github.com/soedinglab/MMseqs2/blob/master/data/update_clustering.sh#L271) and has to concatenate the old clusters with the new ones, fails.

2) In our run, we are missing ~200K new sequences that had a hit after the search against the old cluster representatives but it seems to be lost in the `swapresults` [step](https://github.com/soedinglab/MMseqs2/blob/master/data/update_clustering.sh#L202) 

Thanks
Antonio

**Comment by martin-steinegger** [comment]
Thanks for this detailed analysis. I have fixed the issues with commit ae4c7344d0174b54ba65646fc35fa91751209a6e and created a regression test for the update workflow.

**Comment by genomewalker** [comment]
Hi Martin
thank you very much for the quick fix! We will test it now.

Cheers
Antonio

**Comment by genomewalker** [comment]
@martin-steinegger  It worked perfectly now!

Thank you very much for the fix
