### ISSUE TITLE
linclust clusters non-identical sequences with --min-seq-id 1.0 -c 1.0

### ISSUE THREAD

**Issue by chris-rands** [soedinglab/MMseqs2#200]
## Expected Behavior
Running linclust with with --min-seq-id 1.0 -c 1.0 clusters identical sequences

## Current Behavior
Non-identical sequences are clustered

## Steps to Reproduce (for bugs)
my cmd:
`mmseqs linclust my_mmseqs2.db my_mmseqs2.linclust.clusters tmp --min-seq-id 1.0 -c 1.0 --cov-mode 0 -v 3 -e 0.001`

## MMseqs Output (for bugs)
When I parse the output, I find non-identical sequences clustered together, e.g. these 2, shown here BLASTed:
```
Query  1   MYQNVLNSVNNAAIHPWDYSWFVSIMPKNNTFTHQNFTGIRTSLRLS  47
           MYQNVLNSVNNAAIHPWDYSWFVSIMPKNNTFTHQ FTGIRTSLRLS
Sbjct  1   MYQNVLNSVNNAAIHPWDYSWFVSIMPKNNTFTHQIFTGIRTSLRLS  47
                                              ^ different aa
```
## Context
Initially I thought this is just due to the reduced protein alphabet, but in this example (and others) the different residues are `I` and `N`, which doesn't appear to follow the reduced alphabet i found in the paper `(L, M), (I, V), (K, R), (E, Q), (A, S, T), (N, D), and (F, Y)`

You might say that clustering identical sequences is pointless, since it's a simple string/pattern matching exercise, but since I was trying a few different thresholds, I wanted to implement it through a consistent mmseqs2 workflow. Either way, it would be nice to understand the behaviour.

## Your Environment
Running arch-linux with MMseqs2/7-4e23d

Thank you!

**Comment by martin-steinegger** [comment]
Please use the -a flag to compute the real sequence identity. See https://github.com/soedinglab/MMseqs2/wiki#how-does-mmseqs2-compute-the-sequence-identity

**Comment by chris-rands** [comment]
Thank you, I overlooked that part of the docs. I tested with the `-a` flag and it works, but what does the `-a` flag described as "add backtrace string (convert to alignments with mmseqs convertalis utility)" do?

**Comment by milot-mirdita** [comment]
`-a` is a shortcut to also enabling `--alignment-mode 3`, which tells the Smith-Waterman alignment implementation to compute the full alignment instead of only the score (which is a lot cheaper) of the best alignment.

**Comment by chris-rands** [comment]
Thank you
