### ISSUE TITLE
result2msa output file type

### ISSUE THREAD

**Issue by smsaladi** [soedinglab/MMseqs2#205]
When running result2msa, it looks like ffindex-type files are generated:

```bash
mmseqs result2msa  \
    euk_screen/screenDB \
    uref_euk85_repDB_lfs/uref_euk85_rep \
    euk_screen_prof/euk_screen_prof \
    euk_screen_msa/euk_screen_msa
```

produced 

```bash
[saladi1@comet-ln2 mmdb]$ ll euk_screen_msa/
total 46G
drwxr-xr-x  2 saladi1 cit132  33K May 17 00:10 .
drwxr-xr-x 14 saladi1 cit132  41K May 20 12:32 ..
-rw-r--r--  1 saladi1 cit132 136G May 16 17:38 euk_screen_msa
-rw-r--r--  1 saladi1 cit132    4 May 16 17:39 euk_screen_msa.dbtype
-rw-r--r--  1 saladi1 cit132  24M May 16 17:39 euk_screen_msa.index
```

However, the extensions `.ffindex` and `.ffdata` are not used. Is this done on purpose? To use the `ffindex_soedinglab` utilities as well as functions from `ffindex.py`. It looks like those extensions are sought after.

Maybe a quick, backward-compatible fix, is to also write soft links. E.g. in this case:

```
lrwxrwxrwx  1 saladi1 cit132   14 May 17 00:10 euk_screen_msa.ffdata -> euk_screen_msa
lrwxrwxrwx  1 saladi1 cit132   20 May 17 00:10 euk_screen_msa.ffindex -> euk_screen_msa.index
```

**Comment by martin-steinegger** [comment]
The output of `result2msa` is normal mmseqs2 database. To make the database compatible with hhsuite the `.index` has to be renamed to `.ffindex` and the first column of the file has to be sorted lexicographic. You need to rename the datafile to `.ffdata`.
