### ISSUE TITLE
Identical sequences not clustering unless -c == 1 or --min-seq-id == 1 or < 0.9

### ISSUE THREAD

**Issue by bfssi-nicholas-petronella** [soedinglab/MMseqs2#206]
## Expected Behavior
My colleagues and I have noticed an unexpected behavior with linclust (using the easy-linclust pipeline in particular), it appears to not be clustering identical sequences unless -c == 1 or --min-seq-id == 1 or < 0.9. We're not sure if we're misunderstanding the functionality of the linclust options or if there is a bug. Here are the FASTA contents for the sequences I have been testing with (note they are all identical):

```
>Dupe
MTEQEKTSAVVEETREAVDTTSQPVATEKKSKNNTALILSAVAIAIALAAGVGLYGWGKQ
QAVNQTATSDALANQLTALQKAQESQKAELEGIIKQQAAQLKQANRQQETLAKQLDEVQQ
KVATISGSDAKTWLLAQADFLVKLAGRKLWSDQDVTTAAALLKSADASLADMNDPSLITV
RRAITDDIASLSAVSQVDYDGIILKLAAANQLSNQVDNLRLADNDSDGSPMDSDGEELSSSIS
EWRINLQKSWQNFMDNFITIRRRDDTAVPLLAPNQDIYLRENIRSRLLVAAQAVPRHQEE
TYRQALENVSTWVRAYYDTDDATTKAFLDEVDQLSQQNISMDLPETLQSQAMLEKLMQTR
VRNLLAQPAAGTTEAKPAPAPAPAPAPAPAPAPAPAPAPQGDTPAAAPQGE
>Dupe2
MTEQEKTSAVVEETREAVDTTSQPVATEKKSKNNTALILSAVAIAIALAAGVGLYGWGKQ
QAVNQTATSDALANQLTALQKAQESQKAELEGIIKQQAAQLKQANRQQETLAKQLDEVQQ
KVATISGSDAKTWLLAQADFLVKLAGRKLWSDQDVTTAAALLKSADASLADMNDPSLITV
RRAITDDIASLSAVSQVDYDGIILKLAAANQLSNQVDNLRLADNDSDGSPMDSDGEELSSSIS
EWRINLQKSWQNFMDNFITIRRRDDTAVPLLAPNQDIYLRENIRSRLLVAAQAVPRHQEE
TYRQALENVSTWVRAYYDTDDATTKAFLDEVDQLSQQNISMDLPETLQSQAMLEKLMQTR
VRNLLAQPAAGTTEAKPAPAPAPAPAPAPAPAPAPAPAPQGDTPAAAPQGE
>Dupe3
MTEQEKTSAVVEETREAVDTTSQPVATEKKSKNNTALILSAVAIAIALAAGVGLYGWGKQ
QAVNQTATSDALANQLTALQKAQESQKAELEGIIKQQAAQLKQANRQQETLAKQLDEVQQ
KVATISGSDAKTWLLAQADFLVKLAGRKLWSDQDVTTAAALLKSADASLADMNDPSLITV
RRAITDDIASLSAVSQVDYDGIILKLAAANQLSNQVDNLRLADNDSDGSPMDSDGEELSSSIS
EWRINLQKSWQNFMDNFITIRRRDDTAVPLLAPNQDIYLRENIRSRLLVAAQAVPRHQEE
TYRQALENVSTWVRAYYDTDDATTKAFLDEVDQLSQQNISMDLPETLQSQAMLEKLMQTR
VRNLLAQPAAGTTEAKPAPAPAPAPAPAPAPAPAPAPAPQGDTPAAAPQGE
```

## Current Behavior
Below are a set of commands we've tested. Note that defaults for alignment-mode and cov-modes were used in the example commands, however we have tried the other modes and the same results are exhibited. The -a flag is also being used since we noticed it was recommended in a previous issues post. Finally, we have been checking the output _cluster.tsv file to verify the clusters.

Commands 1 - 5 vary the --min-seq-id parameter.
Commands 6 - 10 vary the -c parameter.

_Cmd1 (-c 0.95 --min-seq-id 0.7)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.95 --min-seq-id 0.9 --max-iterations 1000 -a`

_Cmd2 (-c 0.95 --min-seq-id 0.8)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.95 --min-seq-id 0.8 --max-iterations 1000 -a`

_Cmd3 (-c 0.95 --min-seq-id 0.9)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.95 --min-seq-id 0.9 --max-iterations 1000 -a`

_Cmd4 (-c 0.95 --min-seq-id 0.99)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.95 --min-seq-id 0.99 --max-iterations 1000 -a`

_Cmd5 (-c 0.95 --min-seq-id 1)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.95 --min-seq-id 1 --max-iterations 1000 -a`

_Cmd6 (-c 0.5 --min-seq-id 0.9)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.5 --min-seq-id 0.9 --max-iterations 1000 -a`

_Cmd7 (-c 0.9 --min-seq-id 0.9)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.9 --min-seq-id 0.9 --max-iterations 1000 -a`

_Cmd8 (-c 0.99 --min-seq-id 0.9)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 0.99 --min-seq-id 0.9 --max-iterations 1000 -a`

_Cmd9 (-c 1 --min-seq-id 0.9)_
`mmseqs easy-linclust duplicate_cluster_test.faa dupe_test tmp --add-self-matches -c 1 --min-seq-id 0.9 --max-iterations 1000 -a`

## MMseqs2 _cluster.tsv output
_Cmd1 cluster.tsv output: (-c 0.95 --min-seq-id 0.7)_
Dupe | Dupe
Dupe | Dupe2
Dupe | Dupe3

_Cmd2 cluster.tsv output: (-c 0.95 --min-seq-id 0.8)_
Dupe | Dupe
Dupe | Dupe2
Dupe | Dupe3

_Cmd3 cluster.tsv output: (-c 0.95 --min-seq-id 0.9) **(Issue)**_
Dupe | Dupe
Dupe2 | Dupe2
Dupe3 | Dupe3

_Cmd4 cluster.tsv output: (-c 0.95 --min-seq-id 0.99) **(Issue)**_
Dupe | Dupe
Dupe2 | Dupe2
Dupe3 | Dupe3

_Cmd 5 cluster.tsv output: (-c 0.95 --min-seq-id 1)_
Dupe | Dupe
Dupe | Dupe2
Dupe | Dupe3

_Cmd 6 cluster.tsv output: (-c 0.5 --min-seq-id 0.9) **(Issue)**_
Dupe | Dupe
Dupe2 | Dupe2
Dupe3 | Dupe3

_Cmd7 cluster.tsv output: (-c 0.9 --min-seq-id 0.9) **(Issue)**_
Dupe | Dupe
Dupe2 | Dupe2
Dupe3 | Dupe3

_Cmd8 cluster.tsv output: (-c 0.99 --min-seq-id 0.9) **(Issue)**_
Dupe | Dupe
Dupe2 | Dupe2
Dupe3 | Dupe3

_Cmd9 cluster.tsv output: (-c 1 --min-seq-id 0.9)_
Dupe | Dupe
Dupe | Dupe2
Dupe | Dupe3

## Context
In the above commands only commands 1,2,5,9 yield the expected result. If I am understanding the parameters correctly shouldn't all the above commands yield the same result when 100% identical sequences are input? We have attempted playing with all of the different modes and parameters (they did yield different albeit incorrect results) but unless -c == 1 or --min-seq-id == 1 or < 0.9 then the identical sequences are not clustering.

## Your Environment
mmseqs easy-linclust was used for the tests above
MMseqs2 Version: 8.fac81

**Comment by martin-steinegger** [comment]
Thank you for reporting this bug and this detailed analysis. This really helps me a lot. 
I understand the issues now and I think I can fix the behavior the next days. 
The issues occurs because we do not pick the best diagonal at the 'kmermatcher'. Since it is not the best diagonal the sequence will be filtered before the smith waterman alignment stage. The filtering criteria are less strict with decreasing sequence identity criteria, so there the sequence will be aligned and clustered.

**Comment by martin-steinegger** [comment]
I have pushed a fix for the issue https://github.com/soedinglab/MMseqs2/commit/4d62a0638e97deaef14402181c1091d7f66c1bef

**Comment by bfssi-nicholas-petronella** [comment]
Excellent, I will update and give it a shot.
Thanks so much for your response and extremely fast update.
Your program/code is really remarkable stuff, thank you so much for sharing it with the open source community.

**Comment by martin-steinegger** [comment]
@bfssi-nicholas-petronella the code just improves through issues like yours. thanks a lot for your help and your encouraging words :)

**Comment by ggautreau** [comment]
Is this issue the same as the issue #88 ?

**Comment by martin-steinegger** [comment]
@ggautreau it was a different issue. Do you still encounter issues?

**Comment by ggautreau** [comment]
No, it's seem to be ok for me (using the release 8-fac81 ) even without using the option --kmer-per-seq 80 and --max-seqs 300 (that you advised me to use one year ago)

**Comment by bfssi-nicholas-petronella** [comment]
Hi Martin, it looks like this fix has not been pushed to bioconda. When I install from source all is good and the bug is fixed. However, when I use the conda install the bug remains.
Would it be possible to push the latest version of Mmseqs2 to bioconda?
Thanks

**Comment by milot-mirdita** [comment]
We still have a bit of work to do until the next release. We are targeting next week for the next release, which will then also have a new bioconda release. 

Until then please either use the statically compiled version or build MMseqs2 yourself.
