### ISSUE TITLE
[feature request] reads from gzipped FASTA files support in mmseqs createdb

### ISSUE THREAD

**Issue by jhcepas** [soedinglab/MMseqs2#21]
creating dbs directly from gzipped FASTA files would be very useful when dealing with huge datasets that are usually compressed.

**Comment by milot-mirdita** [comment]
Hi Jaime,

I added this feature to my dev branch. I will merge it into the main branch as soon as my branch is tested and stable.

Best,

Milot

**Comment by milot-mirdita** [comment]
Sorry, should not have closed the issue yet. I'll update it when the feature lands in the main branch.

**Comment by chuckpr** [comment]
+1 for gzipped input support. Thanks!

**Comment by milot-mirdita** [comment]
I just merged reading gziped input files for a few tools.

**Comment by jhcepas** [comment]
thanks @milot-mirdita !
