### ISSUE TITLE
Frame-shift aware sequence-to-protein search?

### ISSUE THREAD

**Issue by phiweger** [soedinglab/MMseqs2#211]
In Diamond, I can query long-read assemblies against protein databases using the `--long-reads` flag, which basically allows for translated search (blastx) with frame-shift tolerance:

https://github.com/bbuchfink/diamond/blob/master/src/ChangeLog#L35

This is important, bc/ most long-read only assemblies contain a lot of indels, and hence frame shifts.

Is there something comparable in MMseqs2?

Thanks a lot,
Adrian

**Comment by martin-steinegger** [comment]
We currently do not have any frame shift aware alignment in MMseqs2. They are not easy implement within MMseqs2 at the moment.

**Comment by phiweger** [comment]
Thanks for the quick reply.
