### ISSUE TITLE
createindex --check-compatible fails for nucleotide databases

### ISSUE THREAD

**Issue by simone-pignotti** [soedinglab/MMseqs2#215]
While the amino acid DBs are checked at startup and not rebuilt unless needed, the nucleotide DBs are always rebuilt. I believe the problem is that `splitsequence /opt/mmseqs-web/databases/test_nt /tmp/1055089089153665676/nucl_split_seq --max-seq-len 10000 --sequence-overlap 0 --threads 24 --compressed 0 -v 3` is ran before `indexdb`.
NT:
```
mmseqs-web-worker_1     | Check index /opt/mmseqs-web/databases/test_nt.idx
mmseqs-web-worker_1     | Index is incompatible and will be recreated.
```
AA:
```
mmseqs-web-worker_1     | Check index /opt/mmseqs-web/databases/test_aa.idx
mmseqs-web-worker_1     | Index is already up to date and compatible. Force recreation with --check-compatibility 0 parameter.
```

**Comment by milot-mirdita** [comment]
Fixed the issue in latest master. I'll make a new app release soon too.

**Comment by simone-pignotti** [comment]
Great, thank you!
