### ISSUE TITLE
Need to concatenate multiple database files into one?

### ISSUE THREAD

**Issue by LiguanLi** [soedinglab/MMseqs2#217]
Hi there:)

I am trying to use MMseqs2 to annotate sequences in ORF.fasta against database Refseq. One question maybe very obvious. The database I downloaded has >50 separated volumes. Wondering whether I need to concatenate all these volumes into one complete database? Looks MMseqs2 can only handle one database file.

Thanks a lot in advance for your help!

**Comment by martin-steinegger** [comment]
Currently the easy-search does not support it. However you can do the following.

     mmseqs createdb orfs.*.fas orfs 
     mmseqs search orfs targetDB alnRes tmp -a 
     mmseqs convertalis orfs targetDB alnRes alnRes.m8

**Comment by LiguanLi** [comment]
Thanks for quick reply! Can it work for targetDB? like this:

mmseqs createdb target.*.fasta targets 
mmseqs search ORF.fasta targets alnRes tmp -a 
mmseqs convertalis ORF.fasta targets alnRes alnRes.m8

**Comment by milot-mirdita** [comment]
Nearly correct, the query fasta has to be converted into the MMseqs2 database format too:

```
mmseqs createdb ORF.fasta queries
mmseqs createdb target.*.fasta targets
mmseqs search queries targets alnRes tmp -a
mmseqs convertalis ORF.fasta targets alnRes alnRes.m8
```

**Comment by LiguanLi** [comment]
Thanks you guys for such fast response!

**Comment by milot-mirdita** [comment]
Happy to help!
