### ISSUE TITLE
mmseqs cluster error

### ISSUE THREAD

**Issue by AlvaroRodriguezDelRio** [soedinglab/MMseqs2#218]
Hi!
I am running mmseqs cluster on an protein fasta file. According to the standard output the clustering went fine, and I can work with the output file for running subsequent commands (createtsv, etc). However, after running mmseqs cluster I also get the following error:

there must be an error: 3462516 deleted from 2208131 that now is empty, but not assigned to a cluster

Do you have any idea of what may be the cause, and whether this may interfere in the clustering?

Thanks!

Álvaro

**Comment by martin-steinegger** [comment]
Could you please provide a log of your clustering run?

**Comment by AlvaroRodriguezDelRio** [comment]
Thanks for your answer!

One more question, I just noticed the line in the log file saying "WARNING: combining cluster mode 0 in combination with coverage mode 2 can produce wrong results." in the log. What's the reason for this warning?

You can find the log file here: 

https://www.dropbox.com/s/skdw24yg3333fzr/clustering.log?dl=0

Thanks again!

Álvaro

**Comment by martin-steinegger** [comment]
@AlvaroRodriguezDelRio I just noticed that you use a super old version of MMSeqs2. I would recommend you to update it. We fixed many bug in the mean time. 

The cluster mode 0 (set cover) requires a bi-directional coverage criteria. If it is used with unidirectional coverage than it pick representative sequences that do not fulfill the clustering criteria anymore.

**Comment by martin-steinegger** [comment]
@AlvaroRodriguezDelRio do you still encounter this issue?
