### ISSUE TITLE
Odd results when clustering Swiss-Prot sequences by percent identity

### ISSUE THREAD

**Issue by GLHolliday79** [soedinglab/MMseqs2#220]
Please let me preface this with I'm sure I'm doing something silly, but for the life of me I can't figure out what.

## Expected Behavior

The number of proteins in the 70% set *should* be somewhere between the 90% and 50% sets. It definitely shouldn't be a larger set than the 50% group.

## Current Behavior

commands being run:
```
mmseq easy-cluster uniprot_sprot.fasta id90 tmp9 --min-seq-id 0.9
mmseq easy-cluster uniprot_sprot.fasta id70 tmp7 --min-seq-id 0.7
mmseq easy-cluster uniprot_sprot.fasta id50 tmp5 --min-seq-id 0.5
```
```
grep "Q07343" id50_cluster.tsv 
Q07343	Q07343
Q07343	P14646

grep "P14646" id90_cluster.tsv 
P14646	P14646
P14646	Q07343

grep "Q08493" id70_cluster.tsv 
Q08493	Q08493
Q08493	Q08499
Q08493	P14270
Q08493	Q01063
Q08493	Q3UEI1
Q08493	P14646
Q08493	Q07343
```

This was done on the Jul 15th 2019 version of Swiss-Prot (downloaded from UniProtKB on the 18th July)

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 9-d36de
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): Homebrew
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
Homebrew: 2.1.7
Make: GNU Make 4.1
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): support for both AVX2 and SSE available. Mem: 62 GiB
* Operating system and version: x86_64-pc linux 62.9 GiB

**Comment by martin-steinegger** [comment]
I have clustered the swissprot at 90, 70 and 50% and the respective cluster sizes are `326642`, `209899` and `123019`. 

```
# 90%
easy-cluster /Users/mad/Downloads/uniprot_sprot.fasta.gz /tmp/uni_90 /tmp/uni_tmp --min-seq-id 0.9
grep -c ">" /tmp/uni_90_rep_seq.fasta
326642

# 70%
mmseqs easy-cluster /Users/mad/Downloads/uniprot_sprot.fasta.gz /tmp/uni_70 /tmp/uni_tmp --min-seq-id 0.7
grep -c ">" /tmp/uni_70_rep_seq.fasta
209899

# 50%
mmseqs easy-cluster ~/Downloads/uniprot_sprot.fasta.gz /tmp/uni_50 /tmp/uni_tmp/ --min-seq-id 0.5
grep -c ">" /tmp/uni_50_rep_seq.fasta
123019
```

If you want to know the amount of clusters from the `cluster.tsv` file than you need to count how many identifiers are in the first column. 
E.g. 
`cut -f1  id90_cluster.tsv| uniq | wc -l `

**Comment by GLHolliday79** [comment]
Thanks for the reply, I can confirm I get the comparable counts for the number of clusters. 326662, 209915, and 123014; I am assuming the slight difference is in the downloaded data.

However, I am confused by the fact that for a specific example (Q07343), the 70% cluster has 7 members whereas the 50% cluster only has  2. This seems... wonky (for want of a better word). I would expect that the number of members would be between the 50% and 90% count... am I missing something about how the tool actually works?

**Comment by martin-steinegger** [comment]
yes it is not guaranteed that the cluster will be the same between clustering runs with different sequence identity thresholds. One big reason for this the set cover algorithm that greedily picks the representative sequences based on the amount of sequence they can cover. There is an exponential amount of possible clustering, we just report one of them.

**Comment by GLHolliday79** [comment]
Thank you. Could you tell me how I would re-create the CD-HIT like results?

**Comment by martin-steinegger** [comment]
So you want the longest sequence to be the representative sequence. 
This can be done with `--cluster-mode 3`. 

The closet result to CD-HIT can be achieved by the following command: 

    REASSIGN=TRUE mmseqs cluster seqDB clu tmp --cluster-mode 3

We will make the REASSIGN variable into a real MMseqs2 parameter.

**Comment by GLHolliday79** [comment]
Very much appreciated, thank you. I will close this ticked off then :-)
