### ISSUE TITLE
How to inspect a taxonomy db?

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#222]
When creating a taxonomy database via:

```
mmseqs createdb target.fasta targetDB
mmseqs createtaxdb targetDB tmp
```

...how can the user know what taxonomy is given to each sequence in the tax database? There doesn't seem to be a subcommand for inspecting the taxonomy database. One could maybe to it with the `mmseqs filtertaxdb` command, but it requires a "targetDB" and a "taxaDB"; however, the `mmseqs createtaxdb` doesn't seem to create any specific "taxaDB" file. 

It appears that `mmseqs createtaxdb` doesn't warn about missing uniprot identifiers. It really doesn't provide any summary at all. I just tried provided a full `seqID <--> uniprot` mapping file versus a truncated file, and I got the same "Database created" output message, so it seems that even if there's really little to no taxonomic info in the taxonomy database, the database will still be created without the user knowing what info is actually in it. 

I'm using version 9.d36de

**Comment by nick-youngblut** [comment]
Just to better clarify why I want to inspect the taxonomy database created by `mmseqs createtaxdb`:

The docs state that `mmseqs createtaxdb` will automatically create the taxDB by downloading NCBI taxdump and getting uniprot taxID mapping. It seems to do this and then state "Database created", but I don't know if any of my sequences were actually mapped to any taxonomy info. All my sequences should just be uniprot IDs; for example:

```
>A0A1Q6BRU5
MAKITVFSPVKNFSGVSVGITFSHGVGVVEEGSAAHKYFQRRGYAFSLEEDRASQSPGASQDLPEGGKTAEKEGASTPPDIDIPGMPGAKALRSEWIAFAESLGIETESLTIPQIRERIIVEHLNAPNV
>A0A2V1A9G4
MSSRNQFRKNIGSVGPFGEPFLNGVPGFGENFTIPFALCDKDEYLLWLFHFIGQLRTQYGENVARYVVEYINGNDVQQIMIRNLASSVIYSTLGYGVCMVYNQKYCDTALGPMDCFRKFHQNFCKYKLEDLEEWFSNWAVVMTKLRAEGEIEAYEFSQELNGFTDEELELMDNMQYGLYDKKELIRRYLQGSGSDVIDLSKRAYDVNSKHGQPPLHKKAIDGSWFLSKPLSEAVGPE
>A0A0A9U2E6
MLDALSIFSKVSLGLVVVREPLGRSLSLSLVAALPIALQHGSEWCRMALAQTRMLS
```

but I don't know `mmseqs createtaxdb` is actually parsing these UniProt IDs correctly and mapping them to taxonomy info.

**Comment by martin-steinegger** [comment]
The database base produced by createtaxdb contains a file called `_mapping` that maps the internal mmseqs id to an taxonomical id `MMseqsId TaxId`. It is possible to inspect this mapping file by merging it with the `.lookup` file (this file contains `MMseqsId FastaId`. 

    awk 'FNR==NR{f[$1]=$0; next} $1 in f{ print $2" has taxid"} !($1 in f){print $2" has no taxid"} ' DB_mapping DB.lookup

**Comment by nick-youngblut** [comment]
So, if the the `*_mapping` file is empty, that means that `mmseqs createtaxdb` didn't map any tax info to the sequences? I didn't get any warning from `mmseqs createtaxdb` stating that there was a mapping issue for any of my sequences. All of my sequences are just labeled with UniProt identifiers (see the fasta snippet above), so I thought that `mmseqs createtaxdb` could handle that mapping automatically so that I didn't have to manually creating a seqID <--> taxID mapping file (ie., `mmseqs createtaxdb --tax-mapping-file my_custom_mapping_file`)

**Comment by martin-steinegger** [comment]
Yes if its empty than it could not map any identifier. It can handle the mapping of Uniprot sequences automatically. `createtaxdb` performs the following code to retrieves the mmseqs identifiers to tax. id mapping. 

    URL="ftp://ftp.expasy.org/databases/uniprot/current_release/knowledgebase/idmapping/idmapping.dat.gz"
    wget -nv -O - "$URL" | zcat | awk '$2 == "NCBI_TaxID" {print $1"\t"$3 }' > taxidmapping
    awk 'NR == FNR { f[$1] = $2; next } $2 in f { print $1"\t"f[$2] }' taxidmapping DB.lookup > DB_mapping

**Comment by nick-youngblut** [comment]
Thanks for the awk code! The code + your explanation really helps with determining which records in the taxDB actually have taxonomy info.

**Comment by adriaaula** [comment]
Hello! 

I wanted to use also the taxonomy database, but I think in a similar situation to the one described here: 
```
-rw-r--r-- 1 aauladell bio    0  2 oct 14:46 DB_mapping
-rw-r--r-- 1 aauladell bio 3,8M 10 set 15:25 delnodes.dmp
-rw-r--r-- 1 aauladell bio 991K 10 set 15:25 merged.dmp
-rw-r--r-- 1 aauladell bio 175M 10 set 15:25 names.dmp
-rw-r--r-- 1 aauladell bio 139M 10 set 15:25 nodes.dmp
-rw-r--r-- 1 aauladell bio    0 10 set 19:38 targetDB_mapping
-rw-r--r-- 1 aauladell bio    0 10 set 19:43 targetDB_mapping.complete
-rw-r--r-- 1 aauladell bio 2,8G  2 oct 13:33 taxidmapping
-rw-r--r-- 1 aauladell bio  43G  9 set 18:15 uniref90.fasta
-rw-r--r-- 1 aauladell bio  32G 10 set 15:17 unirefDB
-rw-r--r-- 1 aauladell bio    4 10 set 15:18 unirefDB.dbtype
-rw-r--r-- 1 aauladell bio 3,8M 10 set 19:43 unirefDB_delnodes.dmp
-rw-r--r-- 1 aauladell bio  12G 10 set 15:12 unirefDB_h
-rw-r--r-- 1 aauladell bio    4 10 set 15:13 unirefDB_h.dbtype
-rw-r--r-- 1 aauladell bio 2,3G 10 set 15:19 unirefDB_h.index
-rw-r--r-- 1 aauladell bio 2,3G 10 set 15:18 unirefDB.index
-rw-r--r-- 1 aauladell bio 2,9G 10 set 15:23 unirefDB.lookup
-rw-r--r-- 1 aauladell bio    0  2 oct 14:47 unirefDB_mapping
-rw-r--r-- 1 aauladell bio 991K 10 set 19:43 unirefDB_merged.dmp
-rw-r--r-- 1 aauladell bio 175M 10 set 19:43 unirefDB_names.dmp
-rw-r--r-- 1 aauladell bio 139M 10 set 19:43 unirefDB_nodes.dmp
```

My `_mapping` files are empty. 

I tried to use the awk code you posted below but it didn't work. My opinion is that it is maybe I haven't downloaded the proper uniprot? In my case I downloaded `uniref90.fasta` 

Maybe in the wiki page the example could be started with the specific ftp for uniprot, I don't know. 

mmseqs2 version 15c7762

**Comment by adriaaula** [comment]
I don't know if this will appear, I am going to put some @ 
@milot-mirdita @martin-steinegger

**Comment by milot-mirdita** [comment]
Can you make a new issue please and post the commands you used to create the database?
