### ISSUE TITLE
Global alignment?

### ISSUE THREAD

**Issue by jvivian-atreca** [soedinglab/MMseqs2#223]
Firstly, thank you for the great tool and documentation. Is there an option to run MMSeqs2 as a global aligner? I know the standard output format is BLAST's M8 format, which is a local aligner, but was hoping I could coerce MMSeqs2 into using the entire sequence and still get useful values like similarity score, E-value, etc. 

`search` even has a `--global-alignment` option, but it doesn't actually force a global alignment, just how the substitution scoring works.

**Comment by milot-mirdita** [comment]
We currently don't support global alignments. It should be not too difficult to integrate a fast NW implementation as a separate MMseqs2 module. However, since none of us is working with global alignments, this would be a very low priority feature.

The `--global-alignment` parameter is really badly named and does something unrelated for normal searches. We really should remove it.

**Comment by jvivian-atreca** [comment]
@milot-mirdita — Thank you for the reply. 

> The --global-alignment parameter is really badly named and does something unrelated for normal searches. We really should remove it.

Ah ok, that's good to know.

> Either opal or parasail might serve as the base for the implementation. If you are interested in contributing this feature we could help guide you through.

Thank you for the references and the offer to assist in contributing. Currently my language comfortability extends only to Python and Rust, so it'd be a stretch for me at the moment.

I don't want to close this issue in the case you want to keep it open to consider down the line, but I consider it addressed. Thanks again!

**Comment by milot-mirdita** [comment]
I am moving this issue to the projects page and closing it for now. Since there is currently none working on it.

**Comment by iwangtoknow** [comment]
@milot-mirdita Hi Milot, how is it going with this topic of global alignment? 

My workflow to clustering proteins like below:
1. blastp for local alignment, find similar sequence pairs;
2. needle for global alignment access similarity for blastp pairs;
3. mcl to cluster the needle result.

According to my previous experience, only a local alignment could be not enough to have clusters.
I'm not clear about the clustering function in mmseqs2, is it enough to substitute my whole workflow?

Hope to see your comment.

Cheers,

**WANG**

**Comment by milot-mirdita** [comment]
We don't have any need internally at the moment for global alignments, so we don't really plan on implementing real global alignments. We would be happy for external contributions or guiding someone through the implementation though.

What exactly is the purpose of global protein alignments in your case? Generally we would solve this problem through a high bi-directional coverage cut-off (See https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster).

**Comment by iwangtoknow** [comment]
Hi Milot,
I'm working on a single species, local alignment is sensitive for remote homologs, but I need homologs that are closed to each other. I need global alignment to obtain coverage of the protein pair result from local alignment. After clustering procedure, my next step is building phylogeny of the protein families.
The phylogeny shows more details in the protein family. According my experience, only the local alignment is not enough for filtering the undesired proteins out of a family.
I'd like to help with the implementation of NW.
**WANG**
