### ISSUE TITLE
linclust generates duplicate representative sequence IDs

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#224]
I'm using `mmseqs 9.d36de`, and running `linclust` as in the following:

```
# cluster
mmseqs linclust --threads 24 seq_db cluster_db tmp_dir

# creating _h file
mmseqs createsubdb cluster_db seq_db_h cluster_db_h

# get representative sequences for each cluster
mmseqs result2flat seq_db cluster_db output_rep_seqs.faa --use-fasta-header
```

While the entire rep seq ID is unique (eg., `>1000000 2+209	3`), the base ID (eg., `>1000000`) is not, so any downstream tool that strips off the characters past the first space (` 2+209	3` in this example) will result in ambiguous mappings to the sequences.

**Comment by martin-steinegger** [comment]
You could use `convert2fasta` instead of `result2flat`. This should printout the whole header information. 

     mmseqs convert2fasta cluster_db output_rep_seqs.faa

**Comment by nick-youngblut** [comment]
I tried using `convert2fasta` instead of `result2flat`, but I still get many duplicate IDs, even without removing everything after the first space. For example:

```
>93922 149-149	3
PTTGELYKVAGKENNDSIKGYRSAYNKATETAKAGYYSVELTDYHIKVESSATPHCGILHFTYPSSDQSRIQIDLARRVGGTSTSQYIKVVDDYTIQGWMKFTPDGGGCGNGEGKADYTVYYYAQFSKPLANYGFWSADIPEHWVRKRDEVV
--
>93922 149-149	3
LARFGAKVTQTDTSVTVEKGELNAIDIDASQIPDLVPVLTVCAAFAKGTTRIYN
--
>93922 149-149	3
ITDTVTKDMESCFSTDCQETYNQTPVSFTFITPETEELFKPDNYPERFSSWFEKFVEHV
```

**Comment by martin-steinegger** [comment]
Could you please provide a sample set to reproduce the error?

**Comment by milot-mirdita** [comment]
Was `seq_db` created by `extractorfs`? That module creates a special header file to identify where the ORF came from. I could build something to would allow to resolve the original header again, however that would still not result in unique headers.

The easiest solution might be to write some small 'awk/sed/perl' script that replaces the spaces in the FASTA header with an underscore or something similar.

**Comment by martin-steinegger** [comment]
Please reopen if the error still occurs.

**Comment by mmpust** [comment]
I experience the same problem. After running linclust and extracting the representative sequences, I have duplicate IDs
```
>k99_9972_2 # 266 # 886 # 1 # ID=81340_2;partial=00;start_type=GTG;rbs_motif=AGGAG;rbs_spacer=5-10bp;gc_cont=0.655
>k99_9972_2 # 500 # 1270 # 1 # ID=10959_2;partial=00;start_type=TTG;rbs_motif=GGxGG;rbs_spacer=5-10bp;gc_cont=0.471
```
So reads mappings and downstream tools break because of this.

**Comment by martin-steinegger** [comment]
We are aware of the problem. The issue is that prodigal does not respect the fasta definition here. Everything after a white space is a comment, not an identifier. 
I recommend combining the first seven columns into an identifier before clustering.
