### ISSUE TITLE
MMSeqs2 identifying mismatches in identical sequences unless `-a 1` 

### ISSUE THREAD

**Issue by jvivian-atreca** [soedinglab/MMseqs2#225]
## Expected Behavior
Identical sequences would return 0 mismatches and an identity of 1.0

## Current Behavior
Identical sequences incorrectly labelled as having mismatches which lowers the identity % when run with default options.

## Steps to Reproduce (for bugs)
Create two FASTA files, `query.fasta` and `target.fasta` with a single identical sequence: 
```
>Test-query
RATQGISAWLASASLLQSQYANSFPWTF
```

Then run the latest docker container (a73c7fd8ba9c)
```
docker run -v $(pwd):/data soedinglab/mmseqs2 mmseqs easy-search /data/query.fasta /data/target.fasta /data/test.m8 /data/tmp
```

I was trying to compute the alignment to see which AA it thought was a mismatch, but interestingly adding `-a 1` changes the identity to 1.0.

## MMseqs Output (for bugs)
```
Test-query      Test-target     0.954   28      1       0       1       28      1       28      3.965E-20       59
```
MMSeqs2 reports an identity of 0.954 instead of 1. After alignment length (28), it reports 1 mismatch. Adding `-a 1` changes this to 
```
Test-query      Test-target     1.000   28      0       0       1       28      1       28      3.965E-20       59
```

## Context
I ran MMSeqs2 with 293 query sequences against 600,000 target sequences. A separate pairwise global alignment run I did identified 1,745 identical sequences across query and target whereas MMSeqs2 reported zero 100% identical matches. Adding `-a 1` seems to mostly correct this issue. Reading the options, it seems that `-a` exists just to return the aligned string, so I'm surprised to see it affects how identity / mismatches are calculated.

## Your Environment
I used the latest Docker container (a73c7fd8ba9c)

**Comment by milot-mirdita** [comment]
This is expected but unintuitive behavior. MMseqs2 does not, by default, compute the real alignment boundaries or sequence identity. It computes only the Smith-Waterman score and approximates the sequence identity (See: https://github.com/soedinglab/MMseqs2/wiki#how-does-mmseqs2-compute-the-sequence-identity).

But `easy-search` should do the thing that is the least surprising so we change this behavior.

**Comment by jvivian-atreca** [comment]
Hi @milot-mirdita — Thank you for the clarification. I read that section but I didn't understand its implication with respect to exact sequences.
