### ISSUE TITLE
Alignments from mmseqs taxonomy (-a flag not working)?

### ISSUE THREAD

**Issue by shandley** [soedinglab/MMseqs2#226]
Might be missing something with the command syntax, but shouldn't it be possible to pull out alignment stats into an m8 formatted file from a mmseqs taxonomy command? 

## Expected Behavior
Alignment file made available for convertalis too *.m8 format.

## Current Behavior
No alignment file created with -a flag using mmseqs2 taxonomy

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

mmseqs taxonomy $OUT/seqtable_queryDB $DB $OUT/taxonomyResult tmp_aa -a --start-sens 1 --sens-steps 3 -s 7 --search-type 2 \
        --tax-lineage true --lca-ranks "superkingdom:phylum:class:order:family:genus:species";

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

taxonomy results come out perfect, but there are no alignment files for convertalis

**Comment by milot-mirdita** [comment]
This is a bit of a problem of confusing documentation. `convertalis` is never called in the taxonomy workflow. You can instead pass the parameter `--tax-output-mode 1` to get only an alignment result and then call `lca` and `convertalis` separately:

```
mmseqs taxonomy $OUT/seqtable_queryDB $DB $OUT/taxonomyResult tmp_aa -a --start-sens 1 --sens-steps 3 -s 7 --search-type 2 --tax-output-mode 1
mmseqs convertalis $OUT/seqtable_queryDB $DB $OUT/taxonomyResult $OUT/aln.m8 --format-output "query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,qaln,taln"
mmseqs lca $OUT/seqtable_queryDB $DB $OUT/taxonomyResult $out/lcaDB --tax-lineage true --lca-ranks "superkingdom:phylum:class:order:genus:species"
mmseqs createtsv $OUT/seqtable_queryDB $out/lcaDB $OUT/lca.tsv
```

We'll think how to make this clearer or how to allow to add alignment information to a taxonomy result.

**Comment by shandley** [comment]
Hi @milot-mirdita. Thanks! This seems to be working exactly as we need. Thanks for the quick reply!
