### ISSUE TITLE
result2msa segmentation fault (Linux/MacOS) and cygwin error (Windows)

### ISSUE THREAD

**Issue by Alopex-Lagopus** [soedinglab/MMseqs2#229]
## Expected Behavior
MSA completes

## Current Behavior
Currently, the result2msa command seems to be throwing errors on any operating system and build I try. Also perhaps worth noting it only happens on certain input sequences for whatever reason (you can see from my Windows attempt, it aborts halfway through).

## Steps to Reproduce (for bugs)
create db
index db
search db with query file
try to run result2msa -> crash
Files can be supplied as requested

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

Ubuntu, self-compile:

mmseqs result2msa /hdd/mmtestoutput3/mmseqs_files/in.mmdb /hdd/humanref/jhhutargetDB /hdd/mmtestoutput3/mmseqs_files//out.mm_search /hdd/mmtestoutput3/mmseqs_files//out.mm_msa
result2msa /hdd/mmtestoutput3/mmseqs_files/in.mmdb /hdd/humanref/jhhutargetDB /hdd/mmtestoutput3/mmseqs_files//out.mm_search /hdd/mmtestoutput3/mmseqs_files//out.mm_msa 

MMseqs Version:           	4404fe0a78cf6684e1e701e523789d8e6c1bfbe5
Substitution matrix       	nucl:nucleotide.out,aa:blosum62.out
Profile e-value threshold 	0.001
Allow deletions           	false
Add internal id.          	false
Compositional bias        	1
Filter MSA                	0
Maximum seq. id. threshold	0.9
Minimum seq. id.          	0
Minimum score per column  	-20
Minimum coverage          	0
Select N most diverse seqs	1000
Threads                   	4
Compress MSA              	false
Summarize headers         	false
Summary prefix            	cl
Omit consensus            	false
Skip query                	false
Gap open cost             	11
Gap extension cost        	1
Compressed                	0
Verbosity                 	3

Start computing  multiple sequence alignments.
Query database size: 11 type: Aminoacid
Target database size: 20667 type: Aminoacid
[>                                                                ] 0.00% 1 eta [======>                                                          ] 10.00% 2 etaSegmentation fault (core dumped)

Windows 7 static compile (different db/query file):

F:\>mmseqs result2msa plsworkout2/mmseqs_files/in.mmdb db/testtargetDB plsworkou
t2/mmseqs_files/out.mm_search plsworkout2/mmseqs_files/out.mm_msa
result2msa plsworkout2/mmseqs_files/in.mmdb db/testtargetDB plsworkout2/mmseqs_f
iles/out.mm_search plsworkout2/mmseqs_files/out.mm_msa

MMseqs Version:                 4404fe0a78cf6684e1e701e523789d8e6c1bfbe5
Substitution matrix             nucl:nucleotide.out,aa:blosum62.out
Profile e-value threshold       0.001
Allow deletions                 false
Add internal id.                false
Compositional bias              1
Filter MSA                      0
Maximum seq. id. threshold      0.9
Minimum seq. id.                0
Minimum score per column        -20
Minimum coverage                0
Select N most diverse seqs      1000
Threads                         8
Compress MSA                    false
Summarize headers               false
Summary prefix                  cl
Omit consensus                  false
Skip query                      false
Gap open cost                   11
Gap extension cost              1
Compressed                      0
Verbosity                       3

Start computing  multiple sequence alignments.
Query database size: 19 type: Aminoacid
Target database size: 20197 type: Aminoacid
[>                                                                ] 0.00% 1 eta
[===>                                                             ] 5.56% 2 eta
[=======>                                                         ] 11.11% 3 eta
[==========>                                                      ] 16.67% 4 eta
[==============>                                                  ] 22.22% 5 eta
[==================>                                              ] 27.78% 6 eta
[=====================>                                           ] 33.33% 7 eta
[=========================>                                       ] 38.89% 8 eta
[============================>                                    ] 44.44% 9 eta
[================================>                                ] 50.00% 10 et
[====================================>                            ] 55.56% 11 et
[=======================================>                         ] 61.11% 12 et
      0 [mmseqs] mmseqs 1552 cygwin_exception::open_stackdumpfile: Dumping stack
 trace to mmseqs.exe.stackdump

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):  MMseqs2 Version: 4404fe0a78cf6684e1e701e523789d8e6c1bfbe5
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
Self-compiled (macos 10.13, ubuntu 18, fedora 30...), statically compiled (Windows 7). Also tried statically compiled SSE for ubuntu.
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
cmake 3.14 and 3.15
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): AVX2: No. SSE: Yes. RAM: 16gb
* Operating system and version: MacOS10.13, Ubuntu 18.04, fedora 30, Windows 7

**Comment by martin-steinegger** [comment]
Thank you for reporting this issue. Could you provide the input files to reproduce the error?

**Comment by Alopex-Lagopus** [comment]
[mmseqslinux.zip](https://github.com/soedinglab/MMseqs2/files/3623807/mmseqslinux.zip)

[mmseqwin.zip](https://github.com/soedinglab/MMseqs2/files/3623810/mmseqwin.zip)

Thanks for looking into this -- these files should reproduce the error but may be machine/environment dependent. We have had the same error on three PCs (~5-8 years old) but had success today on MacOS on a < 1 year old computer. I don't know if that will help diagnose the issue, but the files should contain the relevant inputs to reproduce the issue, from two different operating systems.

**Comment by milot-mirdita** [comment]
Sorry this took so long. Thank you for the bug report. The issue should now be fixed in git master. Could you try the latest commit?
