### ISSUE TITLE
apply are generating malformed STDIN to MSA programs

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#230]
Hi,

I am using a strategy that I have been using for some time successfully but since the last update, it has stopped working.

The idea is to group the sequences and generate an MSA for each cluster to generate models for each MSA and compare all models with hhsearch.

So after compiling my cluster, I use `createseqfiledb` and then use` apply` with clustalo.

Exactly the apply step has returned me some errors and it never finishes.

The usual pipeline is:
```
# .... a lot of clusters hierarchically prepared  
mmseqs mergeclusters sbps.DB sbps.CLU $(\ls -d1t id_0cov_0.8evalue_* | tac | sed 's/$/\/MMseqsClust/' | xargs ) --threads 30 
mmseqs createtsv sbps.DB sbps.DB sbps.CLU sbps.CLU.tsv --threads 40

mmseqs createseqfiledb sbps.DB sbps.CLU sbps.CLU.SEQ --threads 30 --min-sequences 3

## errors from this point
mmseqs apply sbps.CLU.SEQ sbps.CLU.SEQ.MSA --threads 30 -- clustalo -i - --output-order=input-order --threads=1 --iter=5 
```

The error is exemplified by this:
```
apply sbps.CLU.SEQ sbps.CLU.SEQ.MSA --threads 30 -- clustalo -i - --threads=1 --iter=5 

MMseqs Version:	4404fe0a78cf6684e1e701e523789d8e6c1bfbe5
Threads   	30
Compressed	0
Verbosity 	3

Start applying.
write stdin1: Bad address                                         ] 0.00% 1 eta -
ERROR: Sequence 'WP_078846918.1/28-316' has 0 residues
FATAL: Reading sequence file '-' failed
ERROR: Sequence 'WP_082295029.1/41-339' has 0 residues            ] 2.09% 29 eta 2h 51m 21s       
FATAL: Reading sequence file '-' failed
Entry 30 exited with error code 1!

```

I may share the `sbps.DB` and `sbps.CLU` and associated files to check, but I'm sure that they are fine. Just tell me how to send to you.

But I don't know if the issue happens in `createseqfiledb` but since it doesn't return any error message and the files seem okay, the problem may be the STDIN.
Searching sequences like `WP_082295029.1/41-339` in the files I was able to find it and the sequence is the same as the initial fasta file. 

Thanks in advance.

**Comment by acpguedes** [comment]
The `apply` of the `MMseqs Version:	661832da23fb6198b5c2265dd16998081d6cc75d` worked fine, I just runned the apply step in this version.

**Comment by milot-mirdita** [comment]
Can you upload this `sbps.CLU.SEQ` database somewhere so I can try to reproduce the issue? Sorry, I am a bit swamped with work currently.

**Comment by acpguedes** [comment]
Sorry to send you too late.   
Would you check if you may download the data from [here](https://drive.google.com/open?id=1pqUXLM6MT1cQVyQkccNDecMRdwNA8Osi) 

If you cannot, do you suggest any other place to upload it?

**Comment by milot-mirdita** [comment]
It told me to request permissions to access the file, which I did.

**Comment by acpguedes** [comment]
It is granted

**Comment by milot-mirdita** [comment]
Thanks a lot. The latest commit should fix the issue.
