### ISSUE TITLE
MMseqs2 apparently slower than Diamond

### ISSUE THREAD

**Issue by zsram** [soedinglab/MMseqs2#231]
[mmseqs2.log.txt](https://github.com/soedinglab/MMseqs2/files/3654776/mmseqs2.log.txt)
## Expected Behavior
To be faster

## Current Behavior
It takes the double of time than Diamond to perform the same task with similar results over the same query and target database

## Steps to Reproduce (for bugs)
time diamond blastx -d /d/Databases/Kegg/sram/kegg -q MOMZ_moomz1_200m.fna -o MO
MZ_moomz1_200m.kegg.raw --sensitive --max-target-seqs 1
real 32m12.614s
user  1091m19.492s
sys  34m5.028s

time mmseqs easy-search MOMZ_moomz1_200m.fna /d/Databases/Kegg/sram/mmseqs/ke
gg mmseqs_results2.m8 tmp --start-sens 1 --sens-steps 3 -s 6 --strand 2 --max-seqs 1
real 56m26.161s
user 2146m1.584s
sys 37m49.528s

## Your Environment
MMseqs2 Version: 4404fe0a78cf6684e1e701e523789d8e6c1bfbe5
40 cores Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
128 GB main memory
Query Fasta: 516296 metagenomic sequences (454 FLX), average seq size ~400bp
No other processes were running during the tests (besides those elementary to the SO)

**Comment by martin-steinegger** [comment]
Could you please provide the log? Thanks a lot.

**Comment by zsram** [comment]
Hi Martin, I've uploaded a log file
Thanks and best regards,
---sram

**Comment by martin-steinegger** [comment]
@zsram I can not see the uploaded log. Can you past it in a gist https://gist.github.com/?

**Comment by zsram** [comment]
@martin-steinegger OK. Here I am pasting that text:
easy-search MOMZ_moomz1_200m.fna /d/Databases/Kegg/sram/mmseqs/kegg test.m8 tmp --start-sens 1 --sens-steps 3 -s 6 --strand 2 --max-seqs 1 

MMseqs Version:                       	4404fe0a78cf6684e1e701e523789d8e6c1bfbe5
Substitution matrix                   	nucl:nucleotide.out,aa:blosum62.out
Add backtrace                         	false
Alignment mode                        	3
E-value threshold                     	0.001
Seq. id. threshold                    	0
Min. alignment length                 	0
Seq. id. mode                         	0
Alternative alignments                	0
Coverage threshold                    	0
Coverage mode                         	0
Max sequence length                   	65535
Compositional bias                    	1
Realign hits                          	false
Max reject                            	2147483647
Max accept                            	2147483647
Include identical seq. id.            	false
Preload mode                          	0
Pseudo count a                        	1
Pseudo count b                        	1.5
Score bias                            	0
Gap open cost                         	11
Gap extension cost                    	1
Threads                               	40
Compressed                            	0
Verbosity                             	3
Seed substitution matrix              	nucl:nucleotide.out,aa:VTML80.out
Sensitivity                           	6
K-mer size                            	0
K-score                               	2147483647
Alphabet size                         	21
Max results per query                 	1
Split database                        	0
Split mode                            	2
Split memory limit                    	0
Diagonal scoring                      	true
Exact k-mer matching                  	0
Mask residues                         	1
Mask lower case residues              	0
Minimum diagonal score                	15
Spaced k-mers                         	1
Spaced k-mer pattern                  	
Local temporary path                  	
Rescore mode                          	0
Remove hits by seq. id. and coverage  	false
Sort results                          	0
Mask profile                          	1
Profile e-value threshold             	0.001
Use global sequence weighting         	false
Filter MSA                            	1
Maximum seq. id. threshold            	0.9
Minimum seq. id.                      	0
Minimum score per column              	-20
Minimum coverage                      	0
Select N most diverse seqs            	1000
Omit consensus                        	false
Min codons in orf                     	30
Max codons in length                  	32734
Max orf gaps                          	2147483647
Contig start mode                     	2
Contig end mode                       	2
Orf start mode                        	1
Forward frames                        	1,2,3
Reverse frames                        	1,2,3
Translation table                     	1
Translate orf                         	0
Use all table starts                  	false
Offset of numeric ids                 	0
Create lookup                         	0
Add orf stop                          	false
Chain overlapping alignments          	0
Merge query                           	1
Search type                           	0
Number search iterations              	1
Start sensitivity                     	1
Search steps                          	3
Run a seq-profile search in slice mode	false
Strand selection                      	2
Disk space limit                      	0
MPI runner                            	
Force restart with latest tmp         	false
Remove temporary files                	true
Alignment format                      	0
Format alignment output               	query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits
Database output                       	false
Overlap threshold                     	0
Split seq. by length                  	true
Database type                         	0
Do not shuffle input database         	tcreatedb MOMZ_moomz1_200m.fna tmp/9700814981231218113/query --max-seq-len 65535 --dont-split-seq-by-len 1 --dbtype 0 --dont-shuffle 1 --id-offset 0 --compressed 0 -v 3 

Assuming DNA database, forcing parameter --dont-split-seq-by-len true
Converting sequences
[===================================================
Time for merging to query_h: 0h 0m 0s 231ms
Time for merging to query: 0h 0m 0s 283ms
Time for merging to query.lookup: 0h 0m 0s 0ms
Time for processing: 0h 0m 1s 696ms
Tmp tmp/9700814981231218113/search_tmp folder does not exist or is not a directory.
extractorfs tmp/9700814981231218113/query tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa --min-length 30 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --translate 1 --use-all-table-starts 0 --id-offset 0 --create-lookup 0 --threads 40 --compressed 0 -v 3 

[=================================================================] 516.30K 0s 579ms
Time for merging to q_orfs_aa_h: 0h 0m 0s 661ms
Time for merging to q_orfs_aa: 0h 0m 0s 709ms
Time for processing: 0h 0m 3s 128ms
prefilter tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_0 --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 1 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 40 --compressed 0 -v 3 -s 1.000 

Query database size: 2548633 type: Aminoacid
Estimated memory consumption: 68G
Target database size: 13003941 type: Aminoacid
Index table k-mer threshold: 174 at k-mer size 7 
Index table: counting k-mers
[=================================================================] 13.00M 1m 24s 806ms
Index table: Masked residues: 71357266
Index table: fill
[=================================================================] 13.00M 50s 887ms
Index statistics
Entries:          3111458326
DB size:          27569 MB
Avg k-mer size:   2.430827
Top 10 k-mers
    SGQQRIA	74997
    GPGGKLL	59639
    GGQRVAR	38490
    LLGPGKT	25908
    YDYAIPL	22840
    GGRRVAR	21815
    PHLGGQR	19799
    TPHDFEV	17697
    PSLGGQR	13748
    FSCSHVV	12988
Time for index table init: 0h 2m 34s 667ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 174
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 2548633
Target db start 1 to 13003941
[=================================================================] 2.55M 23s 498ms

7.258993 k-mers per position
1015 DB matches per sequence
0 overflows
0 sequences passed prefiltering per query sequence
1 median result list length
1142796 sequences with 0 size result lists
Time for merging to pref_0: 0h 0m 0s 915ms
Time for processing: 0h 3m 3s 800ms
align tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_0 tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_0 --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 3 -e 0.001 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 40 --compressed 0 -v 3 

Compute score, coverage and sequence identity
Query database size: 2548633 type: Aminoacid
Target database size: 13003941 type: Aminoacid
Calculation of alignments
[=================================================================] 2.55M 2s 531ms
Time for merging to aln_0: 0h 0m 0s 899ms

1405837 alignments calculated.
219658 sequence pairs passed the thresholds (0.156247 of overall calculated).
0.086187 hits per query sequence.
Time for processing: 0h 0m 5s 264ms
createsubdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/order_0 tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_0 -v 3 --subdb-mode 1 

Time for merging to input_0: 0h 0m 0s 273ms
Time for processing: 0h 0m 0s 816ms
prefilter tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_0 /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_1 --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 1 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 40 --compressed 0 -v 3 -s 3.5 

Query database size: 2328975 type: Aminoacid
Estimated memory consumption: 68G
Target database size: 13003941 type: Aminoacid
Index table k-mer threshold: 146 at k-mer size 7 
Index table: counting k-mers
[=================================================================] 13.00M 1m 31s 355ms
Index table: Masked residues: 71357266
Index table: fill
[=================================================================] 13.00M 1m 21s 643ms
Index statistics
Entries:          5077775275
DB size:          38820 MB
Avg k-mer size:   3.967012
Top 10 k-mers
    SGQQRIA	74997
    GPGGKLL	59639
    GQQVARA	45640
    GGQRVAR	38490
    GKTLRAG	27665
    LLGPGKT	25908
    ALGSGKS	22863
    GGRRVAR	21815
    GRFVVEV	21110
    AIGSGKS	20435
Time for index table init: 0h 3m 16s 755ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 146
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 2328975
Target db start 1 to 13003941
[=================================================================] 2.33M 2m 23s 577ms

183.593905 k-mers per position
20689 DB matches per sequence
0 overflows
0 sequences passed prefiltering per query sequence
1 median result list length
54469 sequences with 0 size result lists
Time for merging to pref_1: 0h 0m 0s 793ms
Time for processing: 0h 5m 46s 599ms
align tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_0 /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_1 tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_1 --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 3 -e 0.001 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 40 --compressed 0 -v 3 

Compute score, coverage and sequence identity
Query database size: 2328975 type: Aminoacid
Target database size: 13003941 type: Aminoacid
Calculation of alignments
[=================================================================] 2.33M 3s 448ms
Time for merging to aln_1: 0h 0m 0s 794ms

2274506 alignments calculated.
57971 sequence pairs passed the thresholds (0.025487 of overall calculated).
0.024891 hits per query sequence.
Time for processing: 0h 0m 6s 29ms
mergedbs tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge_new tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_0 tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_1 --compressed 0 -v 3 

Merging the results to tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge_new
Time for merging to aln_merge_new: 0h 0m 0s 301ms
Time for processing: 0h 0m 1s 706ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge -v 3 

Time for processing: 0h 0m 0s 0ms
mvdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge_new tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge -v 3 

Time for processing: 0h 0m 0s 0ms
createsubdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/order_1 tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_0 tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_1 -v 3 --subdb-mode 1 

Time for merging to input_1: 0h 0m 0s 267ms
Time for processing: 0h 0m 0s 790ms
prefilter tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_1 /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_2 --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 1 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 40 --compressed 0 -v 3 -s 6.0 

Query database size: 2271004 type: Aminoacid
Estimated memory consumption: 68G
Target database size: 13003941 type: Aminoacid
Index table k-mer threshold: 118 at k-mer size 7 
Index table: counting k-mers
[=================================================================] 13.00M 1m 31s 294ms
Index table: Masked residues: 71357266
Index table: fill
[=================================================================] 13.00M 1m 21s 848ms
Index statistics
Entries:          5094244039
DB size:          38915 MB
Avg k-mer size:   3.979878
Top 10 k-mers
    SGQQRIA	74997
    GPGGKLL	59639
    GQQVARA	45640
    GGQRVAR	38490
    GKTLRAG	27665
    LLGPGKT	25908
    ALGSGKS	22863
    GGRRVAR	21815
    GRFVVEV	21110
    AIGSGKS	20435
Time for index table init: 0h 3m 15s 901ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 118
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 2271004
Target db start 1 to 13003941
[=================================================================] 2.27M 43m 26s 530ms

3262.541404 k-mers per position
476704 DB matches per sequence
0 overflows
0 sequences passed prefiltering per query sequence
1 median result list length
18145 sequences with 0 size result lists
Time for merging to pref_2: 0h 0m 0s 779ms
Time for processing: 0h 46m 49s 482ms
align tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_1 /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_2 tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_2 --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 3 -e 0.001 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 40 --compressed 0 -v 3 

Compute score, coverage and sequence identity
Query database size: 2271004 type: Aminoacid
Target database size: 13003941 type: Aminoacid
Calculation of alignments
[=================================================================] 2.27M 3s 348ms
Time for merging to aln_2: 0h 0m 0s 785ms

2252859 alignments calculated.
16146 sequence pairs passed the thresholds (0.007167 of overall calculated).
0.007110 hits per query sequence.
Time for processing: 0h 0m 5s 939ms
mergedbs tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa tmp/9700814981231218113/search_tmp/10627605686170015473/aln tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_2 --compressed 0 -v 3 

Merging the results to tmp/9700814981231218113/search_tmp/10627605686170015473/aln
Time for merging to aln: 0h 0m 0s 302ms
Time for processing: 0h 0m 1s 611ms
Remove temporary files
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_0 -v 3 

Time for processing: 0h 0m 0s 19ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_0 -v 3 

Time for processing: 0h 0m 0s 12ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_0 -v 3 

Time for processing: 0h 0m 0s 7ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_1 -v 3 

Time for processing: 0h 0m 0s 15ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_1 -v 3 

Time for processing: 0h 0m 0s 7ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_1 -v 3 

Time for processing: 0h 0m 0s 11ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/pref_2 -v 3 

Time for processing: 0h 0m 0s 24ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_2 -v 3 

Time for processing: 0h 0m 0s 11ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/input_2 -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/search/aln_merge -v 3 

Time for processing: 0h 0m 0s 11ms
offsetalignment tmp/9700814981231218113/query tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa /d/Databases/Kegg/sram/mmseqs/kegg /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/search_tmp/10627605686170015473/aln tmp/9700814981231218113/result --chain-alignments 0 --merge-query 1 --search-type 0 --threads 40 --compressed 0 --db-load-mode 0 -v 3 

Computing ORF lookup
Computing contig offsets
Computing contig lookup
Time for contig lookup: 0h 0m 0s 93ms
Writing results to: tmp/9700814981231218113/result
[=================================================================] 516.30K 0s 162ms

Time for merging to result: 0h 0m 0s 158ms
Time for processing: 0h 0m 1s 659ms
Remove temporary files
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/q_orfs_aa 

Time for processing: 0h 0m 0s 45ms
rmdb tmp/9700814981231218113/search_tmp/10627605686170015473/t_orfs_aa 

Time for processing: 0h 0m 0s 0ms
convertalis tmp/9700814981231218113/query /d/Databases/Kegg/sram/mmseqs/kegg tmp/9700814981231218113/result test.m8 --sub-mat nucl:nucleotide.out,aa:blosum62.out --format-mode 0 --format-output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits --translation-table 1 --gap-open 11 --gap-extend 1 --db-output 0 --db-load-mode 0 --search-type 0 --threads 40 --compressed 0 -v 3 

[=================================================================] 516.30K 0s 84ms
Time for merging to test.m8: 0h 0m 0s 181ms
Time for processing: 0h 0m 2s 227ms
Removing temporary files
rmdb tmp/9700814981231218113/result 

Time for processing: 0h 0m 0s 8ms
rmdb tmp/9700814981231218113/query 

Time for processing: 0h 0m 0s 38ms
rmdb tmp/9700814981231218113/query_h 

Time for processing: 0h 0m 0s 3ms

**Comment by zsram** [comment]
@martin-steinegger

**Comment by martin-steinegger** [comment]
Thank you for the log. 

If you use `--start-sens 1 --sens-steps 3 -s 6` then MMseqs2 performs three searches with the sensitivity `-s 1`, `-s 3.5` and `-s 6` while in each step previously successful aligned sequences are left out. From your log I can see that the most sensitive search `-s 6` took `46m 49s 482ms` while not resulting in a much deeper annotation. Only 16146 extra ORFs sequences got annotated while the searches with `-s 1` and `-s 3.5` annotated already 277629. Searching with `-s 6` is also more sensitive compare to DIAMOND (see https://github.com/soedinglab/MMseqs2/wiki#set-sensitivity--s-parameter). The respective sensitivity should be DIAMONDS `--more-sensitive`. 

My recommendation would be to search the following way:

time mmseqs easy-search MOMZ_moomz1_200m.fna /d/Databases/Kegg/sram/mmseqs/ke
gg mmseqs_results2.m8 tmp -s 3.5 --max-accept 1 --max-rejected 5 

This should roughly take 6-7 minutes.

**Comment by zsram** [comment]
@martin-steinegger Thank you very much. You are absolutely right, it took now 7 minutes as you correctly predicted.

**Comment by jolespin** [comment]
Is `--max-accept 1` equivalent to `--max-target-seqs 1` in Diamond?
