### ISSUE TITLE
metaclust include hhblits compatible format of metaclust50/95

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#24]
metaclust50 and metaclust95 was clustered by mmseqs2. It is only available as gzip fasta. I was wondering if it is possible to get hhsuite compatible format of metaclust so that I can use hhblits to search my query against it.

**Comment by martin-steinegger** [comment]
Thanks for your request. We will discuss the next days. Its a huge computational effort to create a HHblits database of such big databases.

**Comment by martin-steinegger** [comment]
We decided to not further pursue this project due to the extreme demand on computational resources.

**Comment by martin-steinegger** [comment]
We did something similar now. Its called BFD https://bfd.mmseqs.com/ 
BFD was created by clustering 2.5 billion protein sequences from Uniprot/Tremble +Swissprot, Metaclust and Soil Reference Catalog Marine Eukaryotic Reference Catalog assembled by plass https://plass.mmseqs.com.

**Comment by milot-mirdita** [comment]
Here you are (that took quite a while):
```
$ md5deep bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz
6a634dc6eb105c2e9b4cba7bbae93412  bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz
```

**Comment by kad-ecoli** [comment]
hhblits3 on bfd takes 25GB of physical memory. Is there a way to restrain hhblits3 memory consumption? Thank you.
