### ISSUE TITLE
The user guide and the cli disagree on the range of the sensitivity parameter

### ISSUE THREAD

**Issue by konstin** [soedinglab/MMseqs2#240]
The user guide and the cli help say different things about the `-s` parameter.

The user guide says the following, both in the pdf bundled with the latest release and in the latest wiki version (https://github.com/soedinglab/mmseqs2/wiki#search-workflow)

> ```
> -s [float] Target sensitivity in the range [1:8.5] (default=4).
> ```
> Adjusts the sensitivity of the prefiltering and influences the prefiltering run time. 1.0 fastest -
8.5 sensitive. The sensitivity between 8 to 8.5 should be as sensitive as BLAST. For detailed
explanation see section Computation of Prefiltering Scores using mmseqs prefilter.

The cli help (`mmseqs search --help`) says:

> ```
> -s FLOAT                     sensitivity: 1.0 faster; 4.0 fast default; 7.5 sensitive (range 1.0-7.5) [5.700]
> ``` 

As defined here:

https://github.com/soedinglab/MMseqs2/blob/5ae5503a923ec4338464d09cc1ff4bc3680727da/src/commons/Parameters.cpp#L30

I'm wondering about this since I'd like to search at a sensitivity similar to BLAST and since the cli doesn't reject values bigger than 7.5.

MMseqs2 Version: 6d92cd21676ccc36531f2852f7eb747f6389435f (Release 10-6d92c)

**Comment by martin-steinegger** [comment]
Thank you for pointing this out. Yes the parameter description is inconsistent. We will fix this. 

I hope this plot helps to find the right `-s` setting for your use case. https://github.com/soedinglab/mmseqs2/wiki#set-sensitivity--s-parameter

**Comment by martin-steinegger** [comment]
We changed the description. Thank you.

**Comment by zhaoxvwahaha** [comment]
@martin-steinegger 
Hi， 
I download the newest version of mmseqs2, the biggest value is 7.5 from software help information:
-s FLOAT                         Sensitivity: 1.0 faster; 4.0 fast; 7.5 sensitive [5.700]
but on the description from wiki is 8.5, so which one is correct?

And, I would like get same sensitive as PSI-BLAST, if the following parameter is OK:
mmseqs search -a -s 7 --num-iterations 2

**Comment by martin-steinegger** [comment]
`mmseqs search --num-iterations 2` should be already more sensitive than PSI-BLAST. `-s 7` helps mainly in the first iteration to build the initial profiles. 8.5 is incorrect. You can increase `-s` to 10 but there is no boost in sensitivity anymore.
