### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by ARastrojo** [soedinglab/MMseqs2#241]
Hi all, 

I am trying to use mmseqs taxonomy to obtain the putative linage of some proteins from a metagenomic project. The problem I am suffering is that I have some strange results. For intance the LCA is telling me that a certain protein probaly belong to Arabidopsis genera, but no hits were found when using mmseqs search over the same database. How can be that possible? any clue? Here is the code I am using to build the database and both searches:

##################################
#!/bin/bash

#--Download Uniprot DB
wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
wget ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.fasta.gz

tar -xzf uniprot_sprot.fasta.gz
tar -xzf uniprot_trembl.fasta.gz

cat uniprot_sprot.fasta uniprot_trembl > uniprot.fasta

#--Create DB + taxonomy
mmseqs createdb uniprot.fasta uniprotDB
mmseqs createtaxdb uniprotDB tmp

#######################
Taxonomy search

mmseqs taxonomy queryDB uniprotDB taxoDB tmp -s 6
mmseqs createtsv queryDB taxoDB query.lca

Standard seach

mmseqs search queryDB uniprotDB searchDB tmp -s 6
mmseqs convertalis queryDB taxoDB searchDB query.mmseqs

**Comment by martin-steinegger** [comment]
Taxonomy has a different acceptance criteria. E.g. thr e-value threshold is much higher.

**Comment by ARastrojo** [comment]
Thanks for your answer. But I have another interesting issue. I have other contig that using mmseqs search matches to several viral proteins of the same order (i.e. Picornavirales in this case). However, using mmseqs taxonomy, with same parameters as above and the same database used with mmseq search, the LCA result is "Proteobacteria"!!!. By using mmseqs search I have obtanied 1087 hits, 1058 against Picornavirales, including 2 hits with evalue 0 and lots with evalue <1e-100, and 28 hits against eukaryotic organisms, mainly arthropods, that could be the hosts for these sort of viruses. Therefore, I would expect a viral LCA result, and, despite the differences in acceptance criteria, with these results and wonder if the incomplete taxonomy of the viruses could be a problem for the LCA algorithm. I mean, as you known, the taxonomy ranks in viral taxonomy are very poor and most of then are absent. What do you think? Am I missing something?

**Comment by ARastrojo** [comment]
Looking to another search of this contigs using NCBI NR database I have found 1 hit against a Proteobacteria (evalue e-33) among 1088 hits against Picornaviales (evalues from 0, 50 of more hits with evalue < e-100, and so on). Is it possible that viral sequences were not considered in LCA algorithm for any reason?

**Comment by martin-steinegger** [comment]
Could you please add the log of this search?

One thing that might happen is that your database has no taxonomical information for this sequences. Could you check if the identifier of this viruses has a mapping in the `_mapping` file?

**Comment by ARastrojo** [comment]
I have solve the problem, there must be a problem in the database while creating it, because after rebuilding the database the LCA is in consonance with search results. 
Thanks for your help, and sorry for the inconvenience.

**Comment by martin-steinegger** [comment]
@ARastrojo thank you for letting us know! 

We are still doing the free sticker thing (see https://twitter.com/thesteinegger/status/1201076220957315074). If you want a set send me your address at themartinsteinegger at gmail dot com.
