### ISSUE TITLE
Get a summary table informations (cov,id,evalue etc) with cluster.  

### ISSUE THREAD

**Issue by Benjamin-Guinet** [soedinglab/MMseqs2#243]
Hello, I'm using the mmseqs cluster in order to create protein clusters between protein sequences. 

Then from the tsv file I created a tabular bfile such as: 

```
Cluster1 Seq1
Cluster1 Seq2
Cluster2 Seq3
Cluster2 Seq4
Cluster2 Seq5
```

Where `Seq1` and `Seq2` are both in the same `Cluster1` and `Seq3,4` and `Seq5` are in the `Cluster2. `

and now for my project I would need to produce another tabular format with informations such as `coverage`, `identity`, `evalue` and get for instance a file such as :

```
Cluster Name1 Name2 Coverage Identity Evalue
1 Seq1 seq2 0.45 0.76 0.003
2 Seq3 Seq4 0.67 0.56 0.009
3 Seq3 Seq5 0.54 0.32 0.0007
```
and mayb with other columns such as in mmseqs search tab.m8 such as `qstart, qend, sstart, send` etc ? 

I do not know if you already have such parameters or if I  have to simultaneously do a search analysis for homology and then merge the two arrays?

Thank for you help.

**Comment by Grindell** [comment]
Well I spoke too quickly. 
I used 
```
mmseqs cluster sequenceDB resultDb tmp
mmseqs align sequenceDB sequenceDB resultDb alignDB -a
mmseqs convertalis sequenceDB sequenceDB alignDB align.m8 
```

and it worked like a charm
.

**Comment by Benjamin-Guinet** [comment]
Well I spoke too quickly.
I used

```
mmseqs cluster sequenceDB resultDb tmp
mmseqs align sequenceDB sequenceDB resultDb alignDB -a
mmseqs convertalis sequenceDB sequenceDB alignDB align.m8 
```
and it worked like a charm

**Comment by martin-steinegger** [comment]
Thank you for posting the solution. Other user will find it useful!
