### ISSUE TITLE
Manual creation of taxonomy db without NCBI index

### ISSUE THREAD

**Issue by adriaaula** [soedinglab/MMseqs2#244]
Hello there, 

I want to create a taxonomy db from the GTDB release 89. 

I have found that Annotree presents a file with all the predicted gene sequences here:
[https://data.ace.uq.edu.au/public/misc_downloads/annotree/r89/](https://data.ace.uq.edu.au/public/misc_downloads/annotree/r89/)

From this I could obtain a db easily and generate  a tab-separating mapping file explicitly pointing to a genome: 

```
NZ_FWXU01000077.1_1 RS_GCF_900176345.1
NZ_FWXU01000059.1_5 RS_GCF_900176345.1
NZ_FWXU01000047.1_9 RS_GCF_900176345.1
NZ_FWXU01000020.1_25 RS_GCF_900176345.1
NZ_FWXU01000020.1_57 RS_GCF_900176345.1
NZ_FWXU01000020.1_89 RS_GCF_900176345.1
NZ_FWXU01000018.1_9 RS_GCF_900176345.1
NZ_FWXU01000018.1_41 RS_GCF_900176345.1
NZ_FWXU01000018.1_73 RS_GCF_900176345.1
NZ_FWXU01000018.1_105 RS_GCF_900176345.1
```
There is also a taxonomy file [here](https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/) in which for each genome there is the taxonomic information in the following structure: 

```
RS_GCF_900234795.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Beijerinckiaceae;g__Methylobacterium;s__Methylobacterium extorquens
RS_GCF_000012905.2	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhodobacterales;f__Rhodobacteraceae;g__Rhodobacter_A;s__Rhodobacter_A sphaeroides
GB_GCA_003096615.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Beijerinckiaceae;g__Methylobacterium;s__Methylobacterium organophilum
GB_GCA_002709955.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__UBA8366;f__GCA-2696645;g__GCA-2696645;s__GCA-2696645 sp002709955
RS_GCF_001556125.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Beijerinckiaceae;g__Bosea;s__Bosea sp001556125
RS_GCF_001555965.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Sphingomonadales;f__Sphingomonadaceae;g__Sphingomonas;s__Sphingomonas sp001555965
RS_GCF_900101505.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhodobacterales;f__Rhodobacteraceae;g__Mameliella;s__Mameliella alba
RS_GCF_001598375.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Sphingomonadales;f__Sphingomonadaceae;g__Novosphingobium;s__Novosphingobium capsulatum
GB_GCA_001280155.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhizobiales;f__Beijerinckiaceae;g__Methylobacterium;s__Methylobacterium purpurogeneiscleroticus
RS_GCF_001642945.1	d__Bacteria;p__Proteobacteria;c__Alphaproteobacteria;o__Rhodobacterales;f__Rhodobacteraceae;g__HIMB11;s__HIMB11 sp001642945
```

Is there a way to generate a DB without the NCBI structure? Or how would you approach this problem? Maybe I am not seeing other information I could need to do that. 

Thanks in advance!

**Comment by martin-steinegger** [comment]
In the user guide there is an example how to turn a SILVA taxonomy into a mmseqs taxonomy database. I think you can use a similar approach for this. Check out "Create a sequence database with taxonomic information for SILVA" in the wiki https://github.com/soedinglab/MMseqs2/wiki#taxonomy-assignment-using-mmseqs-taxonomy

**Comment by adriaaula** [comment]
Perfect Martin! 

@genomewalker also showed me this [github](https://github.com/rrwick/Metagenomics-Index-Correction) and this [preprint](https://www.biorxiv.org/content/biorxiv/early/2019/07/23/712166.full.pdf) about it. 

Thanks a lot!
