### ISSUE TITLE
result2flat do not convert MSA files to flat-fasta format

### ISSUE THREAD

**Issue by valflanza** [soedinglab/MMseqs2#246]
Hello.

We want to crete a fasta file with all MSA of each cluster.

I previous version wa can do it with.

linclust -> result2msa -> result2flat

And it worked perfectly. In new versions result2flat does not admit MSA files as input.

Any other way to do it??

**Comment by milot-mirdita** [comment]
`linclust -> result2msa -> result2flat` should never have worked. Which version was this?

You have use the `linclust` output for both `result2flat` and `result2msa`:
```
linclust -> result2msa
             -> result2flat
```

**Comment by valflanza** [comment]
I was using `MMseqs2 Release 6-f5a1c` version and I can executed result2flat over MSA file.

Anyway, Is there any way to convert the result2msa output to a flat-file (fasta or similar)

**Comment by simone-pignotti** [comment]
Interested in this issue as well.
For now the only way I could find to obtain a MSA in a standard format is `cluster -> createseqfiledb -> result2flat -> [split] -> [external MSA program]`, where `split` is a script splitting each cluster to a separate file. Without `createseqfiledb` the results will only contain the sequences' numeric IDs.

**Comment by valflanza** [comment]
> Interested in this issue as well.
> For now the only way I could find to obtain a MSA in a standard format is `cluster -> createseqfiledb -> result2flat -> [split] -> [external MSA program]`, where `split` is a script splitting each cluster to a separate file. Without `createseqfiledb` the results will only contain the sequences' numeric IDs.

There is a easier way using `apply` function. (There is an example in the manual).

**Comment by martin-steinegger** [comment]
Something like this should work 

      mmseqs createseqfiledb seqDB resultDB resultWithSeqDB -- clustalo -i stdin -o stdout
      mmseqs apply resultWithSeqDB msaDB -- clustalo -i stdin -o stdout

**Comment by simone-pignotti** [comment]
Thank you both! I was testing on a small dataset, with few singleton clusters, and applying clustalo resulted in an error for such clusters (can't align 1 seq). The problem is that this stops the entire workflow, and no output was produced. Also, can the apply command split the output by cluster?

**Comment by valflanza** [comment]
The point is that `result2msa` create an MSA per each cluster, and even  the MSA is in binary format you can visualize the result with a simple `less` but you can't use for other pourpouse. Is there any way, may be using `applay`, to export this binary-MSA output to flat-text? Because I can see the result and It's exactly that I want.

**Comment by valflanza** [comment]
> The point is that `result2msa` create an MSA per each cluster, and even the MSA is in binary format you can visualize the result with a simple `less` but you can't use for other pourpouse. Is there any way, may be using `apply`, to export this binary-MSA output to flat-text? Because I can see the result and It's exactly that I want.

I've found a solution. We can use linux `strings` function  to convert the binary-MSA to flat-text.

**Comment by martin-steinegger** [comment]
We can develop a module that can convert database into single files but I think millions of single files are hard to handle for a file system. 
Quick fix:
Currently the entires are separated by a null byte. So you could split the file into separate files based on the null byte.

**Comment by milot-mirdita** [comment]
if you only want to get rid of the null bytes separating entries you should use `tr`:
```
tr -d '\000' < input_db > output.flat
```
