### ISSUE TITLE
Can I filter Cluster result?

### ISSUE THREAD

**Issue by valflanza** [soedinglab/MMseqs2#247]
May I fliter a cluster result to obtain a sub-set of clusters?. I have a list of clusters (the representative sequence) and I want to get only this clusters.

How can I do it?

**Comment by martin-steinegger** [comment]
The answer is differs based on the way how you performed the clustering. Could you please provide the commands?

**Comment by valflanza** [comment]
These are my commands

```mmseqs createdb all.fasta all.mmseq
mmseqs linclust all.mmseq all.cluster tmpDir --threads 20 -e 1e-6  --min-seq-id 0.8 --coverage 0.8
mmseqs createtsv all.mmseq all.mmseq all.cluster all.cluster.tsv
mmseqs result2repseq all.mmseq all.cluster all.representatives
mmseqs result2flat all.mmseq all.mmseq all.representatives all.representatives.fasta --use-fasta-header```

I select set of clusters using `all.cluster.tsv` and the point is to recover only the clusters that i want.

**Comment by martin-steinegger** [comment]
The  `createdb` call produces a `.lookup` file. It contains a mapping from the internal numerical mmseqs id to a fasta identfier. So you could filter the lookup file for your desired entries like this: 

     awk 'FNR==NR{f[$1]=1; next} $2 in f{print $1}' desiredIds all.mmseq.lookup > ids
     mmseqs createsubdb ids all.cluster all.cluster.subset

**Comment by valflanza** [comment]
Perfect!!

Thank you very much for your help.
