### ISSUE TITLE
Convertalis taxid in format-output

### ISSUE THREAD

**Issue by Guillaume-Marseille** [soedinglab/MMseqs2#248]
Hello

I would like to obtain the taxids for each hit sequence in the alignment results file. 

According to the [wiki](https://github.com/soedinglab/MMseqs2/wiki#custom-alignment-format-with-convertalis), it seems that this is possible with convertalis by using the "taxid" tag in the format description given with the flag "format-output". However, although I use the latest version of mmseqs (10.6d92c), the program returns an error: "Format code taxid does not exist."

Am I doing something wrong ?

`convertalis ALL.PEP.mms nr.mmdb ALL.PEP_VS_nr.mmseqsout.tax ALL.PEP_VS_nr.mms.m8 --format-output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,empty,qlen,tlen,taxid,theader 

MMseqs Version:         10.6d92c
Substitution matrix     nucl:nucleotide.out,aa:blosum62.out
Alignment format        0
Format alignment output query,target,pident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,empty,qlen,tlen,taxid,theader
Translation table       1
Gap open cost           11
Gap extension cost      1
Database output         false
Preload mode            0
Search type             0
Threads                 128
Compressed              0
Verbosity               3

Format code taxid does not exist.`

I have prepared my target database using the following series of steps: createdb, createdbindex and createtaxdb.

After the search step, I added taxonomic information to the results database with the command addtaxonomy

Thank you for your help
Guillaume

**Comment by milot-mirdita** [comment]
The `taxid` field support was added only a few weeks ago and is only available through the latest git version. It will be included in the next release.

**Comment by Guillaume-Marseille** [comment]
Thanks for your response
that's good news
I'm really looking forward this next release!
But if I want to use the taxid field right away I can still download the code from git and compile it, correct?
Guillaume

**Comment by Guillaume-Marseille** [comment]
The response is yes ;-)
I've just did it.
Bonne journée

**Comment by milot-mirdita** [comment]
Exactly, you can also use the precompiled binaries at https://mmseqs.com/latest/

I've also added links to the corresponding user guide commits for older releases:
https://github.com/soedinglab/MMseqs2/wiki
