### ISSUE TITLE
Diamond --top option for filterdb

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#249]
Hi 
I am trying to emulate the behavior of `--top` from diamond:
```
--top   report alignments within this percentage range of top alignment score (overrides --max-target-seqs)
```
At the moment I am using `apply` with `awk` but I wonder if you have a recommendation on how to achieve it with `filterdb`

Thanks
Antonio

**Comment by milot-mirdita** [comment]
Seems like a useful option, I'll try to implement that tomorrow into `filterdb`.

As a sidenote:
https://twitter.com/thesteinegger/status/1201076220957315074
If you want a set of stickers, send me an email with your address.

**Comment by genomewalker** [comment]
Great! Thank you very much Milot!

**Comment by milot-mirdita** [comment]
Okay this turned into quite the refactoring adventure. I am still not happy with the naming of the parameters, so they might change until release 11.

But you can now do the following:
```
mmseqs filterdb aln_result aln_filtered --beats-first --filter-column 2 --comparison-operator ip --comparison-value 0.8
```
This means it keeps everything that it within 0.8 * alnScore of the first row.

**Comment by martin-steinegger** [comment]
@milot-mirdita can we close this issue?

**Comment by genomewalker** [comment]
Hey!
I missed this one. Thank you very much! This helps a lot!
