### ISSUE TITLE
Running tests?

### ISSUE THREAD

**Issue by wwood** [soedinglab/MMseqs2#25]
Hi there,

I see that there are tests in `src/tests`, but there is no `make test` target or mention of tests in the README. Is there a recommended way of running the tests?

Thanks, ben.

**Comment by martin-steinegger** [comment]
The tests will be compiled after calling the cmake && make. They do not behave like unit tests. 
We use them to debug certain parts of our code. How do you want to use them?

**Comment by martin-steinegger** [comment]
It is possible to benchmark out software with our regression benchmark. It can be downloaded here https://bitbucket.org/martin_steinegger/mmseqs-benchmark

**Comment by wwood** [comment]
Thanks for the quick reply. I was attempting to write an mmseqs package definition for GNU Guix, where the idea is to run tests for the same reasons that the usual `make check` is run, to tests that the software works in the particular environment it is being run in.

**Comment by milot-mirdita** [comment]
We integrated the MMseqs2 regression test into the git repository. See:
https://github.com/soedinglab/MMseqs2/wiki/MMseqs2-Developer-Guide#regression-test
