### ISSUE TITLE
a typo on the rolling hash function

### ISSUE THREAD

**Issue by leomrtns** [soedinglab/MMseqs2#252]
I think I've found a typo on the rolling hash function of linclust, at line
https://github.com/soedinglab/MMseqs2/blob/11e2736028cc12a6523b507b061158903f8de317/src/linclust/kmermatcher.cpp#L55
I guess it should be
```
h ^= RoL(RAND[x_first], (rol*(length-1)) % 16);
```
with rol instead of the fixed 5 ? Probably you define rol=5 somewhere so in practice no harm is done. (In the Supplementary Material of the paper it's `5` but I noticed that now is more general...)

**Comment by martin-steinegger** [comment]
Yes, this should be indeed `rol` instead of 5. But as you noted, we set `rol` to 5 in default. Therefore it should not have an effect for linclust at the moment. But we will fix this, especially since Plass changes the rol parameter.

**Comment by martin-steinegger** [comment]
It is fixed :) 

We are still doing the free sticker thing (see https://twitter.com/thesteinegger/status/1201076220957315074). If you want a set send me your address at themartinsteinegger at gmail dot com.
