### ISSUE TITLE
LCA taxonomy raises an unclear error 

### ISSUE THREAD

**Issue by adriaaula** [soedinglab/MMseqs2#256]
## Expected Behavior

The generation of LCA taxonomy through the following command. 

```sh
mmseqs taxonomy --threads 36 --search-type 3 \
      --lca-ranks species:genus:family:order:class:phylum:superkingdom \
        data/annotation/putative_genes/nuc_mmseq_DB \
        ${dbdir}/gtdb_54kDB data/04_taxgenes/taxresdb ${dbdir}/tmp/
```

The taxonomy DB is made through the last release of GTDB without applying a cluster, as discussed in #244 . 

The db is as follows: 

```
-rw-r--r-- 1 aauladell bio  54G 28 nov 11:05 gtdb_54kDB
-rw-r--r-- 1 aauladell bio    4 28 nov 11:07 gtdb_54kDB.dbtype
-rw-r--r-- 1 aauladell bio    0 28 nov 15:43 gtdb_54kDB_delnodes.dmp
-rw-r--r-- 1 aauladell bio 3,0G 28 nov 11:00 gtdb_54kDB_h
-rw-r--r-- 1 aauladell bio    4 28 nov 11:01 gtdb_54kDB_h.dbtype
-rw-r--r-- 1 aauladell bio 3,9G 28 nov 11:09 gtdb_54kDB_h.index
-rw-r--r-- 1 aauladell bio 4,3G 28 nov 11:08 gtdb_54kDB.index
-rw-r--r-- 1 aauladell bio 4,6G 28 nov 11:14 gtdb_54kDB.lookup
-rw-r--r-- 1 aauladell bio 2,7G 28 nov 15:43 gtdb_54kDB_mapping
-rw-r--r-- 1 aauladell bio    0 28 nov 15:43 gtdb_54kDB_merged.dmp
-rw----r-- 1 aauladell bio 1,8M 28 nov 15:43 gtdb_54kDB_names.dmp
-rw----r-- 1 aauladell bio 3,0M 28 nov 15:43 gtdb_54kDB_nodes.dmp
```

## Current Behavior

Instead, it raises an `out_of_range` error with a `terminate called recursively` after running for 20 hours. 

## MMseqs Output (for bugs)

Raises the following error: 
```
terminate called recursively
terminate called after throwing an instance of 'std::out_of_range/mnt/lustre/scratch/aauladell/databases/gtdb-r89_54k/tmp//14536420861195881021/taxonomy.sh: line 99: 34258 Aborted                 "$MMSEQS" lca "${TARGET}" "${LCA_SOURCE}" "${RESULTS}" ${LCA_PAR}
```

The output log: 
[mmseqs_lca_log.txt](https://github.com/soedinglab/MMseqs2/files/3955181/mmseqs_lca_log.txt)

## Context
Taxonomic classification of a gene catalog with around 500000 seqs. 
 
## Your Environment

MMseqs2 Version: 0a1348be78bd84137bdb373ba32e0e8c054b3e1c
Which MMseqs version was used: statically compiled (Statically-compiled, self-compiled, Homebrew, etc.): statically compiled
Server specifications (especially CPU support for AVX2/SSE and amount of system memory):AVX2 supported, 36 threads and 400 Gb RAM.

**Comment by martin-steinegger** [comment]
Where you able to classify just a single sequence against our gtdb database? Maybe the internal structure of names, nodes and mapping has some error. If you could provide a small subset than I could try to figure out what goes wrong.

**Comment by adriaaula** [comment]
No. 

I took a 100 of my query sequences and it jumped to the error pretty quick. 
```
terminate called after throwing an instance of 'std::out_of_range'
terminate called recursively
terminate called recursively
```

So maybe it's something related with the internal structure of the names, yup. Any idea about what I should try to find? 

With the subset you mean of the GTDB taxonomic database? Bc I guess that the problem is on this side. Which would be the best way of sending it? 

( I would love some stickers! Sending the mail right away :)

**Comment by martin-steinegger** [comment]
Could you send me your _nodes.dmp, _mapping, _names.dmp? Then I could create a fake database and check if I can reproduce the error.

**Comment by adriaaula** [comment]
You can find it here:

https://www.dropbox.com/s/5wqgsa8ndjzw2fv/the_dmps.zip?dl=0

Many thanks for this Martin.

**Comment by martin-steinegger** [comment]
Thank you! 
I could not find any error in the `_mapping`, `_nodes.dmp` and `_names.dmp` files. So I assume the database is fine. I have build a small test case but I was not able to reproduce the error. Could you try to search against the database ([gtdbSmallDb.zip](https://github.com/soedinglab/MMseqs2/files/4018390/gtdbSmallDb.zip)) and see if the error occurs?

      mmseqs taxonomy gtdb_54kDB gtdb_54kDB /tmp/tax /tmp/tmp 

It would be amazing if you could share your script to build the gtdb.

**Comment by adriaaula** [comment]
With the database you sent, by sampling 100 sequences at random from my gene catalog i cannot obtain the taxonomy. 

If I do `mmseqs taxonomy gtdb_54kDB gtdb_54kDB /tmp/tax /tmp/tmp ` it doesn't throw an error at all. 

But if I take this  [subsetDB.zip](https://github.com/soedinglab/MMseqs2/files/4019604/subsetDB.zip) of my query FASTA and run a taxonomic analysis with:

```
mmseqs taxonomy --search-type 1 --threads 2 \
       --lca-ranks species:genus:family:order:class:phylum:superkingdom \
        subsetDB \
        gtdb_54kDB taxresdb /tmp/
```

I get a `terminate called recursively` error. 

Can you run it properly? Sorry for the waste of time. 

For the DB building I did the typical act of not saving properly the steps. I try to replicate it tomorrow and I send it right away. But basically I had obtained the names.dmp and nodes.dmp and from the main fasta having all the predicted coding sequences with the names as `>{orf}_{genomeid}` I generated the mapping file.

**Comment by genomewalker** [comment]
@adriaaula If you used the file I shared, the predicted ORFs have been dereplicated using MMseqs2 by tax_id, @martin-steinegger I will post the workflow we use when I am back from vacation.

**Comment by martin-steinegger** [comment]
@adriaaula Would it be possible to send me the `top1` input (including `.[0-9]`, `.index` `.dbtype`) of the LCA module? So that I do not need to download the full sequences of gtdb. You can find it by looking at the input parameter for the LCA call. The call should look similar to this:

      lca gtdb_54kDB tmp/3061363735539572485/top1 taxresdb --compressed 0 --blacklist 12908,28384 --tax-lineage 0 --threads 12 -v 3


@genomewalker thank you a lot! I would add it to the user guide. I am sure many user would profit from it

**Comment by adriaaula** [comment]
Here you have it 
[top_results.zip](https://github.com/soedinglab/MMseqs2/files/4027399/top_results.zip)

**Comment by martin-steinegger** [comment]
Thank you for sharing your example. However I can also not reproduce the error. In your example there is only one alignment to a sequence, which `lca` classifies as `30551	species	Staphylococcus pseudintermedius`. I am running out of ideas how to help.

```
lca gtdb_54kDB top1 /Users/mad/Downloads/top_results/lca

MMseqs Version:   	0a1348be78bd84137bdb373ba32e0e8c054b3e1c
Compressed        	0
LCA ranks
Blacklisted taxa  	12908,28384
Show taxon lineage	false
Threads           	12
Verbosity         	3

Loading NCBI taxonomy
Loading nodes file ... Done, got 36283 nodes
Loading merged file ... Done, added 0 merged nodes.
Loading names file ... Done
Making matrix ... Done
Init RMQ ...Done
Computing LCA
[=================================================================] 100.00% 100 0s 2ms

Taxonomy for 0 entries not found out of 1
Time for merging to lca: 0h 0m 0s 1ms
Time for processing: 0h 0m 17s 334ms
```

**Comment by martin-steinegger** [comment]
Okay we found the issue. The problem occurs because of  : in the --lca-ranks parameter. The seperator should be ;. The description is wrong in our mmseqs help text. So it should be `--lca-ranks "species;genus;family;order;class;phylum;superkingdom"`. 

Thank you so much for your help to find it. But we have just noticed that ';' make some issues as parameter. If you would write `--lca-ranks species;genus;family;order;class;phylum;superkingdom` than bash will only interpret until `--lca-ranks species`. Luckily this change was not yet part of any release. So we will change it to `,` and add a proper validation of the input parameter. 

Also I did not receive a mail for the stickers. My mail add is themartinsteinegger gmail com 🙂

**Comment by adriaaula** [comment]
Yuuhuuuu! 

I was becoming paranoid with my sequences at the end hahaha
Now it works like a charm, thank you for your efforts. 

I will send the mail for the stickers right away.

**Comment by martin-steinegger** [comment]
@genomewalker did you have time to search for the script? :)

**Comment by colinbrislawn** [comment]
I'm also getting this error. What's the current workaround? 

```bash
Reading LCA results
[=================================================================] 100.00% 3.34M 0s 428ms      

Found 34 different taxa for 3340500 different reads.
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
/tmp/6531700399628113911/easy-taxonomy.sh: line 39: 138605 Aborted                 (core dumped) "$MMSEQS" taxonomyreport "${TARGET}" "${TMP_PATH}/result_lca" "${RESULTS}_report" ${THREADS_PAR}
Error: taxonomyreport died
```

**Comment by martin-steinegger** [comment]
@colinbrislawn how do you call the workflow? What is your MMseqs2 version?

**Comment by colinbrislawn** [comment]
```bash
easy-taxonomy results/BG.fastq /home/cbrislawn/dbs/indexes/library results/mmseq2-BG /tmp \
--search-type 3 -s 2 --mask 0 --max-seqs 100 --max-accept 100 --max-rejected 100 

MMseqs Version:                       	10.6d92c
```

`BG.fastq` is simulated data from a single microbe. `library` is based on RefSeq

Thanks for helping me figure this out!

**Comment by martin-steinegger** [comment]
@colinbrislawn this looks like a different issue. Could you please try the newest version of MMseqs2? It might be fixed by now.

**Comment by colinbrislawn** [comment]
I did run this with the newest release. Did you want to install the newest version on the master branch?

**Comment by martin-steinegger** [comment]
Yes, please test the most recent version on the master branch. We fixed a LCA bug. 

We will release version 11 of mmseqs2 by the end of the week.
