### ISSUE TITLE
Segfault when searching transcribed nucleotides against profiles

### ISSUE THREAD

**Issue by galicae** [soedinglab/MMseqs2#259]
## Expected Behavior
Search a query database of translated nucleotides against the PFAM profile database.

## Current Behavior
Segfault when reaching the `search` step (after `extractorfs`)

## Steps to Reproduce (for bugs)
```
module load MMseqs2/10-6d92c-foss-2018b
cd /Pfam/directory/

mmseqs convertmsa Pfam-A.full.gz pfam_msa_db
mmseqs msa2profile pfam_msa_db pfam_profile --match-mode 1
mmseqs createindex pfam_profile tmp -k 6 -s 7

PFAM="location/of/pfam_profile"
K1M="location/of/input/fasta"
ORFS="where/to/save/orfs"
RES="location/of/final/result"

cd 
mmseqs createdb ${K1M} ${ORFS}
mmseqs search ${ORFS} ${PFAM} ${RES} tmp -k 5 -s 7

module unload MMseqs2/10-6d92c-foss-2018b
```

## MMseqs Output (for bugs)
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7f6b77d84270)
==== backtrace (tid:   1754) ====
 0 0x0000000000142e40 __memcpy_ssse3()  :0
 1 0x00000000004d8b86 PrefilteringIndexReader::getIndexTable()  ???:0
 2 0x00000000004cc0c6 Prefiltering::runSplit()  ???:0
 3 0x00000000004cc90d Prefiltering::runSplits()  ???:0
 4 0x00000000004cd10d Prefiltering::runMpiSplits()  ???:0
 5 0x00000000004c2974 prefilter()  ???:0
 6 0x000000000044a7d6 runCommand()  ???:0
 7 0x0000000000442d29 main()  ???:0
 8 0x0000000000021c05 __libc_start_main()  ???:0
 9 0x000000000044a46c _start()  ???:0
=================================
tmp/14557808422999051349/searchtargetprofile.sh: line 28:  1754 Segmentation fault      $RUNNER "$MMSEQS" prefilter "${INPUT}" "${2}" "${TMP_PATH}/
```

## Context
I want to find candidate transcription factors in a non-model organism. By aligning translated bulk RNA-seq reads against Pfam, I hope to get matches against known transcription factor families or DNA binding domains.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used: release 10-6d92c-foss-2018b
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): for the runs: 1 core, 30Gb memory. CPUs support AVX2, as far as I can tell.
* Operating system and version: CentOS 7

**Comment by martin-steinegger** [comment]
Thank you for reporting this. Could you please provide the full log? It could be possible that the PFAM profiles need too much memory (30GB might be not enough). 

If you want a set of stickers though (see https://twitter.com/thesteinegger/status/1201076220957315074), sent me your address via mail.

**Comment by galicae** [comment]
Thanks for the quick response! I tried with 50G and had no success. Any clues on how much is enough? The Pfam directory is a total of 19G, and the transcriptome is <1G. The prefilter step, which is the one that crashes, says that it is using almost 1G of RAM.

Please find the slurm output files here: https://gist.github.com/galicae/2565fb81f3edc84365671bc0688c5e31

**Comment by martin-steinegger** [comment]
Is it possible for you to provide the database? I would like to reproduce the error.

**Comment by burnsajohn** [comment]
FYI, I built the pfam profile database the same way recently (today, 1-7-2020) and get the same error/segfault. I'm also on CentOS-7 searching a protein database against the pfam profiles derived as @galicae above:

MMseqs Version:                         10.6d92c
Substitution matrix                     nucl:nucleotide.out,aa:blosum62.out
Add backtrace                           false
Alignment mode                          2
E-value threshold                       0.001
Seq. id. threshold    

tmp/1941146063176889841/searchtargetprofile.sh: line 28: 48442 Segmentation fault      $RUNNER "$MMSEQS" prefilter "${INPUT}" "${2}" "${TMP_PATH}/pref" ${PREFILTER_PAR}

Error: Prefilter died

**Comment by milot-mirdita** [comment]
I took a look at the issue yesterday. The problem should already be fixed in Git. Could you please try downloading the latest statically compiled version or build MMseqs2 yourself?

We will make a new release soon.

**Comment by burnsajohn** [comment]
Yes, that worked. I'd installed the prior MMseqs version using conda. I had to run through some system configuration before MMseqs would compile and run from source. I didn't track the steps, though. Once I had it installed, the new version wanted me to re-index the pfam database. Once that was done the search completed quickly.

Thank you for the replies!

**Comment by galicae** [comment]
Thanks for the timely responses! Taking the latest binary solved the previous problem, thanks a lot! However now the characters in the names of the hits are replaced by ^@ characters. Maybe some sort of encoding problem?
