### ISSUE TITLE
Is it possible to perform the suite on DNA sequence?

### ISSUE THREAD

**Issue by zhzhang217** [soedinglab/mmseqs2#26]
Just as the title, I am trying to use the _mmseqs cluster_ on DNA sequence clustering, but it did not work. So how can I apply the suite on DNA sequence clustering?

**Comment by milot-mirdita** [comment]
The only way currently is to use `translatenucs` to do a 6-frame translation of your nucleotide sequence databases to amino acids and proceed from there. (Of course this has its own drawbacks and there is no way to detect frame shifts.)

Hopefully we can get a master student in the future that implements a nucleotide prefilter.

**Comment by milot-mirdita** [comment]
To expand the answer a bit:

You can first use `extractorfs` to extract everything that might look like a protein in all six frames out of your contigs/scaffolds. 

If you already have some putative protein sequences in nucleotide form, then you can skip the `extractorfs` step.

**Comment by zhzhang217** [comment]
@milot-mirdita OK, thanks a lot. I'll try and feed back if there is.
