### ISSUE TITLE
mergedbs docstring question

### ISSUE THREAD

**Issue by smsaladi** [soedinglab/MMseqs2#262]
I wonder if it would make more sense for the help string for mergedbs to read ...

```
Usage: mmseqs mergedbs <i:sequenceDB> <o:resultDB> <i:sequenceDB2> ... <i:sequenceDBn> [options]
```

instead of the way it does as follows:
```
[saladi@brnode06]~/get3_history/queryseqs% mmseqs mergedbs -h
Usage: mmseqs mergedbs <i:sequenceDB> <o:resultDB> <i:resultDB1> ... <i:resultDBn> [options]

Merge multiple DBs into a single DB, based on IDs (names) of entries
 By Martin Steinegger <martin.steinegger@mpibpc.mpg.de>

Options:
 Misc:
   --prefixes STR     Comma separated list of prefixes for each entry []

 Common:
   --compressed INT   write results in compressed format [0]
   -v INT             verbosity level: 0=nothing, 1: +errors, 2: +warnings, 3: +info [3]
```

```
[saladi@brnode06]~/get3_history/queryseqs% mmseqs version
f644744a81f751d49cb6908b93a16722f5c6d489
```

**Comment by milot-mirdita** [comment]
Something like `<i:DB> <o:DB> <i:DB1> ... <i:DBn>` or `<i:allDB> <o:allDB> <i:allDB1> ... <i:allDBn>` would be better. MMseqs2 will merge all entries per key (according to the first database) in db1 ... dbN.

This tool is used in our iterative profile search, to stick the alignment results of all iterations together into one result database.

**Comment by milot-mirdita** [comment]
Btw, if you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de.
