### ISSUE TITLE
linclust error: alignment step died

### ISSUE THREAD

**Issue by Greblica** [soedinglab/MMseqs2#265]
Hi,

I have quite a big number of protein sequences that I want to cluster. I tried to cluster them together, it didn't work out (I don't know if size was the issue, but I was in a hurry), so I split the file in two and clustered each separately (that worked).

I then combined two outputs (*rep_seq.fasta) into a single file that I wanted to cluster once more (cca 75 mil sequences).

However, it always dies in the same way, although I tried changing memory settings and threads. This file is not bigger than the previous ones.
All the sequence names are unique.

MMseqs2 Version: 102e4299ba2788f492a9212c777ca09f6d6ea0f0
(I don't remember how I installed it, I think with cmake).

Command:
mmseqs easy-linclustallMG_plass_rep.fasta allMG_plass_comb_minid90_cm1_c90 tmpP --min-seq-id 0.9 --threads 22 --kmer-per-seq 80 --cluster-mode 2 --cov-mode 1 -c 0.9 --split-memory-limit 150G

Output:
stderr:
terminate called after throwing an instance of 'Sls::error'
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
tmpP/10678025033020444421/clu_tmp/1344998481088077811/linclust.sh: line 75:  6661 Aborted                 $RUNNER "$MMSEQS" "${ALIGN_MODULE}" "$INPUT" "$INPUT" "$RESULTDB" "${TMP_PATH}/aln" ${ALIGNMENT_PAR}

stdout:
align tmpP/10678025033020444421/clu_tmp/1344998481088077811/input_step_redundancy tmpP/10678025033020444421/clu_tmp/1344998481088077811/input_step_redundancy tmpP/10678025033020444421/clu_tmp/1344998481088077811/pref_rescore2 tmpP/10678025033020444421/clu_tmp/1344998481088077811/aln --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.9 --cov-mode 1 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 22 --compressed 0 -v 3 

Compute score and coverage
Query database size: 77815083 type: Aminoacid
Target database size: 77815083 type: Aminoacid
Calculation of alignments
[Error: Alignment step died
Error: Search died

The command is the same as used for previous clustering, the file is not bigger, I have no idea what is the issue.

Any help is appreciated, thanks,
G

**Comment by milot-mirdita** [comment]
Do you still have the full log?

Could you show the first few lines of these files:

```
head -n 3 tmpP/10678025033020444421/clu_tmp/1344998481088077811/input_step_redundancy*
head -n 3 tmpP/10678025033020444421/clu_tmp/1344998481088077811/pref_rescore2*
head -n 3 tmpP/10678025033020444421/clu_tmp/1344998481088077811/aln*
``

That's a very weird error. It seems to be crashing in calculating E-values. That would only be possible if it's fed some corrupted input.

**Comment by Greblica** [comment]
Thanks for the quick reply.


I thought there could be something wrong with the fasta input. But I don't know what it could be. The sequences names are unique, each assigned to exactly one sequence, I cannot seem to find something wrong with it.

Here is the output (aln files are empty):

**head -n3 input_step_redundancy***
==> input_step_redundancy <==
>FBeb10_731870_0+221_3 
VLYMRGWLRQLRKDRGLTQREVAARLGICQSYYGYIETRGRQKKIDLPLLAKIAGVFQVPLMALVDIETSAAEDMEKNPGERS*
>FBeb10_731947_2+221_3 

==> input_step_redundancy.dbtype <==

==> input_step_redundancy_h <==

==> input_step_redundancy_h.dbtype <==


==> input_step_redundancy_h.index <==
0	1	24
1	110	24
2	446	26

==> input_step_redundancy.index <==
0	23	86
1	132	313
2	470	97

==> input_step_redundancy.lookup <==
0	FBeb10_731870_0+221_3	0
1	FBeb10_731947_2+221_3	0
2	FBeb10_732006_221-221_3	0

==> input_step_redundancy.source <==
0	allMG_plass_rep.fasta



**head -n3 pref_rescore2.***

==> pref_rescore2.0 <==
30	131	0
393	136	0
445	457	0

==> pref_rescore2.1 <==
309	203	0
362	461	0
395	187	0

==> pref_rescore2.10 <==
35	232	0
67445	127	0
68377	189	0

==> pref_rescore2.11 <==
36	114	0
363	325	0
397	58	0

==> pref_rescore2.12 <==
300	266	0
59650	410	0
60227	1109	0

==> pref_rescore2.13 <==
304	482	0
391	140	0
1023	155	0

==> pref_rescore2.14 <==
305	640	0
64828	146	0
66020	435	0

==> pref_rescore2.15 <==
31	131	0
392	179	0
444	186	0

==> pref_rescore2.16 <==head -n3 input_step_redundancy*
34	382	0
62015	596	0
62964	114	0

==> pref_rescore2.17 <==
303	372	0
364	274	0
440	465	0

==> pref_rescore2.18 <==
38	1047	0
1300	659	0
1529	196	0

==> pref_rescore2.19 <==
32	169	0
368	66	0
441	244	0

==> pref_rescore2.2 <==
361	927	0
367	103	0
396	129	0

==> pref_rescore2.20 <==
306	1548	0
365	367	0
446	420	0

==> pref_rescore2.21 <==
37	141	0
394	141	0
587	154	0

==> pref_rescore2.3 <==
360	613	0
369	1437	0
448	2236	0

==> pref_rescore2.4 <==
302	81	0
398	459	0
589	219	0

==> pref_rescore2.5 <==
308	129	0
390	242	0
442	2205	0

==> pref_rescore2.6 <==
33	324	0
60859	107	0
61427	166	0

==> pref_rescore2.7 <==
39	253	0
366	930	0
443	242	0

==> pref_rescore2.8 <==
301	66	0
57199	131	0
58070	701	0

==> pref_rescore2.9 <==
307	389	0
399	229	0
731	771	0

==> pref_rescore2.dbtype <==

==> pref_rescore2.index <==
0	603331515	9
1	259700076	9
2	374298787	9

**Comment by milot-mirdita** [comment]
The `input_step_redundancy` file looks very broken.  Could you post the first few sequences from your query file?

```
head allMG_plass_rep.fasta 
```

**Comment by Greblica** [comment]
Sure.

>FBeb10_731870_0+221_3 
VLYMRGWLRQLRKDRGLTQREVAARLGICQSYYGYIETRGRQKKIDLPLLAKIAGVFQVPLMALVDIETSAAEDMEKNPGERS*
>FBeb10_731947_2+221_3 
QIHVRRQGRSQGADRHSRRSAGDVRHRAGQLSAPAGRRRAGHYHSPGKRSAENYGDHHILHESGGEIGMNAIQTKELTRRYGEKTAVDALDLTVKQGELFALLGVNGAGKTTTVKMLSGLLAPTSGDAEILGYSLVSQTQEVKSRINLSPQETAVAPKLTARENLELIAGIYGSTRKEAKEKAAAMLEEFHMQEVAGQRAGTLSGGWQRRLSIAMALISQPQILFLDEPTLGLDVLARRELWNIIEKLKGRVTVILTTHYMEEAASLADRVAILAHSRLRLCGTVQEILDAAEETDFENAFIKLAGGTEA*
>FBeb10_732006_221-221_3 
FLHGLYLKVIRLADISQYLRGLLRAGLSAVLPVYLVTVVLRRVVAGGYYYARHAVKVQHRKGKLGYRVQLAVEICLYAVFGKYQRRLLCKYIGHM
>FBeb10_732009_165-158 
*MMERIQNGVNDCGIREYFPTPYGAKLYAGKPHCHAVHGNFDGRRRFFCDGRYD*
>FBeb10_732039_0+230_3 
*MRSPARVLNSLTKHSQTTEYRFERLYRILFNEEMYYLAYQRIYAKPGNMTQGADGKTIDRMSLSRIEKLIASLKDESYSPQPSRRMYIPKKNGKTRPLGVPSFDDKLVQEVVRMVLEAIYEGHFE

**Comment by Greblica** [comment]
I don't know why ">" are not visible, but they are in the file :).

**Comment by milot-mirdita** [comment]
GitHub Markdown turns them into a quote. 

Everything regarding this file is alright though. That's a new feature to reduce IO that confused me. 
Not sure what else might be going wrong here though.

Could you try the latest git version? Also if you rerun, could you save the full log? I am a bit at a loss on how to recreate the issue.

**Comment by milot-mirdita** [comment]
Can you try clustering the first 100k sequences or so? If that crashes can you send me these sequences?

**Comment by Greblica** [comment]
The issue remains, I attach the output and the sequences.
The sequences come from a previous linclust round, can it be that there are some hidden characters or something? That's the only thing that comes to my mind.

[allMG_plass_rep_h200.fasta.gz](https://github.com/soedinglab/MMseqs2/files/4070687/allMG_plass_rep_h200.fasta.gz)
[linclustPlass1.err.gz](https://github.com/soedinglab/MMseqs2/files/4070698/linclustPlass1.err.gz)
[linclustPlass1.out.gz](https://github.com/soedinglab/MMseqs2/files/4070699/linclustPlass1.out.gz)

**Comment by martin-steinegger** [comment]
I have fixed the behavior of `--createdb-mode 1` in the easy workflows. This should be solved now.
