### ISSUE TITLE
Cluster update speedup

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#269]
Hi
we are continuously updating a large cluster DB with new data, and one of the steps that are taking longer is when the new sequences are updated with the old keys using the function `joinAndReplace`. We are using this function for other purposes and we added to the sorting parts `--parallel` and `--buffer-size` to speed up and reduce the I/O needed for the sorting. I think it would be great to have available these options if `sort` is modern enough and fallback to the original `joinAndReplace` if `sort` doesn't support these options. What do you think?

Antonio

**Comment by milot-mirdita** [comment]
I think it would make sense to either write a separate MMseqs2 module (`mapkeys`, `rekey`,  ... ?) 
or extend `concatdbs` to read in a mapping and reassign keys.
That way we could remove the `joinAndReplace` hack completely.

Would you be interested to write that? I think extending `concatdbs` makes most sense.

**Comment by genomewalker** [comment]
Yes, this would be perfect. 

> Would you be interested to write that? I think extending `concatdbs` makes most sense.

At the moment I am not able to assign any time on this, but I should have some new students soon that could be interested and it would be a great way to get familiar with MMseqs2 internals. I keep you posted.

Thanks!

**Comment by milot-mirdita** [comment]
Could you try the latest git version? I got rid of the `joinAndReplace` function and replaced it with a native MMseqs2 module.

**Comment by genomewalker** [comment]
Thanks @milot-mirdita! We will have a look when back from vacation.
