### ISSUE TITLE
best way to extract a subset of clusters from a larger clusterDB?

### ISSUE THREAD

**Issue by jhcepas** [soedinglab/mmseqs2#27]
Hi there,
what would be the best way to create a cluster DB containing only a subset of cluster IDs from a larger cluster DB? Does `mmseqs createsubdb` can be reliably used with the a set of human readable cluster IDs?  
thanks! CCing @kristinaka

**Comment by martin-steinegger** [comment]
yes, createsubdb can do this.

**Comment by jhcepas** [comment]
thanks @martin-steinegger 
it seems that we cannot use cluster names to extract them. This is a test to reproduce:

```
mmseqs createdb examples/DB.fasta DB.db
mmseqs cluster DB.db DB_clu temp/ --threads 20 -c 0.0 --cascaded -s 7 --cluster-mode 2
mmseqs createtsv DB.db DB.db DB_clu DB_clu.tsv
cut -f1 DB_clu.tsv|head -n5 > requested_clusters
mmseqs createsubdb requested_clusters DB_clu DB_clu_filtered

Start writing to file DB_clu_filtered
Key A7YWM6 not found in database
Key C4KHV1 not found in database
Key C4KHV1 not found in database
Key C4KHV1 not found in database
Key C4KHV1 not found in database
Time for merging files: 0 h 0 m 0 s
```

**Comment by genomewalker** [comment]
@jhcepas we use the lookup tables to subset the DB using the numeric ids mmseqs creates, but it would be much easier and practical if it could be done automatically.

**Comment by jhcepas** [comment]
thanks @genomewalker,
So, once we have identified the names of the clusters to extract, what would be a safe way to get the numeric ids of those clusters so we can used them in createsubdb?

**Comment by genomewalker** [comment]
We do a grep to the DB.lookup file and get the first column. Something like:

`LC_ALL=C grep -w -m {number_elements_in_requested_clusters} -f {requested_clusters} DB.lookup | cut -f1 > requested_clusters_numerical`

Then we use requested_clusters_numerical to do the subset. I am sure there is an mmseqs (@martin-steinegger) way to do it but we couldn't figure it.

**Comment by jhcepas** [comment]
@genomewalker, that works great. 
we will use your approach meanwhile @martin-steinegger can tell us if there is a better way

**Comment by martin-steinegger** [comment]
@jhcepas @genomewalker there is no specific MMseqs2 function that can do this. The initial design idea of was that MMseqs2 and bash command work together. Maybe we should think about good way. 
I think the solution proposed by @genomewalker is quite good. I did not know that grep can do this. It just has a problem if some ids in `{requested_clusteres}` are numerical as well. 

Normally I use a awk script to join two files for this case. 

`join.awk requested_clusters <(awk '{print $2"\t"$1}' DB.lookup ) | cut -f 3 > requested_clusters_numerical`

The join.awk script was created by Dimitre Radoulov and looks like the following. (http://stackoverflow.com/questions/14195954/match-values-in-first-col/umn-of-two-files-and-join-the-matching-lines-in-a-new-f#14196040)

```
## join.awk
#!/usr/bin/awk -f

BEGIN { FS = OFS = "\t"}
NR == FNR {
  # while reading the 1st file
  # store its records in the array f
  f[$1] = $0
  next
}
$1 in f {
  # when match is found
  # print all values
  print f[$1], $0
}
```

**Comment by genomewalker** [comment]
Hi @martin-steinegger 
Thank you very much for the awk suggestion. This solution is more general than our quick and dirty grep :-)
