### ISSUE TITLE
not urgent but: GITDIR-NOTFOUND

### ISSUE THREAD

**Issue by gaboentropy** [soedinglab/MMseqs2#275]
## Expected Behavior
Should see mmseqs version:
MMseqs2 Version: 10-6d92c

## Current Behavior
Instead I see:
MMseqs2 Version: GITDIR-NOTFOUND

## question
How do I fix this? or, rather, is it fixable?

**Comment by milot-mirdita** [comment]
Did you install from the tar.gz? Please checkout from git and compile or manually set whatever string you want by passing `-DVERSION_OVERRIDE=YourString` to cmake.

**Comment by gaboentropy** [comment]
Yeah, from tar,gz. Thanks.

**Comment by milot-mirdita** [comment]
No problem, if you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de.
