### ISSUE TITLE
cluster sequence identities falling below --min-seq-id threshold

### ISSUE THREAD

**Issue by vinaiksundaresan** [soedinglab/MMseqs2#276]
## Context
[seqs.txt](https://github.com/soedinglab/MMseqs2/files/4214811/seqs.txt)

I created a DB and ran the mmseqs cluster command with an alignment coverage and minimum sequence identity of 0.8. I then added sequence identity information to my clustering result by using the align command.
`mmseqs createdb seqs.faa seqs_db`
`mmseqs cluster -c 0.8 --min-seq-id 0.8 seqs_db mmseqs80_clustered_db /tmp`
`mmseqs align seqs_db seqs_db mmseqs80_clustered_db alignment_db -a`
`mmseqs convertalis seqs_db seqs_db alignment_db align.m8`

## Expected Behavior
I expected all the sequence identities contained in align.m8 to be above or equal to 0.8 because of the --min-seq-id flag.

## Current Behavior
I see sequence identities that fall below 0.8. These intra-cluster sequence identities fall as low as 0.55 when I cluster millions of sequences together.

[align_m8.txt](https://github.com/soedinglab/MMseqs2/files/4214947/align_m8.txt)

Does this mean that the --min-seq-id flag is being violated or do I misunderstand how sequence identity is being computed and reported?

## Your Environment
Running mmseqs2 on a cluster in a Unix terminal.
MMseqs2 Version: bc080d753c826a3f9153310f9e12b66976fba905

**Comment by martin-steinegger** [comment]
It is possible that the sequence identity is violated. Reason for this is the cascaded clustering. Sequences can diverge further with each iteration. However, we build a mode to correct this mistakes `--cluster-reassign 1`. It removes member that do not fulfill clustering criteria and tries to assign them to the remaining representative sequences. 

```
mmseqs cluster seqs_db mmseqs80_clustered_db /tmp  --cluster-reassign 1  -c 0.8 --min-seq-id 0.8 
```

**Comment by vinaiksundaresan** [comment]
This works great for my test case! Currently reclustering my larger dataset with the --cluster-reassign flag and hopeful that this will fix my problem. Thank you, marking this issue closed.

**Comment by milot-mirdita** [comment]
If you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de.
