### ISSUE TITLE
Information on mmseqs cluster module

### ISSUE THREAD

**Issue by asetGem** [soedinglab/MMseqs2#279]
## Information

Hi,

I am a bit confused with the MMseqs2 suite modules.

If I understood correctly:

- when I do `mmseqs search args`, it uses the algorithm described in https://www.nature.com/nbt/journal/vaop/ncurrent/full/nbt.3988.html   (3 stages: prefilter, ungapped alignment, gapped SW alignment. The last one generates similarity file, giving the % of similarity for each pair of sequences)
- when I run `mmseqs linclust args`, it executes the algorithm described in https://www.nature.com/articles/s41467-018-04964-5
- For `mmseqs cluster`, I saw that it is slower than linclust, but also way more sensitive. So, I am using this module, to cluster sequences with min-seq-id = 0.8 (default of mmseqs). But I do not understand what is used. In the userguide, I saw :

> mmseqs cluster: Clusters sequences by similarity. It compares all sequences in the sequence DB with each other using mmseqs search, filters alignments according to userspecified criteria (max. E-value, min. coverage,. . . ), and runs mmseqs clust to group similar sequences together into cluster' (p.17)

At the same time, in p.22, I saw:

> The cascaded clustering workflow first runs linclust, our linear-time clustering module, that can produce clustering’s down to 50% sequence identity in very short time. To achieve lower sequence identities and/or to further improve the resulting clusters, we continue with three cascaded clustering steps

Cascaded clustering being the default for `mmseqs cluster`, this would mean that the search module is not used?

When using `mmseqs search args` I can get the similarity file in blast format (using convertalis). Therefore, is it also possible to get this file at the end of clustering step, if it uses mmseqs search algorithm as I saw p.14?

I don't know if my questions are really clear. Please do not hesitate to ask me if you need some more information.

Thanks a lot for your help!

**Comment by martin-steinegger** [comment]
> Cascaded clustering being the default for mmseqs cluster, this would mean that the search module is not used?

In default, `mmseqs cluster` performs first `linclust` followed by cascaded clustering. 

> When using mmseqs search args I can get the similarity file in blast format (using convertalis). Therefore, is it also possible to get this file at the end of clustering step, if it uses mmseqs search algorithm as I saw p.14?

It is possible to get the similarity file by realigning the cluster. Following is an example:

    mmseqs cluster seq clu tmp 
    mmseqs align seq seq clu aln
    mmseqs convertalis seq seq aln aln.m8

**Comment by asetGem** [comment]
> In default, mmseqs cluster performs first linclust followed by cascaded clustering.

So, `mmseqs search` algorithm is never used for clustering?

**Comment by martin-steinegger** [comment]
Each iteration of the cascaded clustering performs a prefilter (`prefilter`), gapped SW alignment (`align`) and a clustering (`clust`).
