### ISSUE TITLE
ERROR: Set 0 has more elements than allocated (1)!

### ISSUE THREAD

**Issue by dcpastor** [soedinglab/mmseqs2#28]
I was trying to use MMSEQS2 for clustering with:

mmseqs cluster DB clu tmp --cascaded -e 1e-5 --max-seqs 30000 --similarity-type 1

It was working fine (MMseqs version ad5b994c5f21d2117c359ecb748811cbd01eba73) but when I try to execute it in another machine (both macOS El Capitan 10.11.6, this time MMseqs version e3ca470308523cb3d997088c65e821cc79e2a422), I get several error messages as follows,

ERROR: Set 0 has more elements than allocated (1)!

and the clustering never finishes.

Any idea of what is this due to or how to solve it?

Thank you in advance

**Comment by milot-mirdita** [comment]
Could you post the whole output log please?

What happens if you run it with only the --cascaded parameter (no e, max-seqs, similarity-type).

**Comment by ClovisG** [comment]
This was a bug introduced by some recent changes. Can you please pull the last version of MMSeqs2 and try again ?

**Comment by ClovisG** [comment]
I close the issue, please re-open it in case you still have troubles.
