### ISSUE TITLE
Segmentation fault with results2msa on nucleotide database (cluster)

### ISSUE THREAD

**Issue by valflanza** [soedinglab/MMseqs2#282]
I am trying to get the msa of a nucleotide cluster results and I have a segmentation fault.

mmseqs result2msa all.mmseq all.mmseq all.cluster.subset all.msa --summarize --max-seq-id 1 --diff 1461 --qsc -50 --omit-consensus

Segment violation

When I use Aminoacid sequence, software works well.

**Comment by milot-mirdita** [comment]
`result2msa` only works for aminoacids currently.
You can use `createseqfiledb` to create a database of unaligned FASTA files and then pass that with the `apply` module to any external nucleotide MSA aligner.

By the way, if you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de.
