### ISSUE TITLE
Smaller query size is considered

### ISSUE THREAD

**Issue by Askarbek-orakov** [soedinglab/MMseqs2#283]
## Expected Behavior
When query has 10,000 sequences
Query database size: 10,000 type: Aminoacid
## Current Behavior
Query database size: 3125 type: Aminoacid

## Steps to Reproduce (for bugs)
Running search or prefilter.

## MMseqs Output (for bugs)
MMseqs Version:           	ca58693979f95537016a0454affcfd529dbde24d
Substitution matrix       	nucl:nucleotide.out,aa:blosum62.out
Seed substitution matrix  	nucl:nucleotide.out,aa:VTML80.out
Sensitivity               	4
k-mer length              	0
k-score                   	2147483647
Alphabet size             	nucl:5,aa:21
Max sequence length       	65535
Max results per query     	300
Split database            	0
Split mode                	2
Split memory limit        	0
Coverage threshold        	0
Coverage mode             	0
Compositional bias        	0
Diagonal scoring          	true
Exact k-mer matching      	0
Mask residues             	0
Mask lower case residues  	0
Minimum diagonal score    	15
Include identical seq. id.	false
Spaced k-mers             	1
Preload mode              	0
Pseudo count a            	1
Pseudo count b            	1.5
Spaced k-mer pattern      	
Local temporary path      	
Threads                   	64
Compressed                	0
Verbosity                 	3

Query database size: 3125 type: Aminoacid
Estimated memory consumption: 193G
Target database size: 37233987 type: Aminoacid
Index table k-mer threshold: 141 at k-mer size 7 
Index table: counting k-mers

**Comment by milot-mirdita** [comment]
Can you post the full log and call to MMseqs2 please?

**Comment by Askarbek-orakov** [comment]
Thanks for your prompt replies!

mmseqs search -s 4 --threads 64 -e 100000 --comp-bias-corr 0 --mask 0 $SCRATCHDIR/queryT.mmsq $SCRATCHDIR/queryT.mmsq $SCRATCHDIR/queryT.mmsq.outDB $SCRATCHDIR > $SCRATCHDIR/test.log

File $SCRATCHDIR/queryT.mmsq has 10000 lines, which I guess should confirm it has 10000 sequences. 

prefilter /scratch/orakov/tmp/queryT.mmsq /scratch/orakov/tmp/queryT.mmsq /scratch/orakov/tmp/9822650028334564073/pref_0 --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seq-len 65535 --max-seqs 300 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 0 --diag-score 1 --exact-kmer-matching 0 --mask 0 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 64 --compressed 0 -v 3 -s 4.0 

Query database size: 313 type: Aminoacid
Estimated memory consumption: 979M
Target database size: 313 type: Aminoacid
Index table k-mer threshold: 127 at k-mer size 6 
Index table: counting k-mers
[=================================================================] 313 0s 11ms
Index table: Masked residues: 0
Index table: fill
[=================================================================] 313 0s 11ms
Index statistics
Entries:          99064
DB size:          488 MB
Avg k-mer size:   0.001548
Top 10 k-mers
    GQQVAR      4
    QRAALA      3
    LSGRVA      3
    LGEIVD      3
    RELAEE      3
    LAAAVG      3
    SGQQAI      3
    RAVSFK      3
    AIGSGK      3
    ALGSGK      3
Time for index table init: 0h 0m 0s 582ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 127
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 313
Target db start 1 to 313
[=================================================================] 313 0s 95ms

46.584655 k-mers per position
349 DB matches per sequence
0 overflows
0 queries produce too much hits (truncated result)
1 sequences passed prefiltering per query sequence
1 median result list length
0 sequences with 0 size result lists
Time for merging to pref_0: 0h 0m 0s 219ms
Time for processing: 0h 0m 6s 996ms
align /scratch/orakov/tmp/queryT.mmsq /scratch/orakov/tmp/queryT.mmsq /scratch/orakov/tmp/9822650028334564073/pref_0 /scratch/orakov/tmp/queryT.mmsq.outDB --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --wrapped-scoring 0 -e 100000 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --zdrop 40 --threads 64 --compressed 0 -v 3 

Compute score and coverage
Query database size: 313 type: Aminoacid
Target database size: 313 type: Aminoacid
Calculation of alignments
[=================================================================] 313 0s 75ms
Time for merging to queryT.mmsq.outDB: 0h 0m 0s 320ms

408 alignments calculated.
408 sequence pairs passed the thresholds (1.000000 of overall calculated).
1.303514 hits per query sequence.
Time for processing: 0h 0m 0s 966ms

**Comment by milot-mirdita** [comment]
Something is going wrong before the prefiltering stage already, could you recreate `$SCRATCHDIR` completely?  Also please specify a scratch directory that does not contain anything (e.g. query, target, results, logs).

**Comment by Askarbek-orakov** [comment]
Thank you! I have put the temporary directory for MMseqs to be separate from the scratchdir where query and intermediate files are stored.
