### ISSUE TITLE
Multi-threading not working when installing from brew on OSX Catalina

### ISSUE THREAD

**Issue by salvoc81** [soedinglab/MMseqs2#289]
## Expected Behavior
Multiple Threads are used when specified

## Current Behavior
The threads are not fully used.
Although the output generates multiple output files, the execution time is same as the one observed when specifying --threads 1

## Steps to Reproduce (for bugs)
Install MMseqs2 using brew

`brew install mmseqs2`

## Context
MMseqs2 installed using homebrew.
libomp: stable 9.0.1 was also installed using brew

NOTE: everything works fine when using the OSX binaries provided in the MMseqs2 web-page

**Comment by milot-mirdita** [comment]
Thanks a lot, that was an unexpected and tricky fuck up.

If you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send me your address to milot at mirdita de. However actually sending them out will take some time I guess with the current circumstances.

**Comment by milot-mirdita** [comment]
Fix was just merged, the updated brew package should now work correctly multi-threaded. Thanks again!

**Comment by salvoc81** [comment]
Grazie @milot-mirdita
