### ISSUE TITLE
Error: result2rbh died

### ISSUE THREAD

**Issue by YongLiedu** [soedinglab/MMseqs2#290]
## Current Behavior
> The merged results are assumed to be sorted by decreasing bitscore.
> Error: result2rbh died

It seems that res_best_merged_sorted is not sorted as expected.

## Steps to Reproduce (for bugs)
```bash
mmseqs rbh in_cds_1_mmdb in_cds_2_mmdb out.out tmp --threads 30 --max-seqs 100 --max-accept 10
```

## MMseqs Output (for bugs)
> Merging the results to tmp/4773716631589885835/res_best_merged
> Time for merging to res_best_merged: 0h 0m 0s 4ms
> Time for processing: 0h 0m 0s 28ms
> filterdb tmp/4773716631589885835/res_best_merged tmp/4773716631589885835/res_best_merged_sorted --sort-entries 2 --filter-column 2 --threads 5 --compressed 0 -v 3
>
> Filtering using regular expression
> [=================================================================] 45.87K 0s 56ms
> Time for merging to res_best_merged_sorted: 0h 0m 0s 11ms
> Time for processing: 0h 0m 0s 77ms
> result2rbh tmp/4773716631589885835/res_best_merged_sorted AA_cds_rbh_BB_cds.out --threads 5 --compressed 0 -v 3
>
> [The merged results are assumed to be sorted by decreasing bitscore.
> The merged results are assumed to be sorted by decreasing bitscore.
> The merged results are assumed to be sorted by decreasing bitscore.
> Error: result2rbh died

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
24479bc27c3f33a3c0121f916038c605beef3e79
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
self-compiled
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
Cmaker 3.10.2, gcc 7.5.0
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
CPU: Xeon(R) CPU E5-2699 v3
RAM: 220G
* Operating system and version:
Ubuntu 18.04

**Comment by martin-steinegger** [comment]
Thank you for reporting this issues. We fixed a bug in the filterdb module. The result list should be sorted now.

**Comment by susheelbhanu** [comment]
Hi, 
I'm running into the same error. My installation is via conda, so, has this been pushed to conda yet, or should I be compiling from source?

Thank you!

**Comment by milot-mirdita** [comment]
This will be part of the next release, please use either our statically compiled binaries (mmseqs.com/latest) or compile from source.

**Comment by susheelbhanu** [comment]
Thank you. I compiled from the source and it seems to work fine. Any tentative timeline for the next release though?!
