### ISSUE TITLE
mmseqs2 cluster - sequence truncated

### ISSUE THREAD

**Issue by EllieYin567** [soedinglab/MMseqs2#291]
Hi, We are using mmseqs2 for the protein sequence clustering and it has been great! 
However, recently, we found for one of the fasta files we tried to cluster, the total input sequence number does not match the cluster output (the members). 
When looking at the log, we found there are some sequences got truncated, which may have cause the problem? 
Do you have any suggestion on why this occur and which parameters we could try to fix the issue? Also, the input fasta file is already de-replicated. 
Attached is the run log for mmseq2. 
[log_clu.txt](https://github.com/soedinglab/MMseqs2/files/4382578/log_clu.txt)
Thank you very much!

**Comment by milot-mirdita** [comment]
Could you please try to rerun the clustering same same dataset with the latest release? We have since improved the handling of long sequence and the issue might already be resolved.

**Comment by EllieYin567** [comment]
Thank you for getting back! We will try to use the latest release. 
Meanwhile, we are testing whether increasing `--max-seqs` will help. Do you think this could be one possibility/ direction to try?

**Comment by milot-mirdita** [comment]
Do the clusters contain less sequences or more than the input? If its more, that should be fixed now. If it's less that was (is still?) a bug. `--max-seqs` should not really affect this.

**Comment by EllieYin567** [comment]
The cluster used to contain less sequences than the input when we used the older version. 
We tried to use the latest version and now the number seems to match! One more question is still on the truncation, that we got messages "1 queries produce too much hits (truncated result)". What does this mean? Should this be a concern? Thank you very much! 
[log_clu_03_25.txt](https://github.com/soedinglab/MMseqs2/files/4388245/log_clu_03_25.txt)

**Comment by milot-mirdita** [comment]
This one query found a extreme amount of hits in the remaining database and could not resolve all the best potential hits due to limits on allowed memory usage. This might result in a slight loss of sensitivity for this one query, all other clusters should be fine though.

**Comment by EllieYin567** [comment]
I see. Thank you very much!

**Comment by milot-mirdita** [comment]
No problem! If you want a set of stickers (see https://twitter.com/thesteinegger/status/1201076220957315074), send your address to milot at mirdita de. I'll send them out once our institute opens again.
