### ISSUE TITLE
Reference database for sensitivity/comparisions

### ISSUE THREAD

**Issue by smsaladi** [soedinglab/MMseqs2#296]
Sorry if this isn't the right forum, but is there a reference database for determining the sensitivity to the first false positive as plotted here to compare the various `-s` and with other packages? 

https://github.com/soedinglab/MMseqs2/wiki#set-sensitivity--s-parameter 

Or said another way, are the databases/code used for the plot available somewhere? I'm trying to validate another method and am hoping place it accurately/make a fair comparison with other the rest.

**Comment by milot-mirdita** [comment]
Everything should be here: 
https://bitbucket.org/martin_steinegger/mmseqs-benchmark
http://gwdu111.gwdg.de/~compbiol/mmseqs2/mmseqs2-benchmark.tar.gz

However, most scripts are also kind of outdated, parameters changed etc. So getting them to run with the latest MMseqs2 version might be a bit of work.

We run a far smaller set of tests on every commit:
https://github.com/soedinglab/mmseqs2-regression
These scripts here originated from the above mentioned repository and might be useful to get commands to run again with the latest MMseqs2.

**Comment by smsaladi** [comment]
Thanks this is very helpful -- the regression testing is awesome
