### ISSUE TITLE
Out of disk space after alignment, can i pick up from here?

### ISSUE THREAD

**Issue by AndresZal** [soedinglab/MMseqs2#30]
Hi, I've been aligning 11 Million seqs for the last couple of days in an ALL vs ALL fashion.
I've passed the pre-filter and pairwise alignment steps, but I ran out of space in the 2tb hdd while trying to merge the final indexes and alignments.
Is there any way of completing the final step (maybe to another free disk or deleting the the prefilter file), or is my only option to recalculate the ALL v ALL in smaller batches.
Thanks for the help! And for making an 11Mx11M alignment feasible without a big cluster. 

Andres

**Comment by martin-steinegger** [comment]
Hi Andres,

thanks a lot for your feedback. It is possible to restart modules in MMseqs2 e.g. prefilter, align, clust, ... (see https://github.com/soedinglab/mmseqs2/wiki#how-to-restart-a-search-or-clustering-workflow) but merging can not be restarted. However there is a way using ffindex_build (https://github.com/soedinglab/ffindex_soedinglab). The following steps should create a new database (you need to adjust the 7 so it matches the amount of "index.[0-9]+" files  in the folder). 

```
for i in {1..7}; do
    ffindex_build -a aln.{0,index.0} -d aln.$i  -i aln.index.$i;
done
ffindex_build -as aln.{0,index.0}
mv aln.0 aln
mv aln.index.0 aln.index
```

Another option: MMseqs2 reports per default 300 alignment. You could just rerun the alignment with `--max-accept` to decrease the hard disk space needed. you can read more about disk space requirements at (https://github.com/soedinglab/mmseqs2/wiki#alignment-module).
