### ISSUE TITLE
Limited number of results in NR NCBI

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#300]
Hi.

I was trying to search single queries against NCBI NR just for test.  
Somehow, I got just a few results ~450 results by a query.

The point is, the lowest e-value is too low ~1e-50.

I've got no error message. Then, I think I'm doing something wrong in `createindex`.
Probably I need to change some parameters as `--max-seqs`.

For example, I used this query:
```
>WP_066948057.1 AAA family ATPase [Microtetraspora fusca]
MRKVPLPEPVSAALTDALDQLRLAVEDLHFGLDIPGAEEARKAQAAVLAQLEDYVIPRVHMSTAPALIVVAGSTGAGKST
LVNTLAAQRVSTTGVRRPTTGTPVLVCHPDDHEWFAEGDLLGGLTRLERPVEGVGTDSVVLSTTERLPPGVALLDTPDID
SVVEEHHEIAHRMLDAADMWVFVTTASRYADAPSWNLLRLAKERGARLVIVLSRVPEKSRDVIVKHFGRMLDEYGLADAE
RFVIKETTVTEGRLPDKEVSELRMWLAHLSVDDERRAAAVRTTLNGVLDSFRNRVPALARHLETQVALRADLRSDVDAAY
MGALADIDEATRNGSLLRGEVLARWQDFAGSGDLIRTLQLRRGGKGGQRGPQRARALRTAIRNALESVINSAAERAAEEV
VVRWRQRAGAGDRLAATPGLGRSSDEATQRTSRAIGAWQDHVTELIRTEGVTKRSVARLVSFDVESLALIFTVSLLGYGA
TDVSSGRGAGALPQRLLRALLGAESLRNISAKARSDLRARIGMVFDEETLRYVDELDGAGIPDEAAATRLYQATYNLEVA
R
```

The NR was prepared with
```
mmseqs databases NR nr tmp
mmseqs createindex nr tmp
```

And the search was performed like this
```
mmseqs easy-search query.fa nr result tmp
```

The same query with blastp has returned me 5000 results using `-max_target_seqs 5000`.

https://github.com/soedinglab/MMseqs2/wiki#disk-space

Do I need to change the parameters in `createindex` ?

I'd like to maximize the number of results for a e-value threshold. As returning all results down to 1e-3 of e-value or other value I choose.

Thanks in advance

**Comment by martin-steinegger** [comment]
You do not need to change any parameters in `createindex` but increase the `--max-seqs`. 

We developed a search mode that returns all results for a given set of parameters. It is still experimental:

```
mmseqs easy-search query.fa nr result tmp --slice-search
```

**Comment by acpguedes** [comment]
Thanks for the answer, but I did not follow precisely.
Should I change `--max-seqs` in `prefilter` or in `createindex`?
Also, do you recommend any number to `--max-seqs`?
1e6 may be to high?

**Comment by martin-steinegger** [comment]
The `--max-seqs` parameter has no impact for `createindex`. Just increase it while searching. If you increase it too high then MMseqs2 will use a lot of hard disk to store the prefilter. 

```
mmseqs easy-search query.fa nr result tmp --max-seq XXXXX
```
