### ISSUE TITLE
create createlinindex overwrites createindex

### ISSUE THREAD

**Issue by acpguedes** [soedinglab/MMseqs2#306]
I'd like to know whats the difference between `createlinindex` and `createindex`.

I did the index to `nr` with `createindex` and after I did `createlinindex` which overwrites the `*.idx` files of the previous index. 

There is a way to keep both indexes avoiding one overwrite the other.

**Comment by milot-mirdita** [comment]
`createlinindex` is part of linsearch which is still very much in development.
It should be creating a separate index (`.linidx`). How are you running it?

**Comment by acpguedes** [comment]
Hi @milot-mirdita 

I did:
```
# download the NCBI NR
mmseqs databases NR nr tmp
# Create index
mmseqs createindex nr tmp
# Create linsearch index
mmseqs createlinindex nr tmp
```

Perhaps I checked again, somehow the process has failed then I runner again the `createlinindex` and it created an index with `*.linidx`.

Sorry, my mistake.

Thanks
