### ISSUE TITLE
mmseqs2 createdb crashes "Illegal instruction"

### ISSUE THREAD

**Issue by orenavram** [soedinglab/MMseqs2#310]
Hi there, 

I encountered a weird behavior when trying to run createdb on an HPC cluster (see below). It looks like machines with less than <= 64GB RAM are unable to run createdb properly while higher RAM machines are (the input file is attached). Does it make sense or maybe I'm missing something? What are the minimum RAM requirements for running mmseqs2 (couldn't find it in the program docs)? Btw, these 2 machines use the same storage so it shouldn't be the issue.

I appreciate your assistance. Thanks!

This is the exact command I'm trying to run:
[64GB RAM machine]$ mmseqs createdb ~/test/outputs/01_ORFs/GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic.01_ORFs.txt ~/test/outputs/02_dbs/GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic -v 3

MMseqs Version:       	3513001d33301f7eaaf58e60a1376488ff017354
Database type         	0
Shuffle input database	true
Createdb mode         	0
Offset of numeric ids 	0
Compressed            	0
Verbosity             	3

Converting sequences
[6162] 0s 561ms
Illegal instruction

[128GB RAM machine]$ mmseqs createdb ~/test/outputs/01_ORFs/GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic.01_ORFs.txt ~/test/outputs/02_dbs/GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic -v 3

MMseqs Version:       	3513001d33301f7eaaf58e60a1376488ff017354
Database type         	0
Shuffle input database	true
Createdb mode         	0
Offset of numeric ids 	0
Compressed            	0
Verbosity             	3

Converting sequences
[6162] 0s 651ms
Time for merging to GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic_h: 0h 0m 0s 356ms
Time for merging to GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic: 0h 0m 0s 489ms
Database type: Nucleotide
Time for merging to GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic.lookup: 0h 0m 0s 14ms
Time for processing: 0h 0m 1s 861ms

[GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic.01_ORFs.txt](https://github.com/soedinglab/MMseqs2/files/4609960/GCF_000481805.1_Pseu_aeru_JJ692_V1_genomic.01_ORFs.txt)

**Comment by milot-mirdita** [comment]
Could you please run `cat /proc/cpuinfo` or `lscpu` on the 64GB node? 
If you were using the binary with the wrong instruction set (e.g. AVX2 on a CPU that does not support AVX2) it should give an error message way earlier.

**Comment by orenavram** [comment]
[bioseq@compute-0-294 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    1
Core(s) per socket:    12
Socket(s):             2
NUMA node(s):          4
Vendor ID:             AuthenticAMD
CPU family:            16
Model:                 9
Model name:            AMD Opteron(tm) Processor 6172
Stepping:              1
CPU MHz:               800.000
CPU max MHz:           2100.0000
CPU min MHz:           800.0000
BogoMIPS:              4200.23
Virtualization:        AMD-V
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              5118K
NUMA node0 CPU(s):     0-5
NUMA node1 CPU(s):     6-11
NUMA node2 CPU(s):     18-23
NUMA node3 CPU(s):     12-17
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc art rep_good nopl nonstop_tsc extd_apicid amd_dcm pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate npt lbrv svm_lock nrip_save pausefilter

**Comment by milot-mirdita** [comment]
Your CPU does not support the minimum requirements of MMseqs2. However once this PR (https://github.com/soedinglab/MMseqs2/pull/309) is merged SSE2 will also be supported.

If you have a Debian based machine you could install the mmseqs2 package from the debian-med apt. It already contains a precursor of this patch and should already work correctly on your CPU.

**Comment by eyalDtau** [comment]
Hi There,

I'm having problems trying to install fix #309. https://github.com/soedinglab/MMseqs2/pull/309

When trying to checkout the fix code I get an error.
https://github.com/soedinglab/MMseqs2/pull/309/commits/bff2883f04c9afa8af78cf259c0c1a9f3f719fd1
It appear that this commit is not part of the mmeseq main branch. 

see below:

# git clone https://github.com/soedinglab/MMseqs2.git
Cloning into 'MMseqs2'...
remote: Enumerating objects: 284, done.
remote: Counting objects: 100% (284/284), done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 34346 (delta 175), reused 143 (delta 78), pack-reused 34062
Receiving objects: 100% (34346/34346), 27.68 MiB | 13.72 MiB/s, done.
Resolving deltas: 100% (26632/26632), done.
Checking out files: 100% (968/968), done.

# git checkout bff2883f04c9afa8af78cf259c0c1a9f3f719fd1
fatal: Not a git repository (or any parent up to mount point /powerapps)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

I also tried to download the SIMD as a sub module.
https://github.com/simd-everywhere/simde
And integrated it with mmeseq with no success.

Can you please share a guide on how to install mmesq2 from source with this fix.

Your help is much appreciated.

Thanks.

BR,
Eyal.

**Comment by milot-mirdita** [comment]
We finished the SIMDe integration yesterday. Please use the main MMseqs2 git. I am happy for any feedback since this is fresh from the oven, but please make a new issue.

**Comment by eyalDtau** [comment]
Thanks.
Will check
