### ISSUE TITLE
Clarification of the --dont-shuffle flag for mmseqs2/10-6d92c

### ISSUE THREAD

**Issue by RachelRodgers** [soedinglab/MMseqs2#313]
Hi, I'm looking for clarification on the --dont-shuffle parameter used with the mmseqs createdb command.  The flag can be set to 0 or 1.  Which option prevents shuffling?  Thanks

**Comment by milot-mirdita** [comment]
The parameter was wrongly named. In release 11 it's now called `--shuffle` and 0 means no shuffling and 1 shuffling is enabled. However I would recommend not changing them. They are an internal optimization to help MMseqs2 not lose sensitivity in one specific case.

If a machine does not have enough RAM (or if MPI is used) the target database is split and processed into multiple chunks. If one chunk is too redundant/similar/biased then `--max-seqs` can explode within this one chunk and we might lose good hits. By more or less randomly assigning sequences to any chunk we can prevent this.

This parameter does not affect the order of the results in the result file (i.e. the `.m8` file). This will still pretty much random, as each query is processed by a different thread and the order of results written is thus not deterministic.

If you want a sorted result file I would recommend to use `sort`:
`sort -s -k1,1 result.m8 > result_sorted.m8`

**Comment by RachelRodgers** [comment]
Ok, thanks!
