### ISSUE TITLE
splitdb followed by createindex

### ISSUE THREAD

**Issue by aburzynski** [soedinglab/MMseqs2#314]
## Expected Behavior
mmseqs createindex
finishes in reasonable time on splitted db

## Current Behavior
mmseqs createindex 
gets stucked in seemingly infinite loop after filling the index

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.
The problem is interimttent but simply running the steps to create subdatabases from the manual, followed by createindex. Size of database does not matter much.
## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.
The output is standard, just incomplete.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
11-e1a1c

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
cluster admin compiled the version so self-compiled
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
probably reasonably current gcc...
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
about 120GB RAM  per node, intel CPUs with SS2, not sure about AVX2.
* Operating system and version:
some flavor of linux (debian-style)

**Comment by martin-steinegger** [comment]
Thank you for reporting it. Could you please provide the log and commands to reproduce the issue?

**Comment by j131j131** [comment]
Commands to reproduce follow. First commands on the whole database (these will run OK):
mmseqs createindex db tmp

Now, split the same database, make sub-databases out of the splits and try createindex on any of the splits. This will sometimes work but most of the time will get stucked, as described. The commands:

mmseqs splitdb db db_p --split 2
mmseqs createsubdb db_p_0_2.index db_h db_p_0_2_h

These commands run smoothly and without reporting any problems. The last one is repeated for each split, as per the manual.
The problematic is then:

mmseqs createindex db_p_0_2 tmp

db can be any amino acid database, the number of splits does not matter.
The log is for db==uniref90 and 4 splits. In interactive mode I can see that there is a summary of time taken to fill the index printed after the last "=", not sure why it is not wisible in the log. But no more lines and no progress beyond this step.
HTH
j131

**Comment by martin-steinegger** [comment]
Okay there was an issue in splitdb. I fixed it (https://github.com/soedinglab/MMseqs2/commit/c0dac797b315003814efdbe5e278fd7c4d0b102b). If you use the newest version it should be resolved.

**Comment by aburzynski** [comment]
Solved. Thank You!
