### ISSUE TITLE
cluster command cd-hit-est with cov 0.95 and similarity 0.9

### ISSUE THREAD

**Issue by liuxianghui** [soedinglab/MMseqs2#317]
Dear Sir:
I want to try mmseqs2 cluster as cd-hit-est. 
cd-hit-est -i $CLUSTERS.IN -c 0.95 -T $MC_CPU -M 0 -G 0 -aS 0.9 -g 1 -r 1 -d 0 -o $CLUSTERS.OUT > $CLUSTERS.log 
Please kindly suggest me the corresponding parameter to set for mmseqs cluster and lincluster.
Thanks a lot.
Xianghui

![image](https://user-images.githubusercontent.com/4928483/84471749-8e533880-acb8-11ea-81fa-d84ffe264628.png)

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by martin-steinegger** [comment]
@liuxianghui thank you for asking this question!  

```
cd-hit-est -i $CLUSTERS.IN -c 0.95 -T $MC_CPU -M 0 -G 0 -aS 0.9 -g 1 -r 1 -d 0 -o $CLUSTERS.OUT > $CLUSTERS.log
```


CD-HIT computes in default global sequence identity, while MMseqs2 computes local. Therefore it is not possible to mimic exactly the same behaviour. But since you turn of the the global sequence identity computation, you can get fairly close to CD-HIT's criteria. Here is my suggested parameter mapping.

```
-c 0.95    -> --min-seq-id 0.95 --seq-id-mode 1
-T $MC_CPU -> --threads $MC_CPU
-G 0       -> local alignments is the default of MMseqs2 
-aS 0.9    -> --cov-mode 1 -c 0.9
-g 1       -> it is not possible with MMseqs2 using greedy incremental clustering (needed for --cov-mode 1). However, setcover assigns sequence to the best matching representative in default. 
-r 1       -> MMseqs2 in default considers forward and reverse strand
```

Final command: 

```
mmseqs easy-cluster in.fa clu tmp --min-seq-id 0.95 --seq-id-mode 1 --cov-mode 1 -c 0.9 --threads $MC_CPU
```

**Comment by liuxianghui** [comment]
thank you. That 's great.
