### ISSUE TITLE
TSV ID-line does not follow user-defined parsing rule

### ISSUE THREAD

**Issue by ChrisSzent-Gyorgyi** [soedinglab/MMseqs2#319]
## Expected Behavior--

I am clustering NGS sequences with linclust (using the createdb database) from protein fasta files incorporating multiple named barcodes present in the fasta IDs. Each ID consists of a number to which the barcode name is appended (e.g. 689_dog). The expected output of createtsv is two columns, the first consisting of the IDs of the representative cluster member (689_dog), and the second consisting of IDs of the cluster members, including the barcode name (689_dog, 435_owl, 691_rat, etc.). 

## Current Behavior--
 
The first column is OK. The second column TSV output consists only of the numbers (689, 435, 691, etc.). It is essential that I have the barcode name for further processing of tabular formatted cluster information. Your documentation states that unkown ID formats are parsed to include everything before the first white space. This is not the case here. I have tried other delimiters (e.g. :, -) or no delimiters, and in each case the second column lists only the numbers. BTW, the clustering works very well, as assessed by inspection of output fasta or MSA files.

## Your Environment--

MMseqs2 Version: 11.e1a1c.  installed from Bioconda. Run on Ubuntu 18.04 under Windows10 WSL1 on a 12-thread processor with 48GB RAM.

mmseqs createdb csgtag10.fa csgtagDB
mmseqs linclust csgtagDB csgtagDB_CL DB_clu.tmp --add-self-matches -a 1 --min-seq-id 0.96
mmseqs createtsv csgtagDB csgtagDB_CL csgtagDB_CL_TSV (faulty output)

mmseqs createseqfiledb csgtagDB csgtagDB_CL csgtagDB_CL_SEQ
mmseqs result2flat csgtagDB csgtagDB csgtagDB_CL_SEQ csgtagDB_CL_SEQ.fasta (OK output)
mmseqs result2msa csgtagDB csgtagDB csgtagDB_CL csgtagDB_CL_MSA (OK output)

I hope that this is an easy code fix. mmseqs is great open-source clustering software that can be run efficiently on my desktop. Thanks!

**Comment by milot-mirdita** [comment]
The problem is a bit of a poor choice we made in the past to give `createtsv` a dual purpose to also work for taxonomy assignment output. To produce the correct output you need to pass `csgtagDB` twice, once for query and once for the target side.
```
mmseqs createtsv csgtagDB csgtagDB csgtagDB_CL csgtagDB_CL_TSV
```

**Comment by ChrisSzent-Gyorgyi** [comment]
Thank you for the very prompt response! Your correction of course solved my problem.  I don't see the dual purpose of createtsv as a deficiency at all; I simply missed the the distinction between the command formats. Perhaps adding to the clustering format documentation a line that notes the different createtsv input formats for dual purposes would help avoid confusion.
