### ISSUE TITLE
uniclust database link dead

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#32]
## Expected Behavior
Go to uniclust website (https://uniclust.mmseqs.com/) and click "Download" to download uniclust database from "http://wwwuser.gwdg.de/~compbiol/uniclust/current_release/"

## Current Behavior
The website http://wwwuser.gwdg.de/~compbiol/uniclust/current_release/ complaint:
Access forbidden!
You don't have permission to access the requested directory. There is either no index document or the directory is read-protected.
If you think this is a server error, please contact the webmaster.
Error 403
wwwuser.gwdg.de

## Steps to Reproduce (for bugs)
http://wwwuser.gwdg.de/~compbiol/uniclust/current_release/

**Comment by milot-mirdita** [comment]
Fixed, thanks a lot!
