### ISSUE TITLE
no hit found between two alleles of the same protein

### ISSUE THREAD

**Issue by abrozzi** [soedinglab/MMseqs2#322]
Hi,

when I do the ```mmseq rbh``` between two proteomes of Neisseria gonorrhoea:

1) FA 1090 (https://www.uniprot.org/uniprot/?query=taxonomy:242231)

and

2) WHON (https://www.ncbi.nlm.nih.gov/nuccore/NZ_LT591910.1)

I expect to find these two proteins matching:

```
>Q5F5V7
MKKSLIALTLAALPVAAMADVTLYGTIKAGVETSRSVDHHRAQADRVKTTTEIADLGSKI
GFKGQEDLGNGLKAIWQLEQKAYVSGTLEGWGNRQSFIGLKGGFGKVRVGRLNSVLKDTG
GFNPWEGKSYYLGLSNIAQPEERHVSVRYDSPEFAGFSGSVQYVPNDNSGKNHSESYHAG
FNYKNSGFFVQYAGSYKRHNFTTEKHQVHRLVGGYDHDALYASVAVQQQDAKLAWSDDNS
HNSQTEVATTVAYRFGNVTPRVSYAHGFKGSVYDADNDNTYDQVVVGAEYDFSKRTSALV
SAGWLQRGKGTEKFVATVGGVGLRHKF
```
and

```
>WHON_02200C
MKKSLIALTLAALPVAAMADVTLYGAIKAGVQTYRSVEHTDGKVSKVETGSEIADFGSKI
GFKGQEDLGNGLKAVWQLEQGASVAGTNTGWGNKQSFVGLKGGFGTIRAGSLNSPLKNTG
ANVNAWESGKFTGNVLEISGMAQREHRYLSVRYDSPEFAGFSGSVQYAPKDNSGSNGESY
HVGLNYQNSGFFAQYAGLFQRYGEGTKKIEYDGQTYSIPSLFVEKLQVHRLVGGYDNNAL
YVSVAAQQQDAKLYGAMSGNSHNSQTEVAATAAYRFGNVTPRVSYAHGFKGTVDSANHDN
TYDQVVVGAEYDFSKRTSALVSAGWLQEGKGADKIVSTASAVVLRHKF
```

beacuse they are two alleles of the same protein and if I do a ```blastp``` of  Q5F5V7  against the WHO proteome  WHON_02200C is the first hit with query coverage 100%, identities are 239/349(68%), and positives are 268/349(76%).

## Expected Behavior

Q5F5V7	WHON_02200C	0.675	348	106	0	1	327	1	348	2.700E-168	469

## Current Behavior
no hit found

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

If I do two database with only these two proteins I see the match:

```
mmseq createdb Q5F5V7.fasta por1b
mmseq createdb WHON_02200C por1a

mmseqs rbh por1b por1a AB tmp --cov-mode 0 -c 0.1 -s 7.5 --max-seqs 15 --min-seq-id 0.0 --allow-deletion 1

mmseqs convertalis por1b por1a AB por.tab 
Q5F5V7	WHON_02200C	0.675	348	106	0	1	327	1	348	2.700E-168	469
```

But when i do the ```rbh``` with the entire proteomes even setting lowest parameters :

```
mmseqs rbh proteomeA proteomeB AB tmp --cov-mode 0 -c 0.1 -s 7.5 --max-seqs 15 --min-seq-id 0.0 --allow-deletion 1
mmseqs convertalis proteomeA proteomeB AB por.tab 

grep Q5F5V7 por.tab
NULL
```
these sequences are not listed in the output.

What shall I set to have them matching?

**Comment by milot-mirdita** [comment]
Please remove the `--max-seqs 15 --allow-deletion 1` parameters. `--max-seqs 15` will decimate the sensitivity since basically no hit's are allowed to pass through the prefiltering stage. The deletion parameter is something very specific to profile creation and is unused in this workflow.

**Comment by abrozzi** [comment]
> Please remove the `--max-seqs 15 --allow-deletion 1` parameters. `--max-seqs 15` will decimate the sensitivity since basically no hit's are allowed to pass through the prefiltering stage. The deletion parameter is something very specific to profile creation and is unused in this workflow.

Thank you very much! Solved!
```
ab$ grep Q5F5V7 aln.tab 
Q5F5V7	WHON_02200C	0.675	348	106	0	1	327	1	348	2.042E-150	469
```
I like ```mmseq```.
