### ISSUE TITLE
Wrong citation link

### ISSUE THREAD

**Issue by padix-key** [soedinglab/MMseqs2#326]
The link to the citation of

> Steinegger M and Soeding J. MMseqs2 enables sensitive protein sequence searching for the analysis of massive data sets. Nature Biotechnology, doi: 10.1038/nbt.3988 (2017).

does not point to the article. I think the correct link should be

https://www.nature.com/articles/nbt.3988

but the current link destination is

https://www.nature.com/nbt/journal/vaop/ncurrent/full/nbt.3988.html

leading to the current articles of Nature Biotechnology.

**Comment by milot-mirdita** [comment]
Thanks a lot!
