### ISSUE TITLE
Clustering with different min_seq_id levels produce same exact clusters

### ISSUE THREAD

**Issue by elsherbini** [soedinglab/MMseqs2#33]
I'm likely not understand the --min-seq-id parameter. I am clustering the same database with different min_seq_id levels. The database is comprised of the ORFs of ~800 _Vibrio_ genomes, with 3.5M ORFs. I don't expect the clusters to be the same for 95% and 30% similiarity threshold, many of the genomes in this database have less than 80% nucleotide identity.

## Steps to Reproduce
output from mmseqs  here: https://gist.githubusercontent.com/elsherbini/381bad1c3e340489514502f4e0f62696/raw/00d47064944d11238edb2f49ffd0af0e94e737cb/mmseqs_output

example_fastadb here: https://gist.githubusercontent.com/elsherbini/381bad1c3e340489514502f4e0f62696/raw/00d47064944d11238edb2f49ffd0af0e94e737cb/example_fastadb

```
>mkdir -p ./tmp30
>rm -rf ./tmp30/*
>mkdir -p ./tmp95
>rm -rf ./tmp95/*
>mmseqs createdb fastaDB DB
>mmseqs cluster DB clu_30 ./tmp30 --min-seq-id 30 --max-seqs 100000 -c 0.8
>mmseqs cluster DB clu_95 ./tmp95 --min-seq-id 95 --max-seqs 100000 -c 0.8
>mmseqs createtsv DB DB clu_30 clusters_30.tsv
>mmseqs createtsv DB DB clu_95 clusters_95.tsv
>cmp --silent clusters_30.tsv clusters_95.tsv && echo 'Files Are Identical! || echo 'Files Are Different!'
Files Are Identical!

```
## Your Environment
```
MMseqs Version:                  	b929632f1b419373143faa2a36179c6b964bdfe3
statically compiled
centos6
```

**Comment by milot-mirdita** [comment]
Hi Joseph,

The parameter has to be a float in the range [0,1]. Sorry that the validation regex didn't give out a warning. We'll fix that asap.

**Comment by elsherbini** [comment]
Ah, yes that was it. I had changed it to a number 0-100 when trying to fix some other error and then kept it when it ran successfully.

**Comment by elsherbini** [comment]
sorry, reopening in case you want to close with a commit to update the validation regex.

**Comment by milot-mirdita** [comment]
Merged the validation regexes (we will still have to improve their errors in the future).
