### ISSUE TITLE
no easy-rbh when mmseqs runs in conda environment

### ISSUE THREAD

**Issue by sanyalab** [soedinglab/MMseqs2#332]
Hello,

I have installed mmseqs2 using conda. This has worked ok. The installed package has the following version attributes

`mmseqs2                   11.e1a1c             h2d02072_0    bioconda`

However, when I go to perform an RBH, using easy-rbh as mentioned in the userguide, I get the error below

`Invalid Command: easy-rbh`
`Did you mean "mmseqs easy-search"?`

I think easy-rbh is not updated for conda installation. Please advice what to do.

Thanks
Abhijit

**Comment by milot-mirdita** [comment]
We introduced the module after the 11th release. It will be part of the next one.

You can either use the non "easy" workflow, i.e. something like:
```
mmseqs createdb query.fasta qdb
mmseqs createdb target.fasta tdb
mmseqs rbh qdb tdb res tmp
mmseqs convertalis qdb tdb res res.m8
```

or you can either download precompiled binaries from the latest git commit at https://mmseqs.com/latest or build the code from source.

**Comment by sanyalab** [comment]
I did what you suggested.  It worked well. Thanks.
