### ISSUE TITLE
An amazing mascot

### ISSUE THREAD

**Issue by lmrodriguezr** [soedinglab/MMseqs2#345]
Sorry for spamming the community with a non-issue.

I just wanted to acknowledge how wonderful the mascot of MMseqs is. **Beautiful logo!**

**Comment by milot-mirdita** [comment]
Thanks :) I'll start sending out stickers soonish again when I start going more often to the office (https://twitter.com/thesteinegger/status/1201076220957315074). Drop me an email at milot at mirdita de if you want a set :)
