### ISSUE TITLE
Question about createtaxdb module

### ISSUE THREAD

**Issue by julie-tooi** [soedinglab/MMseqs2#346]
Hi, I run into a little problem. I want to create taxonomy database with only specific proteins.

I do the following:
- download part of Swissprot database with target proteins (COI) in fasta format
- try to create database by mmseqs2
`docker run --rm -v "$(pwd):/app" soedinglab/mmseqs2 mmseqs createdb app/mmseqs_databases/swissprot-part.fasta app/mmseqs_databases/swissprot-part.fasta.DB`

  and next:
  `docker run --rm -v "$(pwd):/app" soedinglab/mmseqs2 mmseqs createtaxdb app/mmseqs_databases/swissprot-part.fasta.DB app/tmp`

This process consumes a lot of time and memory and never succeed. Maybe there is a faster and easier way to do this?
I'll be much appreciate for any help!

mmseqs2 image version - 11

**Comment by milot-mirdita** [comment]
`createtaxdb` does a somewhat inefficient procedure of downloading the rather large idmapping file from uniprot and using that for mapping to taxids. I would recommend to use the `databases` workflow, which doesn't need the idmapping. And then creating a subset of the database with a combination of the `createsubdb` module and the `db.lookup` file.

The `.lookup` file has a mapping of internal database identifiers to accessions. So you can make a list of database identifiers you want to keep and then call `createsubdb`:

```
mmseqs createsubdb subset.tsv swissprot swissprot_subset
```

Alternatively if you want specific taxa in your database you can use the `filtertaxseqdb` module:

```
mmseqs filtertaxseqdb swissprot swissprot_human --taxon-list 9606
```

**Comment by julie-tooi** [comment]
@milot-mirdita, thank you so much!

I 've done the following to achieve the goal:

1. Got target proteins ID from Swissprot database
2. Filtered `swissprot.lookup` file, saved this new one like `subset.tsv`
3. Started `createsubdb` module as you advised
`mmseqs createsubdb subset.tsv swissprot swissprot_subset`
4. (profit) Use new base as taxDB!

I have only one problem with this workflow.
`createsubdb` module seems to create symbolic links to files from original database.
So, when I use it in docker (that starts under [CWL](https://www.commonwl.org/)) - links became invalid after container stop.
I understand, that this solution saves memory, but maybe there is a way to copy original database files?..

**Comment by milot-mirdita** [comment]
Right now, it always creates symbolic links. We could build something to not generate symbolic links, that sounds like a useful improvement.

**Comment by julie-tooi** [comment]
I'll be waiting for this feature! 
Thanks for help! c:
