### ISSUE TITLE
mmseqs enrich cannot create temporary folder (other commands work)

### ISSUE THREAD

**Issue by thackl** [soedinglab/MMseqs2#353]
## Expected Behavior
tmp folder creation should work just as for other commands

## Current Behavior
`mmseqs enrich profileDB UniRef50DB profileEnrichedDB /tmp` fails with 
"Path  does not exist or is not a directory. Cannot create temporary folder ."
It's the same for any tmp location, and it only affects `enrich`. Specifying /tmp with other mmseqs commands works.

## Your Environment
MMseqs Version:  113e3212c137d026e297c7540e1fcd039f6812b1 (latest release)
static (MMseqs2-Linux-SSE4_1.tar.gz),
no AVX2, CentOS Linux 7

**Comment by milot-mirdita** [comment]
Enrich is not yet ready to use. In fact, it's completely broken currently, but we are actively developing it.

**Comment by thackl** [comment]
Ah, ok, good to know :)
