### ISSUE TITLE
addtaxonomy leads to segfault

### ISSUE THREAD

**Issue by linaruss** [soedinglab/MMseqs2#355]
## Expected Behavior
I would like to add the taxonomy information to my results database (search with UniRef90 as query). 

## Current Behavior
I get a segfault (see below)

## Steps to Reproduce (for bugs)
mmseqs search profile_data /home/db/UniRef90 data_uniref90 tmp -s 4 -c 0.9 --min-seq-id 0.8
mmseqs addtaxonomy /home/db/UniRef90 data_uniref90 data_uniref90_taxa

## MMseqs Output (for bugs)
Loading NCBI taxonomy
Loading nodes file ... Done, got 2279399 nodes
Loading merged file ... Done, added 59566 merged nodes.
Loading names file ... Done
Making matrix ... Done
Init RMQ ...Done
Segmentation fault (core dumped)

## Context
I want to add taxonomic information to the db. Eventually I would like to add more metadata, convert to tsv and continue my work in R.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 
12.113e3
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
conda 4.8.5
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
80 CPU, 423.5 GB remaining memory
* Operating system and version:
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-45-generic x86_64)

**Comment by milot-mirdita** [comment]
`addtaxonomy` is broken in the latest release. We fixed the issue in 333cc350af97e735d8321bbe7a68d8a1bf870e7d. 
You can compile from git or use the latest statically compiled binaries from mmseqs.com/latest/

**Comment by linaruss** [comment]
Thanks! Works fine now with the static build (SSE4.1)
