### ISSUE TITLE
Doing a search with profiles

### ISSUE THREAD

**Issue by CuriousTim** [soedinglab/MMseqs2#369]
Hello
I have many (~200 million) multiple sequence alignments in the form of FASTA files that I would like to use as queries against a target dataset of about 6 billion protein sequences in a PSI-BLAST fashion. It is my understanding that I can convert the FASTA file into Stockholm format and then create a profileDB and use the profileDB to search the dataset (after it has been converted with `mmseqs createdb`). I imagine it would be more efficient if it I combined the queries into a queryDB before doing the search, but I can't really figure out how to do this. Would I have to combine all the MSA's into a massive file Stockholm file before creating the queryDB?
Thanks

**Comment by martin-steinegger** [comment]
How do you have the msas currently stored? Do you have a single file for each of the  200million multiple sequence alignments?

**Comment by CuriousTim** [comment]
Yes each alignment is in it's own file.

**Comment by martin-steinegger** [comment]
Wow thats a lot of single files. If all single files are in a folder then you could use `ffindex_build` (https://github.com/soedinglab/ffindex_soedinglab). 

```
ffindex_build msa msa.tmp.index fastaDir
awk '{print NR"\t"$2"\t"$3}' msa.tmp.index > msa.index
awk 'BEGIN { printf("%c%c%c%c",11,0,0,0); exit; }' > msa.dbtype 
mmseqs msa2profile msa profile
```

Alternative you can turn all of them into a single stockholm format and use `convertmsa` to turn it into a `msa` database.
