### ISSUE TITLE
createtaxdb error /createindex.sh: line 47

### ISSUE THREAD

**Issue by fmaumusINRA** [soedinglab/MMseqs2#370]
Hi,

I am trying to create taxdb for uniref100 database downloaded from uniprot.
I did 
mmseqs createdb uniref100.fasta uniref100
and then
mmseqs createtaxdb uniref100 /mnt/Stockage-1To/databases/uniprot
I am getting the following error which I can't solve:
/mnt/Stockage-1To/databases/uniprot/createindex.sh: line 47: 15246 Killed                  awk 'NR == FNR { f[$1] = $2; next } $2 in f { print $1"\t"f[$2] }' "$MAPPINGFILE" "${TAXDBNAME}.lookup" > "${TMP_PATH}/targetDB_mapping"

Could anyone please help me with this?
Thanks a lot!

**Comment by martin-steinegger** [comment]
We have a module that can setup a database up for you. You can use the following command to the a UniRef100 containing taxonomy information. 
```
mmseqs databases UniRef100 uniref100_mmseqsdb tmp
```

**Comment by fmaumusINRA** [comment]
Thank you for your reply.
I have seen that from the documentation and wish I could use it but this module seems not available with my install:
MMseqs2 Version: 4224ae469df44631b5d8e20aa5c7fd9d74d48c0e
I tried to install more a recent version of mmseqs but had kernel issue (FATAL: kernel too old)

**Comment by milot-mirdita** [comment]
Can you try to compile from source? If you have at least GCC 4.9 on your system it should work:
https://github.com/soedinglab/MMseqs2/wiki#compile-from-source-under-linux

The static binaries require some somewhat recent linux kernel, not quite sure where the hard boundary is though.

**Comment by fmaumusINRA** [comment]
Thanks a lot for your reply,

I tried but I am getting assembler error:
/tmp/cccDx2GQ.s: Assembler messages:
/tmp/cccDx2GQ.s:516: Error: no such instruction: `vpbroadcastq %xmm2,%ymm1'
/tmp/cccDx2GQ.s:525: Error: suffix or operands invalid for `vpaddq'
make[2]: *** [lib/cacode/CMakeFiles/cacode.dir/lambda_calculator.cpp.o] Error 1
make[1]: *** [lib/cacode/CMakeFiles/cacode.dir/all] Error 2
make: *** [all] Error 2


I have
cmake version 2.8.12.2
gcc version 5.5.0 (GCC)

Florian

**Comment by milot-mirdita** [comment]
That sounds like the binutils on your system are also very old.

Forcing an SSE4.1 build by calling `cmake` with `cmake -DHAVE_SSE4_1=1 ...` should work.

Alternatively, if you want to profit from the speedup that AVX2 would enable you need to compile a newer binutils on your own somehow and then set the CMAKE variables to the corresponding paths (CMAKE_AR, CMAKE_LINKER, ...).

You don't have conda or linuxbrew on the system? Either option should come with their own set of standard libraries that might be compatible with older systems.

**Comment by milot-mirdita** [comment]
I just checked: The static builds require at least kernel version 3.2.

**Comment by fmaumusINRA** [comment]
Thanks a lot, I understand the problem is my system. Will work on it.
