### ISSUE TITLE
easy-cluster cov-mode 5 doesn't work

### ISSUE THREAD

**Issue by shiraz-shah** [soedinglab/MMseqs2#371]
This one should be easy to fix, Martin!

## Expected Behavior
Help says:
```
--cov-mode INT 0: coverage of query and target
                                 ...
               5: short seq. needs to be at least x% of the other seq. length [5]

```

## Current Behavior
`mmseqs easy-cluster all.faa all tmp --cov-mode 5 -c 0.85 --threads 64
`
exists with error:
Unknown coverage mode 5.

## MMseqs Output (for bugs)
...
```
cluster tmp/10137019871064957114/input tmp/10137019871064957114/clu tmp/10137019871064957114/clu_tmp --max-seqs 20 -c 0.85 --cov-mode 5 --spaced-kmer-mode 1 --threads 64 --alignment-mode 3 -e 0.001 --remove-tmp-files 1 

Set cluster sensitivity to -s 6.000000
Set cluster mode SET COVER
Set cluster iterations to 3
Unknown coverage mode 5.
Error: Search died

```

## Context
Coverage mode 5 is important because it's the only option that ensures that clustered sequences are around same size, which is crucial for determining orthology.

Alternatively if size similarity can be ensured otherwise (as a new option), then this option will be freed up to handle alignment coverage proper. This would also be faster since only similarly sized sequences would be compared.

## Your Environment
MMseqs2 version: 12.113e3
Server: 72 thread Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
OS: Ubuntu Server 18.04

**Comment by milot-mirdita** [comment]
I think cc47254 should fix the issue.
