### ISSUE TITLE
Finding many small peptides in database

### ISSUE THREAD

**Issue by grst** [soedinglab/MMseqs2#373]
Hi all, 

I am trying to search many (30M) small peptides (15aa length) against a database of 
all known protein sequences (BLAST NR). I know that each of the peptides is contained in the database, i.e. 
there should be at least one exact match in the database. I only care about exact or very close matches, 
a very sensitive search should not be necessary. 

However, the result table contains only 1.6M entries. I manually checked a few peptides, and they are indeed included 
in the database (using `grep` on the mmseqs db). 

So far, I have been using `easy-search` using default parameters: 

```bash
mmseqs easy-search \
        query.fa \
        /path/to/nr \
        result.tsv \
        ./tmp
```

Can you guide me what parameters I need to tune to get more hits (including the exact matches) and at the same 
time not compromise the runtime? Also, I don't understand the differences between the `search` and the `map` command. Should I use the latter for my purpose? 

Thanks in advance, 
Gregor 

## Your Environment

* `MMseqs2 Version: 45c4de7f1daefa06b45688195305eadedaea4d97`
* static build with AVX2 support
* `Intel(R) Xeon(R) CPU E5-2699A v4 @ 2.40GHz`, 44 cores, 1TB RAM
* Operating system and version: `CentOS Linux 7 64bit / Linux 3.10.0-1127.13.1.el7.x86_64)`

**Comment by milot-mirdita** [comment]
We have done some testing on finding very short proteins in our SpacePHARER manuscript (https://github.com/soedinglab/spacepharer, https://www.biorxiv.org/content/10.1101/2020.05.15.090266v1).

The parameters we have found to work well are as follows:
`-k 6 --spaced-kmer-pattern 11011101 --seed-sub-mat VTML40.out --gap-open 16 --gap-extend 2 --min-length 9`

We'll eventually add a short fragment search mode to MMseqs2 itself in the form of setting presets or something like that.

**Comment by grst** [comment]
Hi Milot, 

thanks a lot! Two quick follow-ups: 
 * What sensitivity (`-s`) did you use for the short protein search? 
 * In  https://github.com/soedinglab/MMseqs2/issues/91#issuecomment-393926958 you mentioned that  `--comp-bias-corr` and `--exact-kmer-matching` might be helpful to find perfect matches. Does it make sense to set these for my use case?

**Comment by milot-mirdita** [comment]
I think we kept default sensitivity. I assume that sensitivity won't help a lot for short sequence search. The sensitivity parameter controls the number of similar k-mers generated for the double-consecutive-kmer-matching in the prefilter. I assume that using too dissimilar k-mers would result in low scores and e-values. Those would then be rejected anyway.
My assumption might be wrong though, I'd appreciate if you could report what you learn. 

I don't think ` --exact-kmer-matching` would be useful as that would disable the similar k-mer generation completely. 

`--comp-bias-corr 0` and `--mask 0` might be useful though. We suppress false positives homologes with these parameters. However, we didn't benchmark on super short sequences. They might be doing nothing (as both algorithms use a window-approach), they might work correctly or they might be suppressing true useful hits.

**Comment by grst** [comment]
Thanks again! 

Here are my observations: 
 * sensitivity hardly matters (with a restrictive evalue, the results are almost identical. With a permissive evalue, there are slightly more hits with an increased sensitivity) -> I'll stick with `s=1` or `s=2` for speed. 
 * In fact, the evalue seems to be the restrictive factor (which makes sense, given that the peptides are so small and the database so large). With the default evalue of `0.001`, only 26k out of 630k peptides generate a match (all of them *are* contained in the database at least once). 
 * `--comp-bias-corr 0` and `--mask 0` seem to be advantageous. With a permissive evalue of `1e7`, `630467/630487` peptides are found if the both options are set to 0. If they are set to 1, only 594113/630487 peptides are found. On the first sight, the missing peptides do not look particularly low complexity (e.g. `LASLSSVFFFIISFI`, `LKEKLNRNRENSTAT`, `NEGCNSNSSTPRQNT`). 
 * With a sensitivity of `s=1`, `--comp-bias-corr 0` and `--mask 0` and an evalue of `1e7` *almost all* perfect matches are found (`630467/630487`). With `s>=2` and otherwise same settings *all* perfect matches are found. 

---

For now, I will, therefore, use the following settings and see how that works out: 
```bash
--seed-sub-mat VTML40.out 
-s 2 
--comp-bias-corr 0 --mask 0
--gap-open 16 
--gap-extend 2 
--min-length 9 
--spaced-kmer-pattern 11011101 
-e 10000000
-k 6 
```

---


Here are the raw counts of matches. `biascorr = 0` implies `mask = 0`. 
```console
> wc -l *  | sort -n                                                                                                                  
     1283115 AE009951.2_sens1_biascorr0_eval0.001_mmseqs.tsv     
     1283126 AE009951.2_sens4_biascorr0_eval0.001_mmseqs.tsv
     1283235 AE009951.2_sens2_biascorr0_eval0.001_mmseqs.tsv
     1419374 AE009951.2_sens1_biascorr1_eval0.001_mmseqs.tsv
     1419971 AE009951.2_sens2_biascorr1_eval0.001_mmseqs.tsv
     1420095 AE009951.2_sens4_biascorr1_eval0.001_mmseqs.tsv
   155001100 AE009951.2_sens1_biascorr1_eval10000000_mmseqs.tsv
   198438767 AE009951.2_sens2_biascorr1_eval10000000_mmseqs.tsv
   212674670 AE009951.2_sens1_biascorr0_eval10000000_mmseqs.tsv
   237331138 AE009951.2_sens4_biascorr1_eval10000000_mmseqs.tsv
   247063054 AE009951.2_sens2_biascorr0_eval10000000_mmseqs.tsv
   249672852 AE009951.2_sens4_biascorr0_eval10000000_mmseqs.tsv
  1308290497 total
```
