### ISSUE TITLE
Dots output during Smith-Waterman alignments

### ISSUE THREAD

**Issue by hingamp** [soedinglab/MMseqs2#38]
## Expected Behavior
The align command behaves as expected, I would just like to know the quantitative meaning of the dots which are output during the alignment phase, ie is it one dot per 10k queries or something like this, so that I can get an idea of how much longer this phase will require (or if I should kill the job and re-run with lower number of alignments)

## Current Behavior
Dots are output at an unkown rate...

## Steps to Reproduce (for bugs)
mmseqs search [...] -a true

## MMseqs Output (for bugs)
[...]
```
No preload                      false
Early exit                      false
Threads                         12
Verbosity                       3

Init data structures...
Using 12 threads.
Compute score, coverage and sequence id.
Calculation of Smith-Waterman alignments.
.............
```
Many thanks!

**Comment by milot-mirdita** [comment]
Every 10000 it prints one dot. Every 1000000 a new line.

Also please do not add a true/false after switch parameters like -a. It switches the behavior from the default around and does not take parameters.

**Comment by hingamp** [comment]
Perfect, it means I'm nearly there :)
Thanks for the switch correction too!

**Comment by milot-mirdita** [comment]
Glad to help!
