### ISSUE TITLE
easy-taxonomy too slow

### ISSUE THREAD

**Issue by giantoni** [soedinglab/MMseqs2#385]
## Expected Behavior
I am using mmseqs2 for taxonomy assignment against nt database and I was hoping to have a fast result.

## Current Behavior
Mmseqs2 is running too slow, maybe I need help to optimize my command line.  My fasta files have ~300,000 to 1,000,000 sequences.

## Steps to Reproduce (for bugs)
To create the database I used the following commands:
       wget ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
       mkdir taxonomy && tar -xxvf taxdump.tar.gz -C taxonomy
       blastdbcmd -db nt -entry all -outfmt "%a %T" > nt.fna.taxidmapping
       mmseqs createdb nt.fna nt.fnaDB 
       mmseqs createtaxdb nt.fnaDB tmp --ncbi-tax-dump taxonomy/ --tax-mapping-file nt.fna.taxidmapping
       mmseqs easy-taxonomy $fasta ~/Programs/databases/nt.fnaDB $fasta_result tmp --search-type 3 --lca-mode 2 --threads 32

## MMseqs Output (for bugs)
MMseqs2 lof file (the run is not finished yet): https://gist.github.com/giantoni/efc6f62f85119a071992f9a6ad82d7b2

## Context
For now, I just want to separate my metatranscriptome sequences into domain (bacteria, archae, eukaryota)

## Your Environment
I am using a virtual machine with ubuntu 18.04.5 LTS 118 Gb RAM and 32 cores (it does support both AVX2/SSE).
MMseqs2 Version: 12.113e3

**Comment by milot-mirdita** [comment]
Please try the git version of MMseqs2 (either compile from source or download from https://mmseqs.com/latest). The recent changes from the just published preprint or not part of the latest released version yet.

**Comment by giantoni** [comment]
Thank you! I will try again.

**Comment by giantoni** [comment]
On my first try, I had installed mmseqs2 with conda. Then, I used the git version, it was faster ~8 hrs. However, I am thinking if this is expected or if it is still slow. Any thoughts?

**Comment by milot-mirdita** [comment]
Could you post the full log output of MMseqs2?

**Comment by giantoni** [comment]
https://gist.github.com/giantoni/bcfc7aaab79dd8c72ec265c1fcb8b530

**Comment by milot-mirdita** [comment]
Sorry, I didn't notice before. The taxonomy annotations against nucleotide databases are not supported by the new fast search mode yet. Only searches against a protein reference database will benefit from the recent speed-ups.

**Comment by giantoni** [comment]
Many thanks for the help! I will try using a protein reference database.
