### ISSUE TITLE
column definitions for tophit_report from taxonomy easy-search?

### ISSUE THREAD

**Issue by shandley** [soedinglab/MMseqs2#390]
What are the column headers for the tophit_report output file generated by taxonomy easy-search? Specifically, the 4 columns of numbers in between the targetID and the taxonomyID?

Example:

A0A6B9SVR4	6	0.744	1.026	0.419	112596	species	Wolbachia phage WO	d_Viruses;-_Duplodnaviria;-_Heunggongvirae;p_Uroviricota;c_Caudoviricetes;o_Caudovirales;f_Myoviridae;-_unclassified Myoviridae;s_Wolbachia phage WO

What do the values 6, 0.744, 1.026, and 0.419 represent?

**Comment by martin-steinegger** [comment]
Thank you for this question. We have currently not documented this format. Here is the format definition: 

```
(1) Target identifier 
(2) Number of sequences aligning to target
(3) Unique coverage of target uniqueAlignedResidues / totalLength
(4) Target coverage alignedResidues / totalLength
(5) Average sequence identity
```

I will also added it the user guide.

**Comment by shandley** [comment]
Awesome! Many thanks!

S

**Comment by martin-steinegger** [comment]
Here is the respective documentation: https://github.com/soedinglab/MMseqs2/wiki#taxonomy-top-hit-report 

I hope it is okay that I included your example output.

**Comment by shandley** [comment]
Completely OK! We are using mmseqs for a variety of things and are appreciative of your work. Thanks for the quick reply.

S

**Comment by alvanuffelen** [comment]
Would it also be possible to add information to the documentation for the columns in the tophit_aln file generated by easy-taxonomy?

It looks like this:
> SRR9198630.592021	WP_011133888.1	0.738	96	18	0	0	69	0	96	4.230E-38	146
SRR9198630.592021	WP_011133886.1	0.776	188	32	0	0	143	0	188	4.675E-90	300
SRR9198630.592021	WP_052717518.1	0.483	92	20	0	0	39	0	92	1.978E-17	85
SRR9198630.592021	WP_043595263.1	0.946	103	5	0	0	95	0	103	7.833E-59	207

**Comment by alvanuffelen** [comment]
For anyone searching for the answer, I found it in the documentation:

> By default (--format-mode 0), alnRes.tab will contain alignment result in a BLAST tabular result (comparable to -m 8 -outfmt 6) with 12 columns: (1,2) identifiers for query and target sequences/profiles, (3) sequence identity, (4) alignment length, (5) number of mismatches, (6) number of gap openings, (7-8, 9-10) domain start and end-position in query and in target, (11) E-value, and (12) bit score.
