### ISSUE TITLE
Identical sequences are not clustered together?

### ISSUE THREAD

**Issue by s-devos** [soedinglab/MMseqs2#398]
## Expected Behavior
I am trying to cluster small protein fragments (7-25 AA long) with MMseqs2 using the most sensitive settings. As I am only interested in highly similar proteins, I use a high ID threshold and expect lots of clusters.

## Current Behavior
However, the amount of clusters produced exceeds the number of unique sequences present in my data. Further inspection shows that this is because **_100% identical sequences end up in different clusters_**.

## Steps to Reproduce (for bugs)
These are the steps I follow starting from my fasta file and ending in clustering results:

`mmseqs createdb <fasta-file> fasta_in`
`mmseqs cluster fasta_in fasta_clustered tmp --min-seq-id 0.9`

These unexpected results are also found when:
- using a lower `--min-seq_id` of 0.8;
- using the non-standard similarity type `--similarity type` 1;
- using `--cluster-mode` 1

In addition, the amount of clusters produced are fluctuating heavily when the order of sequences in the FASTA file are shuffled beforehand, ranging between 250-450 using the same settings (notably, when only 246 unique sequences are present)

Am I overseeing something? Do I need to reconsider my parameters given the short size of my fragments?

Update: Further inspection revealed that clustering using only a high sensitivity (`-s 7.5`) but no minimum ID threshold removes this bug, but combining this sensitivity with any ID threshold over 0.80 reintroduces the problem.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used : 96d452cb432fc4674991a48952deaf24d1787e77
* Which MMseqs version was used: Statically-compiled
* Operating system and version: linux-gnu; Ubuntu 16.04.6 LTS

**Comment by s-devos** [comment]
And the full output of a clustering run:

Tmp DB_clustered/tmp folder does not exist or is not a directory.
Create dir DB_clustered/tmp
cluster DB_in/shuffle_in DB_clustered/shuffle_cl DB_clustered/tmp --min-seq-id 0.9

MMseqs Version:                         96d452cb432fc4674991a48952deaf24d1787e77
Substitution matrix                     nucl:nucleotide.out,aa:blosum62.out
Seed substitution matrix                nucl:nucleotide.out,aa:VTML80.out
Sensitivity                             4
k-mer length                            0
k-score                                 2147483647
Alphabet size                           nucl:5,aa:21
Max sequence length                     65535
Max results per query                   20
Split database                          0
Split mode                              2
Split memory limit                      0
Coverage threshold                      0.8
Coverage mode                           0
Compositional bias                      1
Diagonal scoring                        true
Exact k-mer matching                    0
Mask residues                           1
Mask lower case residues                0
Minimum diagonal score                  15
Include identical seq. id.              false
Spaced k-mers                           1
Preload mode                            0
Pseudo count a                          1
Pseudo count b                          1.5
Spaced k-mer pattern
Local temporary path
Threads                                 16
Compressed                              0
Verbosity                               3
Add backtrace                           false
Alignment mode                          3
Allow wrapped scoring                   false
E-value threshold                       0.001
Seq. id. threshold                      0.9
Min alignment length                    0
Seq. id. mode                           0
Alternative alignments                  0
Realign hits                            false
Max reject                              2147483647
Max accept                              2147483647
Score bias                              0
Gap open cost                           nucl:5,aa:11
Gap extension cost                      nucl:2,aa:1
Zdrop                                   40
Rescore mode                            0
Remove hits by seq. id. and coverage    false
Sort results                            0
Cluster mode                            0
Max connected component depth           1000
Similarity type                         2
Single step clustering                  false
Cascaded clustering steps               3
Cluster reassign                        false
Remove temporary files                  false
Force restart with latest tmp           false
MPI runner
k-mers per sequence                     21
Scale k-mers per sequence               nucl:0.200,aa:0.000
Adjust k-mer length                     false
Shift hash                              67
Include only extendable                 false
Skip repeating k-mers                   false

Set cluster sensitivity to -s 1.000000
Set cluster mode SET COVER
Set cluster iterations to 1
linclust DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/clu_redundancy DB_clustered/tmp/17526443716087640986/linclust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 16 --compressed 0 -v 3 --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 3 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --alph-size nucl:5,aa:13 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale nucl:0.200,aa:0.000 --adjust-kmer-len 0 --mask 0 --mask-lower-case 0 -k 0 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --rescore-mode 0 --filter-hits 0 --sort-results 0 --remove-tmp-files 0 --force-reuse 0

kmermatcher DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref --sub-mat nucl:nucleotide.out,aa:blosum62.out --alph-size nucl:5,aa:13 --min-seq-id 0.9 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale nucl:0.200,aa:0.000 --adjust-kmer-len 0 --mask 0 --mask-lower-case 0 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 16 --compressed 0 -v 3

kmermatcher DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref --sub-mat nucl:nucleotide.out,aa:blosum62.out --alph-size nucl:5,aa:13 --min-seq-id 0.9 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale nucl:0.200,aa:0.000 --adjust-kmer-len 0 --mask 0 --mask-lower-case 0 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 16 --compressed 0 -v 3

Database size: 1951 type: Aminoacid
Reduced amino acid alphabet: (A S T) (C) (D B N) (E Q Z) (F Y) (G) (H) (I V) (K R) (L J M) (P) (W) (X)

Generate k-mers list for 1 split
[=================================================================] 1.95K 0s 41ms
Sort kmer 0h 0m 0s 1ms
Sort by rep. sequence 0h 0m 0s 0ms
Time for fill: 0h 0m 0s 0ms
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 156ms
rescorediagonal DB_in/shuffle_in DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_rescore1 --sub-mat nucl:nucleotide.out,aa:blosum62.out --rescore-mode 0 --wrapped-scoring 0 --filter-hits 0 -e 0.001 -c 0.8 -a 0 --cov-mode 0 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 16 --compressed 0 -v 3

[==============================================================] ===1.95K 0s 40ms
Time for merging to pref_rescore1: 0h 0m 0s 3ms
Time for processing: 0h 0m 0s 71ms
clust DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_rescore1 DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 16 --compressed 0 -v 3

Clustering mode: Set Cover
[=================================================================] 1.95K 0s 9ms
Sort entries
Find missing connections
Found 1534 new connections.
Reconstruct initial order
[=================================================================] 1.95K 0s 10ms
Add missing connections
[=================================================================] 1.95K 0s 0ms

Time for read in: 0h 0m 0s 95ms
Total time: 0h 0m 0s 137ms

Size of the sequence database: 1951
Size of the alignment database: 1951
Number of clusters: 417

Writing results 0h 0m 0s 1ms
Time for merging to pre_clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 141ms
createsubdb DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/order_redundancy DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/input_step_redundancy -v 3 --subdb-mode 1

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 1ms
createsubdb DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/order_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_filter1 -v 3 --subdb-mode 1

Time for merging to pref_filter1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 1ms
filterdb DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_filter1 DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_filter2 --filter-file DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/order_redundancy --threads 16 --compressed 0 -v 3

Filtering using file(s)
[=================================================================] 417 0s 17ms
Time for merging to pref_filter2: 0h 0m 0s 7ms
Time for processing: 0h 0m 0s 37ms
rescorediagonal DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/input_step_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/input_step_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_filter2 DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_rescore2 --sub-mat nucl:nucleotide.out,aa:blosum62.out --rescore-mode 1 --wrapped-scoring 0 --filter-hits 1 -e 0.001 -c 0.8 -a 0 --cov-mode 0 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 16 --compressed 0 -v 3

[===============================================================] 417 0s 10ms
==Time for merging to pref_rescore2: 0h 0m 0s 5ms
Time for processing: 0h 0m 0s 52ms
align DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/input_step_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/input_step_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pref_rescore2 DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/aln --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 3 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 16 --compressed 0 -v 3

Compute score, coverage and sequence identity
Query database size: 417 type: Aminoacid
Target database size: 417 type: Aminoacid
Calculation of alignments
[=================================================================] 417 0s 37ms
Time for merging to aln: 0h 0m 0s 2ms

615 alignments calculated.
418 sequence pairs passed the thresholds (0.679675 of overall calculated).
1.002398 hits per query sequence.
Time for processing: 0h 0m 0s 81ms
clust DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/input_step_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/aln DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 16 --compressed 0 -v 3

Clustering mode: Set Cover
[=================================================================] 417 0s 4ms
Sort entries
Find missing connections
Found 1 new connections.
Reconstruct initial order
[=================================================================] 417 0s 5ms
Add missing connections
[=================================================================] 417 0s 4ms

Time for read in: 0h 0m 0s 64ms
Total time: 0h 0m 0s 96ms

Size of the sequence database: 417
Size of the alignment database: 417
Number of clusters: 416

Writing results 0h 0m 0s 5ms
Time for merging to clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 107ms
mergeclusters DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/clu_redundancy DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/pre_clust DB_clustered/tmp/17526443716087640986/linclust/4509971647793470292/clust --threads 16 --compressed 0 -v 3

Clustering step 1
[=================================================================] 417 0s 13ms
Clustering step 2
[=================================================================] 416 0s 33ms
Write merged clustering
[=================================================================] 1.95K 0s 45ms
Time for merging to clu_redundancy: 0h 0m 0s 2ms
Time for processing: 0h 0m 0s 69ms
createsubdb DB_clustered/tmp/17526443716087640986/clu_redundancy DB_in/shuffle_in DB_clustered/tmp/17526443716087640986/input_step_redundancy -v 3 --subdb-mode 1

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 1ms
prefilter DB_clustered/tmp/17526443716087640986/input_step_redundancy DB_clustered/tmp/17526443716087640986/input_step_redundancy DB_clustered/tmp/17526443716087640986/pref_step0 --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -s 1 -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seq-len 65535 --max-seqs 20 --split 0 --split-mode 2 --split-memory-limit 0 -c 0.8 --cov-mode 0 --comp-bias-corr 0 --diag-score 0 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 0 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 16 --compressed 0 -v 3

Query database size: 416 type: Aminoacid
Estimated memory consumption: 978M
Target database size: 416 type: Aminoacid
Index table k-mer threshold: 154 at k-mer size 6
Index table: counting k-mers
[=================================================================] 416 0s 41ms
Index table: Masked residues: 0
Index table: fill
[=================================================================] 416 0s 6ms
Index statistics
Entries:          125
DB size:          488 MB
Avg k-mer size:   0.000002
Top 10 k-mers
    XXXXXX      6
    XXXXXX      6
    XXXXXX      4
    XXXXXX      2
    XXXXXX      2
    XXXXXX      2
    XXXXXX      2
    XXXXXX      2
    XXXXXX      2
    XXXXXX      1
Time for index table init: 0h 0m 1s 308ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 154
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 416
Target db start 1 to 416
[=================================================================] 416 0s 20ms

0.116417 k-mers per position
0 DB matches per sequence
0 overflows
0 queries produce too many hits (truncated result)
1 sequences passed prefiltering per query sequence
Time for processing: 0h 0m 2s 35ms
align DB_clustered/tmp/17526443716087640986/input_step_redundancy DB_clustered/tmp/17526443716087640986/input_step_redundancy DB_clustered/tmp/17526443716087640986/pref_step0 DB_clustered/tmp/17526443716087640986/aln_step0 --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 3 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 0 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 16 --compressed 0 -v 3

Compute score, coverage and sequence identity
Query database size: 416 type: Aminoacid
Target database size: 416 type: Aminoacid
Calculation of alignments
[=================================================================] 416 0s 60ms
Time for merging to aln_step0: 0h 0m 0s 1ms

464 alignments calculated.
437 sequence pairs passed the thresholds (0.941810 of overall calculated).
1.050481 hits per query sequence.
Time for processing: 0h 0m 0s 117ms
clust DB_clustered/tmp/17526443716087640986/input_step_redundancy DB_clustered/tmp/17526443716087640986/aln_step0 DB_clustered/tmp/17526443716087640986/clu_step0 --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 16 --compressed 0 -v 3

Clustering mode: Set Cover
[=================================================================] 416 0s 3ms
Sort entries
Find missing connections
Found 1 new connections.
Reconstruct initial order
[=================================================================] 416 0s 0ms
Add missing connections
[=================================================================] 416 0s 0ms

Time for read in: 0h 0m 0s 10ms
Total time: 0h 0m 0s 13ms

Size of the sequence database: 416
Size of the alignment database: 416
Number of clusters: 409

Writing results 0h 0m 0s 2ms
Time for merging to clu_step0: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 18ms
mergeclusters DB_in/shuffle_in DB_clustered/shuffle_cl DB_clustered/tmp/17526443716087640986/clu_redundancy DB_clustered/tmp/17526443716087640986/clu_step0 --threads 16 --compressed 0 -v 3

Clustering step 1
[=================================================================] 416 0s 21ms
Clustering step 2
[=================================================================] 409 0s 47ms
Write merged clustering
[=================================================================] 1.95K 0s 61ms
Time for merging to shuffle_cl: 0h 0m 0s 6ms
Time for processing: 0h 0m 0s 78ms

**Comment by milot-mirdita** [comment]
Can I close this issue in favor of #400? I think the problem here is also the k-mer size as we mentioned in the other issue.
