### ISSUE TITLE
evalue (-e) argument limited by FLOAT type

### ISSUE THREAD

**Issue by didillysquat** [soedinglab/MMseqs2#399]
Firstly, thank you for making and maintaining such a great tool!

## Expected Behavior
When performing a search (or similar function like 'taxonomy'), when providing an evalue of `-e 1e-50`, I would expect to have results filtered according to this evalue.

## Current Behavior
No results are returned/all results are filtered out, even though there should be hits with evalues smaller than 1e-50. (i.e. I can see the hits when I use an `-e 1e-30`)

## Steps to Reproduce (for bugs)
The input files and outputs are here [didi_e_issue_mmseqs.zip](https://github.com/soedinglab/MMseqs2/files/5872895/didi_e_issue_mmseqs.zip)
```
conda install -c bioconda mmseqs2
mmseqs createdb query_fasta.fasta queryDB
mmseqs createdb target_fasta.fasta targetDB
mkdir no_e_cutoff
mkdir 30
mkdir 50
mmseqs search queryDB targetDB no_e_cutoff/resultDB tmp --search-type 3 >&1 | tee no_e_cutoff/no_e_cutoff.out
mmseqs convertalis queryDB targetDB no_e_cutoff/resultDB no_e_cutoff/resultDB_no_e_cutoff.m8 >&1 | tee -a no_e_cutoff/no_e_cutoff.out
rm -r tmp
mmseqs search queryDB targetDB 30/resultDB tmp -e 1e-30 --search-type 3 >&1 | tee 30/30.out
mmseqs convertalis queryDB targetDB 30/resultDB 30/resultDB_30.m8 >&1 | tee -a 30/30.out
rm -r tmp
mmseqs search queryDB targetDB 50/resultDB tmp -e 1e-50 --search-type 3 >&1 | tee 50/50.out
mmseqs convertalis queryDB targetDB 50/resultDB 50/resultDB_50.m8 >&1 | tee -a 50/50.out
```

## MMseqs Output (for bugs)
The outputs are contained in the .zip above.

## Context
I'm fairly certain that the problem is being caused due to the fact that 1e-50 when convereted to float will become 0. Therefore the e value will be set to 0. This means that all results are filtered out of the alignment.

If this is not fixable, it would at least be extremely helpful to have a strong warning message. It took me a day to break this all down and find out what the cause was.

Filter with an e-value of 1e-50 is not uncommon. Especially during taxonomy matches (my actual goal) to for example perform QC on raw seq data.

## Your Environment
I installed using conda:
```
# Name                    Version                   Build  Channel
mmseqs2                   12.113e3             h2d02072_2    bioconda
```
The running server:
```
Architecture:         x86_64
CPU op-mode(s):       32-bit, 64-bit
Byte Order:           Little Endian
CPU(s):               256
On-line CPU(s) list:  0-254
Off-line CPU(s) list: 255
Thread(s) per core:   1
Core(s) per socket:   64
Socket(s):            2
NUMA node(s):         2
Vendor ID:            AuthenticAMD
CPU family:           23
Model:                49
Model name:           AMD EPYC 7702 64-Core Processor
Stepping:             0

NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by milot-mirdita** [comment]
I fixed this issue recently in https://github.com/soedinglab/MMseqs2/issues/379. It will be part of the next release, which should happen somewhat soonish. In the meantime you can use the static precompiled binaries available at https://mmseqs.com/latest/.
