### ISSUE TITLE
Reading compressed fasta files? (suggested feature)

### ISSUE THREAD

**Issue by gaboentropy** [soedinglab/MMseqs2#40]
## Expected Behavior
I expect mmseqs to also read files compressed with bzip2

## Current Behavior
I was pleasantly surprised to find that mmseqs reads files compressed with gzip.

## Context
I accidentally used a gripped file and the dabtabase was created all right. I tried a zipped file and it did not work.

## Your Environment
* Git commit used: 405193375c0144c47305f4dfab2f7937e448fa1c
* Which MMseqs version was used: self-compiled

**Comment by milot-mirdita** [comment]
I am quite busy with other higher priority tasks currently.

If you have have time and are interested in the issue look for HAVE_ZLIB in:
./CMakeLists.txt (find_package(BZip2))
./src/commons/KSeqWrapper.cpp

Otherwise I will add this in a couple weeks.

Best regards,
Milot

**Comment by gaboentropy** [comment]
Thanks. There no hurry about it.

Gabriel Moreno-Hagelsieb
Department of Biology
Wilfrid Laurier University
75 University Ave W
Waterloo, ON
Canada N2L 3C5
(519)884-0710 ext 2364

--Unix is user friendly, just rather selective about its friends

**Comment by milot-mirdita** [comment]
Implemented in #8631ca0e527360651cf7871ddd4b8629f48bf430

Thank you for the feature request!

**Comment by martin-steinegger** [comment]
We support bz2 now.

**Comment by gaboentropy** [comment]
Thanks!

Gabriel Moreno-Hagelsieb
Department of Biology
Wilfrid Laurier University
75 University Ave W
Waterloo, ON
Canada N2L 3C5
(519)884-0710 ext 2364

--Unix is user friendly, just rather selective about its friends

On Thu, Aug 10, 2017 at 4:56 AM, Martin Steinegger <notifications@github.com
