### ISSUE TITLE
README and LICENSE files should include libs

### ISSUE THREAD

**Issue by joelb123** [soedinglab/MMseqs2#402]
More minor packaging stuff.

Your LICENCE.md should be spelled LICENSE.md for standardization purposes.  It's one of those weird things about English that "licence" is the verb form only.  I note that your license file has some unwanted material after the end of terms and conditions that includes templated items in brackets.

Please include the license and readme files of the included libraries (ips4o, microtar, simde, tinyexpr, and zstd) in the top-level directory with names like README.zstd.md.  Symlinks are fine.  

It is customary and good practice to put a notice of the included libraries in your README.

**Comment by martin-steinegger** [comment]
Thank you for explaining it. We renamed the file!

**Comment by joelb123** [comment]
Thanks, the library page is helpful.  However, putting licenses in the wiki won't satisfy any license requirements that the copyright be included, such as with an MIT license.  In some cases those licenses are internal to the file, in other cases not.
