### ISSUE TITLE
some included libs are missing provenances and licenses

### ISSUE THREAD

**Issue by joelb123** [soedinglab/MMseqs2#403]
It's good practice to indicate versions and origins (repository URLs and web sites) of included libraries.  Several libraries are missing license files, which may violate the usage terms in many cases.

**Comment by martin-steinegger** [comment]
Thank you for looking into it. What libraries are missing a license?

**Comment by milot-mirdita** [comment]
Which library is missing licenses? I think everything not developed by us should be prefixed by the respective license. I would strongly recommend to not split away any library we bundle (except maybe zstd, as Debian is doing). We occasionally change stuff (e.g. I rewrote microtar completely, to fit our needs, maybe I should move it to `commons` now).\

We could add a module (`mmseqs licenses`?) that lists all libraries used and their licenses, or maintain our own version of debian's copyright file.

**Comment by joelb123** [comment]
Adding a module doesn't meet most common license terms that require redistribution of copyrights.  You know your libraries better than I do, but the directories in lib/ that are missing licenses and readmes are alp/, cacode/, gzstream/, ksw2/,  simd/, and xxhash/.  Libs that you have edited, like microtar, should have a readme indicating you have done so.

**Comment by milot-mirdita** [comment]
I added missing the missing licenses. `lib/simd` is developed by us, it's just at this location for convenience as we occasionally sync it with HHsuite (https://github.com/soedinglab/hh-suite).

**Comment by joelb123** [comment]
Thanks, closing this.
