### ISSUE TITLE
Feature request: split fasta cluster output into separate files

### ISSUE THREAD

**Issue by joelb123** [soedinglab/MMseqs2#406]
Again, this is an easy script, but one might as well ask for what one wants and have it done centrally.

A typical downstream use of the clusters is to do multple-sequence-alignment calculations and then look at some stats on those such as the fraction missing and fraction parsimony-informative.   This means making a directory to hold a fasta of each cluster and then running one's favorite MSA/treebuilder algorithm on it (MUSCLE, in my case), then doing some descriptive statistics on them. 

It would be nice if optionally mmseqs would do this splitting on its own.  Nicer still if it would spawn the MSA/treebuilder with a user-specified set of arguments and do the summary stat calculation with output to TSV.  I note that MUSCLE is public-domain and pretty fast.

**Comment by milot-mirdita** [comment]
You probably want to use `mmseqs apply` for this purpose (see: https://github.com/soedinglab/hh-suite/blob/master/scripts/createdb.sh#L37).

We don't have a module to unpack a database into separate files. You can use `ffindex_unpack` from the HH-suite. MMseqs2 could use the same functionality.

**Comment by joelb123** [comment]
I'm not asking how to write a script to do this splitting; doing so takes only a few minutes.  I'm pointing out that the splitting is a workflow much more common than the default.  Instead of having a sizeable fraction of your users have to each cough up their own scripts, this would make a fine option.

**Comment by milot-mirdita** [comment]
I added a module `unpackdb` for this purpose.

**Comment by joelb123** [comment]
Thanks, I'll use it!
