### ISSUE TITLE
small database for testing

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#407]
As of mmseqs  12.113e3, the amino acid databases available via `mmseqs databases` are:

```
  Name                	Type      	Taxonomy	Url
- UniRef100           	Aminoacid 	     yes	https://www.uniprot.org/help/uniref
- UniRef90            	Aminoacid 	     yes	https://www.uniprot.org/help/uniref
- UniRef50            	Aminoacid 	     yes	https://www.uniprot.org/help/uniref
- UniProtKB           	Aminoacid 	     yes	https://www.uniprot.org/help/uniprotkb
- UniProtKB/TrEMBL    	Aminoacid 	     yes	https://www.uniprot.org/help/uniprotkb
- UniProtKB/Swiss-Prot	Aminoacid 	     yes	https://uniprot.org
- NR                  	Aminoacid 	     yes	https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA
```

...and I believe that all are quite large and take a long time to download and construct. It would be helpful for testing purposes to have a small database (or databases), especially a small subset database of each `UniRef[0-9]+` database.

**Comment by milot-mirdita** [comment]
The PDB and UniProtKB/Swiss-Prot are pretty small, if you want a smaller database you could use the `examples/DB.fasta` file, which is a subset of Uniprot we generated or benchmarking some time ago.

**Comment by nick-youngblut** [comment]
> smaller database you could use the examples/DB.fasta file

I hoping for a small DB with a taxonomy. 

UniProtKB should work
