### ISSUE TITLE
CDD database

### ISSUE THREAD

**Issue by fmaumusINRA** [soedinglab/MMseqs2#410]
Hello,

Doing some protein work, among the databases proposed for download, would it be possible to add a profile library corresponding to the CDD database? I need to search for protein domains.

Thanks,
Florian

**Comment by milot-mirdita** [comment]
This should work:
```
wget https://ftp.ncbi.nih.gov/pub/mmdb/cdd/fasta.tar.gz
mmseqs tar2db fasta.tar.gz cddmsa
mmseqs apply cddmsa cddmsa_wo_cons -- awk '/^>/ { i++ } i > 1 { print; }'
awk 'BEGIN { printf("%c%c%c%c",11,0,0,0); exit; }' > cddmsa_wo_cons 
mmseqs msa2profile cddmsa_wo_cons cdd --match-mode 1

mmseqs easy-search QUERY.fasta cdd res.m8 tmp
```

Could you try out if this performs approximately how you expect it to? If this works well I can add it to the `databases` workflow.

**Comment by fmaumusINRA** [comment]
It works like a charm, thanks a lot.
I think it is a very useful database and, I don't know why, I can find pfam domains that were missed when using the pfam database (both seed & full).

**Comment by milot-mirdita** [comment]
Could you share one query that finds a PFAM match in CDD and not in PFAM(-full/seed)?

The PFAM databases are essentially built with the same procedure as described above.

**Comment by fmaumusINRA** [comment]
Sorry I think that was was the case when using pfam as querydb, experimenting...
Anyway, thanks a lot for providing CDD database!!

**Comment by milot-mirdita** [comment]
I added the CDD to the `databases` downloader. Thanks for the suggestion!
