### ISSUE TITLE
Creating database from fasta file instead of a previously formatted blastDB?

### ISSUE THREAD

**Issue by shandley** [soedinglab/MMseqs2#412]
Do you have a recommendation for creating a mmseqs nt database from a collection of fasta files? The instructions for making a mmseqs2 database from a blastdb are clear.

My guess is that one could just take a collection of fasta files and convert them to a blastdb using makeblastdb, but I worry about the other things that creating a blastdb will do (repeat masking).

As a more specific example, we would like to make a 'taxonomy aware' version of an mmseqs database for all NCBI Virus RefSeq genomes from NCBI Assembly (https://www.ncbi.nlm.nih.gov/assembly). So would you recommend we just download them and make a blastdb of these or is there an approach more amenable to the use of mmseqs?

Thanks,

Scott

**Comment by milot-mirdita** [comment]
Adding taxonomy support for the NT is on my todo list, but it is a bit more involved and I haven't had time for it yet.

If you are using the assembly files with their original file names you could use something like this (didn't test it, only collected  what I think might work from previous fragments i've written):
```
ls -1 assemblies \
    | awk 'match($1, /^(([A-Z]{3})_([0-9]{3})([0-9]{3})([0-9]{3})\.[0-9]+_.+?)_genomic/, a) { print "https://ftp.ncbi.nlm.nih.gov/genomes/all/"a[2]"/"a[3]"/"a[4]"/"a[5]"/"a[1]"/"a[1]"_assembly_stats.txt"; }' > assembly_urls.tsv
mkdir tmp
cd tmp
aria2c --input-file=../assembly_urls.tsv
for i in *; do awk '/^# Taxid:/ { gsub(/_assembly_stats.txt/, "", FILENAME); print FILENAME"\t"$3; exit; }' $i; done > ../assembly_taxid_mapping.tsv
cd ..
mmseqs createdb assemblies/* refseqdb
mmseqs createtaxdb refseqdb tmp --tax-mapping-file assembly_taxid_mapping.tsv --tax-mapping-mode 1
```

**Comment by shandley** [comment]
Thanks milot-mirdita!

I will take a closer look, but think I may have come up with a solution using bbtools gi2taxid to encode the taxonomy IDs in the fasta headers:

A simple for-do loop script like this:

`for i in *.fna.gz; do
	F=`basename $i .fna.gz`;

gi2taxid.sh in=${i} out=${F}_taxID.fna.gz \
	server=t \
	taxpath=${TAXPATH} \
	-Xmx64g \
	pigz=6 unpigz=t bgzip=t preferbgzip=t zl=9;

done;`

This isn't exactly full taxonomy support, but I am then able to pull the taxIDs from either the tophit or lca reports and can analyze them downstream using something like taxonkit (https://bioinf.shenwei.me/taxonkit/). Not as optimal as built in taxonomy support within mmseqs2 and running LCA will be an additional challenge, but it is a partial and useful solution for us.

Thanks! Look forward to seeing full NT taxonomy support!
