### ISSUE TITLE
taxonomy --majority function unavailable in latest version of mmseqs

### ISSUE THREAD

**Issue by ana-bugseq** [soedinglab/MMseqs2#413]
I am trying to use the taxonomy --majority parameter for taxonomic assignment to metagenomic contigs described in this paper, https://www.biorxiv.org/content/10.1101/2020.11.27.401018v1.full.pdf, but it seems like the functionality hasn't been updated yet! When will this function be made available? Thank you!

**Comment by milot-mirdita** [comment]
We are in the process of preparing release 13. This will include all the recent changes in a stable release. It should be done in the next few days/this week.

In the meantime you can use the static precompiled binaries downloadable from https://mmseqs.com/latest.
