### ISSUE TITLE
Segmentation Fault when using --cluster-reassign

### ISSUE THREAD

**Issue by sanyalab** [soedinglab/MMseqs2#415]
## Expected Behavior
Successful Completion
## Current Behavior
Error Thrown despite the Temp directory having over 100GB space.
## Steps to Reproduce (for bugs)
1. Install MMSeqs2 under Conda: DONE NO ERRORS
`conda install -c conda-forge -c bioconda mmseqs2`

2. Create Sequence DB: DONE NO ERRORS
`mmseqs createdb AllPeptide.fasta AllPeptide_DB --dbtype 1 --write-lookup 1`

3. Run MMSeqs2 cluster module with --cluster-reassign: ERROR
`mmseqs cluster AllPeptide_DB ConnComp_DB $TMPDIR --mask 0 -c 0.8 --cov-mode 0 -e 0.01 --max-seqs 50 --min-seq-id 0.9 --cluster-mode 1 --similarity-type 1 --cluster-steps 5 --cluster-reassign`

4. Run MMSeqs2 cluster module with --cluster-reassign and -a: ERROR
`mmseqs cluster AllPeptide_DB ConnComp_DB $TMPDIR --mask 0 -c 0.8 --cov-mode 0 -e 0.01 --max-seqs 50 --min-seq-id 0.9 --cluster-mode 1 --similarity-type 1 --cluster-steps 5 --cluster-reassign -a`

5. Run MMSeqs2 cluster module **without** --cluster-reassign and -a: SUCCESS
`mmseqs cluster AllPeptide_DB ConnComp_DB $TMPDIR --mask 0 -c 0.8 --cov-mode 0 -e 0.01 --max-seqs 50 --min-seq-id 0.9 --cluster-mode 1 --similarity-type 1 --cluster-steps 5`

## MMseqs Output (for bugs)
`m3131Alignment format is not supported!`
`31mmAlignment format is not supported!`
`Alignment format is not supported!`
`lignment format is not supported!ted!d_pref_swaped_aln: 0h 0m 1s 254ms`
`mm*** glibc detected *** mmseqs: free(): corrupted unsorted chunks: 0x00007f148cd69ce0Alignment format is not supported!
3931m39/ngsprod/sanyalab/TEMP/9163273558071586774/cascaded_clustering.sh: line 240: 25359 Segmentation fault      (core dumped) "$MMSEQS" clust "${SOURCE}" "${TMP_PATH}/clu_accepted_plus_wrong_plus_single" "${2}" ${TMP}4 of overall calculated).`
`Error: Clustering step 4 diednce.`

## Context
I am trying to do the following
1) cluster 2 million intra-species protein sequences that are at least over 80% identical to their homologs
2) Generate descriptive statistics for each cluster
3) Use the clusters to create HMMs

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 12.113e3
* Which MMseqs version was used (Conda install): 12.113e3
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): CPU Model: Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz, supports sse4_1, sse4_2, MEM Free: 200GB, MEM Total: 256GB
* Operating system and version: Red Hat 4.4.7-18, gcc version 4.4.7 20120313

**Comment by milot-mirdita** [comment]
I think I fixed the same issue recently. You can either compile from git or download the latest statically compiled binaries from mmseqs.com/latest. The fix will be part of the next release that will be available very soon.

**Comment by sanyalab** [comment]
Yes!! I saw that. I think its not part of the conda release yet. 

Best Regards
Abhijit
