### ISSUE TITLE
Hi. I created a Pfam database (Pfam-A.full) and did the search of my sequences. Everything went well. My question is: what columns can I get using convertalis? (with --format-output). Thank you!

### ISSUE THREAD

**Issue by jorgeibarracaballero** [soedinglab/MMseqs2#425]
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by milot-mirdita** [comment]
We describe all the fields in the wiki:
https://github.com/soedinglab/MMseqs2/wiki#custom-alignment-format-with-convertalis

**Comment by jorgeibarracaballero** [comment]
I will review it carefully. Thank you for your reply and thank you for this great program.
