### ISSUE TITLE
Wrong Type Database Error

### ISSUE THREAD

**Issue by nabney** [soedinglab/MMseqs2#429]
After clustering, I needed to convert the files back into FASTA files for future uses. However, when I use the commands: 
mmseqs createseqfiledb DB clu clu_seq
mmseqs result2flat DB DB clu_seq clu_seq.fasta

I get the error that my DB file is a Generic file type instead of a Amino Acid file type. I converted my original database file from FASTA to text using this command:
mmseqs createdb examples/DB.fasta DB

I attached my original FASTA database as well as resulting file after the previous command. I appreciate any help for solving this error!
[Archive.zip](https://github.com/soedinglab/MMseqs2/files/6223963/Archive.zip)

**Comment by milot-mirdita** [comment]
What MMseqs2 release are you using? I remember fixing this bug previously and can't reproduce it in release 13 anymore.

**Comment by nabney** [comment]
How do you check the release of MMSeqs2 that I am using? I just recently downloaded it a couple weeks ago.

**Comment by milot-mirdita** [comment]
It will show you when you execute `mmseqs version`.

**Comment by nabney** [comment]
fb39ca1ee88313974f285740faa856ea68509193. this is the version that I get; I am not sure if this is correct or I downloaded something wrong.

**Comment by nabney** [comment]
Sorry this is the version:
fb39ca1ee88313974f285740faa856ea68509193

**Comment by milot-mirdita** [comment]
Could you list all steps you did in order you executed them and also copy paste the corresponding output on the terminal here? We fixed this issue with `result2flat` quite a while ago and it shouldn't happen in the version you downloaded.

**Comment by nabney** [comment]
Here you go: 
mmseqs createdb seqdump.fasta (seqdump.fasta is my original database of proteins)
mkdir tmp
mmseqs cluster seqdumpDB DB_cluster tmp --min-seq-id 0.7 (after this I get the list of cluster files and they have the file name like DB_cluster.#)
mmseqs createseqfiledb  seqdumpDB DB_cluster DB_clu_seq

After this last command, I get this error:
MMseqs Version:	fb39ca1ee88313974f285740faa856ea68509193
Min sequences	1
Max sequences	2147483647
HH format    	false
Preload mode 	0
Threads      	8
Compressed   	0
Verbosity    	3

Input database "seqdumpDB" has the wrong type (Generic)
Allowed input:
- Index
- Nucleotide
- Profile
- Aminoacid

Hopefully this helps; I appreciate the help!

**Comment by milot-mirdita** [comment]
I can't reproduce the issue, seems something corrupted the seqdumpDB (or more specifically `seqdumpDB.dbtype`) along the way and everything is now in a bad/weird state. Does this happen if you start over in a clean folder only containing the fasta file?

**Comment by nabney** [comment]
Ahh yess it worked when I created a new folder; I am not sure what happened before. Thank you so much!

**Comment by nabney** [comment]
Sorry I have another question. If I only want a FASTA file with a specific cluster, then how do I do this? When I run the code to create a FASTA file, it seems to recombine all the clusters into one sequence, however, I want only one cluster for a file.

**Comment by milot-mirdita** [comment]
I am not 100% sure what you want, from here there are multiple ways you can go for downstream processing:

* You can use `unpackdb` to split a database into separate files
* You can use `createsubdb` to get only a smaller subset based on a list of database keys 
* You can use `view` to extract a single entry

For `createsubdb` and `view` you need to give the internal database identifiers (keys). You can get those from the `seqdumpDB.lookup` file. You can grep for your FASTA accession in the second column and take the number from the first column for `view`'s `--id-list` parameter or `createsubdbs` first input file.

`unpackdb` will name the files based on this internal identifier, if no `.lookup` file is present. You can copy/symlink the `.lookup` file from the `seqdumpDB` to the `DB_clu_seq` to get better names, as these share the same database keys:
```
ln -s seqdumpDB.lookup DB_clu_seq.lookup
mmseqs unpackdb DB_clu_seq unpackdir
````

**Comment by milot-mirdita** [comment]
I improved `createsubdb` and `view` in 14a3dce2ae6319caf671e81d91a41c1292401285 to also directly parse FASTA accessions if a `.lookup` file is present, if the `--id-mode 1` parameter is given.

**Comment by nabney** [comment]
So I am basically trying to get the FASTA file of one cluster, however, when I do the code to get the FASTA file all the sequences combine again into one file instead of by clusters. So when I use the unpackdb, will I get the FASTA files of the individual clusters?

**Comment by milot-mirdita** [comment]
Yes. Though you'll get individual files for all the individual clusters, which might be a lot. The other two options I listed are more useful if you only want one or a subset of results.

**Comment by nabney** [comment]
Okay, I am really new to this software and using Terminal commands. How would I use createsubdb? I am not really sure what keys are and how to specify them for the one cluster that I want.

**Comment by Louis-MG** [comment]
Hello, I am facing the same issue. My command was:
`mmseqs createdb --dbtype 2 /mnt/projects_tn01/KMER_analysis/DATA/kmdiff/case_kmers.fasta ./test/DB`

The command completes with the ouptut saying it is a Nucleotide database. I then build  an other database of the same type with:
`mmseqs createdb --dbtype 2 /mnt/software/ncbi/genome_library/2022/all_seq.fna.gz /mnt/scratch/LM/ncbi_database/`
Again, the ouptut confirms it is a Nucleotide database.

Then I want to `search`:
`mmseqs search /mnt/scratch/LM/test/ /mnt/scratch/LM/ncbi_database/ /mnt/scratch/LM/results/ /mnt/scratch/LM/tmp`
And I get ;
```
Input database "/mnt/scratch/LM/test/" has the wrong type (Generic)
Allowed input:
- Index
- Nucleotide
- Profile
- Aminoacid
```
[log.txt](https://github.com/soedinglab/MMseqs2/files/11021316/log.txt) for he output without the error. I tried several time to rebuild the input database, including deleting the entire folder and changing its name just in case.

**Comment by marade** [comment]
I downloaded all NCBI phages and was able to trigger this error with them.

MMseqs Version: 15.6f452

mmseqs search --search-type 3 -c 0.5 -v 3 --cov-mode 2 --alignment-mode 3 --threads 8 --headers-split-mode 1 --sort-results 1 --max-seq-len 10000000 --db-load-mode 2 /home/ubuntu/NCBI-phages-20231219.fa /home/ubuntu/allDB /home/ubuntu/mmseqs-results.tab /tmp/tmpbvzkw379

Input database "/home/ubuntu/NCBI-phages-20231219.fa" has the wrong type (Generic)
Allowed input:
- Index
- Nucleotide
- Profile
- Aminoacid

**Comment by milot-mirdita** [comment]
You have to call `easy-search` to pass a FASTA files into MMseqs2. Or you first call `createdb` on your FASTA file manually and then pass the database into `search`, as it only takes database input. Please open a new issue in GitHub if things are still not working.
