### ISSUE TITLE
.index file misplaced upon createdb ?

### ISSUE THREAD

**Issue by gjoni** [soedinglab/MMseqs2#43]
Runnig ./mmseqs createdb mydb.fasta tmp/db creates a db.index file in the tmp/ folder, but adding the '--max-seq-len 14000' option results in 14000.index file in the current folder (not the tmp/ folder) and no tmp/db.index file. Is this the expected behavior? I'm using the latest mmseqs version.

**Comment by milot-mirdita** [comment]
I just reviewed the code and will fix the issue tomorrow. As a work around until tomorrow, place the --max-seq-len parameter as the first argument after the createdb command, then it should still work.

Sorry for the inconvenience.

**Comment by gjoni** [comment]
Thanks a lot! Works perfectly.

**Comment by martin-steinegger** [comment]
Fixed the issue.

**Comment by gjoni** [comment]
Thank you so much!
