### ISSUE TITLE
mmseqs easy-taxonomy lca_tsv output column names

### ISSUE THREAD

**Issue by shandley** [soedinglab/MMseqs2#435]
It looks like with the newest release that the default output from mmseqs easy-taxonomy has changed a bit. There are now 4 additional numeric columns that were not there by default in prior releases. I assume this has something to do with the new contig annotation settings.

Can you let me know what the column headers are? Specifically for columns 5-8 in the example below (the 5, 1, 1, 1.000)?

207026	2420051	species	Yasminevirus sp. GU-2018	5	1	1	1.000	Viruses;unknown;unknown;unknown;unknown;unknown;Yasminevirus sp. GU-2018	d_Viruses;-_unclassified viruses;s_Yasminevirus sp. GU-2018

**Comment by milot-mirdita** [comment]
I expanded the "Taxonomy Output and TSV" section in the wiki with a description:
https://github.com/soedinglab/MMseqs2/wiki#taxonomy-output-and-tsv

There is also a small tutorial for the contig based taxonomy annotation here:
https://github.com/soedinglab/MMseqs2/wiki/Tutorials#contig-taxonomic-assignment-and-auxiliary-modules
