### ISSUE TITLE
How does mmseqs taxonomy work for paired-end reads?

### ISSUE THREAD

**Issue by ShangjinTan** [soedinglab/MMseqs2#436]
I want to use mmseqs taxonomy to assign a taxonomy for paired-end reads against the silva database.

mmseqs first converts a fasta file into sequence DB. Do I need to do assignment independently for the forward and reverse reads? Is there a way to congregate the results based on the forward and reverse ends and get a consensus one?

**Comment by milot-mirdita** [comment]
MMseqs2 doesn't have an inbuilt module to merge paired-end reads.
You could use plass `mergereads` module which has integrated [flash](http://ccb.jhu.edu/software/FLASH/index.shtml), to merge paired-end reads. The output from plass can be directly consumed by the MMseqs2 taxonomy.

**Comment by milot-mirdita** [comment]
The plass `mergereads` module would merge all pairs that can be merged and leave all unmerged `pairs` alone to be classified separately. If you don't want that, then you have to build some custom post processing logic on the result tsv flies.

**Comment by 2061574124** [comment]
> We don't want to merge paired-end reads as only a very small portion of reads are overlapped. We hope to assign a taxon to each pair of reads. Is it possible?↳

hello, have you fix it? I have the same problem as you, with very little overlap data. How did you do the align and quantification? thanks
