### ISSUE TITLE
Discrepancy between msaconvert documentation and usage help

### ISSUE THREAD

**Issue by etowahadams** [soedinglab/MMseqs2#437]
The documentation says in the ["Convert an external MSA into a profile"](https://github.com/soedinglab/mmseqs2/wiki#convert-an-external-msa-into-a-profile) that 

> It is possible to use MSAs in FASTA, A3M and CA3M format. 

But when I try using an MSA in fasta format to build a profile database and search with it, for example
```
mmseqs convertmsa myMSA.fasta msaDb
mmseqs msa2profile msaDb profileDB
mmseqs search profileDB targetDB hitDB tmp --start-sens 1 --sens-steps 3 -s 7
```
I get 
```
Input tmp/17085414453924316708/pref_0 does not exist
Error: Alignment died
```
Looking at `mmseqs convertmsa -h`, it says `usage: mmseqs convertmsa <i:msaFile.sto[.gz]> <o:msaDB> [options]`. I tried using a stockholm formatted msa and did the same the above, and was able to search with no errors. Is the documentation wrong about FASTA MSAs being able to be used, or is there some issue? Or perhaps I am mistaken by what the documentation is trying to say.

**Comment by milot-mirdita** [comment]
I think the profile queries and iterative increasing sensitivity searches `--start-sens 1 --sens-steps 3` might be currently incompatible. We have a bit of a combinatorial explosion of different search modes and not every mode works with every other mode correctly.
