### ISSUE TITLE
Question: why does mmseqs taxonomy not calculate LCA?

### ISSUE THREAD

**Issue by ms-gx** [soedinglab/MMseqs2#439]
Why does `mmseqs taxonomy` not calculate LCA for a query but the best hit?

**Comment by milot-mirdita** [comment]
You mean for nucl-nucl taxonomy searches? The current implementation of the algorithm doesn't support it yet and we haven't had the resources to implement it yet. The various protein based searches all use LCA.

**Comment by ms-gx** [comment]
Sorry, yes I meant the nucl-nucl obviously.
Ah, OK, I was wondering if there is a technical reason, because I could not think of any ;)
Case closed...

**Comment by milot-mirdita** [comment]
There is a technical reason: Our nucleotide alignment algorithm needs one seeding point to align. This seeding point is not correctly propagated for the LCA in the nucl-nucl taxonomy. It's a bit tricky to solve, but it would mostly need a few days of thinking and work.
