### ISSUE TITLE
Profile searching VOGDB?

### ISSUE THREAD

**Issue by rmFlynn** [soedinglab/MMseqs2#440]
Thank you for all the work you have put into MMseqs2. I hope it can support my use case.

## Desired outcome

I would like to make a MMseqs2 target profile database from VOGDB data however I can't find a path to do so. To do this I attempted to process the latest release of the VOGDB files available [here](http://vogdb.org/download)  specifically I am using the MSA files in [vog.raw_algs.tar.gz](http://fileshare.csb.univie.ac.at/vog/latest/vog.raw_algs.tar.gz). Contained in  vog.raw_algs.tar.gz are many FASTA formatted MSA files with each file being named after the VOG ID but not containing it in the text of the files. I have tried using a similar workflow to that of the PFAM format and several other approaches to no avail.

Here are some of my observations on the situation: 

 VOGDB is not in stockholm format, unlike PFAM, and convertmsa does not support it. However, instead of raising an error  convertmsa produces empty files without alerting the user.

To skip preprocessing and run msa2profile command directly requires the datatype and index files to exist, and I don't know how to generate these correctly from the data at hand.

Making a database from the MSA data is not a problem and the database can be searched without issue except that VOG IDs are not transferred from the file name. It seems that the problem is only with generating profiles.

## Reproduction / Examples

Example  where convertmsa creates files, but they are empty and there is no error.

```BASH
# make temp folders
mkdir vog
cd vog
mkdir mmseqs
mkdir temp
wget http://fileshare.csb.univie.ac.at/vog/latest/vog.raw_algs.tar.gz
# tar xzf vog.raw_algs.tar.gz
# gzip -c *.msa > vog.raw_algs.gz
cd ..
mmseqs convertmsa vog/vog.raw_algs.tar.gz vog/temp/converted
```

Files are created in vog/temp with the converted prefix, but they are all empty.

The only path to an MMseqs2 profile that has any success is to convert the MSA files first into HH-suite compatible hmm files and then to use the hmm to profile pipeline.

```BASH
# make make temp folders
mkdir vog
mkdir hhmake
mkdir hhmake/vog
cd vog
mkdir mmseqs
mkdir temp
wget http://fileshare.csb.univie.ac.at/vog/latest/vog.raw_algs.tar.gz
wget http://fileshare.csb.univie.ac.at/vog/latest/vog.raw_algs.tar.gz.md5
md5sum -c vog.raw_algs.tar.gz.md5
tar xzf vog.raw_algs.tar.gz
cd ..
 
for f in vog/*.msa;
do
     hhmake -M 50 -i $f -o hhmake/$f.hhm
done
ffindex_build vog/mmseqs/hmm vog/mmseqs/hmm.index hhmake/vog/
mmseqs convertprofiledb vog/mmseqs/hmm vog/mmseqs/profile
```
However, when using a search command against vog/mmseqs/profile only returns individual genes not profiles.

## Environment

MMseqs Version: 4e23d5f1d13a435c7b6c9406137ed68ce297e0fc
MMseqs source: conda install -c conda-forge -c bioconda mmseqs2
OS: NAME=CentOS Linux 7
CPUs: Intel(R) Xeon(R) Gold 5118
Threads/core: 96

**Comment by milot-mirdita** [comment]
Essentially you want something like this (`tar2db` is the most useful module for this use case):
```
wget http://fileshare.csb.univie.ac.at/vog/latest/vog.raw_algs.tar.gz
mmseqs tar2db vog.raw_algs.tar.gz vog_msa --output-dbtype 11 --tar-include ".*msa$"
mmseqs msa2profile vog_msa vog --match-mode 1
mmseqs easy-search QUERY.fasta vog res.m8 tmp
```

You can find the various tricks we use for all the other databases here: https://github.com/soedinglab/MMseqs2/blob/master/data/workflow/databases.sh

I could also include VOGDB in the default `databases` command as it seems quite useful.

**Comment by milot-mirdita** [comment]
I also added VOGDB to the database downloader  (https://github.com/soedinglab/MMseqs2/commit/7be4fca96e84fb3ef56c598967ae6a6925500b9c).

You will be able to download and setup a VOGDB profile database with only one line now:
```
mmseqs databases VOGDB vog tmp
mmseqs easy-search QUERY.fasta vog res.m8 tmp
```

**Comment by rmFlynn** [comment]
Wow! That makes my life super easy, thank you! Really a fantastic tool you have made, I hope lots of people get to benefit from VOGDB being included.

**Comment by milot-mirdita** [comment]
If you have any other databases that you feel should be included, please let us know.

**Comment by rmFlynn** [comment]
Will do

**Comment by rmFlynn** [comment]
I could use your help again. I am trying to replace hmmer in my work follow with mmseqs, but I am not getting the same results.
I am trying to replace:

```BASH
hmmsearch --domtblout vogdb_output  vogdb_loc query_faa
```

With some form of:
```BASH
mmseqs search query_db vogdb_profile vogdb_output tmp_dir -k 5 -s 7.5
# then convertalis
```

However, when I match output on qId I see that before filtering I have 300 records that are in hmmer output and not in mmseqs output. After filtering the number jumps to  699.

There are also some mmseqs hits that are not matched in hmmer about 129, but I am not as worried about extra information.

In the end there are 1247 hmmer hits and only 749 mmseqs hits after filtering. 

To be clear there are 1533 mmseqs hits before filtering but the 300 hits that were in the filtered hmmer hits are not in the unfiltered mmseqs hits.

Any Ideas you have will be much appreciated.

**Comment by milot-mirdita** [comment]
I think our default E-value cutoff is much stricter than HMMer's, you could try increasing that. Something like `-e 10`, however I wouldn't expect our E-values to correspond exactly to the HMMer ones. I think HMMer and MMseqs2 compute them quite differently.

**Comment by milot-mirdita** [comment]
Also increasing the k-mer size to `-k 6` will be a bit beneficial, at the cost of a much higher RAM use. However, VOGDB is pretty tiny anyway so RAM use doesn't matter much anyway.
