### ISSUE TITLE
Memory requirements of clusthash

### ISSUE THREAD

**Issue by CuriousTim** [soedinglab/MMseqs2#442]
What are the memory requirements for `clusthash`? I am trying to redundancy filter a database of about 1.4 billion proteins using `clusthash` and when running the program, I get the message
```
Can not touch 271995225098 into main memory
```
It then continues to run for ~30 mins and then progress just halts. I left it running for 10 hours with no change in progress. I first tried running with 64G memory and then 128G memory with the same results. Do all the sequences in the database need to fit into memory for `clusthash` to work? Would I be better off running `linclust` with `-c 100`?

Thank you

**Comment by milot-mirdita** [comment]
`linclust` implements a splitting mechanism and can process datasets larger than the available memory size. `clusthash` doesn't have a similar mechanism (it's also older and most unused since we have the `linclust` algorithm).

**Comment by CuriousTim** [comment]
Ah I see. I will use `linclust`
