### ISSUE TITLE
Alignment Step Died

### ISSUE THREAD

**Issue by xinhuang66** [soedinglab/MMseqs2#449]
## Expected Behavior

[Peptide_seqs.fasta.txt](https://github.com/soedinglab/MMseqs2/files/6430389/Peptide_seqs.fasta.txt)
I tried to use the attached fasta file to do the easy-cluster using the following command:
mmseqs easy-cluster Peptide_seqs.fasta Peptide_seqs_clu tmp --min-seq-id 0.5 -c 0.8 --cov-mode 1

## Current Behavior
Alignment step died
Linclust died
Search died

## Steps to Reproduce (for bugs)
mmseqs easy-cluster Peptide_seqs.fasta Peptide_seqs_clu tmp --min-seq-id 0.5 -c 0.8 --cov-mode 1

## MMseqs Output (for bugs)
[test_MMseqs2.out.txt](https://github.com/soedinglab/MMseqs2/files/6430406/test_MMseqs2.out.txt)

## Your Environment
Install MMseqs2 on an HPC with conda install -c conda-forge -c bioconda mmseqs2, which was successful.

Thank you!

**Comment by milot-mirdita** [comment]
I found one memory issue when giving only extremely short sequences to MMseqs2.
You can probably work around this issue in release 13 by adding one fake sequence that is longer than 20 AA residues in the input file. 

I would also recommend to add the following parameters `-k 5 --spaced-kmer-mode 0 --comp-bias-corr 0 --mask 0` for clustering such extremely short sequences. You might also want to add `-e inf` as E-values are essentially meaningless for such short sequences. In this case you would only cluster based on seq. id. and coverage.

**Comment by xinhuang66** [comment]
Thank you for this tip, it worked! But I get many clusters, 997 representative sequences, is there a way to reduce the number of clusters? We are trying to identify general patterns/motifs from these sequences. The command I used is:
mmseqs easy-cluster Peptide_seqs.mod.fasta Peptide_seqs_clu tmp -e inf -k 5 --spaced-kmer-mode 0 --comp-bias-corr 0 --mask 0 --min-ungapped-score 0 --min-seq-id 0.0 -c 0.0 --cov-mode 1

Thank you!

> I found one memory issue when giving only extremely short sequences to MMseqs2.
> You can probably work around this issue in release 13 by adding one fake sequence that is longer than 20 AA residues to the input file.
> 
> I would also recommend to use the following parameters `-k 5 --spaced-kmer-mode 0 --comp-bias-corr 0 --mask 0` for clustering such extremely short sequences. You might also want to add `-e inf` as E-values are essentially meaningless for such short sequences. In this case you would only cluster based on seq. id. and coverage.

**Comment by milot-mirdita** [comment]
I wouldn't turn of all three of min seq. id., coverage and e-value. You should keep a high coverage, a low sequence identity also doesn't really make a lot of sense as there isn't really enough homology signal to tell if two of these fragments belong together.

I don't think you can reduce the number of representatives much more, without clustering basically random sequences with each other.

**Comment by xinhuang66** [comment]
Thank you very much, I appreciate the advice!
