### ISSUE TITLE
How does mmseqs evalue compare to blastp evalue?

### ISSUE THREAD

**Issue by mooreryan** [soedinglab/MMseqs2#45]
Just a quick question about mmseqs evalues. In the current version of the preprint, there is a line about how the mmseqs evalue compares to blastp evalue...

> E ≤ 0.1 corresponds to the same false discovery rate as E ≤ 0.01 in BLAST.

If you run mmseqs search and blastp on the same queries against the same database, is the mmseqs evalue always going to be equivalent to 10 times the blastp evalue?

**Comment by martin-steinegger** [comment]
The E-value is not guaranteed to be always higher than the one of blastp. It always depends on the composition bias of the specific sequence. 

You can see in Figure S. 8 how the false discovery rates of MMseqs2 and blastp relate to each other and choose an acceptable e-value cutoff based on that. You can see the accuracy of blastp and MMseqs2 compared in Figure S. 8.

If you need a comparable e-value you would need to turn off the compsition bias correction of Blast (--comp_based_stats 0) and MMseqs2 (--comp-bias-corr 0) .

**Comment by mooreryan** [comment]
Thanks, I will check out that figure. 

Just to clarify, if I turn the comp bias corr setting to 0 for both blastp and mmseqs, then will the evalues be the same or will the mmseqs evalue be 10 times the blastp evalue like in the preprint?

**Comment by martin-steinegger** [comment]
The e-value should behave the same MMseqs2~Blastp but I would not recommend it.

**Comment by mooreryan** [comment]
Thanks, that clears it up.
