### ISSUE TITLE
What are the column headers in the .tsv after using 'mmseqs createtsv' ?

### ISSUE THREAD

**Issue by drelo** [soedinglab/MMseqs2#458]
## Expected Behavior

I am following this tutorial https://github.com/soedinglab/MMseqs2/wiki/Tutorials#metagenomic-pathogen-detection , specially the **'Annotating the catalogue'** section, I followed this to search for Pfam domains in several genomes. The pipeline looks great and worked fine. From the tutorial, I understood column 5 is the e-value, the first 2 are self-explanatory and I am also familiar with the blast output but in this case I got 11 columns and I am not fully sure this tsv is similar. 

My question is can I have a list of all the columns so I can parse it accordingly? Thanks 
  
Sorry if this info is elsewhere but I couldn't find it I also searched here the issues but I couldn't find it.

## Current Behavior

I got a tsv file with rows like this

`genome1        PF20143.1       100     0.412   3.484E-23       156     291     298     73      205     259`

## MMseqs Output (for bugs)

I followed this tutorial https://github.com/soedinglab/MMseqs2/wiki/Tutorials#metagenomic-pathogen-detection no bug or anomaly in this case.

## Context

Sorry if the question is similar to https://github.com/soedinglab/MMseqs2/issues/434 but I don't even have the list of column headers in this cae. 

## Your Environment

MMseqs2 Version: 13.45111
Ubuntu 20.04

**Comment by martin-steinegger** [comment]
Thank you for asking. This should be the order: 
`Query Target Score Seq.Id. E-value qStartPos qEndPos qLen tStartPos tEndPos tLen`

**Comment by drelo** [comment]
Thank you!
