### ISSUE TITLE
createtsv for linclust output

### ISSUE THREAD

**Issue by HaimAshk** [soedinglab/MMseqs2#459]
Hi,

In the output format of createtsv for linclust results, it seems that the sequence id of the cluster members is not printed correctly.

I would be very thankful for your help!
Haim  

## Expected Behavior
my FASTA headers are SV_xxxx and this is what I expect to see also as the cluster members column (2nd column)
```
SV_178977       SV_19100
SV_178977       SV_32607
SV_178977       SV_116547
```

## Current Behavior
Instead I only get a numerical identifier of the sequence:

```
SV_178977       19100
SV_178977       32607
SV_178977       116547
```

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

mmseqs linclust input_fasta.mmseqdb.gz input_fasta.mmseqdb_fasta.mmseqdb.linclust /tmp/
mmseqs createtsv input_fasta.mmseqdb.gz input_fasta.mmseqdb.linclust input_fasta.mmseqdb.linclust.tsv

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

```
MMseqs Version:                 	1f302134aa1c6c7c4e2b9da272fd26af33860780
First sequence as representative	false
Target column                   	1
Add full header                 	false
Sequence source                 	0
Database output                 	false
Threads                         	256
Compressed                      	0
Verbosity                       	3
```

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 1f302134aa1c6c7c4e2b9da272fd26af33860780

**Comment by martin-steinegger** [comment]
I tried to cluster sequences with the header you mentioned but can not reproduce the issue. 
Is it possible for you to share the file, exact command line and log? Thank you so much.

**Comment by HaimAshk** [comment]
Thanks for the quick response!

Here is sample of the data together with the commands I have run and the logs. I hope I have not missed anything:

```
mmseqs createdb --compressed 1 /tmp/global2/hashkenazy/sample.fa /tmp/global2/hashkenazy/sample.fa.mmseqdb.gz > /tmp/global2/hashkenazy/sample.fa.mmseqdb.std 2>&1

mmseqs linclust /tmp/global2/hashkenazy/sample.fa.mmseqdb.gz /tmp/global2/hashkenazy/sample.fa.mmseqdb.linclust /tmp/hahskenazy/   1>  /tmp/global2/hashkenazy/sample.fa.mmseqdb.linclust.std 2>&1

mmseqs createtsv /tmp/global2/hashkenazy/sample.fa.mmseqdb.gz /tmp/global2/hashkenazy/sample.fa.mmseqdb.linclust /tmp/global2/hashkenazy/sample.fa.mmseqdb.linclust.tsv > /tmp/global2/hashkenazy/sample.fa.mmseqdb.linclust /tmp/global2/hashkenazy/sample.fa.mmseqdb.linclust.tsv.std 2>&1
```

[MMSEQ_linclust_example.tar.gz](https://github.com/soedinglab/MMseqs2/files/6647982/MMSEQ_linclust_example.tar.gz)

Thanks for the help!
Haim

**Comment by milot-mirdita** [comment]
I think you need to specify `/tmp/global2/hashkenazy/sample.fa.mmseqdb.gz` twice, as it's both the query and target database for `createtsv`. Sorry this is a bit confusing when used together with the clustering workflows :/

**Comment by HaimAshk** [comment]
Great, thanks a lot! 
Specifying both the query and target database indeed solved the problem, sorry for the bother :-)
