### ISSUE TITLE
Stable versions

### ISSUE THREAD

**Issue by meren** [soedinglab/MMseqs2#46]
Thanks for the awesome open-source tool.

I can't find any tags except "[vNatBiotech](https://github.com/soedinglab/MMseqs2/tree/vNatBiotech)". I was wondering whether there is interest in making a release for a stable version (with a numerical version), which may help users and developers.

Thanks!

Best wishes,

**Comment by milot-mirdita** [comment]
Dear Murat,

We consider every commit, that has passed the regression pipeline on CodeShip as stable (see the codeship badge). 

However we are aware about policies at many institutes to only allow using tagged stable software versions. We are currently preparing a pipeline to easily produce stable tagged releases on all relevant platforms (GitHub Releases, Homebrew, Linuxbrew, Bioconda, Docker, etc.).

We hope to have this done soon. Until then please use either the latest static build (that one has always passed the regression pipeline) or the latest regression pipeline passing commit.

Best regards,
Milot

**Comment by meren** [comment]
The need for official tags is more for reproducibility than trusting the stability of the master or to address policy issues. Indeed a git commit ID could address the need for reproducibility, but I am not sure if the society is ready to see that in a paper ;)

I understand that this will be resolved, so thanks for that.

Best wishes,

**Comment by milot-mirdita** [comment]
We did tag a commit id for the Nature Biotech publication through [Zenodo](https://zenodo.org/record/840208).

We had many important improvements since then though, on speed, user experience and also new modules.

**Comment by josemduarte** [comment]
Agree with @meren . Releases and tags are important mostly for reproducibility, and also for developers to announce milestones to users. Additionally when using [semantic versioning](http://semver.org/) tags have very specific meanings that can help users a lot.

**Comment by martin-steinegger** [comment]
We just created the first release after vNatBiotech. The version numbering system is: running nummber followed by the five frist chars of release commit hash. (e.g. 1-c7a89, 2-f1307, ...).
