### ISSUE TITLE
problem with the output of mmseqs: target is not only target name (Expected Behavior: chr1; Current Behavior: chr1_342 )

### ISSUE THREAD

**Issue by RitschMuriel** [soedinglab/MMseqs2#470]
Task: I am looking for amino acid sequences in a genome (nucleotide level) with mmseqs. Equivalent to tblastn.

in the output of mmseqs (mmseqs convertalis) I get not only the target in the column but also  an underscore and a number (example: expected:chr1 → chr1_123)
Start and stop positions are never greater than 66,000.

I think the genome sequence has been split into different parts. How can I reassign the position of the parts to the complete genome?
Or did I build the index for the genome incorrectly?
What have I done wrong

Code (MMseqs2 Version: 6.f5a1c):

REF=path to fasta genom
FASTA=path to fasta query
RES=path to output folder
QRY=path to query (folder)
TARGET=
TARGET_TMP=
RES_TMP=

BN=$(basename "$FASTA")
NAME=$(echo $BN| cut -d '.' -f1)
QUERY="$QRY""$NAME"_db
RESULT="$RES""$NAME"_result
RESULT_blastformat="$RES""$NAME"_result_mmseq.csv 

mmseqs createdb "$REF" "$TARGET"
mmseqs createindex "$TARGET" "$TARGET_TMP"

mmseqs createdb "$FASTA" "$QUERY"
mmseqs search --threads 12 "$QUERY" "$TARGET" "$RESULT" "$RES_TMP" -a
mmseqs convertalis --threads 12 "$QUERY" "$TARGET" "$RESULT" "$RESULT_blastformat"

**Comment by milot-mirdita** [comment]
Could you please try again with the latest MMseqs2 version? I think we resolved some of the weirdness with overlong sequences a while ago.

**Comment by milot-mirdita** [comment]
What conda command did you use to install MMseqs2?
Conda just offered me a brand-new installation of MMseqs2 with the same ancient version 6.f5a1c.

**Comment by RitschMuriel** [comment]
With the new version the error is fixed. Thanks
