### ISSUE TITLE
_nodes.dmp, _merged.dmp and _delnodes.dmp for custom taxdb

### ISSUE THREAD

**Issue by fmaumusINRA** [soedinglab/MMseqs2#474]
I am having a problem with the taxonomy module, probably linked to building a taxdb by myself.

I have created the taxdb for proteins I want to be all classified simply as "virus" (taxid 10239)

head NEWDB_all_70_rep.fasta 
>DB_2501651210_000001|2501651824|2501735350
MSITKFINKRKYMDFSTFESASQALSLSIYFLVGAAAAIAFVQGFKSN

mmseqs createdb NEWDB_all_70_rep.fasta NEWDB_70_rep
awk '{print $2 "\t10239"}' NEWDB_70_rep.lookup > taxidmapping
mkdir ncbi-taxdump && cd ncbi-taxdump
wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
tar xzvf taxdump.tar.gz
cd -
mmseqs createtaxdb NEWDB_70_rep /tmp --ncbi-tax-dump ncbi-taxdump/ --tax-mapping-file taxidmapping

I am then able to use this taxdb with taxonomy module

I then used concatdbs to add my taxdb to U90

mmseqs concatdbs ../NEWDB/NEWDB_70_rep U90 U90andNEWDB70 --threads 1
mmseqs concatdbs ../NEWDB/NEWDB_70_rep_h U90_h U90andNEWDB70_h --threads 1
nohup mmseqs createindex U90andNEWDB70 /tmp/ &
mmseqs createtaxdb U90andNEWDB70 /tmp

I am then able to use this concat taxdb with taxonomy module

I then applied taxonomy filter to the concatdb

nohup mmseqs filtertaxseqdb U90andNEWDB70 U90andNEWDB70_nostrepto --taxon-list '!35493' 1>& filter.out &

In this case, I get the following error:
Input taxonomy database "../../../U90andNEWDB70_nostrepto" is missing files:
- ../../../U90andNEWDB70_nostrepto_nodes.dmp
- ../../../U90andNEWDB70_nostrepto_names.dmp
- ../../../U90andNEWDB70_nostrepto_merged.dmp

In fact, I'm finding out that there were none of the _nodes.dmp, _merged.dmp and _delnodes.dmp files created for the new taxdb and the concatdb. Maybe that's where the problem comes from?

Could you kindly help figuring out what's wrong with this? 

Thanks a lot for your help,
Florian

**Comment by milot-mirdita** [comment]
I think I know what the bug. Creating the following symlink manually should fix the db:
```
ln -s U90andNEWDB70_taxonomy U90andNEWDB70_nostrepto_taxonomy
```

The dmp files are turned into a binary format (`_taxonomy`) that can be loaded nearly instantly. `filtertaxseqdb` doesn't create the correct symlink for this file.

**Comment by fmaumusINRA** [comment]
Thank you so much for your prompt reply.
the symlink fixed it all.

Florian

**Comment by fmaumusINRA** [comment]
Hi again,
I was wondering if you have implemented this commit in the last version? Thanks
https://github.com/soedinglab/MMseqs2/commit/56f7685b563b4a20720f0cc5c1224d9cf1706f5c
