### ISSUE TITLE
mmseqs search not returning proteins present in database as top hits

### ISSUE THREAD

**Issue by geronimp** [soedinglab/MMseqs2#48]
Hello,

First, thank you for the fantastic work on mmseqs2, its super fast! I think I’ve come across an issue where exact matches arent being detected by the mmseqs2 search algorithm. 

## Expected Behavior
Exact matches hit eachother

## Current Behavior
When a subset of sequences from a reference database are searched against the database, a surprisingly large fraction of proteins do not return themselves as their best hit. The severity of the problem depends on the database size, in the example below 2.8% of proteins do not hit themselves, but when I came across this issue I was generating a larger database where using the same test 31% of proteins were not hitting themselves at all. This result does not change if sensitivity is increased to the maximum (-s 8.5). I find this behaviour concerning given you’d expect an exact matches to be returned in a relatively small database

## Steps to Reproduce (for bugs)
If I grab 10 random genomes ([genome_proteins.tar.gz](https://github.com/soedinglab/MMseqs2/files/1444710/genome_proteins.tar.gz)) from NCBI and create a reference database using their proteins, and use one of these genomes as the query database:
```
cat *faa > pooled.faa

mmseqs createdb \
	pooled.faa \
	reference_DB

mmseqs createdb \
	GCF_000352185.1_protein.faa \
	query_DB
```
Then search query against the reference using default settings, and convert this to a blast-like output:
```
mkdir tmp 

mmseqs search \
	query_DB \
	reference_DB \
	result_DB \
	tmp 

mmseqs convertalis \
	query_DB \
	reference_DB \
	result_DB \
	result_DB.m8
```

and grab the top hit for each protein (i.e. first listed):

```
for i in `cat result_DB.m8 | awk '{print $1}' | uniq `
	do grep -m 1 -w ^$i result_DB.m8
done > result_DB.top_hits.m8
```
Then, when we check the results in R:
```
library('data.table')
d = fread('result_DB.top_hits.m8')
# Check if query matches the reference sequence ID
d$self_match = d$V1 == d$V2

# Check percentage of total hits do not hit themselves?
round(table(d$self) / nrow(d) * 100, 1)
                                                                                                                                            
FALSE  TRUE                                                                                                                                 
  2.8  97.2  

# What is the average %ID of each group?
mean(d[self_match == TRUE]$V3)                                                                                                            
[1] 0.9556934                                                                                                                               
mean(d[self_match == FALSE]$V3)                                                                                                           
[1] 0.7872742  
```

## Your Environment
Im using mmseqs2 version 2-2.d96d2469

I'm also wondering why very few of the proteins that do hit themselves have a %ID of <100%?

Thank you for any help you can provide,

Joel

**Comment by martin-steinegger** [comment]
@geronimp Thanks a lot for this great report!

MMseqs2 finds the identical hits but it does not always place them first. We sort hits by e-value but the e-value has a numerical issues. If scores are too high than the e-value can become 0. I have added a fix. MMseqs2 sorts now by e-value & score (https://github.com/soedinglab/MMseqs2/commit/d7efa6fdce8b93c77367f78dd50938313991ced2).

Another problem is that for example `NZ_KB733011.1_3357` has a lot of 100% identical hits. It is not possible sort the "right" hit `NZ_KB733011.1_3357` first.  
```
NZ_KB733011.1_3357      NZ_KB733011.1_201       1.000   130     0       0       1       131     1       131     2.25E-80        259
NZ_KB733011.1_3357      NZ_KB733011.1_2104      1.000   130     0       0       1       131     1       131     2.25E-80        259
NZ_KB733011.1_3357      NZ_KB733011.1_2421      1.000   130     0       0       1       131     1       131     2.25E-80        259
NZ_KB733011.1_3357      NZ_KB733011.1_2561      1.000   130     0       0       1       131     1       131     2.25E-80        259
NZ_KB733011.1_3357      NZ_KB733011.1_3357      1.000   130     0       0       1       131     1       131     2.25E-80        259
```

The sequence identity issue can be solved by using `-a` (As @milot-mirdita mentioned)

Just a remark. You can extract the first hit of each result also with mmseqs. 

```
mmseqs filterdb result_DB result_DB.firsthit --extract-lines 1
mmseqs convertalis query_DB reference_DB result_DB.firsthit result_DB.firsthit.m8
```

**Comment by martin-steinegger** [comment]
@geronimp Please reopen this issue if the you still encounter similiar problems.

**Comment by geronimp** [comment]
Hi Martin and Milot,

Fantastic, thank you both for your great answers and all the information - the evalue and score sorting is helpful.

Thanks again,

Joel
