### ISSUE TITLE
libatomic not found

### ISSUE THREAD

**Issue by daron-m-standley** [soedinglab/MMseqs2#480]
## Expected Behavior
Hi, I expected that this library would come with a/the conda environment. It's not a problem to install the library myself. I just wanted to point out that this happened.  

## Current Behavior
When I run a test:

`homedir/miniconda2/pkgs/mmseqs2-13.45111-h95f258a_1/bin/mmseqs easy-cluster fasta/test.fasta clusterRes tmp --min-seq-id 0.5 -c 0.8 --cov-mode 1`

I immediately get this error:

`homedir/miniconda2/pkgs/mmseqs2-13.45111-h95f258a_1/bin/mmseqs: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

## Steps to Reproduce (for bugs)
I tried it twice on two different compute nodes

## MMseqs Output (for bugs)
 No other output 
 
## Context
I installed with conda into a new environment, following the README

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
Here is my conda environment:
```
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py39hf3d152e_0
  - gawk=5.1.0=h7f98852_0
  - gettext=0.19.8.1=h0b5b191_1005
  - hhsuite=3.3.0=py39pl5262h8f06ca0_2
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgomp=11.1.0=hc902ee8_8
  - libidn2=2.3.2=h7f98852_0
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libunistring=0.9.10=h7f98852_0
  - mmseqs2=13.45111=h95f258a_1
  - ncurses=6.2=h58526e2_4
  - openssl=1.1.1k=h7f98852_0
  - perl=5.26.2=h36c2ea0_1008
  - pip=21.2.3=pyhd8ed1ab_0
  - python=3.9.6=h49503c6_1_cpython
  - python_abi=3.9=2_cp39
  - readline=8.1=h46c0cb4_0
  - setuptools=49.6.0=py39hf3d152e_3
  - sqlite=3.36.0=h9cd32fc_0
  - tk=8.6.10=h21135ba_1
  - tzdata=2021a=he74cb21_1
  - wget=1.20.3=ha56f1ee_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
```

* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
mmseqs2=13.45111=h95f258a_1

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
conda 
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
cmake version 2.8.12.2

* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
```
 uname -a | grep x86_64
Linux 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
* Operating system and version:
CentOS Linux release 7.5.1804 (Core)

**Comment by milot-mirdita** [comment]
Thank you! That's quite surprising that this can happen. We'll have to investigate whats going on.

**Comment by milot-mirdita** [comment]
What conda command did you use to install mmseqs2? `libatomic` is provided by `libgcc-ng` which is installed.

**Comment by daron-m-standley** [comment]
Thanks for your reply. I just used
```
conda install -c conda-forge -c bioconda mmseqs2
```
I thought everything installed properly, but perhaps I missed an error...

**Comment by daron-m-standley** [comment]
you're correct!
`homedir/miniconda2/pkgs/libgcc-ng-7.2.0-h7cc24e2_2/lib/libatomic.so.1`
exists
So maybe I just need to do something with my path. Will take another look tomorrow!

**Comment by milot-mirdita** [comment]
You should use the binary placed in the conda `bin` directory. I don't think calling binaries from inside the `pkg` directory is supported.

**Comment by daron-m-standley** [comment]
Ah! How right you are. So it was all my fault. I hope I didn't waste too much of your time.

**Comment by milot-mirdita** [comment]
No worries, happy to have double checked that all dependencies are in order :)

**Comment by losted-star** [comment]
> 



> Ah! How right you are. So it was all my fault. I hope I didn't waste too much of your time.

I met the same problem with you, can you show the details step by step how to fix up the issue, thanks!

**Comment by milot-mirdita** [comment]
How did you install mmseqs and how do you call it?

**Comment by losted-star** [comment]
I have solved this problem by using mmseqs in bin dir of Anaconda, thanks a lot!
