### ISSUE TITLE
convert mmseqs2 result to a3m

### ISSUE THREAD

**Issue by hartrials** [soedinglab/MMseqs2#482]
Steps:

1. Use `mmseqs search` to generate MSA.
2. Use `mmseqs2 result2msa` to convert the mmseqs2 result to hhsuite compatible database.
3. Use `hhblits` to generate `a3m` format result.

My question:
Are there any parameters in mmseqs2 that can directly obtain the MSA in `a3m` format?

**Comment by milot-mirdita** [comment]
There is a3m output support in my fork (`--msa-format-mode 5/6`): 
https://github.com/milot-mirdita/mmseqs2

We are currently working on finishing up the changes there and merging everything back to the main MMseqs2 git. There is still some work to be done however.

**Comment by hartrials** [comment]
OK, thanks!
