### ISSUE TITLE
Replicating scoring of other SW implementations

### ISSUE THREAD

**Issue by gvmichael** [soedinglab/MMseqs2#487]
## Expected Behavior
I would like to replicate the scores given by other implementations of SW local alignment such as parasail. 

## Current Behavior
Even when I use the same substitution matrix as parasail, I get different scores. From looking at the code it looks like the substitution matrix is modified by the "lambda" and "background" values. I would like for mmseqs align to simply use the substitution matrix I input without any modifications. 

## Steps to Reproduce (for bugs)
I created a list of repetitive sequences
['AAAAAAAAAAAAAA',
 'CCCCCCCCCCCCCC',
 'DDDDDDDDDDDDDD',
 'EEEEEEEEEEEEEE',
 'FFFFFFFFFFFFFF',
 'GGGGGGGGGGGGGG',
 'HHHHHHHHHHHHHH',
 'IIIIIIIIIIIIII',
 'KKKKKKKKKKKKKK',
 'LLLLLLLLLLLLLL',
 'MMMMMMMMMMMMMM',
 'NNNNNNNNNNNNNN',
 'PPPPPPPPPPPPPP',
 'QQQQQQQQQQQQQQ',
 'RRRRRRRRRRRRRR',
 'SSSSSSSSSSSSSS',
 'TTTTTTTTTTTTTT',
 'VVVVVVVVVVVVVV',
 'WWWWWWWWWWWWWW',
 'YYYYYYYYYYYYYY',
 'XXXXXXXXXXXXXX']

I converted these sequences to a database and used "map" with this database against itself with the following BLOSUM62 substitution matrix (the # in the first 3 lines was removed for formatting):

Background (precomputed optional): 0.0794 0.0213 0.0501 0.0468 0.0525 0.0647 0.0228 0.0642 0.0491 0.0869 0.0323 0.0376 0.0447 0.0426 0.0649 0.0564 0.0528 0.0591 0.0115 0.0284 0.00001
Lambda     (precomputed optional): 0.34657
Avg SeqId  (precomputed optional): 0.32351
	A	C	D	E	F	G	H	I	K	L	M	N	P	Q	R	S	T	V	W	Y	X
A	4	0	-2	-1	-2	0	-2	-1	-1	-1	-1	-2	-1	-1	-1	1	0	0	-3	-2	0
C	0	9	-3	-4	-2	-3	-3	-1	-3	-1	-1	-3	-3	-3	-3	-1	-1	-1	-2	-2	-2
D	-2	-3	6	2	-3	-1	-1	-3	-1	-4	-3	1	-1	0	-2	0	-1	-3	-4	-3	-1
E	-1	-4	2	5	-3	-2	0	-3	1	-3	-2	0	-1	2	0	0	-1	-2	-3	-2	-1
F	-2	-2	-3	-3	6	-3	-1	0	-3	0	0	-3	-4	-3	-3	-2	-2	-1	1	3	-1
G	0	-3	-1	-2	-3	6	-2	-4	-2	-4	-3	0	-2	-2	-2	0	-2	-3	-2	-3	-1
H	-2	-3	-1	0	-1	-2	8	-3	-1	-3	-2	1	-2	0	0	-1	-2	-3	-2	2	-1
I	-1	-1	-3	-3	0	-4	-3	4	-3	2	1	-3	-3	-3	-3	-2	-1	3	-3	-1	-1
K	-1	-3	-1	1	-3	-2	-1	-3	5	-2	-1	0	-1	1	2	0	-1	-2	-3	-2	-1
L	-1	-1	-4	-3	0	-4	-3	2	-2	4	2	-3	-3	-2	-2	-2	-1	1	-2	-1	-1
M	-1	-1	-3	-2	0	-3	-2	1	-1	2	5	-2	-2	0	-1	-1	-1	1	-1	-1	-1
N	-2	-3	1	0	-3	0	1	-3	0	-3	-2	6	-2	0	0	1	0	-3	-4	-2	-1
P	-1	-3	-1	-1	-4	-2	-2	-3	-1	-3	-2	-2	7	-1	-2	-1	-1	-2	-4	-3	-2
Q	-1	-3	0	2	-3	-2	0	-3	1	-2	0	0	-1	5	1	0	-1	-2	-2	-1	-1
R	-1	-3	-2	0	-3	-2	0	-3	2	-2	-1	0	-2	1	5	-1	-1	-3	-3	-2	-1
S	1	-1	0	0	-2	0	-1	-2	0	-2	-1	1	-1	0	-1	4	1	-2	-3	-2	0
T	0	-1	-1	-1	-2	-2	-2	-1	-1	-1	-1	0	-1	-1	-1	1	5	0	-2	-2	0
V	0	-1	-3	-2	-1	-3	-3	3	-2	1	1	-3	-2	-2	-3	-2	0	4	-3	-1	-1
W	-3	-2	-4	-3	1	-2	-2	-3	-3	-2	-1	-4	-4	-2	-3	-3	-2	-3	11	2	-2
Y	-2	-2	-3	-2	3	-3	2	-1	-2	-1	-1	-2	-3	-1	-2	-2	-2	-1	2	7	-1
X	0	-2	-1	-1	-1	-1	-1	-1	-1	-1	-1	-1	-2	-1	-1	0	0	-1	-2	-1	-1

This was the map command:
map //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB_Self //app/clustering/tmp -e 0 -s 1.0 --exact-kmer-matching 1 -k 0 --rescore-mode 2 --sub-mat /app/matrices/blosum62-parasail.out

## MMseqs Output (for bugs)

There were no errors in running the map function.

After map finished, I took the scores for each sequence with itself and divided these scores by the length of the sequence. This gave the score for each amino acid with itself, which should agree with the substitution matrix, e.g. A with A should be 4. For parasail, this was exactly the result. For mmseqs, the scores were fractional, not corresponding to  the original matrix:

A	4.43
C	10.43
D	6.79
E	5.71
F	6.79
G	6.79
H	9.14
I	4.43
K	5.71
L	4.43
M	5.71
N	6.79
P	8.07
Q	5.71
R	5.71
S	4.43
T	5.71
V	4.43
W	12.79
X	-0.21
Y	8.07

## Your Environment
Include as many relevant details about the environment you experienced the bug in.

Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): ad5837b
Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): lastest Docker container
Operating system and version: Windows 10 (Docker in git bash)

**Comment by martin-steinegger** [comment]
MMseqs2 does not report RAW scores in default but bit scores. Parasail reports raw scores. You can get the raw scores by using `convertalis q t aln --format-output query,target,raw`

**Comment by gvmichael** [comment]
I've been using the convertalis command this way:

`convertalis //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB_Self //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB_Self_converted.tsv --format-output query,target,raw --gap-open 11 --gap-extend 1 --sub-mat /app/matrices/blosum62-parasail.out `

I've used convertalis with both the "raw" and "bits" fields. I've found that, using the approach above, the raw scores are approximately 13% higher on average than Parasail scores. However, by using the bits score and doubling it, I've found that the MMseqs2 score varies only from -3% to +3% of the parasail score. For some amino acids (D, F, G, N, P, Y) it gave the same value as Parasail did.

So it seems like twice the bits score is close to parasail, but not quite identical. Below is the comparison between parasail scores, MMseqs2 2*bits, and MMseqs2 raw:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>


<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Sequence | Parasail | MMseqs2-2*bits | MMseqs2-raw
-- | -- | -- | --
AAAAAAAAAAAAAA | 56 | 58 | 62
CCCCCCCCCCCCCC | 126 | 124 | 145
DDDDDDDDDDDDDD | 84 | 84 | 95
EEEEEEEEEEEEEE | 70 | 72 | 80
FFFFFFFFFFFFFF | 84 | 84 | 95
GGGGGGGGGGGGGG | 84 | 84 | 95
HHHHHHHHHHHHHH | 112 | 110 | 128
IIIIIIIIIIIIII | 56 | 58 | 62
KKKKKKKKKKKKKK | 70 | 72 | 80
LLLLLLLLLLLLLL | 56 | 58 | 62
MMMMMMMMMMMMMM | 70 | 72 | 80
NNNNNNNNNNNNNN | 84 | 84 | 95
PPPPPPPPPPPPPP | 98 | 98 | 112
QQQQQQQQQQQQQQ | 70 | 72 | 80
RRRRRRRRRRRRRR | 70 | 72 | 80
SSSSSSSSSSSSSS | 56 | 58 | 62
TTTTTTTTTTTTTT | 70 | 72 | 80
VVVVVVVVVVVVVV | 56 | 58 | 62
WWWWWWWWWWWWWW | 154 | 150 | 178
YYYYYYYYYYYYYY | 98 | 98 | 112
XXXXXXXXXXXXXX | 0 | 6 | -2



</body>

</html>

**Comment by milot-mirdita** [comment]
I think you have to use the normal `search` workflow instead of the `map` workflow, as `map` uses an ungapped alignment (the `rescorediagonal` module) instead of a real SW (the `align` module).

Make sure to also pass `--comp-bias-corr 0 --mask 0` when using the `search` workflow.

**Comment by gvmichael** [comment]
Using the search workflow (with --comp-bias-corr 0 --mask 0) and convertalis:

`search //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB_Self //app/clustering/tmp -e 0 -s 1.0 --exact-kmer-matching 1 --sub-mat /app/matrices/blosum62-parasail.out --comp-bias-corr 0 --mask 0 `

`convertalis //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB_Self //app/database/Repetitive_Aminos14/Repetitive_Aminos14_DB_Self_converted.tsv --format-output query,target,raw --gap-open 11 --gap-extend 1 --sub-mat /app/matrices/blosum62-parasail.out `

I now get values that seem to be within roundoff error (+-1) of parasail values (below). These values still don't give whole numbers when divided by 14, though they are at most 0.07 from whole numbers. Is there any way to get an exact match for Parasail values? I'm guessing at this point it might be a floating point arithmetic issue which may not be easily resolvable. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/hr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/hr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Sequence | Parasail | MMseqs2-search-raw
-- | -- | --
AAAAAAAAAAAAAA | 56 | 57
CCCCCCCCCCCCCC | 126 | 127
DDDDDDDDDDDDDD | 84 | 84
EEEEEEEEEEEEEE | 70 | 69
FFFFFFFFFFFFFF | 84 | 84
GGGGGGGGGGGGGG | 84 | 84
HHHHHHHHHHHHHH | 112 | 112
IIIIIIIIIIIIII | 56 | 57
KKKKKKKKKKKKKK | 70 | 69
LLLLLLLLLLLLLL | 56 | 57
MMMMMMMMMMMMMM | 70 | 69
NNNNNNNNNNNNNN | 84 | 84
PPPPPPPPPPPPPP | 98 | 97
QQQQQQQQQQQQQQ | 70 | 69
RRRRRRRRRRRRRR | 70 | 69
SSSSSSSSSSSSSS | 56 | 57
TTTTTTTTTTTTTT | 70 | 69
VVVVVVVVVVVVVV | 56 | 57
WWWWWWWWWWWWWW | 154 | 154
YYYYYYYYYYYYYY | 98 | 97



</body>

</html>

**Comment by milot-mirdita** [comment]
The alignment algorithm itself uses only `int`-math, however the substitution matrix read in does quite a bit of float-math. I don't think we can easily fix this. I guess we probably end up computing slightly differently rounded substitution scores.

**Comment by gvmichael** [comment]
Okay that makes sense. Thank you!
