### ISSUE TITLE
Could not allocate entries memory in IndexTable::initMemory

### ISSUE THREAD

**Issue by ChristophKnapp** [soedinglab/MMseqs2#49]
Hi,
I was trying to generate the index files of a huge database. To be precise the nr database from blast. It creates the database without problems but when I run the createindex module mmseqs2, it stops with the error.

Could not allocate entries memory in IndexTable::initMemory

I'm aware that this is not a bug but the computer I'm trying to run it on runs out of memory. It processes all sequences though and stops right at the end when the index files should have been written. 

I still can search the resulting database, its just indexing the database on the fly. The computer has 64 Gb of memory, which is used in the process to 94% before swap is used.

Now my question. 
Is there anything I can do, except of extending the hardware to make this work? 
In future I would set the -s parameter to 8 as this gives about the same sensitivity as blast?
Would this further increase the memory usage?

Thank you in advance

Christoph

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MMseqs Output (for bugs)
Could not allocate entries memory in IndexTable::initMemory

## Context
createindex module fails 

## Your Environment
64 bit latest debian linux 
24 cpus
64 gb of RAM
latest git hub version self compiled with cmake.

**Comment by milot-mirdita** [comment]
Hi Christoph,

We removed split index support from createindex a few months ago. The implementation was not really mature enough. If you want to use a precomputed index table, it currently has to fit into memory completely. 

We wanted to reimplement that feature soonish (for our upcoming webserver manuscript), though i cannot give you a timeline for that.

We should definitely give a good error message though, if createindex is going to fail anyway.

Best regards,
Milot

**Comment by soeding** [comment]
Hi Martin und Milot,

eine Möglichkeit, MMseqs2 fuer kleinere Speicher benutzbar zu machen wäre, nur manche der k-mere in den Index zu schreiben, so dass der Index z.B. 4mal kleiner wird. Intuitiv wuerde ich von den häufigsten k-meren, die z.B. zusammen 87% der Total Counts ausmachen 85% weglassen, weil diese am wenigsten spezifisch sind. Dann hat man insgesamt 0.87^2 = 75% der k-mere herausgeschmissen. Ich vermute, dass dann die Sensitivität relativ wenig abnimmt.

Oder etwas smoother, mann dünnt die k-mere mit einem Faktor exp(-a * CumFrac) aus, wobei CumFrac der kumulierte Anteil der Totalen k-mer-Counts ist, nach Counts per k-mer sortiert.

Viele Gruesse,
Johannes





On 08 Nov 2017, at 15:12, Milot Mirdita <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Christoph,

We removed split index support from createindex a few months ago. The implementation was not really mature enough. If you want to use a precomputed index table, it currently has to fit into memory completely.

We wanted to reimplement that feature soonish (for our upcoming webserver manuscript), though i cannot give you a timeline for that.

We should definitely give a good error message though, if createindex is going to fail anyway.

Best regards,
Milot

**Comment by milot-mirdita** [comment]
Precomputed split indices should work again. We recently re-implemented this feature.
