### ISSUE TITLE
Adding taxonomy to nr database cost a lot

### ISSUE THREAD

**Issue by julie-tooi** [soedinglab/MMseqs2#490]
Thank you for your tool - it is very nice, fast and useful. 
Previously I used already prepared mmseqs databases with taxonomy (like Uniprot) and everything works fine.

But now I have to use nr database. I used the instruction from the manual and have fasta and taxid file with blastdbcmd.
Next steps with mmseqs:

`mmseqs createdb nr_20210908.fna nr_20210908_mmseqDB`
`mmseqs createtaxdb nr_20210908_mmseqDB tmp --ncbi-tax-dump /media/tertiary/database_nr/taxonomy/ --tax-mapping-file /media/tertiary/database_nr/nr_20210908.fna.taxidmapping`

So this second step with adding taxonomy working now more than week and took **168G RAM** (and it is still working!)

I use server to run the annotation with 12 threads, 62G RAM and 128G Swp (and it looks like a lot for the db preparing)
mmseqs output for now it is:
```
MMseqs Version:                 12.113e3
NCBI tax dump directory         /media/tertiary/database_nr/taxonomy/
Taxonomical mapping file        /media/tertiary/database_nr/nr_20210908.fna.taxidmapping
Threads                         12
Verbosity                       3
```

Maybe you have some ideas how to do it cheaper for computational resources? 
Some memory limit or even another way get taxonomy annotation to nr database?

Thank you!

**Comment by milot-mirdita** [comment]
For the `nr` we have the specialized `nrtotaxmapping` module. You give it the [accession2taxid](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/) files and the NR sequence database (from `createdb`) and it will create the correct `_mapping` file. It should be quite a bit cheaper than the `awk` command used in `createtaxdb` (see https://github.com/soedinglab/MMseqs2/blob/master/data/workflow/databases.sh#L415 on how it's used).

For that you have to upgrade to the latest MMseqs2 release though. The latest release also has the `nr` included in the `databases` downloader script, which utilizes this module internally.

**Comment by milot-mirdita** [comment]
We noticed one thing with the `awk` based script: Some linux distributions ship `mawk` as the default awk, which is generally very fast, but seems to be a lot slower for the purpose of joining two files (we use it for that purpose in the `createtaxdb` workflow). 

You can install `gawk` and switch Ubuntu to use that by default with something like this: https://askubuntu.com/a/561626
`gawk` seems to be much much faster for this purpose.

**Comment by milot-mirdita** [comment]
`nrtotaxmapping` is slightly weird as it already requires the NCBI taxdb files to be present.
In the `databases` workflow, I create an empty `_mapping` file first, so `createtaxdb` will not try to create one, then call `createtaxdb` and then finally `nrtotaxmapping`.

I have to integrate `nrtotaxmapping` into `createtaxdb` eventually to clean this up I guess.
