### ISSUE TITLE
Resfinder download fails

### ISSUE THREAD

**Issue by smdabdoub** [soedinglab/MMseqs2#494]
## Expected Behavior
The Resfinder database is downloaded and an mmseqs2 index is created.

## Current Behavior
Fails at the download extraction step.

## Steps to Reproduce (for bugs)
mmseqs databases Resfinder db/rf tmp

## MMseqs Output (for bugs)
databases Resfinder db/rf tmp 

MMseqs Version:              	13.45111
Force restart with latest tmp	false
Remove temporary files       	false
Compressed                   	0
Threads                      	48
Verbosity                    	3

--2021-10-08 14:50:24--  https://api.bitbucket.org/2.0/repositories/genomicepidemiology/resfinder_db/commit/master?fields=hash,date
Resolving api.bitbucket.org (api.bitbucket.org)... 18.205.93.8, 18.205.93.6, 18.205.93.7, ...
Connecting to api.bitbucket.org (api.bitbucket.org)|18.205.93.8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 89 [application/json]
Saving to: 'tmp/9391455786971071082/version'

tmp/9391455786971071082/version               100%[=================================================================================================>]      89  --.-KB/s    in 0s      

2021-10-08 14:50:24 (13.7 MB/s) - 'tmp/9391455786971071082/version' saved [89/89]

--2021-10-08 14:50:24--  https://bitbucket.org/genomicepidemiology/resfinder_db/get/master.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c3:9b0a, 2406:da00:ff00::34cc:ea4a, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 457328 (447K) [application/x-tar-gz]
Saving to: 'tmp/9391455786971071082/master.tar.gz'

tmp/9391455786971071082/master.tar.gz         100%[=================================================================================================>] 446.61K  --.-KB/s    in 0.07s   

2021-10-08 14:50:25 (5.88 MB/s) - 'tmp/9391455786971071082/master.tar.gz' saved [457328/457328]

tar: *.fsa: not found in archive
createdb tmp/9391455786971071082/*.fsa db/rf --compressed 0 -v 3 

Input tmp/9391455786971071082/*.fsa does not exist
Error: createdb died

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): h95f258a
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): singularity container downloaded from Biocontainers
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): Intel Xeon 8268, 192GB RAM
* Operating system and version: RHEL 7.9

**Comment by milot-mirdita** [comment]
This is quite confusing. For whatever reason your system's `tar` doesn't use the default `--wildcards` option. It seems to be having `--no-wildcards` set as the default mode. I don't have access to RHEL, but in the centos 7.9 docker image this doesn't seem to happen.

You can probably get around this issue by doing:

```
TAR_OPTIONS="--wildcards" mmseqs databases Resfinder db/rf tmp
```

**Comment by milot-mirdita** [comment]
Is this a public container? I would like to know how exactly this failed to improve the script for the future.
