### ISSUE TITLE
[question] What does `--max-seq-length` do?

### ISSUE THREAD

**Issue by cdiener** [soedinglab/MMseqs2#499]
## Expected Behavior

Using the `--max-seq-length` parameter in `mmseqs linclust` will only return sequences with a length smaller than the setting.

## Current Behavior

Even with the default parameter linclust will return larger sequences (up to 600K nt in my case). Also choosing very large values triggers an integer overflow.

## Steps to Reproduce (for bugs)

```bash
mmseqs linclust foods foods_99 /tmp --cov-mode 0 -c 0.8 --min-seq-id 0.99 --threads 20 --split-memory-limit 250G --max-seq-len 3000000000
```

## MMseqs Output (for bugs)

```
...
Seq. id. threshold                      0.99                                                                                                                                  
Min alignment length                    0
Seq. id. mode                           0
Alternative alignments                  0
Coverage threshold                      0.8
Coverage mode                           0
Max sequence length                     -1294967296
Compositional bias                      1
Max reject                              2147483647
Max accept                              2147483647
...
```

## Context

mmseqs version 13.45111. `conda info`:

```
     active environment : metagenomics
    active env location : /users/cdiener/miniconda3/envs/metagenomics
            shell level : 3
       user config file : /users/cdiener/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.7.8.final.0
       virtual packages : __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /users/cdiener/miniconda3  (writable)
      conda av data dir : /users/cdiener/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /users/cdiener/miniconda3/pkgs
                          /users/cdiener/.conda/pkgs
       envs directories : /users/cdiener/miniconda3/envs
                          /users/cdiener/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.7.8 Linux/4.15.0-121-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 52778:1127
             netrc file : None
           offline mode : False
```

**Comment by milot-mirdita** [comment]
`--max-seq-length`  decides what that maximum internal sequence length is and how we allocate memory for various sequences. 

I guess you want something like the opposite to `--min-aln-len` to reject all alignments (and therefore cluster members) that are too long?

**Comment by cdiener** [comment]
Much simpler I think. I just wanted to make sure that my very long sequences (2e4 - 2e9 nts) are clustered completely and that `mmseqs linclust` doesn't remove very long sequences. The `--max-seq-length` makes it seem like it would throw out any sequence longer than that which would be the majority in my case, but it looks like this is not the case.

**Comment by milot-mirdita** [comment]
We changed the majority of the MMseqs2 modules to take `--max-seq-len` to be the starting amount of memory and to progressively allocate more memory if needed.

Dealing with long nucleotide sequences is still something where we plan on investing a lot more time, however it should mostly work at the moment. Not really how well it will deal with sequences around your upper bound though. It might start to use excessive amounts of RAM.

**Comment by cdiener** [comment]
Awesome. I'm fine with that as long as it does not silently drop sequences. Thanks for the clarification.

**Comment by milot-mirdita** [comment]
The "worst" thing that can happen I guess is that sequences remain unclustered even though they have high sequence identity.

To produce good clusterings, I would make sure you use coverage mode 1 (See https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster). There is also the `--kmer-per-seq-scale`  parameter (for nucleotide searches/clustering set to 0.2 by default). This scales the number of extracted k-mers based on the sequence length. Here, 0.2 means the base `--kmer-per-seq` and an additional `0.2 * sequence length`.
