### ISSUE TITLE
Creating fasta files from clustering results

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#50]
Hi 
I would like to know if there is a native way in MMseqs2 to create separated files from the clustering results. Now we are using `createseqfiledb` to have a fasta version of the clustering database and we extract the cluster sequence from there using _awk_ like this:

```bash
mawk '/^>/{close("cluster_"i".fa"); x="cluster_"++i".fa"}{gsub("\x0", "", $0); print > x}' cluster_db_fa
```
I looked through the documentation and I wasn't able to find anything. Do you have a better solution?

Many thanks
Antonio

**Comment by martin-steinegger** [comment]
We do not have a native way to produce a seperate file for each cluster. When clustering millions/billions of sequences this would produce too much single files. This would stress the filesystem too much. 
Why do you need single files?

**Comment by genomewalker** [comment]
It's related with the cluster evaluation and representative selection we are using. We need to find a compromise between speed and I/O bottlenecks. Now we were using `createsudb` to query the DB and get DBs for each cluster and distribute it in the HPC cluster to perform our validation, but it takes a long time, the original DB is ~250M proteins. It is faster when we have the files in the scratch partition of each node and the files partitioned in folders. This is the fastest way we found so far, from `createseqfiledb`:
```
mawk '{if ($0 ~ /^\x0/ || NR == 1){gsub("\x0","",$0); print "#"$0; print $0}else{print $0}}' DB_clu_fa | csplit -z --suppress-matched -s -f cluster_ -b "%01d.fa" - '^#/' {*}
```
After we split the ~32M files in folders with 100K files in each. All of this done in a fast SSD partition.

Do you have any suggestions?

Thanks

**Comment by martin-steinegger** [comment]
I would use ffindex_apply_mpi (https://github.com/soedinglab/ffindex_soedinglab). It is compatible with MMseqs2 databases. It works like map from map/reduce. It calls for every index entry (e.g. each cluster) a process. The stdout of the process will be written as respective entry into an output database. The tool supports OMP and MPI to spread out the job over several compute nodes.

Just write a program (e.g.`selectRepSeq`) which takes the a fasta input from stdin and prints out the representive sequence as stdout. You can call ffindex_apply_mpi like this:

`ffindex_apply_mpi -d repSeq -i repSeq.index clu_createseqfiledb clu_createseqfiledb.index -- selectRepSeq`

**Comment by soeding** [comment]
Hi Martin,

super hilfreiche Q&As. Tut die unbedingt auch in den Userguide!

Ciao,
Johannes


On 12 Nov 2017, at 11:10, Martin Steinegger <notifications@github.com<mailto:notifications@github.com>> wrote:


I would use ffindex_apply_mpi (https://github.com/soedinglab/ffindex_soedinglab). It is compatible with MMseqs2 databases. It works like map from map/reduce. It calls for every index entry (e.g. each cluster) a process. The stdout of the process will be written as respective entry into an output database. The tool supports OMP and MPI to spread out the job over several compute nodes.

Just write a program (e.g.selectRepSeq) which takes the a fasta input from stdin and prints out the representive sequence as stdout. You can call ffindex_apply_mpi like this:

ffindex_apply_mpi -d repSeq -i repSeq.index clu_createseqfiledb clu_createseqfiledb.index -- selectRepSeq

**Comment by genomewalker** [comment]
Hi Martin
ffindex_apply is awesome, I've been playing around and it is quite straight forward to plug it in our pipeline avoiding the generation of the files.

Many thanks!
Antonio

**Comment by milot-mirdita** [comment]
Hi Antonio,

Just a quick remark, if you try to use any of the other ffindex tools (e.g. ffindex_get) with MMseqs2 databases. Index files have numeric keys and are also sorted numerically sorting in MMseqs2. If you want to use a tool like ffindex_get you have to sort the index file lexicographically first and pass the sorted index to the other tools.

```
LC_ALL=C sort DB.index > DB.index_sorted
```

ffindex also has a tool to split a database into separate files (ffindex_unpack), but, as Martin said, this generally is a bad idea for most file systems.

Best regards,

Milot

**Comment by genomewalker** [comment]
Thanks milot! ffindex has been a great discovery and in fact speeded up our evaluation pipeline a lot. If I understand correctly we can use ffindex_get with a clusterDB in the same way ffindex_apply does, using the offset in the index file to retrieve a whole cluster?

Many thanks for all your help and developing such awesome tools!
Antonio

**Comment by milot-mirdita** [comment]
Be careful about `ffindex_get`, it has a lot of overhead. It is mostly intended for debugging purposes.

**Comment by soeding** [comment]
Dear Yuichiro,

thank you for your encouragement. 

I am afraid we do not offer a tblastn-like search mode yet.

Martin, Milot, do we have a tool to translate a nucleotide database to putative protein ORFs?

Best wishes,
Johannes
