### ISSUE TITLE
[question] Output cluster score

### ISSUE THREAD

**Issue by PedroMTQ** [soedinglab/MMseqs2#506]
Is it possible to output some sort of cluster-associated score when using mmseqs to cluster protein sequences?
I'm using `create_db`, followed by `cluster`, and finally `createtsv`. 
From my understanding the tsv will contain the representative sequence on the left, and the associated clustered sequences on the right.
I would like to maybe have some sort of score - either per line or per cluster.
Maybe I'm misunderstanding something here, but would this be possible?

Regards,
Pedro

**Comment by milot-mirdita** [comment]
You can call `align` on the cluster output to get pairwise alignment and thus alignment scores and E-values.  We currently don't have cluster scores, however we are working on a novel search method that would provide something like that. 

Another thing you can do is use `summarizealis` on the aligned cluster result, that will give you some kind of summary per cluster, though it's not a single score.

**Comment by PedroMTQ** [comment]
ok thanks 
i'll try that out
