### ISSUE TITLE
Clustering large nucleotide sequence set with easy-clust

### ISSUE THREAD

**Issue by fplaza** [soedinglab/MMseqs2#512]
Hello,

I would like to perform clustering of a large nucleotide sequence with the easy-clust .
However, it is not clear for me whether the "--min-seq-id" and "-c" parameters refer to alignments in nucleotide space or alignments in amino-acid space after sequence translation.

Thanks,
Florian

**Comment by martin-steinegger** [comment]
They function and mean the same in nucleotide space.
