### ISSUE TITLE
Create SeqTaxDB for GTDB

### ISSUE THREAD

**Issue by psj1997** [soedinglab/MMseqs2#514]
Hi,

I have seen that in the mmseqs user guide, there is a part about how to preprocess the GTDB database. I am still confusing after reading that. I want to ask if there is more details about how to build the database from the latest GTDB data (https://data.ace.uq.edu.au/public/gtdb/data/releases/release202/202.0/)  for mmseqs taxonomy? 

Thanks for your any suggestions.

Sincerely
Shaojun

**Comment by milot-mirdita** [comment]
You should be able to just call:
```
mmseqs databases GTDB gtdb tmp
```

And it will download and setup the latest release for you.

**Comment by psj1997** [comment]
Thanks! For some reason, I want to remove some genomes from GTDB and build the reference genome from that for mmseqs taxonomy. How can I do that? 

Sincerely
Shaojun

**Comment by milot-mirdita** [comment]
You can copy the steps we do in the `databases` workflow to create this database in this file:
https://github.com/soedinglab/MMseqs2/blob/13-45111/data/workflow/databases.sh
Look for the `"GTDB"` string.


The easier solution is probably to just create the gtdb with the command I mentioned, then look up all genomes you don't want in the `_names.dmp` file we create. And remove them with:
```
mmseqs filtertaxseqdb gtdb gtdb_subset --taxon-list "!first_id&&!second_id&&...."
```

This should work well for the latest release (13), however we changes some things in git mmseqs (names.dmp is not created by default anymore) so will be harder there.

**Comment by psj1997** [comment]
Thanks! I will try that.

**Comment by ajtritt** [comment]
@milot-mirdita 
Was this database built with just representatives from GTDB?

**Comment by milot-mirdita** [comment]
The `databases` workflow downloads this file:
https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/genomic_files_reps/gtdb_proteins_aa_reps.tar.gz

**Comment by jolespin** [comment]
@milot-mirdita How can I build this database if I already have GTDB downloaded for GTDB-Tk?

**Comment by milot-mirdita** [comment]
I have not looked into the database format of GTDB-Tk. I would recommend to use the `workflow`. For our new taxonomy classifier [Metabuli](https://github.com/steineggerlab/Metabuli), we provide a prebuilt GTDB.
