### ISSUE TITLE
BLAST Database error: No alias or index file found for protein database

### ISSUE THREAD

**Issue by sulfierry** [soedinglab/MMseqs2#518]
BLAST Database error: No alias or index file found for protein database 
I have the error below:

Bio.Application.ApplicationError: Non-zero return code 2 from ‘psiblast -out 7NDB_B_WT.out -query 7NDB_B_WT.fasta -db /mnt/research/common-data/Bio/blastdb/nr -evalue 5000 -num_iterations 3 -out_ascii_pssm 7NDB_B_WT.pssm’, message ‘BLAST Database error: No alias or index file found for protein database [/mnt/research/common-data/Bio/blastdb/nr] in search path [/media/leon//Machine_learning_model_binding_free_energy_BFE_change_predictions/TopNetmAb/7NDB/features/7NDB_B_A_344_S::]’

I downloaded the “nr” file from the blast database and created a database link in the directory [/mnt/research/common-data/Bio/blastdb/nr]. But the error persists.

Please, can anyone help me?

**Comment by martin-steinegger** [comment]
We currently do not support BLAST database input into MMseqs2. You would need to first generate a database with fasta or just use our `mmseqs database` command to download databases from a preset.
