### ISSUE TITLE
Segmentation fault during prefiltering

### ISSUE THREAD

**Issue by JuElv** [soedinglab/MMseqs2#52]
## Expected Behavior
When running with highly reduced databases with the size of lower than 1MB, it works just fine. 
Both the complete call for the search workflow ./mmseqs search "query" "target" "result" "tmp"
as well as the explicit call for the prefilter module only ./mmseqs prefilter "query" "target" "result" are running as expected.

## Current Behavior
Using bigger files for query and target data, which in no means are unreasonable in my opinion  (5.1 MB each), the program exits with a segmentation fault during the prefiltering step. See output below for more detailed information.

## Steps to Reproduce (for bugs)
strictly following the steps from your user guide on a freshly installed mmseqs distribution,
compiled from scratch
1) converted files into mmseqs-readable format from plain fasta files
./mmseqs createdb "querypath" "query"
./mmseqs createdb "targetpath" "target"
2) created new temp folder on local harddrive
3) tried to run the whole search workflow
./mmseqs search "query" "target" "result" "tmp"
3b) after failing the search due to the segmentation fault, decided to clean the databases and temp folder
and ran the prefilter module explicitly as this seems to have been the problem
./mmseqs prefilter "query" "target" "result"

## MMseqs Output (for bugs)
**Search workflow:**
Program call:
/local/jelvers/Masterthesis/Testdata/querysample03 /local/jelvers/Masterthesis/Testdata/targetsample03 /local/jelvers/Masterthesis/temp/6581086409424530102/pref_5.7 --sub-mat blosum62.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 32000 --max-seqs 300 --offset-result 0 --split 0 --split-mode 2 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --mask 1 --min-ungapped-score 15 --spaced-kmer-mode 1 --pca 1 --pcb 1.5 --threads 4 -v 3 -s 5.7 

MMseqs Version:                 bcb164e42c79555cc521196c7f94f4b0123da048
Sub Matrix                      blosum62.out
Sensitivity                     5.7
K-mer size                      0
K-score                         2147483647
Alphabet size                   21
Max. sequence length            32000
Max. results per query          300
Offset result                   0
Split DB                        0
Split mode                      2
Coverage threshold              0
Coverage Mode                   0
Compositional bias              1
Diagonal Scoring                1
Mask Residues                   1
Minimum Diagonal score          15
Include identical Seq. Id.      false
Spaced Kmer                     1
No preload                      false
Early exit                      false
Pseudo count a                  1
Pseudo count b                  1.5
Threads                         4
Verbosity                       3

Initialising data structures...
Using 4 threads.
Could not find precomputed index. Compute index.
Use kmer size 6 and split 1 using Target split mode.
Needed memory (1414056568 byte) of total memory (8293187584 byte)
Target database: /local/jelvers/Masterthesis/Testdata/targetsample03(Size: 14015)
Substitution matrices...
Query database type: Aminoacid
Target database type: Aminoacid
Time for init: 0 h 0 m 2s

Query database: /local/jelvers/Masterthesis/Testdata/querysample03(size=14015)
Process prefiltering step 1 of 1

Index table: counting k-mers...
/local/jelvers/Masterthesis/temp//6581086409424530102/blastp.sh: line 86:  8824 Segmentation fault      (core dumped) $RUNNER $MMSEQS prefilter "$INPUT" "$TARGET" "$TMP_PATH/pref_$SENS" $PREFILTER_PAR -s $SENS
Error: Prefilter died
[Inferior 1 (process 8814) exited with code 01]

**Prefilter module call**
Program call:
/local/jelvers/Masterthesis/Testdata/querysample03 /local/jelvers/Masterthesis/Testdata/targetsample03 /local/jelvers/Masterthesis/Mmseqs_output/ 

MMseqs Version:                 bcb164e42c79555cc521196c7f94f4b0123da048
Sub Matrix                      blosum62.out
Sensitivity                     4
K-mer size                      0
K-score                         2147483647
Alphabet size                   21
Max. sequence length            32000
Max. results per query          300
Offset result                   0
Split DB                        0
Split mode                      2
Coverage threshold              0
Coverage Mode                   0
Compositional bias              1
Diagonal Scoring                1
Mask Residues                   1
Minimum Diagonal score          15
Include identical Seq. Id.      false
Spaced Kmer                     1
No preload                      false
Early exit                      false
Pseudo count a                  1
Pseudo count b                  1.5
Threads                         4
Verbosity                       3

Initialising data structures...
Using 4 threads.
Could not find precomputed index. Compute index.
Use kmer size 6 and split 1 using Target split mode.
Needed memory (1414056568 byte) of total memory (8293187584 byte)
Target database: /local/jelvers/Masterthesis/Testdata/targetsample03(Size: 14015)
Substitution matrices...
[New Thread 0x7ffff6210700 (LWP 9087)]
[New Thread 0x7ffff5a0f700 (LWP 9088)]
[New Thread 0x7ffff520e700 (LWP 9089)]
Query database type: Aminoacid
Target database type: Aminoacid
Time for init: 0 h 0 m 2s

Query database: /local/jelvers/Masterthesis/Testdata/querysample03(size=14015)
Process prefiltering step 1 of 1

Index table: counting k-mers...

Thread 3 "mmseqs" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5a0f700 (LWP 9088)]
0x0000000000542911 in tantan::getProbabilities(char const*, char const*, int, double const* const*, double, double, double, double, double, float*) ()

## Context
As already stated above, with smaller databases everything works fine. Even running a small different query set on the target database works just fine, as does the other way round (normal query, reduced target db).
Please tell me if u need the fasta files to recreate this bug.

## Your Environment
MMseqs2 Version: bcb164e42c79555cc521196c7f94f4b0123da048
Self-compiled build, following your description in "Compile from source"
cmake version 3.5.2
gcc version 4.8.5 (SUSE Linux) 
Memory: 7.7 GiB RAM
openSUSE Leap 42.2, Kernel: 4.4.92-18.36-default, 64 bit

**Comment by martin-steinegger** [comment]
Thanks for reporting this bug. It would be great if you could make the fafsa available.

It seems to be a problem while masking the sequence with tantan. Does --mask 0 crash as well?

**Comment by JuElv** [comment]
Thanks for your quick reply.
Yeah, --mask 0 apparently seems to change something, but the error basically stays the same:
But mentioning the masking, the data we have is already masked with tantan, does this pose a problem for mmseqs?

/local/jelvers/Masterthesis/temp//4778667373760070442/blastp.sh: line 86: 14547 Segmentation fault      (core dumped) $RUNNER $MMSEQS prefilter "$INPUT" "$TARGET" "$TMP_PATH/pref_$SENS" $PREFILTER_PAR -s $SENS
Error: Prefilter died


[query.txt](https://github.com/soedinglab/MMseqs2/files/1548211/query.txt)
[target.txt](https://github.com/soedinglab/MMseqs2/files/1548212/target.txt)

**Comment by martin-steinegger** [comment]
We did not handle the lower case 'z' properly. Should be fixed now.

**Comment by JuElv** [comment]
Thanks for the quick fix, works properly now. Very much appreciated

**Comment by martin-steinegger** [comment]
Thanks for reporting!
