### ISSUE TITLE
query cover

### ISSUE THREAD

**Issue by slambrechts** [soedinglab/MMseqs2#520]
Hi,

If I only want to look for hits with a minimum query cover of 80%, should I add `--cov-mode 2 -c 0.8` to the `mmseqs search` command?

I'm new to MMseqs2, and I'm looking for the equivalent of using `--query-cover 80` in diamond

**Comment by martin-steinegger** [comment]
Yes, `--cov-mode 2 -c 0.8` this correct!  You can read more about it [here](https://github.com/soedinglab/MMseqs2/wiki#how-to-set-the-right-alignment-coverage-to-cluster).

**Comment by slambrechts** [comment]
ok great, thank you
