### ISSUE TITLE
Run as webserver on local cluster

### ISSUE THREAD

**Issue by hochshi** [soedinglab/MMseqs2#522]
Hi,

I would like to run mmseqs2 as a webserver locally on our cluster. I couldn't find any instructions on how to do so. Is there something I'm missing?
Hopefully, I would to leverage MPI for worker nodes and serve the API from a single node

Thank you

**Comment by martin-steinegger** [comment]
@hochshi the relevant repository for our server is here https://github.com/soedinglab/MMseqs2-App 
Their is a small guide how to set up a server.

**Comment by hochshi** [comment]
@martin-steinegger  thank you very much
