### ISSUE TITLE
clusterupdate excluding sequences

### ISSUE THREAD

**Issue by mbi2gs** [soedinglab/MMseqs2#53]
## Context
[test.fasta.txt](https://github.com/soedinglab/MMseqs2/files/1612640/test.fasta.txt)
[test_dup.fasta.txt](https://github.com/soedinglab/MMseqs2/files/1612641/test_dup.fasta.txt)

First, I created a DB and ran the cluster command on a small test set of 10 sequences (test.fasta)
Second, I duplicated 2 sequences by copying the sequence entries in the fasta file, and changed the sequence names (test_dup.fasta). I then created a new DB, and ran the clusterupdate command. For comparison, I also ran the cluster command on the new DB, to show the difference in output.

```
mkdir tmp tmp2 tmp3
mmseqs createdb test.fasta DB
mmseqs createdb test_dup.fasta DB_dup

# Clustering simple data set in "test.fasta"
mmseqs cluster DB clu1 tmp --min-seq-id 0.9 --cluster-mode 1

# Clustering duplicated data set in "test_dup.fasta"
mmseqs cluster DB_dup clu2 tmp2 --min-seq-id 0.9 --cluster-mode 1

# Updating cluster results "clu1" with new duplicated sequences 
# (expected to give similar output to "clu2")
mmseqs clusterupdate DB DB_dup clu1 clu3 tmp3 --min-seq-id 0.9 --cluster-mode 1
```

## Expected Behavior
Duplicated sequences to cluster together with the original sequences (which works when running cluster command on the duplicated data set).

clu2 is what I would expect, with the duplicated sequences 10 ("seq9B") and 12 ("seq10B") clustering with 9 ("seq9") and 11 ("seq10") respectively (1 and 6 are close homologs, so it's correct that they're clustering together):
```
2*
3*
4*
5*
6
1*
7*
8*
10
9*
12
11*
```

## Current Behavior
clu3 is NOT what I would expect. 10 and 12 are not included in the results. 
```
2*
3*
4*
5*
6
1*
7*
8*
9*
11*
```

## Your Environment
Running mmseqs2 from inside a Docker container derived from the Ubuntu:precise container.

**Comment by ClovisG** [comment]
Dear Matt,
Thanks a lot for your report!
Pulling the last version & recompiling it should so the trick. Note that your call should be:
`mmseqs clusterupdate DB DB_dup clu1 DB_mapped clu3 tmp3 --min-seq-id 0.9 --cluster-mode 1`

You can check the results by calling:
`mmseqs createtsv DB_dup DB_dup clu2 clu2.tsv
mmseqs createtsv DB_mapped DB_mapped clu3 clu3.tsv`

Best,
Clovis.

**Comment by mbi2gs** [comment]
Thanks for the quick response Clovis!

How is DB_mapped created?

**Comment by ClovisG** [comment]
Dear Matt,
It's the same DB as your new sequence DB, except that the keys in the ffindex are mapped to keep stable index (i.e. the conserved sequences that were in the original sequence DB will have the same keys in DB_mapped).

Best,
Clovis.

**Comment by mbi2gs** [comment]
Okay, great. Where do I find the DB_mapped files, or what command do I run to make them?

**Comment by ClovisG** [comment]
It's an output of the methode; it will be created automatically while you run the clusterupdate call.

**Comment by ClovisG** [comment]
Dear Matt,
I'll close the issue now, if you encounter further problems, do not hesitate to re-open it.

Best,
Clovis.

**Comment by mbi2gs** [comment]
Hi Clovis, I pulled the most recent version and recompiled it. 
Running the call
```
mmseqs clusterupdate DB DB_dup clu1 DB_mapped clu3 tmp3 --min-seq-id 0.9 --cluster-mode 1
```

resulted in the following error message:
```
Please recreate your database or add a .dbtype file to your sequence/profile database.
Error: Search died
```

I duplicated and renamed the "DB_dup.dbtype" file to "DB_mapped.dbtype", but that did not solve the issue.

Thanks

**Comment by ClovisG** [comment]
Hi Matt,
My bad. It should work now.

Sorry about that.
Clovis.

**Comment by mbi2gs** [comment]
Cool, I'll give it a try and check back.

**Comment by mbi2gs** [comment]
Worked like a charm!
