### ISSUE TITLE
Kalamari database link out of data

### ISSUE THREAD

**Issue by Mattstorey** [soedinglab/MMseqs2#531]
## Expected Behavior
`mmseqs databases Kalamari kalamari tmp` should grab the "Kalamari" sequences and produce a taxonomy database.

## Current Behavior
Fails to download anything and database creation crashes. Inspection of the ../data/workflow/databases.sh script shows the link to download a .tsv file from the kalamari repo is no longer valid. 

## Steps to Reproduce (for bugs)
`mmseqs databases Kalamari kalamari tmp`

## MMseqs Output (for bugs)

```
databases Kalamari kalamari tmp 

MMseqs Version:              	fcf52600801a73e95fd74068e1bb1afb437d719d
Force restart with latest tmp	false
Remove temporary files       	false
Compressed                   	0
Threads                      	8
Verbosity                    	3

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     34      0 --:--:-- --:--:-- --:--:--    34
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    32    0    32    0     0     24      0 --:--:--  0:00:01 --:--:--    24
createdb tmp/10928370746232574590/kalamari.fasta kalamari --compressed 0 -v 3 

Converting sequences

Time for merging to kalamari_h: 0h 0m 0s 3ms
Time for merging to kalamari: 0h 0m 0s 3ms
Database type: Nucleotide
The input files have no entry:  - tmp/10928370746232574590/kalamari.fasta
Please check your input files. Only files in fasta/fastq[.gz|bz2] are supported
Error: createdb died
```

## Context
Updating the link might partially resolve the error. I have tried a manual download of the Kalamari database but can't get the final taxonomy database to be successfully produced.  

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):MMseqs Version:              	fcf52600801a73e95fd74068e1bb1afb437d719d
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): Statically-compiled
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): ARMv8 Processor rev 0 (v8l) × 8 
* Operating system and version: Ubuntu 18.04

**Comment by martin-steinegger** [comment]
I have changed the link pointing to a commit that contains the 3.7v tsv file.
