### ISSUE TITLE
using mmseqs apply by passing file instead of stdin

### ISSUE THREAD

**Issue by sadiogo** [soedinglab/MMseqs2#536]
I've been trying to generate an MSA of each cluster using an external tool.

The problem is the external tool doesn't accept input from stdin and requires a file.

My workaround was to use ```ffindex_unpack``` to generate a file for each cluster and then pass those to external tool. But this can lead to  a lot of trouble and I want to avoid it,

How would one proceed to use ```mmseqs apply``` to generate a temporary file and pass that file to the external tool? 

I've been trying to generate a bash script for this but it's my first ever attempt with bash scripting and I'm having trouble "capturing" the entire cluster in the temporary file.

**Comment by sadiogo** [comment]
I have found a [wrapper script](https://github.com/soedinglab/MMseqs2/issues/196#issuecomment-485953970) that works in another issue. Alternatively, I also came up with simple solution:
```
#!/bin/bash

external-tool <(cat)
```

**Comment by milot-mirdita** [comment]
/dev/stdin might also work as a filename

**Comment by sadiogo** [comment]
Yes @milot-mirdita , that worked too!

Here's the full wrapper script for handling clusters with single sequences, should anybody else need it:
```
#!/bin/bash

FILE=$(mktemp)
cat /dev/stdin > $FILE

nseq=$( cat $FILE | grep -c '^>')

if [ $nseq -gt 1 ];
then
    external-tool $FILE
else
    cat $FILE
fi
```

**Comment by milot-mirdita** [comment]
I would recommend to add a `trap` call to cleanup the temp file, this could potentially create very many temp files and thus might lead to issues (see e.g. https://stackoverflow.com/questions/687014/removing-created-temp-files-in-unexpected-bash-exit)

**Comment by sadiogo** [comment]
Yeah, that definitely should go in:
```
#!/bin/bash

FILE=$(mktemp) || exit 1
trap 'rm -f "$FILE"' EXIT

cat /dev/stdin > $FILE

nseq=$( cat $FILE | grep -c '^>')

if [ $nseq -gt 1 ];
then
    external-tool $FILE
else
    cat $FILE
fi
```
