### ISSUE TITLE
Not listing matches above this fraction of aligned (covered) residues

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#56]
## Expected Behavior
Hi
Maybe we are missing something but when searching [query.fasta.gz](https://github.com/soedinglab/MMseqs2/files/1633161/query.fasta.gz) against [target.fasta.gz](https://github.com/soedinglab/MMseqs2/files/1633162/target.fasta.gz) with `-c 0.6 --cov-mode 2` it should report some hits. For example when we don't specify `-c` we get the following hits (`convertalis --format-mode 2`):
```
HMP|SRS011061-1749_-_6362_6616_orf-8|-  UniRef90_R6XCA5 0.880   81      10      0       4       84      933     1013    2.87E-45        151     84      1237
HMP|SRS011061-1749_-_6362_6616_orf-8|-  UniRef90_K1U8B3 0.926   76      6       0       4       79      48      123     5.41E-45        150     84      187
HMP|SRS011061-1749_-_6362_6616_orf-8|-  UniRef90_R6C0S7 0.920   76      6       0       4       79      936     1011    1.41E-44        149     84      1244
HMP|SRS011061-1749_-_6362_6616_orf-8|-  UniRef90_R5XLP5 0.920   76      6       0       4       79      935     1010    1.41E-44        149     84      1246
HMP|SRS011061-1749_-_6362_6616_orf-8|-  UniRef90_R7L9E9 0.908   76      7       0       4       79      935     1010    6.99E-44        147     84      1246
``` 
The query coverage is > 0.6 and in theory should pass the filter. We are using the commit **2c5dcabb805a4bd6d2db64095782a211aa1153fe** as we are having the same problems reported in https://github.com/soedinglab/MMseqs2/issues/55 with the last commit **ce3e98e04303a23e27392c2c49c18692b2474214** when searching.

Many thanks 
Antonio

## Steps to Reproduce (for bugs)
```
mmseqs createdb query.fasta.gz QUERY
mmseqs createdb target.fasta.gz DB
mmseqs search QUERY DB RESULT tmp -c 0.6 --cov-mode 2
```
## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 
**2c5dcabb805a4bd6d2db64095782a211aa1153fe**
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): 
**self-compiled**
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: 
**gcc version 5.4.0** and **cmake version 3.9.4**
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): 
CPU: **Intel(R) Xeon(R) CPU E7-4820 v4 @ 2.00GHz**
Memory: **2TB**
* Operating system and version:
**Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux**

**Comment by martin-steinegger** [comment]
Thanks for reporting this issue Antonio. I just pushed a fix for the issue.

**Comment by genomewalker** [comment]
Hi Martin
thank you very much, but something very weird is happening. If I search with `--cov-mode 2 -c 0.6` I get:
```
0 alignments calculated.
0 sequence pairs passed the thresholds (-nan of overall calculated).
0 hits per query sequence.
Time for alignments calculation: 0 h 0 m 0s
```
but when `--cov-mode 2 -c 0.59` or `--cov-mode 2 -c 0.61` then:
```
217 alignments calculated.
217 sequence pairs passed the thresholds (1 of overall calculated).
217 hits per query sequence.
Time for alignments calculation: 0 h 0 m 0s
```
Cheers
Antonio

**Comment by martin-steinegger** [comment]
Did you delete your tmp data?

**Comment by genomewalker** [comment]
My bad... time to go to bed... works as expected :-)

Many thanks
Antonio
