### ISSUE TITLE
Question: How to krona plot from easy-taxonomy

### ISSUE THREAD

**Issue by AmaliT** [soedinglab/MMseqs2#568]
Hi

I have run `mmseqs easy-taxonomy`on my query sequences using the `nr`database and now am keen to generate `krona` plot using `mmseqs taxonomyreport`. However I am a bit unsure on what I feed as resultDB for the `tanomyreport`module. Are you able to advise me on this. Thanks in advance

```
#workflow used
mmseqs databases NR ncbi_nr tmp 
mmseqs easy-taxonomy 00.rawdata/ccs.fasta 00.rawdata/M1.ccs.fasta ncbi_nr mmseq2_analysis/results tmp
```

**Comment by milot-mirdita** [comment]
You have to specify the `--report-mode 1` parameter to generate Krona output.

Splitting `easy-taxonomy` up makes generating both outputs at the same time easier:

```
mmseqs createdb 00.rawdata/ccs.fasta 00.rawdata/M1.ccs.fasta qdb
mmseqs taxonomy qdb ncbi_nr mmseq2_analysis/results tmp
mmseqs taxonomyreport ncbi_nr mmseq2_analysis/results  mmseq2_analysis/results_kraken --report-mode 0
mmseqs taxonomyreport ncbi_nr mmseq2_analysis/results  mmseq2_analysis/results_krona --report-mode 1
```

`easy-taxonomy` does a bunch additional output files that are slightly more difficult to replicate, however if you only need these two, i'd use this.
