### ISSUE TITLE
Error in `mmseqs': free(): invalid pointer: 0x0000000000ccb6d8 ***

### ISSUE THREAD

**Issue by genomewalker** [soedinglab/MMseqs2#57]
Hi,
here is the log for the error I reported in https://github.com/soedinglab/MMseqs2/issues/55#issuecomment-357820039

Many thanks
Antonio

## Expected Behavior

MMseqs2 should find the query in Uniref90 database 

## Current Behavior

MMseqs2 fails with `***free(): invalid pointer: 0x0000000000ccb6d8 ***` during the **prefilter**

## Steps to Reproduce (for bugs)

Query file: [query.fasta.gz](https://github.com/soedinglab/MMseqs2/files/1633833/query.fasta.gz)
Target file: ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz

```
export LIBC_FATAL_STDERR_=1
mmseqs createdb QUERY query.fasta.gz
mmseqs createdb DB uniref90.fasta.gz
mmseqs search QUERY DB resultsDB tmp --threads 64 2>&1 | tee search.log
```

## MMseqs Output (for bugs)
[search.log](https://github.com/soedinglab/MMseqs2/files/1633824/search.log)

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): 
**31e1fddc9b9368570bb39be3051232d4e64f7ae9**
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): 
**self-compiled**
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: 
**gcc version 5.4.0** and **cmake version 3.9.4**
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): 
CPU: **Intel(R) Xeon(R) CPU E7-4820 v4 @ 2.00GHz**
Memory: **2TB**
* Operating system and version:
**Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux**

**Comment by milot-mirdita** [comment]
Issue should be fixed now. Thank you for the bug report!

**Comment by genomewalker** [comment]
Hi Milot
now working as expected!
Many thanks
Antonio
