### ISSUE TITLE
Question: convertalis format-mode  and custom column headers

### ISSUE THREAD

**Issue by tamuanand** [soedinglab/MMseqs2#572]
Hi

I have a question on outputting custom column headers. This [wiki page](https://github.com/soedinglab/mmseqs2/wiki#custom-alignment-format-with-convertalis)  states: 
`Column headers can be added to the output with --format-mode 4`

I am using MMseqs2 Version: 13.45111 - when looking at the help text on command line, there does not seem to be a `--format-mode 4`  available. Am I missing something?

More importantly: how can I generate column headers?

Thanks in advance

```
mmseqs convertalis -h
usage: mmseqs convertalis <i:queryDb> <i:targetDb> <i:alignmentDB> <o:alignmentFile> [options]
 By Martin Steinegger <martin.steinegger@snu.ac.kr>
options: align:
 --gap-open TWIN           Gap open cost [nucl:5,aa:11]
 --gap-extend TWIN         Gap extension cost [nucl:2,aa:1]
misc:
 --format-mode INT         Output format: 0: BLAST-TAB, 1: SAM, 2: BLAST-TAB + query/db length, 3: Pretty HTML [0]
 --format-output STR       Choose comma separated list of output columns from: query,target,evalue,gapopen,pident,fident,nident,qstart,qend,qlen
                           tstart,tend,tlen,alnlen,raw,bits,cigar,qseq,tseq,qheader,theader,qaln,taln,qframe,tframe,mismatch,qcov,tcov
                           qset,qsetid,tset,tsetid,taxid,taxname,taxlineage,qorfstart,qorfend,torfstart,torfend [query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits]

```

**Comment by milot-mirdita** [comment]
This feature is only present in git MMseqs2. We still haven't managed to make a new release, since we were busy with other projects and also some personal stuff. Things should hopefully start to stabilize soon, so we might finish up a new MMseqs2 release. In the meantime you can use the precompiled binaries available at https://mmseqs.com/latest.

**Comment by martin-steinegger** [comment]
This should be now available in our newest release: https://github.com/soedinglab/MMseqs2/releases/tag/14-7e284
