### ISSUE TITLE
Multiple result database output files from mmseqs search

### ISSUE THREAD

**Issue by rachelmugge** [soedinglab/MMseqs2#579]
Hi,
I ran the `mmseqs search` command on one sample (named 'B001'), and all went well. Now I would like to use `mmseqs convertalis` to convert the result database file into a .m8 file; however, `mmseqs convertalis` expects one file as input for the result database, and the output from `mmseqs search` produced 10 result_db files from one sample:

`mmseqs2_B001_result_db.0	mmseqs2_B001_result_db.6
mmseqs2_B001_result_db.1	mmseqs2_B001_result_db.7
mmseqs2_B001_result_db.2	mmseqs2_B001_result_db.8
mmseqs2_B001_result_db.3	mmseqs2_B001_result_db.9
mmseqs2_B001_result_db.4	mmseqs2_B001_result_db.dbtype
mmseqs2_B001_result_db.5	mmseqs2_B001_result_db.index`

Is this acceptable? If so, is there a way to merge the 'result_db' files into one file? Alternatively, should I convert each of these outputs into a .m8 file separately, and then merge?

For reference, I ran this command to produce the above output:

`mmseqs search /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_query_db/mmseqs_B001_queryDB /Volumes/FireFly_Promise_Pegasus/Databases/mmseqs2_uniref90_db/UniRef90 /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/tmp --db-load-mode 3 --threads 10 --max-seqs 25 -s 1 -a -e 1e-5`

Thank you!

**Comment by milot-mirdita** [comment]
This is the expected output. MMseqs2 creates one output file for each thread and skips the merging step if its not 100% required, since merging can be quite slow.

You can just call `convertalis` on the basename and it will work as expected:
```
mmseqs search /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_query_db/mmseqs_B001_queryDB /Volumes/FireFly_Promise_Pegasus/Databases/mmseqs2_uniref90_db/UniRef90 /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db output.m8
```

If you really want MMseqs2 to create a merged database you can set the `MMSEQS_FORCE_MERGE=1` environment variable. Though I would generally not recommend to do that.

**Comment by rachelmugge** [comment]
Thanks for the reply. I ran this command: 

`mmseqs convertalis /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_query_db/mmseqs_B001_queryDB /Volumes/FireFly_Promise_Pegasus/Databases/mmseqs2_uniref90_db/UniRef90 /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/output.m8`

But received this error:

Input database "/Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db" has the wrong type (Generic)
Allowed input: Alignment

Does this mean there was an issue with the `mmseqs search` command from the step before?

**Comment by milot-mirdita** [comment]
can you do:
```
head -n 1 /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db*
```

and 

```
xxd /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db.dbtype
```

and post the result here?

**Comment by rachelmugge** [comment]
Sure-
Command:
`head -n 1 /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db*`

Output:
`head: Error reading /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db`

Command: 
`xxd /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db.dbtype`

Output:
`xxd: /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db.dbtype: No such file or directory`

So I modified the command (was missing a file name):
`xxd /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.dbtype`

Output:
`00000000: 0500 0000                                ....`

**Comment by rachelmugge** [comment]
Sorry, I should have caught that too- here's the output:

=> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.0 <==
43203327	69	0.966	1.240E-12	1	90	91	205	234	328	1	90	-1	-1	30M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.1 <==
334865	92	0.880	3.585E-20	0	149	150	237	286	749	0	149	-1	-1	50M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.2 <==
120149317	52	0.617	1.736E-06	11	112	118	176	209	708	2	115	-1	-1	34M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.3 <==
143724087	93	0.808	1.312E-20	141	1	150	350	396	468	147	1	-1	-1	47M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.4 <==
25771205	59	0.736	8.067E-09	35	148	151	0	37	218	32	148	-1	-1	38M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.5 <==
55486032	102	0.918	6.450E-24	147	1	150	688	736	909	147	1	-1	-1	49M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.6 <==
60998159	79	0.808	7.981E-16	0	140	143	175	221	427	0	140	-1	-1	47M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.7 <==
42373176	84	0.926	9.312E-18	1	123	126	257	297	470	1	123	-1	-1	41M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.8 <==
49017404	69	0.944	1.328E-12	111	4	113	37	72	197	111	1	-1	-1	36M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.9 <==
96050344	80	0.717	2.917E-16	1	138	141	5	50	110	1	138	-1	-1	46M

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.dbtype <==

==> /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db.index <==
0	0	4932

**Comment by milot-mirdita** [comment]
I think the same copy paste issue happened in the original `convertalis` command (`mmseqs2_B001_result_db/mmseqs2_B001_result_db`):

`
mmseqs convertalis /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_query_db/mmseqs_B001_queryDB /Volumes/FireFly_Promise_Pegasus/Databases/mmseqs2_uniref90_db/UniRef90 /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/mmseqs2_B001_result_db/mmseqs2_B001_result_db /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_2/08_mmseqs2/output.m8
`

This one should create the correct output file

**Comment by rachelmugge** [comment]
That was an easy fix. Thanks for catching my obvious mistake!
