### ISSUE TITLE
Manually limit memory consumption

### ISSUE THREAD

**Issue by jirihon** [soedinglab/MMseqs2#58]
Hi,
is it please possible to set a limit on the amount of memory MMseqs2 uses for its computations? Or to set the number of computation chunks?
I know from the MMseqs2 wiki it automatically detects how much memory it can use and eventually it splits database into chunks etc. But this is not practical for grid computing environment where you have to request a specific amount of memory a priori and your job is then executed on a machine which actually has much more memory but it is shared with other jobs. It can then happen that MMseqs2 will consume more memory than allowed just because its available from the system point of view. The queue management software will then kill the job as it exceeded assigned resources.

**Comment by milot-mirdita** [comment]
We do not currently have a very easy way to limit memory.

For the prefilter (main module for normal sequences searches) you can specify an appropriate `--split` value, that will then reduce the required memory to (I think there is an error in the user guide, have to double check, but this should be the correct formula):

```
(7 byte * N * L) / #splits + 8 byte * 21^k
```

We have to more very memory intense modules:`swapresults` and `kmermatcher`. These are very important for profile searches and linclust. Their splitting logic is however not exposed to the command line interface yet.

The clustering module also can use a lot of memory, but if you stay with the default cascaded clustering that should not become an issue.

A hack to limit how much memory `swapresults`, `kmermatcher`  and `prefilter` will use, would be to manually edit `size_t Util::getTotalSystemMemory()` in `commons/Util.cpp`.

We will discuss what we can do about this limiting memory issue internally and get back to you.

**Comment by jirihon** [comment]
What about to implement new command line option that would rewrite the output of `size_t Util::getTotalSystemMemory()` when set?

**Comment by milot-mirdita** [comment]
Thats one possibility, however the issue is quite a bit more complicated to solve generally.

First, `getTotalSystemMemory` is not used everywhere, only a few modules have a splitting logic.

There is also the issue that we read input databases completely into memory if they will have random accesses. That is also currently not tracked through `getTotalSystemMemory`. You can disable that for a few tools with `--no-preload`, but then you pay a large IO cost.

Then there is the issue that letting MMseqs2 share the memory bus among unrelated processes is probably also not the best idea. The prefilter benefits a lot from high-bandwidth, low latency access to its index structure.

**Comment by jirihon** [comment]
I hope it would be still very useful to have an option to override `getTotalSystemMemory`. I understand there might be modules that does not have a splitting logic (either it is not implemented yet, or it simply does not make sense) a many other aspects (like the preloading). But I see these as use cases where you simply MUST HAVE enough memory to be able to do the computations. On the other hand, the option to override `getTotalSystemMemory` would allow me to fake the total system memory to keep reasonable memory/computation length trade-off on grid computing architecture with job scheduler.

**Comment by milot-mirdita** [comment]
Replace the function with something like this:

```
size_t Util::getTotalSystemMemory() {
    char* memoryOverride = getenv("MMSEQS_MEMORY_OVERRIDE");
    if (memoryOverride != NULL) {
        return strtoull(memoryOverride, NULL, 10);
    }

    // check for real physical memory
    long pages = getTotalMemoryPages();
    long page_size = getPageSize();
    uint64_t sysMemory = pages * page_size;
    return sysMemory;
}
```

Then you can use `MMSEQS_MEMORY_OVERRIDE` env variable to control the maximum memory.

What are you trying to achieve? Manually setting `--split` would be my preferred solution, until we implement something better. That will work for all search modes (except target profile searches), but not for linclust and cascaded clustering.

**Comment by jirihon** [comment]
Thank you for this. Surely I can achieve the same thing using the `--split` option. Thank your also for adding a documentation. Previously, I could not find (in the wiki) what is the option for setting the number of chunks.

**Comment by milot-mirdita** [comment]
I just pushed a new parameter `--split-memory-limit` where you can specify how much memory the split based tools (prefilter, swap...) are allowed to use in megabyte.

**Comment by jirihon** [comment]
Thank you very much for adding this.

**Comment by milot-mirdita** [comment]
I broke something else though, hold on with upgrading just yet.

**Comment by milot-mirdita** [comment]
Now its okay
