### ISSUE TITLE
Can't  find ‘out.mm_msa'

### ISSUE THREAD

**Issue by Lsz-20** [soedinglab/MMseqs2#581]
I'm using the mmseqs2 in netsurfp,and something wrong with the result2msa,it seems that after search, the 'out.mm_msa' didn't exist.
Here are the output:
NetSurfP-2  : INFO     Running `mmseqs search example_out/mmseqs_files/in.mmdb db/swissprot example_out/mmseqs_files/out.mm_search /tmp/tmphggd3z8b --num-iterations 2 --max-seqs 2000`
03:25 NetSurfP-2  : INFO     Running `mmseqs result2msa example_out/mmseqs_files/in.mmdb db/swissprot example_out/mmseqs_files/out.mm_search example_out/mmseqs_files/out.mm_msa`
03:25 NetSurfP-2  : INFO     Parsing MMseqs2 MSA database
Traceback (most recent call last):
  File "/opt/conda/envs/netsurfp/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/netsurfp/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nfs/my/lsz/netsurfp2/netsurfp2/__main__.py", line 95, in <module>
    entry()    
  File "/nfs/my/lsz/netsurfp2/netsurfp2/__main__.py", line 59, in entry
    profiles = searcher(protlist, args.out)
  File "/nfs/my/lsz/netsurfp2/netsurfp2/preprocess.py", line 150, in __call__
    with open(mmmsa) as fdat, open(mmmsa + '.index') as fidx:
FileNotFoundError: [Errno 2] No such file or directory: 'example_out/mmseqs_files/out.mm_msa'

**Comment by milot-mirdita** [comment]
Can you try running `export MMSEQS_FORCE_MERGE=1` before running netsurfp?

**Comment by Lsz-20** [comment]
> export MMSEQS_FORCE_MERGE=1

It show me the same problem

**Comment by milot-mirdita** [comment]
netsurfp seems to not be really open source, so I can't find exactly whats going wrong. 

I found this https://github.com/Eryk96/NetSurfP-3.0/blob/main/nsp2/netsurfp2_dev/preprocessing/mmseqs.py, but it looks somewhat different to your error message.


I would recommend to make a fake mmseqs script that fixes the issue for netsurfp:
```
mv /opt/conda/envs/netsurfp/bin/mmseqs /opt/conda/envs/netsurfp/bin/mmseqs_real
cat << 'HERE' > /opt/conda/envs/netsurfp/bin/mmseqs
#!/bin/sh 
export MMSEQS_FORCE_MERGE=1
mmseqs_real "${@}"
HERE
chmod +x /opt/conda/envs/netsurfp/bin/mmseqs
```

**Comment by Lsz-20** [comment]
Sorry for the late reply，I have tried your method but it also show me the same question.I think i still need to explore it again.

**Comment by Lsz-20** [comment]
Is it caused by the version? I'm using mmseqs2=13.45111.
when i try to run the command:'mmseqs result2msa example_out/mmseqs_files/in.mmdb db/swissprot example_out/mmseqs_files/out.mm_search example_out/mmseqs_files/out.mm_msa', I found the output are 'out.mm_msa_***.ff***'
but the code in 'preprocess.py' which create out.mm_msa is 'mmmsa = os.path.join(mmdir, 'out.mm_msa')'
Is the different file name different when running the command?

**Comment by Lsz-20** [comment]
I have found the reason. the netsurfp use the older mmseqs2, so the output has the different name.
