### ISSUE TITLE
get the latest docker image

### ISSUE THREAD

**Issue by rujinlong** [soedinglab/MMseqs2#591]
Hi Martin & Milot,

It seems the latest build of mmseqs solved the GTDB issue https://github.com/soedinglab/MMseqs2/issues/561. I would like to use the docker image of this build, but the image on docker hub is outdated (one year ago)? I noticed the github actions built a latest image recently, where can I find the image?

best,
Jinlong

**Comment by milot-mirdita** [comment]
There are instructions on the github packges page:
https://github.com/soedinglab/MMseqs2/pkgs/container/mmseqs2

you have to pull the container from the github container registry. I don't think that we will use docker hub again in the future.

```
docker pull ghcr.io/soedinglab/mmseqs2:master
```

The container is built for x86_64 and arm64.

**Comment by rujinlong** [comment]
Thanks, Milot. This works.

**Comment by josemduarte** [comment]
Just came across this issue after seeing that docker hub was outdated. Would it be possible to add a note to docker hub to point people to github container registry?

**Comment by milot-mirdita** [comment]
Thanks for the note! I replaced the readme and description at docker hub with a pointer to GHCR.
