### ISSUE TITLE
createseqfiledb: Invalid entry in line x!

### ISSUE THREAD

**Issue by Kinaro7** [soedinglab/mmseqs2#6]
When I use createseqfiledb on a clusterDB file, as described in the readme, I get a continuous stream of "Invalid entry in line x!" messages, where x are different lines.

What does this error mean? The resulting clu_seq file is empty.

**Comment by Kinaro7** [comment]
Nevermind. I misunderstood how clusthash works.

**Comment by milot-mirdita** [comment]
Could you expand a bit on what you were trying? Maybe we can make mmseqs a bit user friendlier.

**Comment by Kinaro7** [comment]
I used a sequenceDB file, not an alignmentDB file, because I expected it to work like "cluster". That was easy to fix, though.

I still struggle a bit with understanding the output of the cluster modules.  What I actually want to do, is to use "clusthash" to reduce the redundancy of the PDB. The hope is, that this will reduce the number of chains enough, so I can create a somewhat useful visualization of the distance graph.

**Comment by martin-steinegger** [comment]
Do you try to cluster the database or just to reduce sequences that have exactly the same lenght? Hashclust can just reduce sequences of the same lenght while the clustering can reduce sequence of different lenght.

**Comment by Kinaro7** [comment]
I want to do multiple things.
First I want to reduce the redundancy of the DB by filtering out exact duplicates. "Hashclust" seems to detect exact duplicates after reducing the alphabet, which might be even better for my use case.
Later, I want to compare different clustering methods, including the ones provided by MMseqs.

If I understand the module correctly, "hashclust" creates an alignmentDB that includes all exact matches between sequences that have had their alphabet reduced. This alignmentDB can then be used by "clust" to cluster the sequences. If I use sequence identity in "clust", which can only be 1 or 0 (not listed) when I use "hashclust" the resulting clusters should contain only said reduced-alphabet-exact-matches.

Is that correct?

**Comment by martin-steinegger** [comment]
So using "hashclust" is already a bit advanced. You need to do two things in order to cluster with hashclust. First call hashclust and define your target sequence identity with --min-seq-id. As a second step you have to input the result database in the "clust" module. The result is your clustering.

**Comment by Kinaro7** [comment]
Ok, that is exactly what I did. The hard part was figuring out how to extract the clusters or better the representative sequences. I hope what I did (last paragraph of my previous comment) was correct. It felt a bit hacky, though.

Oh and by the way: Thanks to all contributors, for this awesome piece of software!

**Comment by martin-steinegger** [comment]
Thank you for your encouraging words. 
There is a way in MMseqs2. It will create fasta file of the rep sequences.

mmseqs result2msa qDb tDB clu clu_rep --only-rep-seq
mmseqs result2flat qDb tDB clu_rep clu_rep.fasta

**Comment by Kinaro7** [comment]
That looks more elegant than my solution, I will try that later.
