### ISSUE TITLE
How to get the cluster representative like cd-hit (-c 1.0)? 

### ISSUE THREAD

**Issue by ChongLC** [soedinglab/MMseqs2#601]
Dear MMSeqs2 devlopers, 

I was a user of CDHIT to remove the duplications in a dataset. However, it is not ready for big data. So, I come across MMSeqs2 which can be used as an alternative to CDHIT from this paper [(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6026198/)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6026198/). 

My command for CDHIT: 
cd-hit -i `<input fasta file>` -o `<output fasta file>` -c `1.00`

I have tested with a few parameters of MMSeqs clustering. Unfortunately, it does not work as expected. 
## example fasta file 
(consisting of 8 sequences - S2 and S3 are partial identical sequences of S1 while S5, S6, S7, and S8 are partial identical sequences of S4; expected final cluster representative: S1 and S4)
```
>S1
MKQYIVLACMCLVAAAMPTSLXXXXSSCTEEENKHHMGIDVIIKVTKQDQTPTNDKICQSVTEVTETEDDEVSEEVVKGDPTTYYTIVGAGLNMNFGFTKCPKILSISESSDGNTVNTRLSSVSPGQGKDSPAITREEALAMIKDCEMSIDIRCSEEEKDSDIKTHPVLGSNISHKKVSYKDIIGSTIVDTKCVKNLEFSVRIGDMCEESSELEVKDGFKYVDGSASEGATDDTSLIDSTKLKACV

>S2
MKQYIVLACMCLVAAAMPTSLXXXXSSCTEE

>S3
SEEEKDSDIKTHPVLGSNISHKKVSYKDIIGSTIVDTKCVKNLEFSVRIGDMCEESSELEVKDGFKYVDGSASEGATDDTSLIDSTKLKACV

>S4
MDEMDEIVRIVNDSMWYVPNAFMDDGDNEGHISVNNVCHMYLAFFDVDISSHLFKLVIKHCDLNKRLKCGNSPLHCYTMNTRFNPSVLKILLRHGMRNFDSKDKKGHIPLHHYLIHSLSIDNKIFDILTDPIDDFSKSSDLLLCYLRYKFNGSLNYYVLYKLLTKGSDPNCVDEDGLTSLHYYCKHISAFHESNYYKSKSHTKMRAEKRFIYAIIDHGANINAVTKIGNTPLHTYLQQYTKHSPRVVYALLSRGADTRIRNNLNCTPIMEYIKNDCATGHILIMLLNWHEQKYGKLQKEEGQHLLYLFIKHNQGYGSRSLNILRYLLDRFDIQKDEYYNTMTPLHTAFQNCNNNVASYLVYIGYDINLPTKDDKTVFDLVFENRNIIYKADVVNDIIHHRLKVSLPMIKSLFYKMSEFSPYDDHYVKKIIAYCLLRDESFAELHTKFCLNEDYKSVFMKNISFDKIDSIIEKCSRDISLLKEIRISDTDLYTVLRTEDIRYHTYLEAIHSDKRISFPMYDDLIEQCHLSMEHKSKLVDKALNKLESTIDSQSRLSYLPPEIMRNIITKLSDYHLNSMLYGKNHYKYYP

>S5
MDEMDEIVRIVNDSMWYVPNAFMDDGDNEGHISVNNVCHMYLAFFDVDISSHLFKLVIKHCDLNKRLKCGNSPLHCYTMNTRFNPSVLKILLRHGMRNFDSKDKKG

>S6
ANINAVTKIGNTPLHT

>S7
IVRIVNDSMWYVPNAFMDDGDNEGHISVNNVCHMYLAFFDVDISSHLFKLVIKHCDLNKRLKCGNSPLHCYTMNTRFNPSVLKILLRHGMRNFDSKDKKGHIPLHHYLIHSLSIDNKIFDILTDPIDDFSKSSDLLLCYLRYKFNGSLNYYVLYKLLTKGSDPNCVDEDGLTSLHYYCKHISAFHESNYYKSKSHTKMRAEKRFIYAIIDHGANINAVTKIGNTPLHTYLQQYTKHSPRVVYALLSRGADTRIRNNLNCTPIMEYIKNDCATGHILIMLLNWHEQKYGKLQKEEGQHLLYLFIKHNQGYGSRSLNILRYLLDRFDIQKDEYYNTMTPLHTAFQNCNNNVASYLVYIGYDINLPTKDDKTVFDLVFENRNIIYKADVVNDIIHHRLKVSLPMIKSLFYKMSEFSPYDDHYVKKIIAYCLLRDESFAELHTKFCLNEDYKSVFMKNISFDKIDSIIEKCSRDISLLKEIRISDTDLYTVLRTEDIRYHTYLEAIHSDKRISFPMYDDLIEQCHLSMEHKSKLVDKALNKLESTIDSQSRLSYLPPEIMRNIITKLSDYHLNSMLYGKNHY

>S8
LFIKHNQGYGSRSLNILRYLLDRFDIQKDEYYNTMTPLHTAFQNCNNNVASYLVYIGYDINLPTKDDKTVFDLVFENRNIIYKADVVNDIIHHRLKVSLPMIKSLFYKMSEFSPYDDHYVKKIIAYCLLRDESFAELHTKFCLNEDYKSVFMKNISFDKIDSIIEKCSRDISLLKEIRISDTDLYTVLRTEDIRYHTYLEAIHSDKRISFPMYDDLIEQCHLSMEHK
```

### Test 1 (--min-seq-id 1)
mmseqs cluster test_mmseqs/DB test_mmseqs/seqid1_v2 seqid1_tmp_v2 --min-seq-id 1

Result: 
| cluster_rep | cluster_member |
|-------------|-------------------|
| S1 | S1 |
| S2 | S2 |
| S3 | S3 |
| S5 | S5 |
| S6 | S6 |
| S7 | S4, S7 |
| S8 | S8 |

### Test 2 (--min-seq-id 1, -c 1.0, and --cov-mode 1)
mmseqs cluster test/DB test/seqid1_test seqid1_tmp --min-seq-id 1 --cov-mode 1 -c 1.0

Result: 
| cluster_rep | cluster_member |
|-------------|-------------------|
| S1 | S1, S3, S2 |
| S4 | S4, S5, S7, S8 | 
| S6 | S6 | 

** PS: 
1. This result is close to expected. However, I have no idea why the mmseqs does not group the S6 within the S4 cluster since S6 is a partial sequence of S4. 
2. There are no differences in the results if reducing the -c from 1.0 to 0. 

With these results, I am not sure if I use the correct parameter settings. Kindly advise me on the corresponding parameter to set for the MMSeqs2 cluster that is equivalent to CDHIT in order to have a non-redundant sequence dataset. 

Regards, 
Chong

**Comment by martin-steinegger** [comment]
@ChongLC interesting case. Thank you for the detailed analysis. The issue seems to occur because our default parameters are not sensitive enough to match S6 to S4. Following is a command that clusters the sequences correctly. We should consider using  `--exact-kmer-matching 1` as default for high similarities in MMseqs2. 
`mmseqs easy-cluster /tmp/test.fas test_clu tmp -c 1.0 --cov-mode 1 --min-seq-id 1.0 --exact-kmer-matching 1`
Alternative increasing `-s` also works.

**Comment by ChongLC** [comment]
@martin-steinegger 
Thank you for the suggestion. It works perfectly with the --exact-kmer-matching.
