### ISSUE TITLE
Not sure if clustering finished correctly

### ISSUE THREAD

**Issue by adimil** [soedinglab/MMseqs2#61]
## Current Behavior
When clustering is done I get these error messages about buffer size, I am not sure if this means there is a problem with the results. Should I run it again or is this fine?

## MMseqs Output (for bugs)
Clustering step 1...
Clustering step 2...
Clustering step 3...
Clustering step 4...
Clustering step 5...
Writing the results...
Tried to process the clustering list for the query 488890 , the length of the list = 169845
Output buffer size < clustering result size! (1000000 < 1559909)
Increase buffer size or reconsider your parameters -> output buffer is already huge ;-)
Tried to process the clustering list for the query 1208093 , the length of the list = 234332
Output buffer size < clustering result size! (1559910 < 2152804)
Increase buffer size or reconsider your parameters -> output buffer is already huge ;-)
Tried to process the clustering list for the query 11891971 , the length of the list = 277233
Output buffer size < clustering result size! (2152805 < 2534475)
Increase buffer size or reconsider your parameters -> output buffer is already huge ;-)
Time for merging files: 0 h 0 m 1 s
...done.

## Your Environment
MMseqs Version:	06c71aa6c8003203db75ebbb9f213fd34abcabd4

**Comment by milot-mirdita** [comment]
That should be fine, the mergeclusters util was rewritten since that commit and cannot produce that warning anymore (https://github.com/soedinglab/MMseqs2/commit/78280850cbfad179ea61dc1c59ac04fe3babaed1)

You probably should update to the latest version, that merging step will be faster.
