### ISSUE TITLE
mmseqs linux static version is actually dynamic

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#62]
## Expected Behavior
 wget https://mmseqs.com/latest/mmseqs-static_sse41.tar.gz
download static version of mmseqs

## Current Behavior
download dynamically linked binary instead.

## Steps to Reproduce (for bugs)
wget https://mmseqs.com/latest/mmseqs-static_sse41.tar.gz
tar -xvf mmseqs-static_sse41.tar.gz 
ldd ./mmseqs2/bin/mmseqs

## MMseqs Output (for bugs)
./mmseqs2/bin/mmseqs: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./mmseqs2/bin/mmseqs)
./mmseqs2/bin/mmseqs: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./mmseqs2/bin/mmseqs)
./mmseqs2/bin/mmseqs: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./mmseqs2/bin/mmseqs)
./mmseqs2/bin/mmseqs: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./mmseqs2/bin/mmseqs)
	linux-vdso.so.1 =>  (0x00007ffe4434b000)
	libz.so.1 => /lib64/libz.so.1 (0x0000003a88a00000)
	libbz2.so.1.0 => not found
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003a91a00000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003a87a00000)
	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x0000003a88e00000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003a91600000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003a87e00000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003a87600000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003a87200000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003a88600000)

**Comment by milot-mirdita** [comment]
Ahhh sorry, thanks a lot! Codeship just rebuild the release now.

I'll push the fixed build scripts for windows and osx also soonish, as soon as I've stabilized my local dev-branch.
