### ISSUE TITLE
Searching a large DB

### ISSUE THREAD

**Issue by adimil** [soedinglab/MMseqs2#63]
## Context
I have a large DB (~140 million proteins) and I want to search against it many times.

## Current Behavior
If I try to create an index it results in a very large file (~300G) which is impossible to use.
I tried creating the index with --split but I get the error:
`Creating a split index is not supported anymore.`

What would be the right way to conduct this search? Should I split the DB manually?

## Your Environment
`MMseqs Version:         9f344f3d6765a1131f22794d9a6fd9fcd8ca2cdf`

_Thanks,
Adi_

**Comment by martin-steinegger** [comment]
Do not index the database so it splits it on the fly.  

      mmseqs createdb LARGE.fasta LARGE
      mmseqs search LARGE LARGE aln /tmp/

This issue is related to https://github.com/soedinglab/MMseqs2/issues/49. We will work on a split able index solution.

**Comment by milot-mirdita** [comment]
Duplicate/Related #49
