### ISSUE TITLE
persisten segmentation fault error across different contig datasets 

### ISSUE THREAD

**Issue by clb21565** [soedinglab/MMseqs2#632]
## Expected Behavior
easy-cluster should be successfully clustering a set of contigs 
## Current Behavior
easy-cluster fails to cluster due to memory usage issue(?) 

multiple different contig files fail, subsets of the same contig file also fails, this is especially true for larger contigs (100kbp-300kbp) 

the odd thing is that i have rarely ever had troubles with mmseqs in recent memory

PS: Y'all are ANGELS for keeping up with all the users and issues listed for mmseqs. Seriously grateful, hoping you have ample funding to keep the devs happy... 

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

mmseqs easy-cluster contigs.fasta contigs99 contigs99.tmp --min-seq-id 0.99 -c 0.6 --cov-mode 1

in addition, i think these posts are also relevant 
https://github.com/soedinglab/MMseqs2/issues/617
https://github.com/soedinglab/MMseqs2/issues/608

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

MMseqs Version:                                                                 7.4e23d
Sub Matrix                                                                      blosum62.out
Rescore mode                                                                    0
Remove hits by seq.id. and coverage                                             false
E-value threshold                                                               0.001
Coverage threshold                                                              0.6
Coverage Mode                                                                   1
Seq. Id Threshold                                                               0.99
Seq. Id. Mode                                                                   0
Include identical Seq. Id.                                                      false
Sort results                                                                    0
In substitution scoring mode, performs global alignment along the diagonal      false
Preload mode                                                                    0
Threads                                                                         128
Verbosity                                                                       3

Prefilter database: contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref
Query database: contigs99.tmp/13034246008736284953/input
Touch data file contigs99.tmp/13034246008736284953/input ... Done.
Target database: contigs99.tmp/13034246008736284953/input
Result database: contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref_rescore1
...............................................
Done.
Time for merging files: 0h 0m 0s 679ms
Time for processing: 0h 0m 1s 529ms
Program call:
clust contigs99.tmp/13034246008736284953/input contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref_rescore1 contigs99.tmp/13034246008736284953/clu_tmp/2990889066216
221615/linclust/5258601894198672332/pre_clust --cluster-mode 3 --max-iterations 1000 --similarity-type 2 --threads 128 -v 3 

MMseqs Version:                 7.4e23d
Cluster mode                    3
Max depth connected component   1000
Similarity type                 2
Threads                         128
Verbosity                       3

Init...
Opening sequence database...
Opening alignment database...
done.
Clustering mode: Greedy Low Mem
Writing results...
...done.
Time for clustering: 0h 0m 0s 268ms
Time for merging files: 0h 0m 0s 219ms
Total time: 0h 0m 0s 601ms

Size of the sequence database: 479805
Size of the alignment database: 479805
Number of clusters: 463570
Time for processing: 0h 0m 0s 814ms
Program call:
createsubdb contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/order_redundancy contigs99.tmp/13034246008736284953/input contigs99.tmp/13034246008736284953/clu_tmp/2990
889066216221615/linclust/5258601894198672332/input_step_redundancy 

MMseqs Version: 7.4e23d
Verbosity       3

Start writing to file contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/input_step_redundancy
Time for merging files: 0h 0m 0s 103ms
Time for processing: 0h 0m 1s 107ms
Program call:
createsubdb contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/order_redundancy contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672
332/pref contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref_filter1 

MMseqs Version: 7.4e23d
Verbosity       3

Start writing to file contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref_filter1
Time for merging files: 0h 0m 0s 99ms
Time for processing: 0h 0m 0s 357ms
Program call:
filterdb contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref_filter1 contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pre
f_filter2 --filter-file contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/order_redundancy 

MMseqs Version:                 7.4e23d
Filter column                   1
Column to take                  -1
Filter regex                    ^.*$
Positive filter                 true
Filter file                     contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/order_redundancy
Beats first                     false
Mapping file                  
Threads                         128
Verbosity                       3
trim the results to one column  false
Extract n lines                 0
Numerical comparison operator 
Numerical comparison value      0
Sort entries                    0
Include identical Seq. Id.      false
join to DB                    
Compute Positions             
Replace transitively          

Filtering with a filter files.
..............................................Time for merging files: 0h 0m 0s 668ms
Time for processing: 0h 0m 2s 11ms
Program call:
align contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/input_step_redundancy contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/52586018941986723
32/input_step_redundancy contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/pref_filter2 contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601
894198672332/aln --sub-mat blosum62.out -a 0 --alignment-mode 3 -e 0.001 --min-seq-id 0.99 --seq-id-mode 0 --alt-ali 0 -c 0.6 --cov-mode 1 --max-seq-len 65535 --max-seqs 2147483647 --comp-bias-corr 0 --realign
 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 128 -v 3 

MMseqs Version:                 7.4e23d
Sub Matrix                      blosum62.out
Add backtrace                   false
Alignment mode                  3
E-value threshold               0.001
Seq. Id Threshold               0.99
Seq. Id. Mode                   0
Alternative alignments          0
Coverage threshold              0.6
Coverage Mode                   1
Max. sequence length            65535
Max. results per query          2147483647
Compositional bias              0
Realign hit                     false
Max Reject                      2147483647
Max Accept                      2147483647
Include identical Seq. Id.      false
Preload mode                    0
Pseudo count a                  1
Pseudo count b                  1.5
Score bias                      0
Gap open cost                   11
Gap extension cost              1
Threads                         128
Verbosity                       3

Init data structures...
Compute score, coverage and sequence id.
Touch data file contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/input_step_redundancy ... Done.
Query database type: Nucleotide
Target database type: Nucleotide
**Calculation of Smith-Waterman alignments.
.contigs99.tmp/13034246008736284953/clu_tmp/2990889066216221615/linclust/5258601894198672332/linclust.sh: line 73: 121353 Segmentation fault      $RUNNER "$MMSEQS" "${ALIGN_MODULE}" "$INPUT" "$INPUT" "$RESULTD
B" "${TMP_PATH}/aln" ${ALIGNMENT_PAR}
Error: Alignment step died
Error: linclust died
Error: Search died**

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
7.4e23d

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
statically-compiled using conda

* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
Nodes: 1
Cores per node: 128
Memory: 240.00 GB

* Operating system and version:
linux

**Comment by milot-mirdita** [comment]
Can you try the newest MMseqs2 release? 7 is really ancient. MMseqs2 is however really not well tested for clustering whole genomes. You might have more luck in running only linclust and not the whole clustering workflow.

> PS: Y'all are ANGELS for keeping up with all the users and issues listed for mmseqs. Seriously grateful, hoping you have ample funding to keep the devs happy...
🥲

**Comment by clb21565** [comment]
WOW, i really installed the wrong one bad 
fixed it
best wishes
connor
