### ISSUE TITLE
How to avoid getting multiple split databases

### ISSUE THREAD

**Issue by tnn111** [soedinglab/MMseqs2#644]
Hi,

I'm trying to use the taxonomy feature and when I do, my output DB seems to be split in many smaller DBs. Is there any way to control this split? I'd like to just turn it off. I have 1 TB of memory so I shouldn't have problems.

Other than that, this works great!

**Comment by milot-mirdita** [comment]
You can set the `MMSEQS_FORCE_MERGE` environment variable (e.g. `export MMSEQS_FORCE_MERGE=1`). The split databases are, however, an IO optimization and not related to memory. Merging after every module invocation can slow MMseqs2 down considerably.

**Comment by tnn111** [comment]
Is there a way of merging them after the run is done? It’s not a big deal; it’s just a little less cluttered.

I really appreciate the software. I’ve been using the taxonomy module extensively with impressive results. Thank you!

**Comment by PabloOfEpidemiology** [comment]
I'm having the same problem with the linclust command. I get many DB files, perhaps because the original dataset that I am clusterising is huge (16 million SARS sequences). I wonder, if there is a way to merge them post-alignment/linclust?

**Comment by milot-mirdita** [comment]
`easy-linclust` will merge the results into easily processable `.tsv` files. You should use the `linclust` workflow only if you want to process the MMseqs2 internal database formats with other MMseqs2 modules.
