### ISSUE TITLE
How to run --cascaded in the latest MMseqs2 version?

### ISSUE THREAD

**Issue by ksteczk** [soedinglab/MMseqs2#65]
I tried to run cascaded clustering on a database:
`mmseqs cluster pdb pdb_005 tmp -e 0.005 --cluster-mode 1 --cascaded -t 24`
but the program doesn't recognize --cascaded option, although it is mentioned on the wikipage. I found out another option from the '-h' help: --single-step-clustering and set it up to false:
`mmseqs cluster pdb pdb_005 tmp -e 0.005 --cluster-mode 1 --threads 24 --single-step-clustering false`
and I get:

> Program call:
> pdb pdb_005 tmp -e 0.005 --cluster-mode 1 --threads 24 --single-step-clustering false
> 
> MMseqs Version:                                                                 GITDIR-NOTFOUND
> Sub Matrix                                                                      blosum62.out
> Sensitivity                                                                     4
> K-mer size                                                                      0
> K-score                                                                         2147483647
> Alphabet size                                                                   21
> Max. sequence length                                                            32000
> Max. results per query                                                          20
> Offset result                                                                   0
> Split DB                                                                        0
> Split mode                                                                      2
> Split Memory Limit                                                              0
> Coverage threshold                                                              0.8
> Coverage Mode                                                                   0
> Compositional bias                                                              1
> Diagonal Scoring                                                                1
> Mask Residues                                                                   1
> Minimum Diagonal score                                                          15
> Include identical Seq. Id.                                                      false
> Spaced Kmer                                                                     1
> No preload                                                                      false
> Early exit                                                                      false
> Pseudo count a                                                                  1
> Pseudo count b                                                                  1.5
> Threads                                                                         24
> Verbosity                                                                       3
> Add backtrace                                                                   false
> Alignment mode                                                                  3
> E-value threshold                                                               0.005
> Seq. Id Threshold                                                               0
> Realign hit                                                                     false
> Max Reject                                                                      2147483647
> Max Accept                                                                      2147483647
> Cluster mode                                                                    1
> Max depth connected component                                                   1000
> Similarity type                                                                 2
> Single step clustering                                                          false
> Cascaded clustering steps                                                       3
> Remove Temporary Files                                                          false
> Sets the MPI runner
> Kmer per sequence                                                               20
> Shift hash                                                                      5
> Rescore mode                                                                    0
> Remove hits by seq.id. and coverage                                             false
> In substitution scoring mode, performs global alignment along the diagonal      false
> 
> Set cluster settings automatic to s=6
> Set cluster iterations to 3
> Please provide \<sequenceDB\> \<outDB\> \<tmp\>

I use self compiled version, cloned from the git yesterday (20180220).
`mmseqs`

> MMseqs2 Version: GITDIR-NOTFOUND

So how to run cascaded clustering? I'm also not sure whether missing version number means something went wrong...

**Comment by milot-mirdita** [comment]
We recently made cascaded the default, since it performs better and has fewer potential runtime pitfalls.

Also please note that switch parameters such as `--single-step-clustering` do not take an argument.
With `--single-step-clustering false` you would run a single step clustering.

I'll update the documentation. Sorry about that!

**Comment by ksteczk** [comment]
Great, it worked, thank you.

**Comment by milot-mirdita** [comment]
I'll leave this ticket open, until I updated the documentation.
