### ISSUE TITLE
Extract hits from targetdb

### ISSUE THREAD

**Issue by fmaumusINRA** [soedinglab/MMseqs2#662]
Hi,

I have a dummy question here but can't figure it out.
I have searched a querydb against uniprot db and used filterdb to keep the best matches only.
Now I would like to build a new db that contains only those best matches, i.e. to extract a list of uniprot ids to a new db, and create the corresponding fasta file using convert2fasta.
Any help would be warmly appreciated!

**Comment by milot-mirdita** [comment]
`createseqfiledb` is what you want, kind of. It still returns an MMseqs2 database containing the sequences in fasta format. But its easy to remove the null bytes and just interpret this as a FASTA file. `--threads 1` forces it to not create multiple splits.

```
mmseqs createdb QUERY.fasta qdb
mmseqs createdb DB.fasta db
mmseqs search qdb db res tmp
mmseqs createseqfiledb db res outdb --threads 1
tr -d '\000' < outdb > outdb.fasta
```

this is something that is annoyingly non-obvious since forever. We should definitely improve this.

**Comment by fmaumusINRA** [comment]
Thanks a lot for your fast response.
I have tried and I am getting the following error
Invalid database read for id=36855603, database index=../../uniprot.index
getEntryLen: local id (36855603) >= db size (27159746)

I have done createindex on the uniprot db but the error remains.

**Comment by milot-mirdita** [comment]
Can you post the command line call you executed?

Also, please don’t use createindex if you don’t know that you need it, it’s pretty easy to make stuff slower with it.

**Comment by fmaumusINRA** [comment]
Yes, I am using taxonomy filtered uniprot as db
nohup mmseqs search nemat_prt70_Vir120_prt35 ../../uniprot_jan2022/U90c22_euk_noNem_noStrepto ViridiRep_vs_U90c22_euk_noNem_noStrepto /mnt/2to-stockage/tmp/ 1>& search.out &
mmseqs createseqfiledb ../../uniprot_jan2022/U90c22_euk_noNem_noStrepto ViridiRep_vs_U90c22_euk_noNem_noStrepto outdb --threads 1

**Comment by fmaumusINRA** [comment]
Ow, your solution seems to work when I am using the whole uniprot as db with createseqfiledb instead of the taxonomy filtered version.
mmseqs createseqfiledb ../../uniprot_jan2022/U90_22 ViridiRep_vs_U90c22_euk_noNem_noStrepto outdb --threads 1
Thanks a lot!

**Comment by fmaumusINRA** [comment]
> this is something that is annoyingly non-obvious since forever. We should definitely improve this.

Hello,
Is this somehow fixed in a recent release?
Thanks
