### ISSUE TITLE
Best-hit iterative search produces hits far from best

### ISSUE THREAD

**Issue by sleyn** [soedinglab/MMseqs2#67]
Hello!

I've installed mmseqs2 to CentOS 7 with linuxbrew.
I'm trying to search best hits with iterative approach suggested in manual:

`mmseqs search "$query" "$target" result tmp --start-sens 1 --sens-steps 3 -s 7 --max-accept 1`
 
I've compared this method with BLAST on a small dataset. However mmseqs2 produces not a best hit but just some hit. For example:

`PS064S07MM_81253        fig|6666666.201545.peg.1407     0.509   1167    572     0       0       1167    0       1155    0.00E+00        1101` 

If I run the standard search:

`mmseqs search "$query" "$target" result tmp`

I see the same best hit as in BLAST with the best score and e-value. Here is the convertalis output till the real best hit appears:

`PS064S07MM_81253        fig|6666666.201634.peg.2302     0.536   1172    543     0       0       1167    0       1172    0.00E+00        1182                                                                                                
PS064S07MM_81253        fig|451640.5.peg.1619   0.685   1172    369     0       0       1168    0       1172    0.00E+00        1599                                                                                                        
PS064S07MM_81253        fig|1125712.3.peg.1765  0.518   1178    567     0       0       1165    0       1178    0.00E+00        1137                                                                                                        
PS064S07MM_81253        fig|553184.4.peg.556    0.528   1170    552     0       0       1165    0       1170    0.00E+00        1158                                                                                                        
PS064S07MM_81253        fig|633147.4.peg.496    0.521   1179    564     0       0       1167    0       1179    0.00E+00        1147                                                                                                        
PS064S07MM_81253        fig|428126.7.peg.233    0.693   1171    359     0       0       1165    0       1171    0.00E+00        1619                                                                                                        
PS064S07MM_81253        fig|1121444.3.peg.1136  0.531   1169    548     0       0       1167    0       1169    0.00E+00        1165                                                                                                        
PS064S07MM_81253        fig|755731.4.peg.2885   0.547   1176    532     0       0       1168    0       1176    0.00E+00        1216                                                                                                        
PS064S07MM_81253        fig|1118059.3.peg.6     0.523   1176    560     0       0       1168    0       1176    0.00E+00        1151                                                                                                        
PS064S07MM_81253        fig|545697.3.peg.2439   0.543   1178    538     0       0       1168    0       1178    0.00E+00        1206                                                                                                        
PS064S07MM_81253        fig|938293.3.peg.417    0.524   1176    559     0       0       1166    0       1176    0.00E+00        1152                                                                                                        
PS064S07MM_81253        fig|879305.3.peg.501    0.529   1173    552     0       0       1166    0       1173    0.00E+00        1163                                                                                                        
PS064S07MM_81253        fig|655811.4.peg.25     0.538   1167    539     0       0       1158    0       1167    0.00E+00        1184                                                                                                        
PS064S07MM_81253        fig|525254.4.peg.863    0.525   1172    556     0       0       1166    0       1172    0.00E+00        1151                                                                                                        
PS064S07MM_81253        fig|6666666.201634.peg.2160     0.548   1169    528     0       0       1168    0       1169    0.00E+00        1213                                                                                                
PS064S07MM_81253        fig|6666666.201633.peg.572      0.544   1171    533     0       0       1168    0       1171    0.00E+00        1204                                                                                                
PS064S07MM_81253        fig|457396.3.peg.1949   0.549   1168    526     0       0       1168    0       1166    0.00E+00        1215                                                                                                        
PS064S07MM_81253        fig|1121334.3.peg.2512  0.552   1176    526     0       0       1159    0       1176    0.00E+00        1231                                                                                                        
PS064S07MM_81253        fig|499175.4.peg.2318   0.544   1179    537     0       0       1167    0       1179    0.00E+00        1212                                                                                                        
PS064S07MM_81253        fig|1384484.3.peg.1483  0.536   1178    546     0       0       1167    0       1178    0.00E+00        1187                                                                                                        
PS064S07MM_81253        fig|1128398.3.peg.2095  0.579   1167    491     0       0       1159    0       1167    0.00E+00        1296                                                                                                        
PS064S07MM_81253        fig|292800.11.peg.3738  0.518   1208    582     0       0       1167    0       1208    0.00E+00        1166                                                                                                        
PS064S07MM_81253        fig|592010.4.peg.3012   0.546   1162    527     0       0       1155    0       1162    0.00E+00        1200                                                                                                        
PS064S07MM_81253        fig|445971.6.peg.1432   0.537   1167    540     0       0       1163    0       1167    0.00E+00        1179                                                                                                        
PS064S07MM_81253        fig|1158602.4.peg.3929  0.503   1174    583     0       0       1166    0       1174    0.00E+00        1091                                                                                                        
PS064S07MM_81253        fig|1408436.3.peg.2383  0.533   1172    547     0       0       1165    0       1172    0.00E+00        1174                                                                                                        
PS064S07MM_81253        fig|563192.3.peg.1723   0.515   1168    566     0       0       1159    0       1168    0.00E+00        1118                                                                                                        
PS064S07MM_81253        fig|290402.41.peg.4483  0.545   1166    530     0       0       1166    0       1166    0.00E+00        1200                                                                                                        
PS064S07MM_81253        fig|657324.3.peg.842    0.518   1172    564     0       0       1165    0       1172    0.00E+00        1133                                                                                                        
PS064S07MM_81253        fig|1211819.3.peg.886   0.960   1168    46      0       0       1168    0       1168    0.00E+00        2359`

So what produces the best-hit search workflow is far from the real best hit. Could I improve it or what I've done wrong? 

Thanks!

**Comment by martin-steinegger** [comment]
Yes there is indeed a chance that the best hit is not found but the chances are low. Prefilter hits found at a lower sensitivity threshold, have more highly conserved k-mers in common. 

Could you try to remove the '--max-accept 1' parameter. Max accept will just align the hits coming from the prefilter until max accept hits are found. It is highly likely that your best hit did not get ranked number 1 since there seem to be so many similar sequences.

**Comment by sleyn** [comment]
Thanks! Without --max-accept 1 this works much better! However there is still ~30 proteins (from the 1100 in query) that have significantly less ident than in BLAST. Like 50-60% vs 90%. I compared idents with the "--alignment-mode 3"  parameter which should produce ident similar to BLAST. They seems to be 3-rd or 4-th hits in the BLAST output but with significant drop of bit score even with the same 0 e-value.

Also why convertalis do not sort output by e-value/bit score?

**Comment by milot-mirdita** [comment]
The results should improve, if you start with a higher start sensitivity (`--start-sens 4`), which should still be plenty fast.

The results should be sorted within each query by e-value.

**Comment by sleyn** [comment]
Thank you for a quick responces, it seems to work well!

I just suggest to sort results with also score because for example in my case a lot of sequences produces 0 e-value with rather big difference in identitiy.

**Comment by milot-mirdita** [comment]
Looking at the score, it should be doing exactly that, could you post an excerpt from your resulting tsv?

**Comment by sleyn** [comment]
For many proteins it is so, but there is still some that produces random sorting.

My first post has the copy-paste from the output. The first hit has score 1182 and 30-th has 2359.

From the last run:
```
PS064S07MM_81253        fig|665943.3.peg.2454   0.544   1174    535     0       1       1167    1       1175    0.00E+00        1194                                                                                                        
PS064S07MM_81253        fig|553171.3.peg.1376   0.528   1180    556     0       3       1168    5       1185    0.00E+00        1159                                                                                                        
PS064S07MM_81253        fig|1280692.3.peg.1008  0.557   1159    513     0       7       1166    6       1164    0.00E+00        1206                                                                                                        
PS064S07MM_81253        fig|561177.4.peg.557    0.536   1165    540     0       7       1166    9       1174    0.00E+00        1157                                                                                                        
PS064S07MM_81253        fig|626939.3.peg.1505   0.558   1161    513     0       7       1166    6       1167    0.00E+00        1214                                                                                                        
PS064S07MM_81253        fig|742817.3.peg.1357   0.563   1160    506     0       3       1159    5       1165    0.00E+00        1256                                                                                                        
PS064S07MM_81253        fig|428126.7.peg.233    0.683   1170    370     0       1       1165    1       1171    0.00E+00        1619                                                                                                        
PS064S07MM_81253        fig|86416.3.peg.2971    0.522   1177    562     0       1       1167    1       1178    0.00E+00        1131                                                                                                        
PS064S07MM_81253        fig|742818.3.peg.1186   0.544   1176    536     0       1       1167    1       1177    0.00E+00        1175                                                                                                        
PS064S07MM_81253        fig|938294.3.peg.1047   0.532   1171    548     0       1       1166    3       1174    0.00E+00        1176                                                                                                        
PS064S07MM_81253        fig|1122217.3.peg.1576  0.540   1171    538     0       1       1166    1       1172    0.00E+00        1182                                                                                                        
PS064S07MM_81253        fig|1118059.3.peg.6     0.523   1175    560     0       1       1168    1       1176    0.00E+00        1151                                                                                                        
PS064S07MM_81253        fig|1123313.3.peg.779   0.538   1172    541     0       1       1165    1       1173    0.00E+00        1156                                                                                                        
PS064S07MM_81253        fig|999412.4.peg.272    0.553   1170    522     0       1       1165    1       1171    0.00E+00        1197                                                                                                        
PS064S07MM_81253        fig|1408436.3.peg.2383  0.535   1171    544     0       1       1165    1       1172    0.00E+00        1174                                                                                                        
PS064S07MM_81253        fig|1235834.3.peg.1094  0.522   1169    558     0       1       1168    1       1170    0.00E+00        1116                                                                                                        
PS064S07MM_81253        fig|1095747.3.peg.509   0.578   1180    497     0       1       1166    1       1181    0.00E+00        1328                                                                                                        
PS064S07MM_81253        fig|393480.8.peg.1669   0.573   1178    503     0       1       1166    1       1179    0.00E+00        1332                                                                                                        
PS064S07MM_81253        fig|445971.6.peg.1432   0.543   1166    532     0       1       1163    1       1167    0.00E+00        1179                                                                                                        
PS064S07MM_81253        fig|1128398.3.peg.2201  0.528   1174    554     0       1       1167    1       1175    0.00E+00        1170                                                                                                        
PS064S07MM_81253        fig|1262449.3.peg.1585  0.523   1177    561     0       1       1167    1       1178    0.00E+00        1140                                                                                                        
PS064S07MM_81253        fig|457404.3.peg.2092   0.577   1184    500     0       1       1166    1       1185    0.00E+00        1335                                                                                                        
PS064S07MM_81253        fig|441770.6.peg.1154   0.518   1162    560     0       1       1159    1       1163    0.00E+00        1157                                                                                                        
PS064S07MM_81253        fig|469601.3.peg.853    0.582   1176    491     0       1       1166    1       1177    0.00E+00        1352                                                                                                        
PS064S07MM_81253        fig|451640.5.peg.1619   0.675   1171    380     0       1       1168    1       1172    0.00E+00        1599                                                                                                        
PS064S07MM_81253        fig|1278306.3.peg.1629  0.585   1186    492     0       1       1166    1       1187    0.00E+00        1361                                                                                                        
PS064S07MM_81253        fig|1211819.3.peg.886   0.997   1167    3       0       1       1168    1       1168    0.00E+00        2359
```

**Comment by sleyn** [comment]
No, everywhere where there are several hits with 0 e-value sorting inside the same e-value is not working:

```
PS064S07MM_22442        fig|470145.6.peg.1745   0.892   762     82      0       1       761     1       763     0.00E+00        1354                                                                                                        
PS064S07MM_22442        fig|537011.5.peg.182    0.735   780     206     0       1       763     1       781     0.00E+00        1135                                                                                                        
PS064S07MM_22442        fig|679189.3.peg.154    0.728   779     211     0       1       761     1       780     0.00E+00        1138                                                                                                        
PS064S07MM_22442        fig|1122985.3.peg.1423  0.759   781     188     0       1       763     1       782     0.00E+00        1188                                                                                                        
PS064S07MM_22442        fig|1121101.3.peg.847   0.932   760     51      0       1       761     1       761     0.00E+00        1411                                                                                                        
PS064S07MM_22442        fig|997886.3.peg.1854   0.966   761     25      0       1       762     1       762     0.00E+00        1463                                                                                                        
PS064S07MM_22442        fig|693979.3.peg.1549   0.805   781     152     0       1       762     1       782     0.00E+00        1260                                                                                                        
PS064S07MM_22442        fig|752555.5.peg.2106   0.732   779     208     0       1       762     1       780     0.00E+00        1136                                                                                                        
PS064S07MM_22442        fig|1121129.3.peg.262   0.718   765     215     0       1       762     1       766     0.00E+00        1075                                                                                                        
PS064S07MM_22442        fig|888832.3.peg.658    0.706   763     224     0       1       760     1       764     0.00E+00        1072                                                                                                        
PS064S07MM_22442        fig|1073351.3.peg.1244  0.930   767     53      0       1       762     1       768     0.00E+00        1409                                                                                                        
PS064S07MM_22442        fig|762982.3.peg.2952   0.805   783     152     0       1       761     1       784     0.00E+00        1252                                                                                                        
PS064S07MM_22442        fig|1121099.3.peg.1781  0.780   786     172     0       1       763     1       787     0.00E+00        1201                                                                                                        
PS064S07MM_22442        fig|563031.3.peg.1927   0.692   790     243     0       1       760     1       791     0.00E+00        1072                                                                                                        
PS064S07MM_22442        fig|997352.4.peg.709    0.706   780     229     0       1       760     1       781     0.00E+00        1083                                                                                                        
PS064S07MM_22442        fig|1122993.3.peg.1367  0.686   787     247     0       1       760     1       788     0.00E+00        1056                                                                                                        
PS064S07MM_22442        fig|767031.3.peg.114    0.677   795     256     0       1       760     1       796     0.00E+00        1049 
```

**Comment by milot-mirdita** [comment]
Ah sorry, its not actually sorting by sequence identity, but by e-value and then bit-score.
In this case fig|470145.6.peg.1745 had a higher alignment score than fig|537011.5.peg.182.

I am not sure what the best output behavior would be. What do you think @martin-steinegger?

**Comment by sleyn** [comment]
@milot-mirdita but bit scores (the most right column) is also not sorted.

**Comment by milot-mirdita** [comment]
Oh, you are right. We'll look into it next week!

**Comment by martin-steinegger** [comment]
We do implemented the sort for the hits like this 

    static bool compareHits (const result_t &first, const result_t &second){ 
        if(first.eval < second.eval ) return true; 
        if(second.eval < first.eval ) return false; 
        if(first.score > second.score ) return true; 
        if(second.score > first.score ) return false; 
        return false; 
    }`

Would it be possible to provide use the query sequence `PS064S07MM_22442` and the target sequences `fig|1073351.3.peg.1244`, `fig|470145.6.peg.1745`, `fig|997886.3.peg.1854` and `fig|767031.3.peg.114`?

**Comment by sleyn** [comment]
Here they are:

`>PS064S07MM_22442                                                                                                                                                     
MNKIISKERFSEKVFKLEIEAPLIAKSRKAGHFVIVRVGDKGERMPLTIAGSDLKKGTIT                                                                                                                                                                                
LVIQEVGLSSTRLCELNEGDYITDVVGPLGQATHIENFGTVVCAGGGVGVAPMLPIVQAL                                                                                                                                                                                
KAAGNRVITVLAGRNKDLIILEKEMRESSDEVIIMTDDGSYGRKGLVTEGVEEVIKREKV                                                                                                                                                                                
DKCFAIGPAIMMKFVCLLTKKYEIPTDVSLNTIMVDGTGMCGACRITVGGKTKFVCVDGP                                                                                                                                                                                
EFDGHQVDFDEMLKRMGAFKKIEREEMNKLQPECEATKEIDEKSRNAAWRQELRKSMKPK                                                                                                                                                                                
ERTAIPRVEMNELDAEYRSHSRKEEVNQGLTAEQAVTEAKRCLDCANPGCMEGCPVGIDI                                                                                                                                                                                
PRFIKNIERGEFLEAAKTLKETSALPAVCGRVCPQEKQCESKCIHLKMNEKPVAIGYLER                                                                                                                                                                                
FAADFERESGQISVPVIAEKNGIKVAVIGSGPAGLSFAGDMAKYGYDVTVFEALHEIGGV                                                                                                                                                                                
LKYGIPEFRLPNKIVDVEIDNLVKMGVTFIKDCIVGKTISVEDLKEEGFKGIFVASGAGL                                                                                                                                                                                
PNFMNIPGENSINIMSSNEYLTRVNLMDAASEDSDTPVAFGKNVAVIGGGNTAMDSVRTA                                                                                                                                                                                
KRLGAERAMIIYRRSEEEMPARIEEVKHAKEEGVEFLTLHNPIEYIADEQGCVKQVILQK                                                                                                                                                                                
MELGEPDASGRRSPVAIPGATETIDIDLAIVSVGVSPNPIVPSSIKGLELGRKGTIAVDD                                                                                                                                                                                
NMESSIPMIYAGGDIVRGGATVILAMGDGRKAAAAMNEQLQSK

>fig|1073351.3.peg.1244                                                                                                                                                                                                                     
MNKIISKEHFSEKVFKLVIEAPLIAKSRKAGHFVIVRVGEKGERMPLTIAAADPVKGTITLVVQEVGLSSTRLCELNEGDYITDVVGPLGQATHIENFGTVVCAGGGVGVAPMLPIVQALKAAGNRVITVLAGRTKELIILEKEMRESSDEVIIMTDDGSYGRKGLVTEGVEDVIKREKVDKCFCIGPAIMMKFVCLLTKKYEIPTDVSLNTIMVDGTGMCGACRITIGGKTKFVC
VDGPEFDGHQVDFDEMLKRMGAFKNIEREEMHKLEEPQTCQATGENTQAEDEKNRNAAWRQELRKSMKAKERTAIPRVEMNELDAEYRSHSRKEEVNRGLTEEQALTEAKRCLDCANPGCMEGCPVGIDIPRFIKNIERGEFLEAAKTLKETSALPAVCGRVCPQEKQCESKCIHLKMNEKPVAIGYLERFAADYERESGQISVPEIKEKNGIKIAVIGSGPAGLSFAGDMAKYGY
DVTVFEALHEIGGVLKYGIPEFRLPNKIVDVEIENLAQMGVKFIKDCIIGKTLSVEQLEEEGFKGIFVASGAGLPNFMNIPGENSINILSSNEYLTRVNLMDAASEDSDTPVPFGKCVAVIGGGNTAMDSVRTARRLGAERAMIIYRRSEEEMPARIEEVKHAKEEGVEFLTLHNPIEYIADEQGKVKQVVLQKMELGEPDASGRRSPVPIPGATETIDIDLAIVSVGVSPNPIVP
SSIKGLELGRKGTIAVNDNMQSSIPTIYAGGDIVRGGATVILAMGDGRKAAAAMNEQLKN

>fig|470145.6.peg.1745                                                                                                                                                                                                                      
MNKIISKEHFSEKVFKLVIEAPLIAKSRKAGHFVIVRVGEKGERMPLTIAEADPVKGTITLVVQEVGLSSTRLCELNEGDYITDVVGPLGKATHIENFGTVVCAGGGVGVAPMLPIVQALKAAGNRVITVLAGRSKELVILEKEMRESSDEVIIMTDDGSYGKKGLVTEGIEEVIKREKVDKCFAIGPAIMMKFVCLLTKKYEIPTDVSLNTIMVDGTGMCGACRITVGGKTKFVC
VDGPEFDGHQVDFDEMLKRMGAFKDIEREEIHKLDAVQPDTCEAVKAVEDRNTPWRAELRKAMKPKERTAIPRVKMNELDPEYRSHSRKEEVNLGLNEEQALTEAKRCLDCANPSCREGCPVGINIPGFIKNIERGEFLEAARVLKQTSALPAVCGRVCPQEKQCESKCIHLKMGHEAVAIGYLERFAADYERESGQISVPEIAEKNGIKVAVVGSGPAGLSFAGDMAKLGYDVTV
FEALHEIGGVLKYGIPEFRLPNKIVDVEIENLSKMGVQFVKDCIIGKTISVEELEQEGYKGVFVASGAGLPNFMNIPGENSINIMSSNEYLTRVNLMDAASEDSDTPVTFGKRVAVIGGGNTAMDSVRTARRLGAEKAMIIYRRSEAEMPARLEEVKHAKEEGVEFLTLHNPIEYIADEKGRVKQVVLQKMELGEPDASGRRSPVAIPGAVETIDIDMAIVSVGVSPNPIVPNSIP
GLELGRKGTIAVNDDMQSSIPTIYAGGDIVRGGATVILAMGDGRRAAAAMDKQLRG

>fig|997886.3.peg.1854                                                                                                                                                                                                                      
MNKIISKERFSEKVFKFEIEAPLIAKSRKAGHFVIVRVGEKGERMPLTIAGSNLKKGTITLVVQEVGLSSTRLCELNEGESITDVVGPLGQATHIEKFGTVICAGGGVGVAPMLPIVQALKAAGNRVITVLAGRNKDLIILEKEMRESSDEVIIMTDDGSYGRKGLVTEGVEEVIKREKVDKCFAIGPAIMMKFVCLLTKKYEIPTDVSLNTIMVDGTGMCGACRITVGGKTKFVC
VDGPEFDGHQVNFDEMLKRMGAFKNIEREEMHKLESECEATKEIDEKSRNAAWRQELRKSMKPKERTAIPRVEMNELDAEYRSHSRKEEVNQGLTAEQAVTEAKRCLDCANPGCMEGCPVGIDIPRFIKNIERSEFLEAAKTLKETSALPAVCGRVCPQEKQCESKCIHLKMNEKPVAIGYLERFAADYERESGQISVPVIAEKNGIKIAVIGSGPAGLAFAGDMAKYGYDVTVFE
ALHEIGGVLKYGIPEFRLPNKIVDVEIDNLGKMGVNFIKDCIVGKTIGVEDLKAEGFKGIFVASGAGLPNFMNIPGENSINIMSSNEYLTRVNLMDAASEDSDTPVAFGKNVAVIGGGNTAMDSVRTAKRLGAERAIIIYRRSEEEMPARIEEVKHAKEEGVEFLTLHNPIEYIADEQGCVKQVILQKMELGEPDASGRRSPVAIPGATETIDIDLAIVSVGVSPNPIVPSSIKGL
ELGRKGTIAVNDNMESSIPMIYAGGDIVRGGATVILAMGDGRKAAAAMHEQLKTNAGN

>fig|767031.3.peg.114                                                                                                                                                                                                                       
MNKIIRKQQFSEKVFCLEVEAPLIARSCRPGNFIIVRVDNRSERVPYTIAKSDPVKGTLTMVIQEVGKSSTKLCRLNVGDEVHDIVGPLGTPSRIENYGTVICAGGGIGIAAILPILTALKQAGNKVISVLAGRTKELVIMVDDVRKYSDEVIIMTDDGSYGEKGVVTVGVEKVIQREHVDKVLAIGPPVMMKFTSLLARKYGIPNDVSLNTIMVDGTGMCGACRLTIGGKTRFVC
IDGPEFNGDLVDWDEMFKRMGTFKEIEAASSPSGGEECQAGTPTKKSIDGKAADGKGATDFRGAGEFGDAAQGTAAEDRPSSPSGEPGEDWRKVLRKALKPKERTAIERVKMPELDPAYRATTRLEEVNIGLTPEMAMQEAKRCLDCPKPSCVEGCPVNIHIPDFIKNIERGHFLEAARILKETSALPAVCGRVCPQEKQCESRCIHLKMNSPAVAIGYLERFAADYERESGHMTL
PDMAPSNGIKVAVVGSGPAGLSFAGDMVKRGFEVYVFEALHEIGGVLKYGIPEFRLPNRIVDVEIENLRRMGVHFQTDTIVGKTISIADLKEKGFKGIFVGSGAGLPNFMGIPGENAINILSSNEYLTRINLMDAANPETDTPIIIGRKVLVIGGGNTAMDSCRTAKRLGADVTLVYRRSEAEMPARLEEVKHAKEEGIHFLTLHNPKEYKADEKGRVCAAVLDVMRLGEPDASGR
RRPETTGETITVDCDQVIVAVGVSPNPLVPKSIKGLELGRKDTIVVNEQMQSSQPEIFAGGDIVRGGATVILAMGDGRRAAANMAERLTAGS
`

**Comment by martin-steinegger** [comment]
Thank you for the sequences. I try to reproduce the issue but on my machine the alignment order is correct: 

```

PS064S07MM_22442        fig|997886.3.peg.1854   0.965   762     27      0       1       762     1       762     0.00E+00        1463
PS064S07MM_22442        fig|1073351.3.peg.1244  0.928   768     49      3       1       762     1       768     0.00E+00        1409
PS064S07MM_22442        fig|470145.6.peg.1745   0.888   765     80      3       1       761     1       763     0.00E+00        1354
PS064S07MM_22442        fig|767031.3.peg.114    0.674   798     220     4       1       760     1       796     0.00E+00        1049
```

What commit (MMseqs Version) do you use?

**Comment by martin-steinegger** [comment]
Is the issue still occurring?

**Comment by sleyn** [comment]
Hi! I didn't test search anymore. Now I'm using only clustering with MMSeqs 2. But I've done several searches before with this result and didn't do anything with mmseqs installation. My version is 1-c7a89.

**Comment by martin-steinegger** [comment]
@sleyn please let us know if the issue still occurs with the newest version. Please reopen if the issue still persists.
