### ISSUE TITLE
FEATURE REQUEST: percent positive substitutions

### ISSUE THREAD

**Issue by xonq** [soedinglab/MMseqs2#670]
Currently cannot find a percent positives output in the `mmseqs search` and `mmseqs convertalis` format output parameter. In some situations it is preferable to use percent positive substitutions as a measure of similarity v percent identity, and some members of the community prefer it. I am requesting an implementation of this

**Comment by milot-mirdita** [comment]
We have implemented this a while ago with `ppos`: https://github.com/soedinglab/MMseqs2/pull/723
