### ISSUE TITLE
evalThr and evalProfile parameters for search function

### ISSUE THREAD

**Issue by luchinoprince** [soedinglab/MMseqs2#675]
Looking at the user guide and at the code I cannot seem to understand the difference between the evalThr and evalProfile parameters of the search method. Given their names I have a hard time understanding which of the two the -e parameter changes, it would be nice to provide a specific explanation of all the hyperparameters of the functions as it is especially usefull for new users as I am.

**Comment by milot-mirdita** [comment]
`-e` maps to `evalThr` this is the alignment acceptance E-value. Everything above will be discarded during the alignment.
`--e-profile` is the profile inclusion E-value. This is relevant for iterative profile searches (psiblast-like), where profiles are built in each iteration. Here we need a stricter E-value to not accidentally connect proteins that should not be connected into one profile.

**Comment by luchinoprince** [comment]
Thank you for the explanation, now I know how to set the hyperoarameters. Looking at the documentation it seems that `-e=1e-3` as default, while `--e-profile=1e-1` as default. So it seems that `-e` has to be generally set to lower, and hence stricter, values. Not sure if I am maybe interpreting wrongly the heuristics of these values?

Lastly, from you answer I understand that if I am running the `search` module with `--num-iterations 3` then the `--e-profile` will account for thresholding during this iterative procedure, while `-e` as a final cutoff value?

**Comment by milot-mirdita** [comment]
Yes, you are indeed right. I clarified with @martin-steinegger, he benchmarked the profile inclusion E-value and saw that the higher inclusion threshold was improving performance. The performance would get worse with inclusion E-values higher than 0.01 though.

Your understanding in your second paragraph is right.
