### ISSUE TITLE
Cannot convert output to different MSA file

### ISSUE THREAD

**Issue by luchinoprince** [soedinglab/MMseqs2#681]
Hi, I am trying to replicate some code that we had run on the previous version of the library and I cannot find what combination of function I have to use to get the desired output. After running a search we want to create different files which contained the MSA for the different query sequences. We used to be able to run the following(after completing the search)

`mmseqs result2msa query_full uniref50 target_full msa_full --msa-format-mode 6` and then `mmseqs unpackdb msa_full ./msas --unpack-name-mode 0 --unpack-suffix ".a3m"`. With the new library, whatever `--msa-format-mode` I choose(now from 1 to 4), I cannot get the unpackdb function to work and give me the different files. 

Could anyone suggest me how get this operation trough in the with the new library?

**Comment by milot-mirdita** [comment]
This looks about right. What's the error message?

**Comment by luchinoprince** [comment]
So on the first command I cannot put `—msa-format-mode 6` as now the values for that parameters are only from 0 to 4. While the second command tells me that I cannot put those optional argument for the function `unpackdb`. If I look from terminal it tells me that the only optional argument is `-v` which is just to control the verbosity of the output. Do I have somehow and old version of the module?

**Comment by milot-mirdita** [comment]
If you have MMseqs2 release 14 installed, then `--msa-format-mode 6` should be available in the `result2msa` module. Could you please post the full output?

**Comment by luchinoprince** [comment]
Sorry for the late reply, 

Currently the version of mmseqs I have is `MMseqs2 Version: 13.45111`. The messages I get for the functions are

```
 --msa-format-mode INT   Format MSA as: 0: binary cA3M DB
                         1: binary ca3m w. consensus DB
                         2: aligned FASTA DB
                         3: aligned FASTA w. header summary
                         4: STOCKHOLM flat file [0]
```
While for `mmseqs unpackdb` I have
```
usage: mmseqs unpackdb <i:DB> <o:outDir> [options]
 By Milot Mirdita <milot@mirdita.de>
options: common:
 -v INT   Verbosity level: 0: quiet, 1: +errors, 2: +warnings, 3: +info [3]
```

Do you think that just updating the version will solve the problem? I downloaded the library using the suggested conda command of the github page.

**Comment by milot-mirdita** [comment]
Yes, the feature is only available in the latest release 14. Did you create a fresh conda environment? Maybe something else was holding back MMseqs2 to the previous release.

**Comment by luchinoprince** [comment]
Yes to my knowledge it was a fresh conda enviroment, I will try again to make sure I have the suggested version. Thank you very much for the availability!

**Comment by luchinoprince** [comment]
Somehow downloading trough `conda` always downloaded an old version of the package, using `wget` solved my problem! Thanks again for the help.
