### ISSUE TITLE
Questions: memory vs threads

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/MMseqs2#69]
This is not bug report, just a question. Does memory consumption by "cluster" and "linclust" in mmseqs2 independent on the number of threads? In other words, for the same database, will I use more memory if I use more CPUs?

**Comment by martin-steinegger** [comment]
Both tools "linclust" and "cluster" are uses more memory if you increase the amount of threads. The increase in memory consumption in linclust should not be too much. In Cluster it can increase the memory consumption substantial.

**Comment by kad-ecoli** [comment]
Is there some formula with which I can calculate the memory consumption wrt the number of threads?

**Comment by martin-steinegger** [comment]
For `cluster` there is a formula to compute thread memory:

```
     threads * (        
               (targetDbSize * 2 * sizeof(IndexEntryLocal)) 
            + (targetDbSize * sizeof(CounterResult))             
            + (targetDbSize * 2 * sizeof(CounterResult) * 2)
        )
```

For `Linclust` there is no formula.
