### ISSUE TITLE
mmseqs local runs too slower than mmseqs colabfold api with max 256GB RAM, more 2 hours on local MSA

### ISSUE THREAD

**Issue by rocke2020** [soedinglab/MMseqs2#690]
I had carefully read this similar issue below. I think my problem may be different and with more details.
https://github.com/soedinglab/MMseqs2/issues/658
## Expected Behavior
mmseqs local runs with similar response time as that in mmseqs colabfold api.
Is there a solution for ColabFold multimer prediction msa search with a good speed(not fastest, but faster) with 256GB memeory?
## Current Behavior
for 1 sequence pair(164 mers and 6 mers) input, local mmseqs msa server use more than 4 hours to process, even much slower than Alphafold orig MSA local running at the same local hardware environment.
**I did not use vmtouch to keep the precomputed database index file within system memory, because I only have max 256GB RAM.**
**Is this very low speed caused by I didn't keep all database into memory?**
>HAGPIA
## Steps to Reproduce (for bugs)
I follow the instructions in https://github.com/sokrypton/ColabFold/tree/main/MsaServer
The only difference in my process with that in the ColabFold instructions: I did not use vmtouch to keep the precomputed database index file within system memory, because I only have max 256GB RAM.
1. run setup_databases.sh successfuly to download all the colab database.
the file read file are all ready. 'UNIREF30_READY',     'COLABDB_READY',    'PDB_READY',    'PDB70_READY',    'PDB_MMCIF_READY'.
the created idx files: colabfold_envdb_202108_db.idx.0 colabfold_envdb_202108_db.idx.1 colabfold_envdb_202108_db.idx.2 colabfold_envdb_202108_db.idx.3 colabfold_envdb_202108_db.idx.4 colabfold_envdb_202108_db.idx.5 colabfold_envdb_202108_db.idx.6 colabfold_envdb_202108_db.idx.7 pdb70_220313.idx uniref30_2202_db.idx
**There is no uniref30_2202_db.idx.[0, 1], but only uniref30_2202_db.idx. Is this normal?**
3. run MsaServer/setup-and-start-local.sh to compile mmseqs locally.
now, mmseqs server  successfully runs. at http://127.0.0.1:8888.
4. test codes below, the mmseqs msa are too slow, more than 4 hours for only 1 sequence pair, the 2 "use_pairing true/false"mode both run, each need 2 hours.
```python
host_url = 'http://127.0.0.1:8888'
query = '>101\nVNPTVFFDIAVDGEPLGRVSFELFADKVPKTAENFRALSTGEKGFGYKGSCFHRIIPGFMCQGGDFTRHNGTGGKSIYGEKFEDENFILKHTGPGILSMANAGPNTNGSQFFICTAKTEWLDGKHVVFGKVKEGMNIVEAMERFGSRNGKTSKKITIADCGQLE\n>102\nHAGPIA\n'
mode = 'env'
submission_endpoint = 'ticket/msa'
res = requests.post(f'{host_url}/{submission_endpoint}', data={'q':query,'mode': mode}, timeout=6.02)
out = res.json()
print(out)
mode = ''
submission_endpoint = 'ticket/pair'
res = requests.post(f'{host_url}/{submission_endpoint}', data={'q':query,'mode': mode}, timeout=6.02)
out = res.json()
print(out)
```
## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

## Your Environment
ColabFold 1.5.2
ubuntu 20.04
256GB RAM, that's why I cannot use vmtouch which need 768GB memory according to the readme.
32 cores cpu
[log-mmseqs-msa-server.log](https://github.com/soedinglab/MMseqs2/files/11145276/log-mmseqs-msa-server.log)

**Comment by milot-mirdita** [comment]
The MSA server will only be fast if you have sufficient RAM. Otherwise it will be super slow as you have experienced. There is no way around that without more RAM.

For local use, please use the`colabfold_search` script. However, that also won't be fast for single sequences. It needs to amortize its overhead over many queries to be fast.

**Comment by rocke2020** [comment]
@milot-mirdita thanks for your reply
https://github.com/sokrypton/ColabFold/blob/main/colabfold_search.sh
in the "colabfold_search.sh" file , there are reminds at first "Do not use this script. Use the python colabfold_search instead".
**why not advice us to this "colabfold_search.sh" scripts? what is "python colabfold_search"?**
Maybe the current "colabfold_search.sh" is need to update, at least it does not work with the script in readme.
`colabfold_search input_sequences.fasta /path/to/db_folder msas`

For single sequences, **the sufficient RAM** means: 768GB-1024GB RAM to stay resident in RAM and have enough RAM spare for worker processes, yes?

**Comment by milot-mirdita** [comment]
Because we don't develop the .sh script anymore and it's not up-to-date. The development is happening in the python version now.

If you want to use the server - with fast response times, like our has - you need a server with ~1TB permanently committed RAM. Anything less will not work.
`colabfold_search` does not have this issue, however, it has slightly different performance pitfalls to look out for.  Single query searches will remain slow, with `colabfold_search`. Our proposed workflow is to gather a few hundred to thousands of queries. Do the MSA generation stage with `colabfold_search` and then batch predict them with `colabfold_batch`.

**Comment by rocke2020** [comment]
thanks very much for @milot-mirdita . Could you explain more on my questions, thanks in advance!!!
1. the python version "colabfold_search" is the file "colabfold/mmseqs/search.py", yes?

2. colabfold_search.sh is mostly for Batch searches. The difference of between Batch searches and single query searches.
Batch searches: input a few hundred to thousands of sequences **as one input set**, and get the only 1 msa sequences set. 
single query searches: input 1 sequence or 2 sequences as a pair as one input set, and get the only 1 msa sequences set.
**If we run multiple "single query searches" in parallel or in batch, this is not batch searches, yes?**

3. when I run mmseqs msa server locally, it succees for ticket/msa, but failed for "ticket/pair".
could you check the mmseqs log file and give me instructions?
[log-mmseqs-msa-server.log](https://github.com/soedinglab/MMseqs2/files/11145675/log-mmseqs-msa-server.log)

Input taxonomy database "/mnt/sdc/colabfold_db/uniref30_2202_db.idx" is missing files:
- /mnt/sdc/colabfold_db/uniref30_2202_db.idx_mapping
- /mnt/sdc/colabfold_db/uniref30_2202_db.idx_nodes.dmp
- /mnt/sdc/colabfold_db/uniref30_2202_db.idx_names.dmp
...
2023/04/04 12:29:49 Execution Error: open /home/qcdong/codes/ColabFold/MsaServer/jobs/3m6olJuvf_TV0UTKJxnGu3V3YnMxyHkkj915xg/pair.a3m: no such file or directory

**Comment by rocke2020** [comment]
the created idx files: colabfold_envdb_202108_db.idx.0 colabfold_envdb_202108_db.idx.1 colabfold_envdb_202108_db.idx.2 colabfold_envdb_202108_db.idx.3 colabfold_envdb_202108_db.idx.4 colabfold_envdb_202108_db.idx.5 colabfold_envdb_202108_db.idx.6 colabfold_envdb_202108_db.idx.7 pdb70_220313.idx uniref30_2202_db.idx

**Comment by milot-mirdita** [comment]
You need to create symlinks in the databases folder:

```
ln -s uniref30_2202_db_mapping uniref30_2202_db.idx_mapping
ln -s uniref30_2202_db_taxonomy uniref30_2202_db.idx_taxonomy
```

That is missing in the setup script. My fault.
