### ISSUE TITLE
taxonomy

### ISSUE THREAD

**Issue by henav** [soedinglab/MMseqs2#71]
Hello, 
I am trying to use MMSEQS2 to assign taxonomy to a large set of predicted genes. However, the command “mmseqs taxonomy” is not identified. 
I am using version 1d62934a57769c971fec3724d3e805f8162b976a . Could you please let me know how I should enable this option?
Thanks

**Comment by milot-mirdita** [comment]
Please use the latest git version, we first introduced the command in 1-c7a89, but it has some flaws there still. The latest git version should work fine.

**Comment by milot-mirdita** [comment]
We just packaged a new MMseqs2 release, that has everything you need.
