### ISSUE TITLE
mmseqs search warnings

### ISSUE THREAD

**Issue by ksteczk** [soedinglab/MMseqs2#72]
After SW alignments in mmseqs search:
`
mmseqs search nr30_db nr70_db nr30_res tmp --num-iterations 6 -e 1 --threads 116
`
everything goes well but there are some warnings poping up in the stage after
> Start computing profiles.

It prints:

> Warning in /home/users/ksteczk/temporary/mmseqs/MMseqs2/src/alignment/MsaFilter.cpp:244: filter:
> Filtering removed all sequences in alignment. Inserting back first sequence.

Is that OK and the warning is rather for debugging?

**Comment by martin-steinegger** [comment]
I tried to reproduce the behavior but I could not. I did not see this message before in my runs. But I think your results will be fine if not all sequences reports this warning.

But just to figure out what does wrong:  Could you provide us the MSA where this issue occurs? I have create a patch which should print out the MSA if the warning occurs ( https://gist.github.com/martin-steinegger/2ecff9e259d97eca3f9c45c69912d113 ). Thanks a lot.

**Comment by ksteczk** [comment]
After testing few strategies I zipped all the commands along with logs for you to have a look after which commands and in which moments the errors occurred.

I also attach those with comments to show how the clustering went and with what time efficiency.

I understand that I should patch the source and run the software again in the suspected steps to printout the problems?

[logs.zip](https://github.com/soedinglab/MMseqs2/files/1815637/logs.zip)

**Comment by martin-steinegger** [comment]
The warning seems to be okay. This happens if the filter removes all sequence. We will remove the warning in future.
