### ISSUE TITLE
importing simtk.openmm error

### ISSUE THREAD

**Issue by incisrdg** [soedinglab/MMseqs2#727]
I am having an error message saying "2023-07-03 13:58:41,863 Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead." What should I do to solve it?

**Comment by milot-mirdita** [comment]
You can ignore that warning. It does not affect ColabFold runs at all. Please direct ColabFold questions to its own github repository: https://github.com/sokrypton/ColabFold
