### ISSUE TITLE
Update needed to GTDB database install code for release 214

### ISSUE THREAD

**Issue by jmtsuji** [soedinglab/MMseqs2#740]
Release 214 of the [GTDB](https://gtdb.ecogenomic.org/) was published in April 2023. A few changes to file formats in the GTDB seems to have broken the `mmseqs databases GTDB` command.

## Expected Behavior
Running `mmseqs databases GTDB gtdb tmp` should install the GTDB database for use with mmseqs.

## Current Behavior
An `errorCode=3 Resource not found` error occurs.

## Steps to Reproduce (for bugs)
Run `mmseqs databases GTDB gtdb tmp`

## MMseqs Output (for bugs)
```
Create directory tmp
databases GTDB gtdb tmp 

MMseqs Version:              	14.7e284
Tsv                          	false
Force restart with latest tmp	false
Remove temporary files       	false
Compressed                   	0
Threads                      	48
Verbosity                    	3


08/24 16:37:41 [NOTICE] Downloading 1 item(s)

08/24 16:37:42 [ERROR] CUID#7 - Download aborted. URI=https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/VERSION
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/VERSION
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

08/24 16:37:42 [NOTICE] Download GID#e7463566c34e03ba not complete: tmp/3792731134469971229/version

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e74635|ERR |       0B/s|tmp/3792731134469971229/version

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   196  100   196    0     0    363      0 --:--:-- --:--:-- --:--:--   364

08/24 16:37:42 [NOTICE] Downloading 1 item(s)
```
(I stopped the download early after seeing the error above...)

## Context
Including the `Resource not found` error above, I developed a fix to address the format of GTDB release 214. Required changes to `data/workflow/databases.sh`:
- `https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/VERSION` should be `https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/VERSION.txt` (approx. line 139)
- Each FAA file inside `gtdb.tar.gz` is now gzipped. Thus, `"${MMSEQS}" tar2db "${TMP_PATH}/gtdb.tar.gz" "${TMP_PATH}/tardb" --tar-include 'faa$' ${THREADS_PAR}` should be `"${MMSEQS}" tar2db "${TMP_PATH}/gtdb.tar.gz" "${TMP_PATH}/tardb" --tar-include 'faa.gz$' ${THREADS_PAR}` (approx. line 374). Similarly, `sed 's|_protein\.faa||g'` should be `sed 's|_protein\.faa\.gz||g'` (approx. line 376).

I'd be happy to make a PR if it helps.

**Importantly**, although the GTDB should download properly after these fixes, the resulting seqtaxdb will still contain the ID collision issue mentioned in #729 involving the `gtdb.lookup` file. Taxonomy results will be unreliable until #729 is fixed.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used: 14.7e284
* Which MMseqs version was used: conda install
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation: N/A
* Server specifications: CPU with SSE and AVX2 support, 512 GB RAM
* Operating system and version: Ubuntu 22.04.3 LTS

**Comment by jmtsuji** [comment]
This issue reported here might be related to #709

**Comment by apcamargo** [comment]
I just came across the same issue today. I'll open up a PR to fix this.

**Comment by jmtsuji** [comment]
Thanks! This is very helpful.

**Comment by jmtsuji** [comment]
Tested the mmseqs master branch after the PR was merged, and the download works now! Thanks @apcamargo  Note that issue #729 persists, so taxonomy will not work properly with the GTDB database. However, I will go ahead and close this specific issue for now.
