### ISSUE TITLE
How much memory is needed for touchdb?

### ISSUE THREAD

**Issue by xtj87515** [soedinglab/MMseqs2#757]
I generated the index files for some Uniprot databases:

```
mmseqs createdb <databases.fasta.gz> input/targetDB
mmseqs createindex input/targetDB tmp
```

This step has generated a bunch of "targetDB.idx.0,1,2...14 "(each is 52GB), and a "targetDB.idx.dbtype" + "targetDB.idx.index".  It seems there should be only one "targetDB.idx" file generated. However, that file was not there although it says in the last few lines of the log "Time for merging to targetDB.idx: 0h 0m 0s 169ms".

I attached the log file. Please see if you spot something wrong.
[LOG_createindex.txt](https://github.com/soedinglab/MMseqs2/files/12741806/LOG_createindex.txt)

Another thing I want to mention is during the "mmseqs createindex input/targetDB imp" step, our memory was constantly exhausted (125G total~ 65G used+ 60G cache/buff, before the procedure started there was only 5Gb being used). I wonder if that might be the cause of not producing the final "targetDB.idx"? I'm working on requesting larger memory right now. If that's the case, how big of RAM do I need?
################################################
After this, I want to fetch the indexed database into memory to speed up the search of queries: 

`mmseqs touchdb input/targetDB`

Log for this was:

> MMseqs Version:	f5f780acd64482cd59b46eae0a107f763cd17b4d
> Threads  	32
> Verbosity	3

##################################################
Then I did:
`mmseqs search query/queryDB input/targetDB output/resultDB /tmp -a -s 8.5 --num-iterations 2 --db-load-mode 2`

This was a simple query but was taking a long time and I had to cancel the job. Normally it took less than a minute to do the search. 
####################################################
My environment is:
Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
32 CPUs, supports AVX and SSE4
125Gb memory
2T disk space
MMseqs2 Version: https://github.com/soedinglab/MMseqs2/commit/f5f780acd64482cd59b46eae0a107f763cd17b4d

##################################################
My questions are:
1) How big of a RAM is required for the createindex step? Was that the reason a "targetDB.idx" was not generated?

2) How much memory do I need for the indexed files to be fetched into memory (i.e. the"touchdb" step)? Is it the total of all the "targetDB.idx.0,1,2...14 " files which will be over 1TB? Or is it something smaller?

3) The log message for mmseqs touchdb step wasn't very helpful. Did it work or not?

Thank you,
Tongji

**Comment by xtj87515** [comment]
So it seems there should be only one "targetDB.idx" file generated after the "mmseqs createindex input/targetDB imp" step. However, that file was not generated although it says in the last few lines of the log "Time for merging to targetDB.idx: 0h 0m 0s 169ms". 

I attached the log file. Please see if you spot something wrong.
[LOG_createindex.txt](https://github.com/soedinglab/MMseqs2/files/12741806/LOG_createindex.txt)

**Comment by xtj87515** [comment]
My environment is:
Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
32 CPUs, supports AVX and SSE4
125Gb memory
2T disk space
MMseqs2 Version: f5f780acd64482cd59b46eae0a107f763cd17b4d

**Comment by xtj87515** [comment]
Another thing I want to mention is that during the "mmseqs createindex input/targetDB imp" step, our memory was constantly exhausted (125G total~ 65G used+ 60G cache/buff, before the procedure started there was only 5Gb being used). I wonder if that might be the cause of not producing the final "targetDB.idx"? I'm working on requesting larger memory right now. If that's the case, how big of RAM do I need?

**Comment by xtj87515** [comment]
> Please refer to the following issue: [#748 (comment)](https://github.com/soedinglab/MMseqs2/issues/748#issuecomment-1732178119)
> 
> i don’t know your use case but you createindex has very specific niches. You will likely not need it. For whole UniProt you will need likely in the TB range of memory

Here at PDB, we have ~250 new entries (~1000 new sequences) deposited each week- we have a weekly process to search these sequences against Uniprot- this is currently done by BLAST. We can probably purchase larger RAM in TBs. In that case, would you recommend caching the whole Uniprot into memory, or like in the other post-merging all queries into one DB?

**Comment by martin-steinegger** [comment]
You do not need to index to search batches of 250 to 1000. What happens if you just search without an index?

**Comment by milot-mirdita** [comment]
I would not recommend to use indexing for a weekly job. Without pre-indexing you can use a smaller machine, i.e. in the 128-256GB RAM range.  500k queries vs UniProt should not be a big issue for such a machine.

Pre-indexing usually helps if you want to search with very single queries or very small sets, or if you have little memory and very fast storage. In other cases it might even hurt performance, I am not sure if this issue was ever resolve in Linux, but creating an index on the fly allows to use a Linux kernel mechanism called Transparent Huge Pages (THP), which results in about 10-15% faster run time for larger batch searches.

So I would recommend to delete all `.idx` files (rm -f -- DB.idx.*) and proceed without `createindex`.

Additionally, for the PDB, I also recommend to first do a 100% seq.id. clustering to not repeat searches for identical queries.

Regarding your question: If the machine running `createindex` did not have enough RAM to fully fit the index it will split it into N splits. These are the targetDB.idx.0 ... targetDB.idx.N files you see. You can manually disable this by specifying `--split 1`, then it will create only the `targetDB.idx` file (and some supporting files). In this case you will still need a machine that can fit the whole precomputed index into memory.

**Comment by xtj87515** [comment]
> I would not recommend to use indexing for a weekly job. Without pre-indexing you can use a smaller machine, i.e. in the 128-256GB RAM range. 500k queries vs UniProt should not be a big issue for such a machine.
> 
> Pre-indexing usually helps if you want to search with very single queries or very small sets, or if you have little memory and very fast storage. In other cases it might even hurt performance, I am not sure if this issue was ever resolve in Linux, but creating an index on the fly allows to use a Linux kernel mechanism called Transparent Huge Pages (THP), which results in about 10-15% faster run time for larger batch searches.
> 
> So I would recommend to delete all `.idx` files (rm -f -- DB.idx.*) and proceed without `createindex`.
> 
> Additionally, for the PDB, I also recommend to first do a 100% seq.id. clustering to not repeat searches for identical queries.
> 
> Regarding your question: If the machine running `createindex` did not have enough RAM to fully fit the index it will split it into N splits. These are the targetDB.idx.0 ... targetDB.idx.N files you see. You can manually disable this by specifying `--split 1`, then it will create only the `targetDB.idx` file (and some supporting files). In this case you will still need a machine that can fit the whole precomputed index into memory.

Thank you, that's very helpful! I do remember reading about the THP but now everything makes more sense. 

In addition to clustering identical queries, do you also recommend merging the query seqs (like you mentioned in the other post)?

**Comment by martin-steinegger** [comment]
Indexing helps for single queries if you can keep it in memory. Otherwise the advantage isn’t big. In case of not using the index, mmseqs splits the target db to fit in memory and indexes it.

**Comment by milot-mirdita** [comment]
Yes! MMseqs2 is not very efficient with small sets of queries. `createindex` is the solution for that, however it comes with many other trade-offs.

**Comment by xtj87515** [comment]
Thank you both for your comments!

**Comment by xtj87515** [comment]
Thank you both for your comments!
