### ISSUE TITLE
failed to createindex

### ISSUE THREAD

**Issue by shawnLiujianwei** [soedinglab/MMseqs2#76]
i tried to build database from one prot fasta contains about 5 million sequence , each of the sequence is preformatted like:

>1006013
ATGGAAGCTACGAAGTCGTCGAAACAAAATTGTTGCAACCCGGTTAAGAAACCCGGACCC
GTTTCAATTGATCATGTTCTCTTAGCTCTCCGTGAGACAAGAGAAGAGCGAGATTTACGA
ATCAGGAGCTTATTCAGTTTCTTTGATTCTGAGAATGTTGGTTACTTAGATTGTGCTCAA
ATTGAGAAGGGGTTATGTGCGCTTCAAATCCCAAGTGGGTATAAATACGCTAAGGAGTTG
TTTAGGGTTTGTGATGCGAATAGAGATGGGCGTGTGGATTATCATGAGTTTCGTAGATAT
ATGGATGATAAGGAGCTTGAGCTGTATAGAATCTTTCAAGCTATTGATGTTGAGCATAAT
GGTTGTATTTCTCCTGAGGGACTTTGGGATTCACTCGTTAAAGCTGGGATTGAGATAAAA
GATGAGGAGCTTGCTCGTTTTGTGGAACATGTTGACAAGGACAATGATGGAATCATTATG
TTTGAAGAATGGAGAGATTTTCTTTTGCTGTACCCTCACGAAGCTACCATTGAAAATATA

>1006013 is the taxmony id we got to unique the sequence

i can create the database by: `mmseqs createdb xxx targetDB`

but when try to createindex by `mmseqs createindex targeDB index`
it throws issue:

`Program call:
prot index

MMseqs Version:       	87f530e8aedc0970c8ec16cb2d33b7507d56cf59
Sub Matrix            	blosum62.out
K-mer size            	0
Alphabet size         	21
Max. results per query	300
Max. sequence length  	32000
Mask Residues         	1
Spaced Kmer           	1
Sensitivity           	7.5
K-score               	0
Include Header        	true
Split DB              	0
Split Memory Limit    	0
Threads               	4
Verbosity             	3
Min codons in orf     	30
Max codons in length  	98202
Max orf gaps          	2147483647
Contig start mode     	2
Contig end mode       	2
Orf start mode        	0
Forward Frames        	1,2,3
Reverse Frames        	1,2,3
Translation Table     	1
Use all table starts  	false
Offset of numeric ids 	0
Add Orf Stop          	false
Remove Temporary Files	false

Program call:
/db/prot index/orfs --min-length 30 --max-length 98202 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 0 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --id-offset 0 --threads 4

MMseqs Version:      	87f530e8aedc0970c8ec16cb2d33b7507d56cf59
Min codons in orf    	30
Max codons in length 	98202
Max orf gaps         	2147483647
Contig start mode    	2
Contig end mode      	2
Orf start mode       	0
Forward Frames       	1,2,3
Reverse Frames       	1,2,3
Translation Table    	1
Use all table starts 	false
Offset of numeric ids	0
Threads              	4
Invalid sequence with index 48657!
Invalid sequence with index 48658!
Invalid sequence with index 48659!
Invalid sequence with index 4866048607!
!
Invalid sequence with index 48608!
Invalid sequence with index 48609!
Invalid sequence with index 48670!
Invalid sequence with index 48671!
Invalid sequence with index 48641!
Invalid sequence with index !
Invalid sequence with index 48642!
Invalid sequence with index 48643!
48623!
Invalid sequence with index 48624!
Invalid sequence with index 48625!
Invalid sequence with index 48626!
Invalid sequence with index 48627!
Invalid sequence with index 48628!
Invalid sequence with index 48629!
Invalid sequence with index 48680!
Invalid sequence with index 48681!
Invalid sequence with index 4868248672!
`

i used the docker image to run these .

anybody have similar problem ?

**Comment by milot-mirdita** [comment]
Please make sure your input to `createdb` is formatted like an actual FASTA file (with `>` to start a new header):

```
>1006013
ATGGAAGCTACGAAGTCGTCGAAACAAAATTGTTGCAACCCGGTTAAGAAACCCGGACCC
...
>...
```

**Comment by elileka** [comment]
How big is your file? Is it possible to send it to us? If not, could you perhaps make a smaller version of it that reproduces the problem? (say with the first 100,000 sequences).

**Comment by shawnLiujianwei** [comment]
[prot.txt](https://github.com/soedinglab/MMseqs2/files/1844193/prot.txt)

here is one smaller version with 10,000 sequences, i tested , same problem.

**Comment by martin-steinegger** [comment]
The issues occurs because the first 10 sequences look like DNA so we assume that the database is a nucleotide database. I changed the sampling strategy. So your sample is now detected as protein database.

**Comment by elileka** [comment]
In addition, it might be helpful to examine your sequences because some are very short (e.g., 1120763) and some are very long and composed solely of DNA characters (e.g., 1001862), which is quite unlikely a for a protein sequence.

**Comment by shawnLiujianwei** [comment]
Seems you are right, i just copy piece data from the hadoop result, didn't check the details, sorry about that
