### ISSUE TITLE
duplicate sequences in createseqfiledb cluster output

### ISSUE THREAD

**Issue by flass** [soedinglab/MMseqs2#77]
Hi,  

I'd wish to use clusthash for a quick clustering of protein sequences.  

On the principle it works fast and fine, but after processing the clusthashdb files with createseqfiledb I get an inconsistent output sequence cluster file:
when a sequence is the >1st ( =  2nd, 3rd, etc.) to appear in a cluster, it will appear again in its own singleton cluster just after. The dataset is hence inflated, with as many clusters as input sequences, but some clusters containing (rightly) several sequences.  

Note that the first member of the cluster is never duplicated, and hence this does not affect singleton clusters.

Below is an example using test.fasta toy protein db as input:

## Expected Behavior
NP_770154.1, WP_028171928.1, WP_011086298.1 form a cluster
WP_084633232.1 is a singleton
NP_774261.1, WP_011090348.1 form a cluster
WP_092187456.1 is a singleton

## Current Behavior
NP_770154.1, WP_028171928.1, WP_011086298.1 form a cluster
WP_028171928.1 and WP_011086298.1 are duplicated as singletons
WP_084633232.1 is a singleton
NP_774261.1, WP_011090348.1 form a cluster
WP_011090348.1 is duplicated as a singleton
WP_092187456.1 is a singleton

## Steps to Reproduce (for bugs)
```bash
mmseqs createdb test.fasta test.mmseqsdb
mmseqs clusthash --min-seq-id 0.99 test.mmseqsdb test.clusthashdb
mmseqs createseqfiledb test.mmseqsdb test.clusthashdb test.clusthashdb_clusters
```

## MMseqs Output (for bugs)
input and output to be found in here:
[test.zip](https://github.com/soedinglab/MMseqs2/files/1848716/test.zip)

## Context
I was aiming at doing a quick clustering of 100% identical seqeunces from large databases ( >3M protein), but could reproduce the bug on a small toy database (see test.fasta) and with 99% similarity cut-off.

## Your Environment

* Git commit used:
done with last version of MMseqs2 Version: e5d64b2701789e7eef8fcec0812ccb910c8dfef3
but already the bug was present with MMseqs2 Version: 6306925fa9ae6198116c26e605277132deff70d0
* Which MMseqs version was used:
self compiled
* Compiler and Cmake versions used and their invocation:
cmake version 3.5.1
gcc version 5.4.1 20160904 (Ubuntu 5.4.1-2ubuntu1~16.04) 
used as in the installation direction on main page of github

* Server specifications:
server is a VM with 8 cores and 64GB RAM
instruction support as in my /proc/cpuinfo:
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm fsgsbase tsc_adjust smep erms xsaveopt arat
* Operating system and version:
Ubuntu 16.04
Linux mymachine 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by martin-steinegger** [comment]
Thank you for your detailed report. The problems seems like a missing `clust` call.  You can see an example how to use `clusthash` here https://github.com/soedinglab/MMseqs2/wiki#how-to-redundancy-filter-sequences-with-identical-length-and-100-length-overlap

So to make your example work you would need to add a `clust` call after  `clusthash` 

    mmseqs createdb test.fasta test.mmseqsdb
    mmseqs clusthash test.mmseqsdb test.clusthashdb --min-seq-id 0.99 
    mmseqs clust test.mmseqsdb test.clusthashdb test.clust
    mmseqs createseqfiledb test.mmseqsdb test.clust test.clust_clusters

**Comment by flass** [comment]
Ha, my bad! That works like this.
Many thanks,
Florent
