### ISSUE TITLE
`-e` and `--e-profile` parameters in `subtractdbs`

### ISSUE THREAD

**Issue by apcamargo** [soedinglab/MMseqs2#770]
Is there any difference between the `-e` and `--e-profile` parameters in `subtractdbs`? From what I understood of the code, MMseqs2 will effectively use the smallest value of the two.

I was using `subtractdbs` to get the difference between two result databases and set `-e 10`. This ended up excluding E-values between 1E-3 and 10 and I only managed to get the expected behavior by setting `--e-profile 10`.

**Comment by milot-mirdita** [comment]
`subtractdbs` will always use the smaller of the two. The module is primarily used for the iterative profile-search and needs some special handling to make sure we don't include too far away hits.

**Comment by apcamargo** [comment]
Ahh, ok. I've been using it as a general subtractor between dbs.

In an all vs. all search, to make sure I got all reciprocal hits in my results, I'm swapping the results db and using `subtractdbs` to take the difference between the original results and the swapped db (which will be the missing hits in asymmetrical pairs).

**Comment by milot-mirdita** [comment]
Then just pass `-e inf -e-profile inf` to it and it should ignore the E-values.

**Comment by apcamargo** [comment]
Thanks, Milot!
