### ISSUE TITLE
Search error with iterations

### ISSUE THREAD

**Issue by mooreryan** [soedinglab/MMseqs2#79]
## Expected Behavior

I'm doing a search of proteins against another protein database using high sensitivity and high number of iterations (`-s 7.5 --num-iterations 4`).

## Current Behavior

I get an error:

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
/scratch/aoh/qwfp/4982015852642442181/blastpgp.sh: line 81: 24849 Aborted                 (core dumped) $RUNNER "$MMSEQS" result2profile "$QUERYDB" "$2" "$TMP_PATH/aln_0" "$TMP_PATH/profile_$STEP" ${TMP}
```

However, when I use `--num-iterations 1`, I don't get the error.

## Steps to Reproduce (for bugs)

I took a small sample of sequences to reproduce the error.

```
mmseqs createdb two.fa two.db
mmseqs createdb rest.fa rest.db
mmseqs search two.db rest.db two_v_rest.db /scratch/aoh/qwfp -s 7.5 --num-iterations 4
```

Here are the files used to recreate the error.

[rest.fa.txt](https://github.com/soedinglab/MMseqs2/files/1890804/rest.fa.txt)
[two.fa.txt](https://github.com/soedinglab/MMseqs2/files/1890805/two.fa.txt)

## MMseqs Output (for bugs)

[mmseqs.err.txt](https://github.com/soedinglab/MMseqs2/files/1890802/mmseqs.err.txt)
[mmseqs.out.txt](https://github.com/soedinglab/MMseqs2/files/1890803/mmseqs.out.txt)

## Your Environment

* Git commit used: `2cfdedc95f6a998826f45a7594971751a5e535f3`
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
* Operating system and version: Fedora release 24 server edition

Here are the outputs from `make` and `cmake` from when I compiled mmseqs like so:

```
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=. .. 1> cmake.out.txt 2> cmake.err.txt
make -j32 1> make.out.txt 2> make.err.txt
make install 1> make_install.out.txt 2> make_install.err.txt
```

 [mmseqs_build_output.tar.gz](https://github.com/soedinglab/MMseqs2/files/1890845/mmseqs_build_output.tar.gz)

**Comment by martin-steinegger** [comment]
Thank you for reporting this issue. @milot-mirdita  We need to add the iterative profile search to our regression test.

The issue should be fixed now.

**Comment by mooreryan** [comment]
I just tried the `easy-search` with the same options with this version of MMseqs `dee959908c91eb72a1d91cd1a26303ea71f6e6e6` and got the same error again.

**Comment by mooreryan** [comment]
Sorry about that.  When I pulled the latest version and re-compiled everything worked.
