### ISSUE TITLE
[Question] Can easy-taxonomy be used for assembly-level taxonomic assignments instead of contig-level? 

### ISSUE THREAD

**Issue by jolespin** [soedinglab/MMseqs2#790]
I've built a custom database and I'm curious if it can be used for assembly-level taxonomic assignments instead of just contig-level?  Are there any parameters to adjust that would be able to use mmseqs easy-taxonomy for this purpose?

**Comment by martin-steinegger** [comment]
My suggestion would be to concat the contigs from one assembly and separate them by multiple Ns.

**Comment by jolespin** [comment]
Thank you, I'll do that.
