### ISSUE TITLE
Too many arguments when creating database

### ISSUE THREAD

**Issue by pipparichter** [soedinglab/MMseqs2#798]
Hello! I am trying to set up a target database, with all the reference sequences that I want to test my query database about (as per the instructions I found [here](https://mmseqs.com/latest/userguide.pdf)). I am trying to use all of GTDB as my target -- I already have it all downloaded on a remote server, so I didn't want to use the mmseq database utility to re-download it. I tried running the following:
`
mmseqs createdb $(ls bacteria/) $(ls archaea/) tmp`

Where the archaea and bacteria subdirectories contain FASTA files with all protein sequences for each representative genome. Understandably (as there are thousands of genomes), this caused mmseqs to complain that there were too many arguments.

The next thing I try is going to be to concatenate everything into a single FASTA file, and then run the same command. However, this file is going to be huge, and I suspect I might run into problems with this as well. Does anyone know of a good way to do this? 

Thanks in advance!

**Comment by milot-mirdita** [comment]
What we do to construct the GTDB in our `databases` workflow is to download the tar files containing the FASTA files.

You can do the same, pack everything into one tar file then call `tar2db` and then `createdb` on the DB created from the previous step.

**Comment by pipparichter** [comment]
Thanks! I'll give it a try

**Comment by pipparichter** [comment]
I have a follow-up question -- when I ran this, I ended up with about 20 DB files, and when calling createdb, I was getting a warning "[filename] is empty or invalid and was ignored." Do you have any idea what the cause of this might be?
