### ISSUE TITLE
`mmseqs search` is producing multiple output files

### ISSUE THREAD

**Issue by pipparichter** [soedinglab/MMseqs2#802]
## Expected Behavior

The command `mmseqs search queryDB targetDB tmp` outputs a single output file, `resultDB`.

## Current Behavior
The command `mmseqs search queryDB targetDB tmp` outputs multiple files, `resultDB.1, resultDB.2 ...`. Some of these files are empty. 

## Other details
I am using `mmseqs ` for a blast-like search of a set of target databases (which is just GTDB split into more manageable chunks so I can run it in parallel). Each split target database is about 6 million sequences, and the `queryDB` is 12 sequences.

**Comment by pipparichter** [comment]
I am assuming this is just a database distributed across multiple files (to keep file size smaller)? But was wondering if, if this is the case, some of the files are empty? Just making sure I haven't messed up somewhere!

**Comment by milot-mirdita** [comment]
This is a performance optimization to not spend a lot of time merging files that are only intended for consumption by other mmseqs modules.

If you want human readable output please either call `converalis` after `search`. Or alternatively use the `easy-search` workflow, which abstracts away all of this by taking FASTA as input and retuning BLAST-tab like output.

**Comment by milot-mirdita** [comment]
Additionally, we built MMseqs2 with much larger query sets in mind, so 12 queries is not very optimal due to poor CPU utilization. That’s why you see empty files, we started up empty threads that didn’t process any queries, but still had to write a result file.

**Comment by pipparichter** [comment]
Got it, thanks again!
