### ISSUE TITLE
Easy-cluster createdb message  "Cannot extract identifier from entry"

### ISSUE THREAD

**Issue by wichne** [soedinglab/MMseqs2#804]
Running easy-cluster pipeline on a fasta file of protein sequences. Getting 575 messages saying "Cannot extract identifier from entry nnnnn" out of 37k input proteins. 
Is this an error or just a warning? 
Are those proteins being clustered or ignored? 
How can I figure out which proteins in my input file are causing the problem so I can fix it? 
Is there a description of the required fasta header format for proper identifier extraction in the manual (I didn't see it)?

Ubuntu 20.04
mmseqs2 v 13.45111

Thanks,
Bill

**Comment by milot-mirdita** [comment]
Something is wrong with the input FASTA headers. This is not necessarily a problem for the clustering itself, however the result files might be not very useful if you cant distinguish cluster members.

It might be an issue with a space between the leading `>` in the FASTA header and the actual accession. MMseqs2 expects there to not be any whitespace.
