### ISSUE TITLE
MMseqs2 as a shared library ?

### ISSUE THREAD

**Issue by mashu** [soedinglab/MMseqs2#81]
Hi,

Would it be possible to use MMseqs2 as a shared-library ?
Any examples how to do blastp like search ?

Regards,

**Comment by martin-steinegger** [comment]
MMseqs2 can not be used as shared library but it can be compiled in other projects. @milot-mirdita do you have documentation for this?

**Comment by milot-mirdita** [comment]
Could you give us a short description of what you want to achieve?

We do not support using MMseqs2 as a shared library, especially since we use exit() for aborting in error conditions. You probably don't want your libraries to kill your application.

**Comment by mashu** [comment]
Shared libraries are usually loaded in many popular scripting languages (i.e. Julia, Python, R)
https://docs.julialang.org/en/release-0.6/manual/calling-c-and-fortran-code/
https://docs.python.org/3/library/ctypes.html
https://www.rdocumentation.org/packages/base/versions/3.4.3/topics/dyn.load

I could call externally command line tool, but library could more elegant.
Basically I would like to obtain BLAST-like bit-scores in all-vs-all comparisons between multiple fasta files.

**Comment by milot-mirdita** [comment]
Sorry, that will not work (at least not without a lot of refactoring).

Our error handling would just kill the whole python/r/julia process. You could hack our EXIT macro, but then you would be leaking memory.

Do you want all-against-all exact Smith-Waterman alignments (like SWIPE) or also the prefiltering stage?

**Comment by mashu** [comment]
Whole pipeline including pre-filtering. But it's ok if not possible. I was just curious. You can close this issue.
