### ISSUE TITLE
Taxonomy info for PDB 

### ISSUE THREAD

**Issue by ahof1704** [soedinglab/MMseqs2#821]
Hi,

How can I get the taxonomy info for the PDB database as well? 
Thanks!

**Comment by milot-mirdita** [comment]
You can download the PDB100 through foldseek. That one includes taxonomy information and is compatible with MMseqs2.

**Comment by ahof1704** [comment]
Awesome. This works. Thanks!

**Comment by milot-mirdita** [comment]
Of note, you want to likely search against the `pdb100_seq` and not the `pdb100`, as the latter contains only the cluster representatives.

Foldseek has in-built cluster search that we haven't ported back to MMseqs2 fully yet.

**Comment by ahof1704** [comment]
Based on your previous suggestion, I simply downloaded the PDB using Foldseek via the following command
`foldseek databases PDB pdb tmp `

Then I used mmseqs to filter for the tax I wanted. 
`mmseqs filtertaxseqdb pdb pdb2_human --taxon-list 9606`

Were you suggesting something different from this? 
Thanks!

**Comment by milot-mirdita** [comment]
Yes, it doesn't only download a `pdb` (with all its including files), but also a `pdb_seq`. You want to use that one, as that contains all PDB entries, not only the cluster representatives.

**Comment by ahof1704** [comment]
Sorry, I think I am a little confused. When you say I should use "that one" you mean the `pdb_seq`?

**Comment by milot-mirdita** [comment]
Yes, I edited the answer above slightly.

**Comment by ahof1704** [comment]
ok, in that case, how should I change the commands I used above to download the `pdb_seq`?

**Comment by milot-mirdita** [comment]
Sorry for the confusion, I'll repeat from the start:

```
# download PDB with Foldseek
foldseek databases PDB pdb tmp

#
# The command above will download and create many files (might not be exactly the same as listed here):
# pdb prefix:
# pdb, pdb.index, pdb.dbtype <- MMseqs2 DB
# pdb_h, pdb_h.index, pdb_h.dbtype  <- MMseqs2 DB
# pdb_ss, pdb_ss.index, pdb_ss.dbtype <- Foldseek specific part
# pdb_ca, pdb_ca.index, pdb_ca.dbtype <- Foldseek specific part
#
# pdb_seq prefix:
# pdb_seq, pdb_seq.index, pdb_seq.dbtype <- MMseqs2 DB
# pdb_seq_h, pdb_seq_h.index, pdb_seq_h.dbtype <- MMseqs2 DB
# pdb_seq_ss, pdb_seq_ss.index, pdb_seq_ss.dbtype <- Foldseek specific
# pdb_seq_ca, pdb_seq_ca.index, pdb_seq_ca.dbtype <- Foldseek specific

# pdb prefix contains only cluster representatives
# pdb_seq  prefix contains all entries, therefore use this one for MMseqs2 searches:
mmseqs easy-search query.fasta pdb_seq res.m8 tmp

```

**Comment by ahof1704** [comment]
Thank you for the clarification! It makes more sense now. 
When using pdb_seq, how would I filter for the taxonomy I want? 
Apparently, I don't have all the needed files: 

```
mmseqs filtertaxseqdb ./pdb_seq ./pdb_seq_human --taxon-list 9606

MMseqs Version: 15.6f452
Compressed      0
Selected taxa   9606
Subdb mode      0
Threads         64
Verbosity       3

Input taxonomy database "./pdb_seq" is missing files:
- ./pdb_seq_mapping
- ./pdb_seq_nodes.dmp
- ./pdb_seq_names.dmp
- ./pdb_seq_merged.dmp
```

**Comment by milot-mirdita** [comment]
Ah sorry, I should have thought about that:

Just call the following before:
```
ln -s pdb_taxonomy pdb_seq_taxonomy
ln -s pdb_mapping pdb_seq_mapping
```

These files need to be symlinked for `filtertaxseqdb` to work.

**Comment by ahof1704** [comment]
Same error, even though the links to taxonomy and mapping now exist: 

```
mmseqs filtertaxseqdb /root/mmseqs2_db/pdb2_seq /root/mmseqs2_db/pdb2_seq_human --taxon-list 9606

MMseqs Version: 15.6f452
Compressed      0
Selected taxa   9606
Subdb mode      0
Threads         64
Verbosity       3

Input taxonomy database "/root/mmseqs2_db/pdb2_seq" is missing files:
- /root/mmseqs2_db/pdb2_seq_mapping
- /root/mmseqs2_db/pdb2_seq_nodes.dmp
- /root/mmseqs2_db/pdb2_seq_names.dmp
- /root/mmseqs2_db/pdb2_seq_merged.dmp

ls /root/mmseqs2_db/pdb2_seq_
pdb2_seq_ca.0       pdb2_seq_ca.index   pdb2_seq_h.dbtype   pdb2_seq_ss.0       pdb2_seq_ss.index   
pdb2_seq_ca.1       pdb2_seq_h.0        pdb2_seq_h.index    pdb2_seq_ss.1       pdb2_seq_taxonomy   
pdb2_seq_ca.dbtype  pdb2_seq_h.1        pdb2_seq_mapping    pdb2_seq_ss.dbtype 

```

Am I missing anything?

**Comment by ahof1704** [comment]
Great! I managed to create the taxonomy and the mapping for the pdb_seq. I also created a subset with just the human sequences using the following: 
`mmseqs filtertaxseqdb /root/mmseqs2_db/pdb2_seq /root/mmseqs2_db/pdb2_seq_human --taxon-list 9606`

It went through without problems I can do a search against this subset. However, when formatting the output with `convertalis` I get the following error: 
```
convertalis /tmp/queryDB /root/mmseqs2_db/pdb2_seq_human /tmp/resultDB resultDB.tab --format-output query,target,evalue,qaln,taln,taxname,pident,cigar 

MMseqs Version:         15.6f452
Substitution matrix     aa:blosum62.out,nucl:nucleotide.out
Alignment format        0
Format alignment output query,target,evalue,qaln,taln,taxname,pident,cigar
Translation table       1
Gap open cost           aa:11,nucl:5
Gap extension cost      aa:1,nucl:2
Database output         false
Preload mode            0
Search type             0
Threads                 64
Compressed              0
Verbosity               3

No datafile could be found for /root/mmseqs2_db/pdb2_seq_human_h!
Traceback (most recent call last):
  File "../run_mmseqs2.py", line 51, in <module>
    subprocess.run(command, shell=True, check=True)
  File "../subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mmseqs convertalis /tmp/queryDB /root/mmseqs2_db/pdb2_seq_human /tmp/resultDB resultDB.tab --format-output "query,target,evalue,qaln,taln,taxname,pident,cigar"' returned non-zero exit status 1.
```

Should I create links to all of these as well? 
`pdb2_seq_h.0       pdb2_seq_h.1       pdb2_seq_h.dbtype  pdb2_seq_h.index  `

**Comment by ahof1704** [comment]
The above works great! Thanks a lot. 

I have another question: my understanding is that `pdb_seq` would be bigger than `pbd`, and therefore have the same [or more] number of found matching sequences than `pdb`. However, I am seeing a decrease as illustrated by the van diagrams below: 
![image](https://github.com/soedinglab/MMseqs2/assets/8103108/4e44a811-fd66-4c01-883f-196b8b0c2342)
![image](https://github.com/soedinglab/MMseqs2/assets/8103108/a0dd407f-4f3c-4696-a7fe-7ca86d11b1d7)

The search parameters used in both cases are the same, as shown below: 
`mmseqs search /tmp/queryDB /root/mmseqs2_db/{db} /tmp/resultDB tmp -a --max-seqs 1 -s 7 --comp-bias-corr 0 --mask 0`

Am I missing anything? 

Thanks
