### ISSUE TITLE
Question - HHblits db - cstranslate_mpi command not found

### ISSUE THREAD

**Issue by adimil** [soedinglab/MMseqs2#83]
I am trying to run hhpred on my clustering results. I have MMseqs2 Version: 9f344f3d6765a1131f22794d9a6fd9fcd8ca2cdf and hhsuite 3.0 installed.
But I cant find the last command (`cstranslate_mpi`) from https://github.com/soedinglab/MMseqs2/wiki#how-to-create-a-hhblits-database

Is it part of mmseqs or hhsuite? Does it need to be installed separately? can I use `cstranslate` instead?

Thanks,
Adi

**Comment by martin-steinegger** [comment]
cstranslate is part of hhsuite3.0. You can use cstranslate instead but it does not provide MPI support.

**Comment by milot-mirdita** [comment]
Careful about the parameters though. I would recommend to install `libopenmpi-dev` (or your OS equivalent) and rebuild the HH-suite, it will detect the presence of MPI and build cstranslate_mpi, ffindex_apply_mpi, hhblits_mpi etc.

**Comment by adimil** [comment]
Thanks!

**Comment by Lucy-code123** [comment]
Where to install cstranslate_mpi? I can not find it anywhere. Can someone give me advice? Thanks!
