### ISSUE TITLE
Can mmseqs easy-search ouput all query-target pairs?

### ISSUE THREAD

**Issue by Zuttergutao** [soedinglab/MMseqs2#839]
Dear all,
I want to get all query-target pairs' identity, So can mmseqs easy-search ouput all query-target pairs without filtering?
If can, can you provide the related args for me.
Thanks!

**Comment by milot-mirdita** [comment]
`--prefilter-mode 2` aligns everything. However, that can be very slow and use a lot of storage.

**Comment by milot-mirdita** [comment]
You might also want to disable the E-value filter (`-e inf`).
