### ISSUE TITLE
Request for few options' description

### ISSUE THREAD

**Issue by ksteczk** [soedinglab/MMseqs2#85]
I have a request for describing some mmseq's options in more depth, at least with a suggestion what effect might have a specific parameter set to its extreme. Especially, maybe they wouldn't be relevant eventually, but I think that's good to know when thinking about optimizing and shaping profiles / searches / clusterings. For instance:

**result2profile**
--qid (intuitive, but how does it affect final profile's e.g. sensitivity?)
--qsc (especially the range - what does the default setting mean compared to extremes?)
--pca
--pcb
--diff (I see explanation in commandline help but get confused by the window and don't know whether should I modify that for manipulating profile's characteristics - mainly specific/nonspecific feature)

**prefilter**
--min-ungapped-score (set up to 15, what does it mean? Does it affect minimum length of k-mer alignment that is needed?)
--k-score
--diag-score

Could you add some comment in documentation what do these do? How varying them affect (or is expected to affect) results? Maybe some of them are hidden in the code, but that's hard to infer for non developer.

I can see also that search doesn't produce results for very short sequences, e.g. the shortest PFAM consensus sequences, what additionally inspire me to rethink all procedures more throughly.

Thanks!

**Comment by milot-mirdita** [comment]
I am not 100% about some parameters, but I can help for some:

### result2profile

`--diff N`: Before a profile is computed, the sequences of the alignments are filtered and only the N most diverse are kept and used for profile computation. `--qid` and `--qsc` also give minimum thresholds for the filtering. I am not sure anymore why we have both, you'll have to wait for Martin to be back from his vocations.

`--pca` `--pcb`: Pseudo-count admixture factors. Do not touch in result2profile, we probably should remove it there completely. Pseudocounts are now computed on the fly during a search.

### prefilter
`--min-ungapped-score`:  The minimum score of the ungapped alignment (last step of the prefilter). The lower this value is, the more elements pass through the prefilter and have to be aligned by the (slow) Smith-Waterman alignment stage.

`--k-score`: Minimum score a k-mer needs to achieve to be stored in the index table. With more k-mer comparisons, you get a higher sensitivity, but it will take more time.

`--diag-score`: You can disable the ungapped alignment stage. (Another thing for Martin to elaborate on).
