### ISSUE TITLE
result2msa input has wrong type (Generic)

### ISSUE THREAD

**Issue by seang123** [soedinglab/MMseqs2#850]
MMseqs2: Downloaded binary with AVX2 support
git commit version: 5f23f1fd6d88056879d901f5d027f18d592d785c
OS: Linux 6.5.0-35-generic Ubuntu x86_64

This is more of a usage question than a bug issue. Apologies if this isn't the correct place for such questions.
I am using mmseqs2 to implement a process similar to that used by [colabfold's mmseqs_search_monomer()](https://github.com/sokrypton/ColabFold/blob/main/colabfold/mmseqs/search.py). 
I have the following process:
1. First I create a queryDB from a fasta file with many sequences in it. `mmseqs createdb queries.fasta queryDB`
2. Next I run the `search`, `expandaln`, `align`, and `filterresult` commands pretty much as described in the colabfold code. 

The output of the `filterresult` command generates 20 files, in my case the base name is `res_exp_align_filter` and then there are also `res_exp_align_filter.{0..19}`, plus `.dbtype` and `.index` files. 

My next step was to generate MSA alignments for each of my query strings. I tried passing the `res_exp_align_filter` file to the result2msa command which works, however this doesn't give the output that I want since I want one MSA file per query sequence. 
Instead I tried the following, I concatenated all the `res_exp_align_filter` files as follows: `cat res_exp_align_filter.{0..19} > res_exp_align_filter.all`. I then used the `res_exp_align_filter.index` file to get the byte offsets for each query and read the appropriate section of the concatenated file. This seems to work, at least insofar that I get what looks like properly aligned sections, with more overlapping targets at the top and less overlapping sequences towards the end. I then write these sections to separate files `./tmp/query`. Finally I try to pass these new files to the `result2msa` command, but then I get the following error:

```
Input database "/tmp/query" has wrong type (Generic)
Allowed inputs:
- Alignment
- Prefilter
- Bi-directional prefilter
- Clustering
```

I'm wondering if there is a simpler way of doing this, and if not why can't I pass the subset of the `res_exp_align_filter` file into the result2msa command even though it has the same structure as the `res_exp_align_filter` file.

**Comment by milot-mirdita** [comment]
```
My next step was to generate MSA alignments for each of my query strings. I tried passing the res_exp_align_filter file to the result2msa command which works, however this doesn't give the output that I want since I want one MSA file per query sequence.
```

This is already one MSA per query sequence. It's just stored in an MMseqs2 database. You can use the `unpackdb` commands (just like in colabfold) to get separate a3m files.

Your concat procedure is not the intended way to use the `result2msa` module. I would recommend against messing with database internals like that.

**Comment by seang123** [comment]
The `unpackdb` command gives me the same output as the byte offset reading approach I was doing. Seems I re-invented that command without knowing it. However, when I run the `unpackdb` command I get a file per query with its alignments in the internal mmseqs2 format, I then want to convert this to the a3m+alignment format with `result2msa --msa-format-mode 6`, but I still get the same error as above, that the file produced by the `unpackdb` command has the wrong type.

I don't really understand why this is the case, since previously when I tested the pipeline with a single sequence queryDB this `result2msa` method worked just fine. Similarly, I am able to run the `result2msa` command on the file which I unpack, but then not on the unpacked files.

**Comment by seang123** [comment]
Ok I seem to have figured it out somewhat, not entirely sure how I got to this point. I think I was calling result2msa on an actual file (ie. res_exp_align_filter.0) instead of the generic name (res_exp_align_filter) which the command expects, although I thought I was doing this initially. 
I still cannot call the `result2msa` command on the `unpackdb` output files. But I can work around that by running `result2msa` on the entire file (with all queries) and the cutting out sections manually. Or maybe I can use convertalis on the unpacked files and do the conversion to the a3m format myself.

**Comment by milot-mirdita** [comment]
After calling `unpackdb` you leave the MMseqs2 world behind and get a normal MSA.

All MMseqs2 modules (except the ones that deal with other input and output formats) only deal with MMseqs2 databases.
So if you have an MMseqs2 database `res_exp_align_filter` from a previous module invocation, you have to use this database in the next module (e.g. `result2msa`). After you are done with all MMseqs2 calls, you call one of the modules that gives use a normal/human-readable output. In this case, `unpackdb`.
