### ISSUE TITLE
taxonomy output with queryID

### ISSUE THREAD

**Issue by ckeuschn** [soedinglab/MMseqs2#855]
Hi, 

is there any way to get a file after running the mmseq taxonomy command from the resulting DB which shows the queryID and the connected assigned taxonomy? The createtsv has only the databaseID NCBI_taxaID in it.

Many thanks
Christoph

**Comment by milot-mirdita** [comment]
Can you please add the MMseqs2 command you were running and the terminal output of MMseqs2?

**Comment by ckeuschn** [comment]
Hi Milot, thanks for coming back on this. I just figured out myself that I mixed up the command and only provided the targetDB (UniprotKB) and my resultDB without my queryDB. That gave me of course a tsv without the queryIDs in it. 
Thanks again, also for a great software :)

**Comment by ckeuschn** [comment]
Hi Milot, thanks for coming back on this. I just figured out myself that I mixed up the command and only provided the targetDB (UniprotKB) and my resultDB without my queryDB. That gave me of course a tsv without the queryIDs in it.
Thanks again, also for a great software :)
