### ISSUE TITLE
How to create an expanded alignment database?

### ISSUE THREAD

**Issue by zdk123** [soedinglab/MMseqs2#857]
In the userguide, there is some text about using a provided expanded alignment database:

>Download one of the three provided expandable profile databases from https://colabfold.mmseqs.com and convert it to the MMseqs2 databases format with tsv2exprofiledb

However, there's nothing about how to go about creating the source tsv files (e.g. from an input fasta file or pre-computed clustering). My flying-blind attempts have resulted in a database without any k-mers
```
No k-mer could be extracted for the database ../../tests/dbs/uniref30_2302_db.
Maybe the sequences length is less than 14 residues.
```

I would greatly appreciate if you can point me to a minimal example.

thanks!

**Comment by milot-mirdita** [comment]
There are some examples in the wiki: https://github.com/sokrypton/ColabFold/wiki/Creating-expandable-search-databases

**Comment by zdk123** [comment]
This works, thanks!
