### ISSUE TITLE
Unexpected Sequence Identity Values for Redundant Sequences

### ISSUE THREAD

**Issue by FelixMQuintana** [soedinglab/MMseqs2#861]
## Expected Behavior
I created a database of 100% identical amino acid sequences with 100% coverage. I expect after going through the prefiltering step and alignment step I would see 100% identical hits. 
## Current Behavior
Instead I found hits with of approximately 93% with reported mismatches of 22 with the same e-values as those with 100% identity.  
## Steps to Reproduce (for bugs)

Attached is the example sequence I found for this bug ([redundant.zip](https://github.com/user-attachments/files/16111570/redundant.zip)). Protein sequence is 303 AA in length with fake names given to the same sequence. I ran the following commands to create the alignment file where I found the issue. 

```
mmseqs createdb redundant.fasta sequenceDB
mmseqs kmermatcher sequenceDB prefilterDB
mmseqs align sequenceDB sequenceDB prefilterDB alignmentDB
mmseqs convertalis sequenceDB sequenceDB alignmentDB alignmentFile
```

## MMseqs Output (for bugs)
Below is the TSV file of the resulting alignment. As you can see these identical sequences sometimes match at 100% others at 93% with some amount of mismatch and all the same bit-scores etc. 
![Screenshot from 2024-07-05 10-47-23](https://github.com/soedinglab/MMseqs2/assets/44539035/4d073d41-99e7-4abc-b057-70974cde7ab0)

## Context

I am attempting to replicate some uniref clusters and found this irregularity and chose to isolate and replicate the issue by creating a completely redundant database. This may be a related to #688 .

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
MMseqs2 Version: 6f45232ac8daca14e354ae320a4359056ec524c2

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
Statically-compiled from release 15-6f452

* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
AMD 3950X with 128GB DDR4 RAM.

* Operating system and version:
Ubuntu 22.04.4 LTS

**Comment by FelixMQuintana** [comment]
This may be related to #688

**Comment by milot-mirdita** [comment]
This is a common trap within MMseqs2. See our wiki entry:
https://github.com/soedinglab/MMseqs2/wiki#how-does-mmseqs2-compute-the-sequence-identity

You need to pass the `-a` to `align` to get accurate sequence identity values, otherwise they are estimated from the alignment score.

**Comment by FelixMQuintana** [comment]
@milot-mirdita  Thanks so much for this clarification. I noticed this page before just wasn't clear to me how it impacted my scores. Fixed my issue. I'm interested in linclust's workflow so I'm running through linclust's prefiltering and alignment step! I'd like to see the alignmentDB before the greedy set cover algo.
