### ISSUE TITLE
MMseqs easy-search for profiles only produces one hit per domain in profile database?

### ISSUE THREAD

**Issue by Andy-B-123** [soedinglab/MMseqs2#862]
## Expected Behavior

Searching a protein query using a profile database with 'easy-search' should return multiple hits for the same domain on a protein sequence, as done by things like InterProScan.

## Current Behavior

I only see single 'domain' hits on a protein sequence, with duplicated domains being represented by slightly different domain hits, but never the same one repeated? Essentially it is classifying similar domains as slightly different ones. 

I am hoping to identify proteins with duplicated/triplicated/quad etc domains and so having slightly different hits is a bit of a blocker.

## Steps to Reproduce (for bugs)

Example protein sequence: https://www.ncbi.nlm.nih.gov/protein/XP_044259022.1?report=fasta

```
mmseqs databases CDD profile_DB_CDD ./tmp_db
mmseqs easy-search query.fasta ./dir_DB_CDD/profile_DB_CDD queries.DBSearch.out ./tmp_db_search --format-mode 4 --threads 8
```

## MMseqs Output (for bugs)

Expected domains from InterProScan:

![](https://github.com/soedinglab/MMseqs2/assets/35752341/e6199e1c-b715-4a99-8c15-b422054955c7)

![](https://github.com/soedinglab/MMseqs2/assets/35752341/d6249702-9ad1-40ab-858e-8c5823f571c9)

![](https://github.com/soedinglab/MMseqs2/assets/35752341/e56399e8-4001-476c-8926-da393a5d0350)

InterProScan run on commandline for that sequence produces multiple identical domains:

![](https://github.com/soedinglab/MMseqs2/assets/35752341/419b44f1-974b-4c3c-8385-89ec80fd4ecb)

MMSeqs domains:

![](https://github.com/soedinglab/MMseqs2/assets/35752341/8af205bd-a582-41a1-9a2f-d684c2d19a87)

Mmseqs produces slightly different hits for the 'left' and 'right' hand side here (eg cd09603 vs cd09602), but InterProScan is classifiying  these as identical ones (cd09601). The sequences for those domains are different, they are not identical. Is mmseqs generally able to produce multiple database hits per gene? Or is it always going to try and find the 'best'? I've tried turning the sensitivity to 1 or the Pfam database but that doesn't seem to change the behaviour.

## Context

I'm trying to classify some mis-annotated genes I've identified and would like to find cases such as this where it's likely a mis-annotation. I'd love to use mmseqs for this as finding domains with something like InterProScan isn't feasible at scale.   
Is there a way to get mmseqs to output identical database hits? Or a way of relaxing/clustering the profile databases? Thank you for your time!

## Your Environment

Latest mmseqs version used mmseqs2/15-6f452

**Comment by milot-mirdita** [comment]
You can specify `--alt-ali N` for up to N alternative/sub-optimal alignments per target.

**Comment by Andy-B-123** [comment]
Amazing, thank you!!! Exactly what I needed, works great now!  
 

![](https://github.com/soedinglab/MMseqs2/assets/35752341/56950bb9-609d-4832-b126-0d7b80c0dde1)
