### ISSUE TITLE
idx.index creation is not 64-bit safe

### ISSUE THREAD

**Issue by jtotzid** [soedinglab/MMseqs2#868]
## Expected Behavior

Created a `idx` file with `mmseqs createindex`. Input is big, uniref30.
I was expecting the resulting `.idx.index` to show me how large each "chunk" in the idx database is...

## Current Behavior

...however, sizes in .idx.index are truncated to 32-bit.

## Steps to Reproduce (for bugs)

I did not create the idx file, I only get to inspect the idx.index afterwards.
So, we have 3 files
```
214G uniref30_2302_db.idx
   4 uniref30_2302_db.idx.dbtype
 506 uniref30_2302_db.idx.index
```
```
$ cat uniref30_2302_db.idx.index

0	0	3
1	4096	49
2	8192	4331
3	162806448128	1075201
4	162419372032	387072001
5	24576	1016217777
6	1016246272	1492528074
7	6803742720	1236666921
8	16630345728	1431766172
9	162807525376	3738374247
10	209495576576	1650065417
12	228709240832	9
13	228709244928	9
14	220025933824	93370172
15	219735580672	9
16	219735584768	290347937
18	99666493440	1236666921
19	109493096448	250490302
20	99666493440	1236666921
21	109493096448	250490302
22	20480	41
23	16384	1
24	152693260288	1016217777
25	153709481984	119952652
```

Copy pasta that into LibreOffice or whatever, add up the length column: adds up to only 15 GB ish!

Lets look at key 9 aka `ENTRIES` and the following key 10 aka `ENTRIESOFFSETS`.
Their offsets are `162807525376` and `209495576576`, ie `ENTRIES` should be of size 209495576576-162807525376=46688051200 but `index` says it's 3738374247 ie 10x too small.
Correct size in hex is: ADED32000 and size in index DED31067:
```
A_DED32000
  DED31067
```
ie. the leading bits got truncated off. The few extra bytes difference are from rounding up to page boundary.

On linux. Installed from prebuilt `https://mmseqs.com/latest/mmseqs-linux-avx2.tar.gz`.

Not sure where and how this happens... the code looks fine. 
There is one 32-bit `length` here https://github.com/soedinglab/MMseqs2/blob/master/src/commons/DBReader.h#L61 but i'm not sure how it would come into play with creating the `.idx.index`.

**Comment by jtotzid** [comment]
How does the truncated length make it into the index file though?
In https://github.com/soedinglab/MMseqs2/blob/master/src/prefiltering/PrefilteringIndexReader.cpp#L247, things look 64-bit safe.
Calls https://github.com/soedinglab/MMseqs2/blob/master/src/commons/DBWriter.cpp#L403, which eventually calls https://github.com/soedinglab/MMseqs2/blob/master/src/commons/DBWriter.cpp#L379 where the length is computed from offsets.
And eventually formatted to text as a 64-bit integer https://github.com/soedinglab/MMseqs2/blob/master/src/commons/DBWriter.cpp#L415.

**Comment by milot-mirdita** [comment]
Most likely from `DBWriter::close`. It will read in the database again with a DBReader (4-byte length), check if the keys are sorted correctly, and if not write the index out again, truncating the length.

**Comment by jtotzid** [comment]
ok, thanks for clarification
