### ISSUE TITLE
metaclust clusters information

### ISSUE THREAD

**Issue by ppflrs** [soedinglab/MMseqs2#87]
Hi,

Is it possible to identify which dataset the scaffolds in metaclust come from?

Thanks,
Pepe

**Comment by ppflrs** [comment]
Too bad 😢  What about the different members for each cluster?

Thanks

**Comment by martin-steinegger** [comment]
yes I can provide this. Let me upload it the next days.

**Comment by martin-steinegger** [comment]
@ppflrs I have rebuilt the metaclust database by adding new identifier and reclustering everything. Every protein source should be now labeled with uniq identifier which can be used to traced the protein to the JGI, OM-RGC, Uniprot or NCBI. 
The new release is available here https://metaclust.mmseqs.com/2018_06/ 
 
The identifier looks like this now

     >RifCSPlowO2_12_1023861.scaffolds.fasta_scaffold367679_1 # 24 # 428 # -1 # ID=367679_1;partial=00;start_type=ATG;rbs_motif=None;rbs_spacer=None;gc_cont=0.435

`RifCSPlowO2_12` identifies the JGI project. The project can be accessed the following way (you need an JGI account): 

https://genome.jgi.doe.gov/portal/pages/dynamicOrganismDownload.jsf?organism=RifCSPlowO2_12

Within the project the contig is contained in the file `1023861.scaffolds.fasta` at fasta record `scaffold367679_1`. 

The rest of the header contains the prodigal prediction information. 

I have also added a file metaclust_50_cluster.fasta.gz which contains all cluster member in a fasta like fromat https://github.com/soedinglab/MMseqs2/wiki#cluster-fasta-like-format.
