### ISSUE TITLE
installation issue (MMseqs2-71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1) 

### ISSUE THREAD

**Issue by vineethvintu** [soedinglab/MMseqs2#886]
## Expected Behavior
Need to Install the mmseqs (MMseqs2-71dd32ec43e3ac4dabf111bbc4b124f1c66a85f1) this particular version 
## Current Behavior
but I am seeing there is no bin directory so I cant specify the PATH
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.
cd /home/username  # Navigate to your home directory
unzip MMseqs2.zip  # Extract the MMseqs2 ZIP file
cd MMseqs2  # Go into the MMseqs2 directory after extraction
mkdir build  # Create a build directory
cd build
cmake ..  # Configure the build with cmake
Setting the PATH
export PATH=$HOME/MMseqs2/build/bin:$PATH

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.
I am unable find the bin directory in Build folder.
so it is not seetting PATH & MMseqs is not getting in my Terminal

## Your Environment
Macbook Pro M3 Pro chip
Using SSH and installing in my Home directory of the Server

**Comment by milot-mirdita** [comment]
You can download precompiled binaries for either the latest git commit at https://mmseqs.com/latest/ or for any previous git commit (that successfully compiled) at `mmseqs.com/archive/GIT_COMMIT`. For the commit you want the first commit that compiled after it is mmseqs.com/archive/03f0bcca33a6af3135082957f1cebf8baff7cc61

If you compile from source please follow the instructions in the wiki:
https://github.com/soedinglab/MMseqs2/wiki#compile-from-source-under-linux

```
cd MMseqs2 # Go into the MMseqs2 directory after extraction
mkdir build # Create a build directory
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=. .. # Configure the build with cmake
make -j16
make install
Setting the PATH
export PATH=$HOME/MMseqs2/build/bin:$PATH
