### ISSUE TITLE
Large sequences being split results in unexpected sequence ID handling

### ISSUE THREAD

**Issue by zkstewart** [soedinglab/MMseqs2#89]
## Context
I am running MMseqs2 search of the UniRef100 database. This database includes many long sequences, one example of which is a titin isoform (UniRef100_UPI000A307CE5).

## Expected Behavior
I would expect the output file after running convertalis on the search output to have the same sequence ID as the UniRef100 sequence, i.e.,

```
evm.model.utg11.204     UniRef100_UPI000A307CE5       0.231   160     116     3       2138    2297    16366   16518   5.20E-36        164
```

## Current Behavior
MMseqs2 is splitting this long entry into two separate ones: UniRef100_UPI000A307CE5_0 and UniRef100_UPI000A307CE5_1. 

I can verify this by performing a grep search for "UPI000A307CE5" on the .lookup file which returns
```
132227718       UniRef100_UPI000A307CE5_0
132227719       UniRef100_UPI000A307CE5_1
```

Additionally, searching for these two lines within the output file created by "createdb" indicates that the tail portion of this UniRef100 sequence has indeed been split from the main.

Because of this splitting behaviour, my output convertalis table has this entry.

```
evm.model.utg11.204     UniRef100_UPI000A307CE5_0       0.231   160     116     3       2138    2297    16366   16518   5.20E-36        164
```

From what I can guess this might not strictly be a bug in MMseqs2 - perhaps exceedingly long sequences can't be handled properly during alignment. I can handle this behaviour now that I am aware of it; it resulted in some confusion as to why I was not obtaining the expected results when parsing the uniref100.xml file for the gene name / taxon code of significant hits. However, I think that a consistent sequence ID should be returned since this behaviour is not clear and it took a bit of investigation to figure out what was happening.

## Steps to Reproduce (for bugs)
Generate and index a FASTA file containing the above-mentioned UniRef100 sequence.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters): a58d38379bfb3c5ad75272d358bfec9f2c100b61
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.): self-compiled
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory): HPC, nodes with support for both.
* Operating system and version: SUSE 12.2

**Comment by martin-steinegger** [comment]
I might have a solution to accept sequences until 2^16. This should avoid this annoying few cases (e.g. Titin). I will implement this in the next days.

**Comment by martin-steinegger** [comment]
I have increased the default --max-seq-len to 65535. So your problem should be solved. You need to recreate your database with `createdb`  and recompute your search again.
