### ISSUE TITLE
The representative sequence obtained by easy-linclust is still redundant

### ISSUE THREAD

**Issue by Prangejet** [soedinglab/MMseqs2#899]
I used easy-linclust (with parameters:  -c 0.9; --min-seq-id 0.9; --cov-mode 1; --cluster-mode 2) for clustering and obtained representative sequences. Then I divided it into single sequences (singleton clusters) and representative sequences of non-singleton clusters (those containing ≥ 2 sequences). Subsequently, I used DIAMOND to create a database of representative sequences of non-singleton clusters and then compared the single sequence with the database using diamond blastp (--id 90, --subject-cover 90, or had tried --query-cover 90). The results showed that a large number of sequences were shared over 90% identity (some sequences shared Identity=100%).

In the MMseq Output provided below, I have removed the information on Converting sequences, which is over 400 million and too long to read.
## Expected Behavior
Non-redundant representative sequences should be obtained
## Current Behavior
a large number of representative sequences are redundant
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.
> mmseqs easy-linclust /home/stu_1/Pantong/5_downstream/4_assembly_prodigal/All_cohort.faa /home/stu_1/Pantong/5_downstream/4_assembly_prodigal/All_cohort All_cohort_tmp/ --min-seq-id 0.9 --cov-mode 1 -c 0.9 --cluster-mode 2 --max-seq-len 10000 --threads 56
## MMseqs Output (for bugs)
Create directory All_cohort_tmp/
easy-linclust /home/stu_1/Pantong/5_downstream/4_assembly_prodigal/All_cohort.faa /home/stu_1/Pantong/5_downstream/4_assembly_prodigal/All_cohort All_cohort_tmp/ --min-seq-id 0.9 --cov-mode 1 -c 0.9 --cluster-mode 2 --max-seq-len 10000 --threads 56 

MMseqs Version:                     	13-45111+ds-2
Cluster mode                        	2
Max connected component depth       	1000
Similarity type                     	2
Threads                             	56
Compressed                          	0
Verbosity                           	3
Substitution matrix                 	nucl:nucleotide.out,aa:blosum62.out
Add backtrace                       	false
Alignment mode                      	0
Alignment mode                      	0
Allow wrapped scoring               	false
E-value threshold                   	0.001
Seq. id. threshold                  	0.9
Min alignment length                	0
Seq. id. mode                       	0
Alternative alignments              	0
Coverage threshold                  	0.9
Coverage mode                       	1
Max sequence length                 	10000
Compositional bias                  	1
Max reject                          	2147483647
Max accept                          	2147483647
Include identical seq. id.          	false
Preload mode                        	0
Pseudo count a                      	1
Pseudo count b                      	1.5
Score bias                          	0
Realign hits                        	false
Realign score bias                  	-0.2
Realign max seqs                    	2147483647
Gap open cost                       	nucl:5,aa:11
Gap extension cost                  	nucl:2,aa:1
Zdrop                               	40
Alphabet size                       	nucl:5,aa:21
k-mers per sequence                 	21
Spaced k-mers                       	0
Spaced k-mer pattern                	
Scale k-mers per sequence           	nucl:0.200,aa:0.000
Adjust k-mer length                 	false
Mask residues                       	1
Mask lower case residues            	0
k-mer length                        	0
Shift hash                          	67
Split memory limit                  	0
Include only extendable             	false
Skip repeating k-mers               	false
Rescore mode                        	0
Remove hits by seq. id. and coverage	false
Sort results                        	0
Remove temporary files              	true
Force restart with latest tmp       	false
MPI runner                          	
Database type                       	0
Shuffle input database              	true
Createdb mode                       	1
Write lookup file                   	0
Offset of numeric ids               	0

createdb /home/stu_1/Pantong/5_downstream/4_assembly_prodigal/All_cohort.faa All_cohort_tmp//9948387321092861199/input --dbtype 0 --shuffle 1 --createdb-mode 1 --write-lookup 0 --id-offset 0 --compressed 0 -v 3 

Shuffle database cannot be combined with --createdb-mode 0
We recompute with --shuffle 0

Time for merging to input_h: 0h 0m 0s 0ms
Time for merging to input: 0h 0m 0s 0ms
Database type: Aminoacid
Time for processing: 0h 4m 46s 360ms
Create directory All_cohort_tmp//9948387321092861199/clu_tmp
linclust All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu All_cohort_tmp//9948387321092861199/clu_tmp --cluster-mode 2 --threads 56 -e 0.001 --min-seq-id 0.9 -c 0.9 --cov-mode 1 --max-seq-len 10000 --spaced-kmer-mode 0 --remove-tmp-files 1 

kmermatcher All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref --sub-mat nucl:nucleotide.out,aa:blosum62.out --alph-size nucl:5,aa:13 --min-seq-id 0.9 --kmer-per-seq 21 --spaced-kmer-mode 0 --kmer-per-seq-scale nucl:0.200,aa:0.000 --adjust-kmer-len 0 --mask 0 --mask-lower-case 0 --cov-mode 1 -k 0 -c 0.9 --max-seq-len 10000 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 56 --compressed 0 -v 3 

kmermatcher All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref --sub-mat nucl:nucleotide.out,aa:blosum62.out --alph-size nucl:5,aa:13 --min-seq-id 0.9 --kmer-per-seq 21 --spaced-kmer-mode 0 --kmer-per-seq-scale nucl:0.200,aa:0.000 --adjust-kmer-len 0 --mask 0 --mask-lower-case 0 --cov-mode 1 -k 0 -c 0.9 --max-seq-len 10000 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 56 --compressed 0 -v 3 

Database size: 440656032 type: Aminoacid
Reduced amino acid alphabet: (A S T) (C) (D B N) (E Q Z) (F Y) (G) (H) (I V) (K R) (L J M) (P) (W) (X) 

Generate k-mers list for 1 split
[=================================================================] 440.66M 1m 58s 106ms
Sort kmer 0h 1m 9s 431ms
Sort by rep. sequence 0h 0m 39s 418ms
Time for fill: 0h 2m 31s 613ms
Time for merging to pref: 0h 0m 0s 1ms
Time for processing: 0h 9m 8s 726ms
rescorediagonal All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_rescore1 --sub-mat nucl:nucleotide.out,aa:blosum62.out --rescore-mode 0 --wrapped-scoring 0 --filter-hits 0 -e 0.001 -c 0.9 -a 0 --cov-mode 1 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 56 --compressed 0 -v 3 

[=================================================================] 440.66M 7m 9s 976ms
Time for merging to pref_rescore1: 0h 2m 33s 403ms
Time for processing: 0h 11m 51s 610ms
clust All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_rescore1 All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pre_clust --cluster-mode 2 --max-iterations 1000 --similarity-type 2 --threads 56 --compressed 0 -v 3 

Clustering mode: Greedy
Total time: 0h 1m 32s 562ms

Size of the sequence database: 440656032
Size of the alignment database: 440656032
Number of clusters: 35665237

Writing results 0h 0m 11s 300ms
Time for merging to pre_clust: 0h 0m 0s 0ms
Time for processing: 0h 2m 42s 666ms
createsubdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/order_redundancy All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy -v 3 --subdb-mode 1 

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 39s 420ms
createsubdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/order_redundancy All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_filter1 -v 3 --subdb-mode 1 

Time for merging to pref_filter1: 0h 0m 0s 0ms
Time for processing: 0h 1m 38s 696ms
filterdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_filter1 All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_filter2 --filter-file All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/order_redundancy --threads 56 --compressed 0 -v 3 

Filtering using file(s)
[=================================================================] 35.67M 56s 656ms
Time for merging to pref_filter2: 0h 0m 11s 819ms
Time for processing: 0h 1m 22s 652ms
rescorediagonal All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_filter2 All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_rescore2 --sub-mat nucl:nucleotide.out,aa:blosum62.out --rescore-mode 1 --wrapped-scoring 0 --filter-hits 1 -e 0.001 -c 0.9 -a 0 --cov-mode 1 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 56 --compressed 0 -v 3 

[=================================================================] 35.67M 9s 733ms
Time for merging to pref_rescore2: 0h 0m 12s 355ms
Time for processing: 0h 0m 38s 935ms
align All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_rescore2 All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/aln --sub-mat nucl:nucleotide.out,aa:blosum62.out -a 0 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.9 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.9 --cov-mode 1 --max-seq-len 10000 --comp-bias-corr 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --gap-open nucl:5,aa:11 --gap-extend nucl:2,aa:1 --zdrop 40 --threads 56 --compressed 0 -v 3 

Compute score and coverage
Query database size: 35665237 type: Aminoacid
Target database size: 35665237 type: Aminoacid
Calculation of alignments
[=================================================================] 35.67M 7m 56s 191ms
Time for merging to aln: 0h 0m 12s 23ms
118495359 alignments calculated
45078108 sequence pairs passed the thresholds (0.380421 of overall calculated)
1.263923 hits per query sequence
Time for processing: 0h 8m 32s 609ms
clust All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/aln All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/clust --cluster-mode 2 --max-iterations 1000 --similarity-type 2 --threads 56 --compressed 0 -v 3 

Clustering mode: Greedy
Total time: 0h 0m 1s 843ms

Size of the sequence database: 35665237
Size of the alignment database: 35665237
Number of clusters: 30248342

Writing results 0h 0m 3s 669ms
Time for merging to clust: 0h 0m 0s 15ms
Time for processing: 0h 0m 9s 943ms
mergeclusters All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pre_clust All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/clust --threads 56 --compressed 0 -v 3 

Clustering step 1
[=================================================================] 35.67M 21s 398ms
Clustering step 2
[=================================================================] 30.25M 29s 933ms
Write merged clustering
[=================================================================] 440.66M 1m 5s 117ms
Time for merging to clu: 0h 0m 10s 164ms
Time for processing: 0h 1m 51s 537ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_filter1 -v 3 

Time for processing: 0h 0m 0s 93ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref -v 3 

Time for processing: 0h 0m 5s 147ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_rescore1 -v 3 

Time for processing: 0h 0m 3s 490ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pre_clust -v 3 

Time for processing: 0h 0m 0s 772ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy -v 3 

Time for processing: 0h 0m 0s 113ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/input_step_redundancy_h -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_filter2 -v 3 

Time for processing: 0h 0m 0s 366ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/pref_rescore2 -v 3 

Time for processing: 0h 0m 0s 306ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/aln -v 3 

Time for processing: 0h 0m 0s 614ms
rmdb All_cohort_tmp//9948387321092861199/clu_tmp/9745907189971917257/clust -v 3 

Time for processing: 0h 0m 0s 192ms
createtsv All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu All_cohort_tmp//9948387321092861199/cluster.tsv --threads 56 -v 3 

Time for merging to cluster.tsv: 0h 3m 32s 713ms
Time for processing: 0h 6m 13s 976ms
result2repseq All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu All_cohort_tmp//9948387321092861199/clu_rep --db-load-mode 0 --compressed 0 --threads 56 -v 3 

[=================================================================] 30.25M 27s 445ms
Time for merging to clu_rep: 0h 0m 24s 792ms
Time for processing: 0h 1m 43s 420ms
result2flat All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_rep All_cohort_tmp//9948387321092861199/rep_seq.fasta --use-fasta-header -v 3 

Time for processing: 0h 2m 39s 415ms
createseqfiledb All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu All_cohort_tmp//9948387321092861199/clu_seqs --threads 56 -v 3 

[=================================================================] 30.25M 2m 3s 327ms
Time for merging to clu_seqs: 0h 0m 12s 135ms
Time for processing: 0h 4m 5s 680ms
result2flat All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/input All_cohort_tmp//9948387321092861199/clu_seqs All_cohort_tmp//9948387321092861199/all_seqs.fasta -v 3 

Time for processing: 0h 13m 23s 618ms
rmdb All_cohort_tmp//9948387321092861199/input -v 3 

Time for processing: 0h 0m 0s 117ms
rmdb All_cohort_tmp//9948387321092861199/input_h -v 3 

Time for processing: 0h 0m 0s 96ms
rmdb All_cohort_tmp//9948387321092861199/clu_seqs -v 3 

Time for processing: 0h 0m 6s 941ms
rmdb All_cohort_tmp//9948387321092861199/clu_rep -v 3 

Time for processing: 0h 0m 0s 101ms
rmdb All_cohort_tmp//9948387321092861199/clu -v 3 

Time for processing: 0h 0m 0s 47ms

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):13-45111+ds-2
* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):I'm not sure where to obtain this information
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
![image](https://github.com/user-attachments/assets/b4aa4788-d89d-4dd4-bdac-15c7da519d3d)

* Operating system and version :Linux admin 4.18.0-193.el8.x86_64 #1 SMP Fri Mar 27 14:35:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by juanjo255** [comment]
@Prangejet Hello, I am having a similar result. Did you find out what was the reason for this?
