### ISSUE TITLE
Error: Prefilter died

### ISSUE THREAD

**Issue by smangul1** [soedinglab/MMseqs2#90]
## Current Behavior

This is the error i am getting 

Starting prefiltering scores calculation (step 1 of 1)
Query db start  1 to 15993152
Target db start  1 to 15993152
tmp/17791169248477116152/blastp.sh: line 75: 20702 Illegal instruction     (core dumped) $RUNNER "$MMSEQS" prefilter "$INPUT" "$TARGET" "$TMP_PATH/pref_$SENS" $PREFILTER_PAR -s "$SENS"
Error: Prefilter died

## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

mmseqs search queryDB targetDB resultDB tmp

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

no output 

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

I am trying to find pairwise alignment between 15M short aa sequences

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):

Invalid Command: Version

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
Statically-compiled
* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
N/A
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
qsub -cwd -V -N align -l h_data=32G,time=10:00:00 run.sh
* Operating system and version:

Linux version 2.6.32-696.18.7.el6.x86_64 (mockbuild@c1bl.rdu2.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18) (GCC) ) #1 SMP Thu Jan 4 17:31:22 UTC 2018

**Comment by milot-mirdita** [comment]
Could you post the output of `lscpu` running on this compute node please? It looks like your compute node does not support AVX2. Could you download the SSE41 build of the archive and try again?

**Comment by smangul1** [comment]
Thanks! This is the output:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD
CPU family:            16
Model:                 4
Model name:            Quad-Core AMD Opteron(tm) Processor 2380
Stepping:              2
CPU MHz:               800.000
BogoMIPS:              4987.57
Virtualization:        AMD-V
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
NUMA node1 CPU(s):     4-7


Serghei

**Comment by smangul1** [comment]
I don't think I have permissions to install, but i can ask cluster admin to do it. Should i ask them to install SSE41?

**Comment by milot-mirdita** [comment]
I am afraid the SSE41 version won't work either. The CPU is sadly too old and does not support the required instruction sets.
