### ISSUE TITLE
Paire-wise sequence alignment is empty using convertalis --format-mode 1

### ISSUE THREAD

**Issue by xiekunwhy** [soedinglab/MMseqs2#92]
Hi,
MMseqs is a good software.
## Steps to Reproduce (for bugs)
Just use your example data
mmseqs search queryDB targetDB resultDB tmp
mmseqs convertalis queryDB targetDB alignDB.pw --format-mode 1
## MMseqs Output (for bugs)
No aligned sequence of  convertalis --format-mode 1 results
>Q8ZZW3 C5A4E9  0.316   361     238     0       16      364     53      413     2.18E-48        178

>Q8ZZW3 Q5JJ64  0.294   361     245     0       20      367     66      426     5.60E-42        159

>Q8ZZW3 F6XRU1  0.228   378     266     0       20      364     11      388     9.10E-25        108

## Your Environment
Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014
MMseqs2 Version: GITDIR-NOTFOUND

**Comment by milot-mirdita** [comment]
You might want to start the search with the `-a` flag, so the backtrace is added to the result file. Without that flat, the pairwise alignment mode of `convertalis` won't produce useful output.

**Comment by xiekunwhy** [comment]
Thank you, it worked.

**Comment by milot-mirdita** [comment]
Happy to help!

**Comment by xiekunwhy** [comment]
It's much better if mmseqs can provide blast m7(xml) output format because we want to use the results for blast2go's es.blast2go.prog.B2GAnnotPipe module.
